### ISSUE TITLE
Why is REFPROP fee based?

### ISSUE THREAD

**Issue by wandadars** [usnistgov/REFPROP-issues#10]
I'm curious as to why REFPROP is not maintained as an open source project? Many national labs host their unclassified projects on Github. There are many advantages to open sourcing a project, especially if the funding is from taxpayers not private sales. 

LANL Github page: https://github.com/lanl

**Comment by ianhbell** [comment]
NIST REFPROP is covered under the Standard Reference Data program of the U.S. Government, and therefore we can claim copyright and charge cost recovery fees for the development of NIST REFPROP.  Without funding from outside money, NIST REFPROP would likely cease to exist.  That's the "how-can-we".

While there are certainly many benefits to open-sourcing software (see for instance the many open-source projects that I have been involved in), securing reliable funding for open-source projects is never a straightforward endeavor.  That's the "why-should-we-not".

If you could put together a consortium that is willing to contribute several million dollars per year to develop REFPROP for the next decade, I think we might consider open-sourcing REFPROP :)

**Comment by wandadars** [comment]
Thanks for the detailed response. That sucks that the government doesn't actually provide a budget item for developing and maintaining REFPROP. That's why I couldn't understand why there was a fee. Those DOE guys get billions to develop/maintain their codes; Uncle Sam could at least throw some coins to you guys.

As a bonus question: Are you the same Ian H Bell that maintains the Coolprop project?

**Comment by ianhbell** [comment]
The current funding situation for federal scientific and engineering research is challenging, to say the least.  So without people like you, there would be no REFPROP in the first place.  If DOE wanted to support us with a long-standing funding agreement, a lot would be possible.

And yes, that's the same Ian Bell.
