### ISSUE TITLE
Refprop 10 backwards compatibility to Refprop 9 DLL

### ISSUE THREAD

**Issue by yiannischoust** [usnistgov/REFPROP-issues#101]
Our lab is using some proprietary software based on refprop DLL version 9.0. I am tasked to update this to version 10 to include newer refrigerants.
We need to know if version 10 is fully backwards compatible with 9. I understand from previous threads that there are macros to handle Refprop 9 commands, but I need to confirm if I can simply replace the DLL file without changing the way our software references it.

Simply replacing the DLL initially produced no error messages except for the R1234ZE refrigerant that needed to be renamed to R1234ZEE.
 
Also, can you please provide the documentation for the version 9 of the DLL?

**Comment by EricLemmon** [comment]
Refprop 10 is indeed fully backwards compatible with 9.0, at least we have not received any complaints to the contrary.  If you do find something that has changed, let us know and we can get it fixed.  The manual for version 9 is included below.  

Is the Excel file part of your software?  If so, we have several methods for updating things or using the old methods directly.

[MANUAL.TXT](https://github.com/usnistgov/REFPROP-issues/files/2817496/MANUAL.TXT)

**Comment by yiannischoust** [comment]
Thank you for your reply.
Our software is .NET based (C#), excel is not involved.  
One concern was whether certain functions were called with different parameters compared to the DLL documentation for version 10, such as SatDLL.

**Comment by ianhbell** [comment]
Correction: REFPROP 9 and 10 are *mostly* backwards compatible.  The behavior is in 99% of the cases exactly the same.  There are some subtle, and not so subtle differences, like the error codes have changed, and some functions that were disfunctional before have been removed.  See also: https://pages.nist.gov/REFPROP-docs/#updates-to-version-100

**Comment by ianhbell** [comment]
Also, I believe the SatDLL function is not a part of the REFPROP DLL.

**Comment by yiannischoust** [comment]
Sorry, I misspelled it, I was referring to SATTdll.

**Comment by ianhbell** [comment]
Yeah, that function is the same in REFPROP 10, only change might be the error codes.

**Comment by yiannischoust** [comment]
Thank you, I think that covers it.
Can anyone send me the equivalent of this 
https://www.nist.gov/sites/default/files/documents/2018/05/23/refprop10a.pdf
for version 9.0?

Thanks

**Comment by ianhbell** [comment]
If you email me at ian.bell@nist.gov<mailto:ian.bell@nist.gov> I can send you the PDF.

**Comment by mary977** [comment]
I don't have version 10. Can you please provide me with version 10?

**Comment by ianhbell** [comment]
@mary977 No, I'm afraid we can't do that, but it can be purchased from: https://www.nist.gov/srd/refprop

**Comment by mary977** [comment]
Why don't I have properties of R1234ze in Refprop 9.1?

**Comment by mary977** [comment]
> @mary977 No, I'm afraid we can't do that, but it can be purchased from: https://www.nist.gov/srd/refprop

ok . thank you

**Comment by ianhbell** [comment]
@mary977 please open a new issue since this is not related to the original post.

**Comment by mary977** [comment]
> @mary977 please open a new issue since this is not related to the original post.

ok
