### ISSUE TITLE
T-EOSmin does not always converge for blends

### ISSUE THREAD

**Issue by kjschultz527** [usnistgov/REFPROP-issues#106]
### Description

Calculation of EOSmin temperature for blends does not converge reliably.

### Steps to Reproduce

Called =REFPROP("T",FluidString10(R32;R1234yf|x,1-x,mass),"EOSmin","SI") for x=1..0).  Sometimes a value is returned, sometimes a #[TQFLSH error 2] or #[SATT error 124] is returned.  See attached Excel file.  Not critical for what I'm doing, but maybe important to someone else?

**Expected behavior:** [What you expect to happen]

Just repeated this -- successfully -- with REFPROP v9.1; see second attachment.

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** REFPROP v10.0  
**Operating System and Version:** Windows 10  
**Access Method:** Excel through REFPROP.XLA  

### Additional Information

If possible, please post examples and/or screenshots of the issue.   Attached...

[TEOSminNotReliableForMixtures¿.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2838734/TEOSminNotReliableForMixtures.xlsx)

[TEOSmin-RPv91.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2838754/TEOSmin-RPv91.xlsx)

**Comment by EricLemmon** [comment]
You bring up a point that really has no good answer in a program where the melting line for mixtures is not known.  Without knowledge of the real minimum in temperature for mixtures, we have made many assumptions over the years as to how to best estimate the minimum temperature, both giving users as much space as possible for calculations, but staying away from the melting point to keep them from trouble.  Furthermore, as with the problem you have found here, many of the older equations of state do not extrapolate well at temperatures below their triple point.  Such extrapolations are needed for mixtures of fluids with very different ranges of the ratio of the triple point to the critical point temperature.  For example, nitrogen+propane at 50/50 mole percent requires extrapolation of about 30 K below the triple point of nitrogen (propane:  Ttrp/Tc=0.23,   nitrogen:  Ttrp/Tc=0.5).  The equation of state for nitrogen, which is now about 25 years old, does not extrapolate well below its triple point, but being developed in 1996 on computers that ran at 50 MHz, the equation is incredibly accurate for all liquid and vapor states.  We are in the process of redoing this equation now, with technology that can fit fluids 100 to 1000 times faster than those in 1996, but with constraints that demand far more superior extrapolation to temperatures down to 0 K, and to temperatures, pressures, and densities to infinite states.

For R32+R1234yf, the situation is similar, the R32 equation starts to loop on itself below its triple point.  The mixture requires calculations below that point, which fail when the equation of state does.  As with nitrogen, R32 is also around 25 years old and is currently being re-fitted to remove these deficiencies.  The picture below shows the (bad) influence of the R32 equation at temperatures below 130 K for a 50/50 mixture.

There is no real easy way to define a minimum temperature that meets all demands required of users until we have developed equations for the melting lines of mixtures and better equations of state for the pure fluids that are more than about 15 years old.  But we are working on it!

(Note:  For a mixture, "melting line" is not the correct term; "freezing line" is more accurate.  But we are all more familiar with the word "melt" so I used it above.)

![image](https://user-images.githubusercontent.com/42392984/52385398-9ead3080-2a3e-11e9-83a5-e2869b7550e7.png)
