### ISSUE TITLE
Loading predefined mixtures causes crash 

### ISSUE THREAD

**Issue by ibell** [usnistgov/REFPROP-issues#107]
I think this is exactly the same bug as https://github.com/usnistgov/REFPROP-wrappers/issues/49 and also the same bug as reported here: https://groups.google.com/forum/#!topic/coolprop-users/Pech-lsnNlU

On linux, this causes a crash:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
path = '/home/ian/REFPROP10'
RP = REFPROPFunctionLibrary(path)
RP.SETPATHdll(path)
MOLAR_BASE_SI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum
r = RP.REFPROPdll('R404A.MIX','PQ','Q',MOLAR_BASE_SI,0,0,101325,0,[1.0])
print(r.herr, r.ierr)
```

I have FLUIDS and MIXTURES folders inside the root folder.

**Comment by mayersre** [comment]
Hi Ian, 

ctREFPROP fails as expected. It fails too wit R404A as pseudopure but not
with R410A as pseudopure, see below. 

>>> from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
>>> RP = REFPROPFunctionLibrary('/opt/rp10')
>>> RP.SETPATHdll('/opt/rp10')
>>> MOLAR_BASE_SI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum
>>> r = RP.REFPROPdll('r410a','PQ','QMOLE',MOLAR_BASE_SI,0,0,101325,0,[1.0])
>>> r = RP.REFPROPdll('r404a','PQ','QMOLE',MOLAR_BASE_SI,0,0,101325,0,[1.0])
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by ianhbell** [comment]
Crashes on windows too.  Let's see about C++, problem could be in the Python wrapper.  Weird.

**Comment by ianhbell** [comment]
Problem is in the Python wrapper.  Fixing it as we speak.

**Comment by ianhbell** [comment]
Fixed.  You'll need to do a ``pip install -U ctREFPROP``

**Comment by mayersre** [comment]
Confirmed, just had a successful test run
