### ISSUE TITLE
Refprop V 10.0 User defined Mixture issue

### ISSUE THREAD

**Issue by jaymeen721** [usnistgov/REFPROP-issues#109]
I wish to make mixture of R23 & R404a, but R404 is not showing in the list, So I have to mixture all the components of R404a.
Due to making mixture using four components, rather than two refrigerants (i.e. pure fluid R23 and Pseudo Pure fluid R404a) So, I am unable to get Phase diagram.
I wish to plot composition v/s Temp. diagram for mixture of R23 & R404a. Please help me, how to obtain plot for R23 & R404a.

**Comment by EricLemmon** [comment]
The easiest way to do this is to go to Substance/Predefined Mixture and select R404A.  Then go to Substance/Specify Composition, select Add Fluid, and select R23.  You can then enter your composition once it appears on the list.  You don't need to change the composition of the other fluids - once you enter a value for R23 and press OK, it will then normalize it for you.

**Comment by jaymeen721** [comment]
Thanks for information.
But My problem is different. I need composition v/s Temperature diagram for binary mixture of Pseudo Fluid R404A & pure refrigerant R23.
Kindly, help in that regards.

**Comment by EricLemmon** [comment]
Ah, I see.  Mixing a pseudo-pure fluid and a pure fluid is not possible thermodynamically.  To calculate VLE, the algorithm needs to be able to calculate the fugacity of each of the pure fluids and find the location where these fugacities are equal in the liquid and vapor states.  This cannot be done when mixing with a pseudo-pure fluid.  You can think of it this way, imagine a 50/50 mixture of the pseudo-pure fluid A containing components B and C and you want to mix it with pure fluid D.  If you want a 80/20 mixture of the "binary" A + D, then the real mixture would be 40/40/20 B/C/D.  If you attempt a VLE calculation, the algorithm would return the wrong compositions - let's say it returns 70% A + 30% D in the liquid and 10 % A+ 90% B in the vapor.  But in the real mixture of B/C/D, the algorithm would equate the fugacities of each component in the liquid and vapor phases and return, for example, a mixture of 60% A + 15% B +25% C in the liquid and 8% A + 27% B + 65% C in the vapor.  Designing equipment in such a manner would result in non-optimal performance, or worse...

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by jaymeen721** [comment]
Hi, your solution is feasible, but still it can't solve my problem as I need composition v/s Temperature plot for that mixture but as no. Of fluid are more than two, it does not give me the plot.

Kindly, suggest if anything can be done in this case.

**Comment by ianhbell** [comment]
The mixture R-404A is already a three-component mixture, and then when you add R-32, you now have a four-component mixture.  P-x and T-x diagrams are only for binary mixtures.   So unfortunately, you'll have to rethink how you handle your problem.  You could calculate the overall bulk composition by modifying the R-32 composition and holding the _relative_ composition of the remaining components constant.  You can see an example of that in my paper on humid air: https://ws680.nist.gov/publication/get_pdf.cfm?pub_id=921756 , section 2.2
