### ISSUE TITLE
NIST mixing rules bug

### ISSUE THREAD

**Issue by blaubacher** [usnistgov/REFPROP-issues#111]
I am using NIST 10.0  I typically use inflator gases, e.g. Argon, Helium, Oxygen, etc.  The mixing rules that I prefer to use are linear models between binary pairs.

With this version, the gas mixing rules don't "stick" when I change them.  They seems to want to change back to a different or default choice.  I’m not sure if it happens before/after “calculate state points”, but I know that if you calculate more than 1 state point, it will switch the mixing rules on the fly…  strange.

look in the "view mixing rules" GUI and experiment with the different options and see if they change on you.
![2019-02-14 09_49_45-clipboard](https://user-images.githubusercontent.com/47639241/52802864-01ee2280-303e-11e9-9ca3-19350c81daa9.png)
![2019-02-14 09_49_45-clipboard](https://user-images.githubusercontent.com/47639241/52802905-1500f280-303e-11e9-8dd5-7312487625c6.png)

**Comment by EricLemmon** [comment]
This appears to be a bug, I will look into it and get it fixed if so.

**Comment by EricLemmon** [comment]
This bug has been fixed now, but there is still the possibility that some combination of events may still cause an incorrect entry.  If you use the new GUI, please watch carefully to help us ensure that we caught all possible ways that could cause problems.

And don't forget that the Apply button has to be pressed before pressing OK to actually make the change!  (I have done that incorrectly way too many times!)

**Comment by blaubacher** [comment]
Hi Dr. Lemmon,

Thanks for the update.  So I obviously need to redownload and reinstall, right?


Thanks
Brian

**Comment by blaubacher** [comment]
Resolved.  Thanks!
