### ISSUE TITLE
More accurate properties for mixture

### ISSUE THREAD

**Issue by XiangtianGuan** [usnistgov/REFPROP-issues#113]
I am dealing with  water and ethanol mixture as a heat change medium.  And I want to call REFPROP to do the design calculation, but since this mixture is a kind of strong association compounds, the properties of the call will be greatly deviated. Is there any way I can call more accurate properties?

**Comment by EricLemmon** [comment]
Although the mixture ethanol and water is composed of two highly associating compounds, it's properties have been measured extensively over the last 100 years, with perhaps more than 5000 measurements available.  These measurements were fitted and the resulting equations were added to the Refprop program.  When you calculate the properties of this mixture, you will obtain the most accurate properties available when Refprop 10 was released.  We have not written a publication on this yet, but that is coming.
