### ISSUE TITLE
Temperature dependence of properties

### ISSUE THREAD

**Issue by savinashg** [usnistgov/REFPROP-issues#115]
I would like to know if there are any equations ( or correlations) available for temperature dependence of following properties of refrigerants e.g. R123, R134a etc.

i) Surface tension
ii) Superheated vapour density

**Comment by ianhbell** [comment]
Indeed there are.  For surface tension, the correlation implemented in REFPROP is documeted:

![image](https://user-images.githubusercontent.com/11966765/53291054-8b060780-376a-11e9-87e4-447563df2cef.png)

and the superheated density is obtained from the equation of state:

![image](https://user-images.githubusercontent.com/11966765/53291061-9d804100-376a-11e9-8573-b8f453acd8ce.png)
