### ISSUE TITLE
temperature-entropy chart of helium and nitrogen do not match with the bibliography

### ISSUE THREAD

**Issue by peraltajo** [usnistgov/REFPROP-issues#116]
Hi Dear,

I write to you from Argentina, testing the free (refprop mini) version of the REFPROP software. I find that the temperature-entropy diagram of nitrogen and helium does not correspond to those found in the bibliography.

I wanted to know if this is a misinterpretation, or is it a software problem.

The bibliography that I take as reference is,

Brookhaven_National_Laboratory_Selected_volume_1

Best regards

**Comment by ianhbell** [comment]
Entropy is a relative property (https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences).  Does it look the same in shape except that the reference state differs?

**Comment by peraltajo** [comment]
First, thanks for your prompt response, I could understand clearly.
Second, I did not know there was a page with frequent questions, I promise to read this page before asking the forum.
Thanks again
Best regards
Juan Pablo
