### ISSUE TITLE
Unit conversion kinematic viscosity

### ISSUE THREAD

**Issue by GZALAT** [usnistgov/REFPROP-issues#118]
Hello,
I noticed a unit conversion error in Refprop 10 for the kinematic viscosities: the values in cm2/s are correctly calculated, but when choosing m2/s as display unit, the applied conversion factor is only 100 instead of 10'000. So all values in m2/s are a factor 100 too high!

**REFPROP Version:** 10
**Operating System and Version:** Win 10
**Access Method:** Excel

**Comment by ianhbell** [comment]
Can you please show a particular example of this behavior?

**Comment by GZALAT** [comment]
That was a fast reply!
Please find attached an example Excel file using only standard unit
packages (we first noticed with a user one)
Thank you

**Comment by ianhbell** [comment]
Unfortunately you cannot attach files to email responses to github issues.  Can you use the github web interface to add your file?  Or a screenshot is fine too.

**Comment by GZALAT** [comment]
Sorry, not used to
[kinViscosityUnitIssue.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2911980/kinViscosityUnitIssue.xlsx)

**Comment by ianhbell** [comment]
Sorry, I'm confused, I don't see any direct calls to REFPROP in your spreadsheet.

**Comment by GZALAT** [comment]
When I reload and open the file that's what it looks like to me:
Screenshot with results:
![image](https://user-images.githubusercontent.com/48068140/53517923-1c111180-3ad0-11e9-9cf1-148c3f6ad062.png)
 and with equations : 
![image](https://user-images.githubusercontent.com/48068140/53518016-5ed2e980-3ad0-11e9-9ad2-4f449df20edb.png)

**Comment by ianhbell** [comment]
Thanks for the report, seems like a bug to me.  We'll investigate.

**Comment by GZALAT** [comment]
Thank you

**Comment by EricLemmon** [comment]
This bug has been fixed now, please contact me directly if you would like to obtain a new DLL (eric.lemmon@nist.gov).
