### ISSUE TITLE
REFPROP Fluid Information Display

### ISSUE THREAD

**Issue by vf126** [usnistgov/REFPROP-issues#119]
Hello all,

I am a very new user with REFPROP and I am trying to see the temperature range of each individual available refrigerant (specifically the maximum and minimum temperatures of each fluid in the Substance->Fluid Information tab, as I only can see the subcategory for the "critical point" parameters
I have tried to look under the Options tab (specifically under preferences) but I cannot seem to find a "checkbox" to get the maximum/minimum options

I would try to pull these values from MATLAB (referencing REFPROP) but I cannot seem to come up with a command to do so

Does anyone have any recommendations on how to display these values either in REFPROP itself or MATLAB? For reference, I am working with a Windows 10 operating system

Thanks so much for any/all assistance!

![image](https://user-images.githubusercontent.com/48064700/53518762-b9a01d00-3a9f-11e9-96d1-7cef5822b38d.png)

**Comment by ianhbell** [comment]
Please see the documentation for the high-level API : https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll 

In the Python interface (available from MATLAB: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab), it would be like this:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'c:/Program Files (x86)/REFPROP10'
RP = REFPROPFunctionLibrary(root);
RP.SETPATHdll(root)
MOLAR_BASE_SI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum
r = RP.REFPROPdll("WATER","","TMAX;PMAX;TTRP",MOLAR_BASE_SI,0,0,0,0,[1.0])
Tmax, pmax, Ttrp = r.Output[0:3]
print(Tmax, pmax, Ttrp)
```

**Comment by EricLemmon** [comment]
Which version of Refprop are you using, the picture you show there does not match what's in version 10.

![image](https://user-images.githubusercontent.com/42392984/53524627-29f96f00-3a9d-11e9-9989-600e5d6a5091.png)

**Comment by vf126** [comment]
> Which version of Refprop are you using, the picture you show there does not match what's in version 10.

Hi Eric,

Thank you for including your screenshot!
I am using REFPROP version 9.1.1.11 on a Windows 10 device
The reason why I clarified my operating system was due to the python/MATLAB compatibility needed for Windows 10 operating systems when using MATLAB (as it appears) 

I am looking for access to the "Range of applicability" values as shown in your screenshot above
Is this an option I can select in the REFPROP program under some sort of preferences?

**Comment by ianhbell** [comment]
I'd like to comment here that the whole python/MATLAB/REFPROP interfacing works fine in Windows 7 too, as that is what I use.  It also works fine on OSX and on linux if those are relevant for you.

To get to the screen Eric showed, in the REFPROP GUI, you can go to Substance->Fluid Information menu.  Or you can access it from MATLAB with the code I showed above.

**Comment by vf126** [comment]
> I'd like to comment here that the whole python/MATLAB/REFPROP interfacing works fine in Windows 7 too, as that is what I use.  It also works fine on OSX and on linux if those are relevant for you.
> To get to the screen Eric showed, in the REFPROP GUI, you can go to Substance->Fluid Information menu.  Or you can access it from MATLAB with the code I showed above.

Hi Ian,

Thank you for the clarification! When I attempt to access the screen that Eric has shown, this is what I see:
![image](https://user-images.githubusercontent.com/48064700/53526156-7cdd2180-3ab1-11e9-9480-154fbd06324e.png)

I am only able to see a portion of what Eric is seeing
Do you know how I can access the "Range of applicability" parameters as Eric is?

**Comment by EricLemmon** [comment]
The REFPROP 10 xls file in Excel is really great for seeing all of the minimums and maximums.  Send me an email (eric.lemmon@nist.gov) and I'll send you the file.

**Comment by ianhbell** [comment]
Really weird.  Seems like your REFPROP installation is somehow corrupted.  Can you try to reinstall REFPROP?  It doesn't seem to be loading anything properly.  Did you get an error message when you started the software?

**Comment by vf126** [comment]
> Really weird.  Seems like your REFPROP installation is somehow corrupted.  Can you try to reinstall REFPROP?  It doesn't seem to be loading anything properly.  Did you get an error message when you started the software?

Hi Ian,

To be completely honest, I seem to have been struggling with installation and initial launch of REFPROP from the beginning when I tried to install the relevant files (as I wasn't able to get MATLAB to call to the relevant location on my drive to utilize the REFPROP program) but when I started the program for this purpose today I didn't seem to run into any error messages-but I agree in that maybe I should attempt to reinstall the program

The weird issue is that I attempted to download the latest version of MATLAB before installing REFPROP, and I received a corrupted installation of that as well (which the MATLAB support team and I thought we had amended since)


Also for reference I am utilizing a Windows 10 HP Envy x360-i'm starting to think it has something to do with my computer itself...

**Comment by ianhbell** [comment]
Indeed, I have literally never seen issues as bad as this before.  The common denominator being your computer does seem possible.

**Comment by EricLemmon** [comment]
Has this issue been resolved?

**Comment by vf126** [comment]
Just about but just as a follow-up I attempted to reinstall REFPROP and I appear to be running into the same issue
Very strange

**Comment by ianhbell** [comment]
Have you tried a reformat of your computer yet?  Something seems very wrong with it...
