### ISSUE TITLE
Speed of sound for methane+helium mixtures is not working well from Excel Addin

### ISSUE THREAD

**Issue by DLozanoMartin** [usnistgov/REFPROP-issues#120]
Hi to all,

### Description of the problem

When I am trying to calculate the speed of sound for some methane + helium mixtures from Excel I am getting the error: "[REFPROP error 810] One or more of the input properties is not thermophysically defined for two-phases states and cannot be calculated". When I try the same estimation from REFPROP GUI I have a correct value, the problem is only from the Excel Addin (I have try both the REFPROP.XLA and the REFPR91.XLA). With the old RefProp version 9.1 I have no problems with these calculations.

### Versions

**REFPROP Version: 10  
**Operating System and Version: Windows 10  
**Access Method: Excel Addin. Excel 365 ProPlus Version 1901

**Comment by ianhbell** [comment]
Can you please provide an example that doesn't work in the Excel interface that works in the GUI?  I'm 95% sure that it is a question of reference states : https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

**Comment by DLozanoMartin** [comment]
I also believe the problem came from the definition of the Enthalpy/Entropy reference state but I would like your advice. Below, there are two pictures that describe my concern.
![1](https://user-images.githubusercontent.com/48202122/53752606-518e7400-3eaf-11e9-9597-81e858e63166.png)
![2](https://user-images.githubusercontent.com/48202122/53752614-55ba9180-3eaf-11e9-9e2b-03704f504362.png)

**Comment by ianhbell** [comment]
Did you see all the warnings that popped up when you entered this mixture into REFPROP?  Not only the failure of the reference state calculation but others too?  The model in REFPROP is _not accurate_ for this mixture, and you should be VERY skeptical about any numbers that come out.  You should verify model calculations against experimental data if at all possible.

**Comment by DLozanoMartin** [comment]
Yes, I know it is not accurate. I am using GERG (and AGA) from Refprop for comparison with my own experimental data of speed of sound. I just hoped that Excel Addin works like the Refprop GUI, to avoid copy and paste from the GUI to my spreadsheet. I have updated my Refprop version from 9.1 to Refprop 10 recently. I thought it was gonna work just like the old version.

**Comment by ianhbell** [comment]
Got it - are your data published somewhere, or are you working on a publication?  We have a student here working on fitting models for some of these mixtures, and I'm sure he would be interested in your data.  You can email me at ian.bell@nist.gov for more information.

**Comment by DLozanoMartin** [comment]
I have tried to change the reference state as it is indicated in the link you give me, but the problem is still there. I just want to get the same values in the Excel Addin than in the GUI, although they are not accurate.

**Comment by EricLemmon** [comment]
One possible way to fix this would be to change the value of iFlag in the Refprop.xla file.  Press Alt-F11, then open the Refprop.xla project, and then open the Refprop10Code module.  Search for iFlag.  You will find this:

```
        'The line below sets a flag to call SATSPLN to use splines for the saturation states of the mixture.  This then allows the calculation of the
        'true critical point, maximum temperature, and maximum pressure at saturation (for the composition in z).  This call can be slow (0.1 to 2 seconds per call)
        'and is best used in a separate xls file for a dedicated mixture.  The spline routine is called when the fluids are/or compositions change.
        'If the spline calculations are desired, it is best to leave this flag always on when calling the REFPROP routine.
           'iFlag = 1
```

Remove the apostrophe so that the line ``iFlag = 1`` is active, save the module, restart Excel, and see if it works now.  Some people have had problems saving the xla file, let us know if that happens to you.

**Comment by DLozanoMartin** [comment]
Yes. This change has corrected my problem. Thank you very much. No problems saving the xla.

**Comment by EricLemmon** [comment]
Indeed, Ian's comment above about needing more data for fitting this mixture is extremely important right now.  Our student doing this work is here for about a month more, and then he leaves (but hopefully we can get him to come back again!)  If it is possible to share these data, we would be very grateful.  Send us a personal email to eric.lemmon@nist.gov and ian.bell@nist.gov (even if obtaining the data at this point in time is not possible).  This will help us make a better model for use in future versions of the program.

If all your questions have been answered, could you close this issue?
