### ISSUE TITLE
Carbon dioxide / methanol and Carbon dioxide / ethanol mixtures

### ISSUE THREAD

**Issue by BarzinG** [usnistgov/REFPROP-issues#123]
### Description

Hi and great thanks for the amazing package. I just have a quick question regarding Co2/Methanol and Co2/ethanol mixtures.

I have been trying to plot p-v diagram for Co2/methanol mixture for a range of ethanol mass fraction  (see images below). For 5% ethanol, the graph is looking reasonable. It seems like for 10% ethanol there is a discontinuity in near critical region on saturated p-v curves. Is this really expected and has a physical rationale behind it? When I increase ethanol content to 20%, critical point drops below the saturation curves which I can't really make sense of. Also the saturated vapour line shows rapid drop towards the left side of the graph. 

I tried to follow the reference to the mixing rule i.e. Literature reference for Carbon dioxide/Methanol
T.M. Blackham and E.W. Lemmon, NIST (2010), but I could not find it! Are these physical behaviors or the artefact of the fitting? If there is a physics here that I don't understand please would you give me a hint?

When I change Co2/Methanol to Co2/ethanol, I receive an error which I know it's because the parameters are not fitted for this substance but I still get a graph that critical point is below saturated curves and does not make sense to me (see last image).

Please could you shed some light on this? I am relatively new to alcohol mixture thermodynamics. 

### Versions

**REFPROP Version:** [REFPROP 10]  
**Operating System and Version:** [OS Win 10]  
**Access Method:** [How you are accessing REFPROP (GUI)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![image](https://user-images.githubusercontent.com/47184569/54032232-eee7f180-41a8-11e9-9294-4457406cb32c.png)
CO2/Methanol 95/5 w/w%
![image](https://user-images.githubusercontent.com/47184569/54032045-69fcd800-41a8-11e9-9b49-2643f53527e9.png)
CO2/Methanol 90/10 w/w%
![image](https://user-images.githubusercontent.com/47184569/54032137-af210a00-41a8-11e9-8402-b083a3627ccc.png)
CO2/Methanol 80/20 w/w%

![image](https://user-images.githubusercontent.com/47184569/54032419-77ff2880-41a9-11e9-8c59-43e4cf746cf9.png)
CO2/Ethanol 80/20 w/w%

**Comment by ianhbell** [comment]
The models were developed at NIST in 2010, but it is now known that the mixtures of CO2 + alcohols have a lot of problems.  We've done some specialized fitting projects for these mixtures and have still not been able to achieve nice results for all binary pairs.  Or frankly, any of the binary pairs.  What you are seeing is mostly artifacts of the model.  Models for mixtures of CO2 + alcohols are tricky to get right, and as a result, we do not yet have any CO2 + alcohol mixtures with very reliable mixture models.

**Comment by BarzinG** [comment]
Hi Ian,

Thank you very much for your reply and clarification. Just one last question, when you are saying we do not yet have any CO2 + alcohol mixtures with **very reliable** mixture models, do you mean there is a limited temperature, pressure or ethanol content range for which the results are believable? if so, what is that?

**Comment by ianhbell** [comment]
None of the above :( I would say that we have no reliable mixture models for CO2 + alcohol mixtures currently.  They represent a surprisingly hard family of systems to develop mixture models for.  My colleagues and I have spent quite some time working on this, and it remains elusive.  Some models are relatively ok sometimes, but they predict liquid-liquid equilibrium when they shouldn't, or yield poor density predictions, or ....

**Comment by EricLemmon** [comment]
If there are no further questions, could you close this issue?
