### ISSUE TITLE
Refprop10 ABFL1 documentation

### ISSUE THREAD

**Issue by StuartLawson** [usnistgov/REFPROP-issues#124]
When looking to add more Refprop subroutines I noticed the following:
............................................................................................................................................................................................................

          subroutine ABFL1dll(a, b, z, kph, ab, Dmin, Dmax, T, P, D, ierr, herr, ab_length, herr_length)

General single-phase flash routine given two inputs and composition. Valid input properties are temperature, pressure, density, energy, enthalpy, or entropy. The character string ab specifies the inputs, which can be T, P, D, E, H, S. An input of ‘EH’ (or ‘HE’) is not supported. The letters in this string must be uppercase.
Care must be taken when sending inputs of T, P, or D, so that the same variable is not sent twice. For example, the following would be wrong:

            call ABFL1 ('TH',T,H,z,kph,0,0,Dmin,Dmax,T,P,D,ierr,herr)

Rather, the following are examples of correct inputs:

          call ABFL1 ('TH',T,H,z,kph,0,0,Dmin,Dmax,tt,P, D,ierr,herr)
          call ABFL1 ('TP',T,P,z,kph,0,0,Dmin,Dmax,tt,pp,D,ierr,herr)
          call ABFL1 ('DS',D,S,z,kph,0,0,Dmin,Dmax,T, P,dd,ierr,herr)

This routine accepts only single-phase inputs, it is intended primarily for use with the more general flash routine
..............................................................................................................................................................................................................

The position of the properties and labels in the declaration and examples do not match 
       
         (a, b, z, kph, ab,   becomes  ('TH',T,H,z,kph,

**Comment by EricLemmon** [comment]
This is indeed an issue of undocumented code.  I have updated the information in the ABFL1 routine to give  the following:

```
      subroutine ABFL1 (ab,a,b,z,kph,iGuess,Dmin,Dmax,T,P,D,ierr,herr)
c
c  General single-phase flash routine given two inputs and composition.
c  Valid input properties are temperature, pressure, density, energy,
c  enthalpy, or entropy.  The character string ab specifies the inputs,
c  which can be T, P, D, E, H, S.  An input of 'EH' (or 'HE') is
c  not supported.  The letters in this string must be uppercase.
c
c  Care must be taken when sending inputs of T, P, or D, so that the same
c  variable is not sent twice.   For example, the following would be wrong::
c      call ABFL1 ('TH',T,H,z,kph,0,0,Dmin,Dmax,T,P,D,ierr,herr)
c
c  Rather, the following are examples of correct inputs::
c      call ABFL1 ('TH',T,H,z,kph,0,Dmin,Dmax,tt,P, D,ierr,herr)
c      call ABFL1 ('TP',T,P,z,kph,0,Dmin,Dmax,tt,pp,D,ierr,herr)
c      call ABFL1 ('DS',D,S,z,kph,0,Dmin,Dmax,T, P,dd,ierr,herr)
c
c  When calling the ABFL1dll routine, the inputs are different::
c      call ABFL1dll (a,b,z,kph,ab,Dmin,Dmax,T,P,D,ierr,herr)
c
c  The examples above are repeated below for this call::
c      call ABFL1dll (T,H,z,kph,'TH',Dmin,Dmax,tt,P, D,ierr,herr)
c      call ABFL1dll (T,P,z,kph,'TP',Dmin,Dmax,tt,pp,D,ierr,herr)
c      call ABFL1dll (D,S,z,kph,'DS',Dmin,Dmax,T, P,dd,ierr,herr)
c
c  This routine accepts only single-phase inputs, it is intended primarily
c  for use with the more general flash routine ABFLSH, but can be called
c  independently for increased calculation speed if the inputs are
c  known to be single-phase.  This will avoid the call to the flash routines
c  to determine the phase of the inputs.  If this routine is called, but
c  the inputs are 2-phase, either an incorrect root or a metastable state
c  will be returned (which is OK if the metastable state is desired).
c
c  However!  This routine is not necessary because all flash calls can be made
c  through a call to ABFLSH or ABFLSHdll.  It is recommended to use either
c  the REFPROP or ABFLSH routines for all flash calculations even for single
c  phase calls when it is not necessary to check the phase of the input
c  properties.  For example, the TH call above for a known liquid phase state
c  could be called like this::
c
      iFlag=10  !Indicates that the input state is in the liquid.
                !Use iFlag=20 for vapor phase states.
      call ABFLSHdll ('TH',T,H,z,iFlag,tt,P,D,Dl,Dv,
     &                   x,y,q,e,hh,s,Cv,Cp,w,ierr,herr)

c  Further information is given in the comments under the ABFLSH and REFPROP
c  subroutines.
```

Thanks for bringing this to our attention!  Let us know if you see anything above that appears incorrect, and we will get it fixed.
