### ISSUE TITLE
Installing REFPROP 10 to a user defined location and without need of system variables

### ISSUE THREAD

**Issue by snyderdj4** [usnistgov/REFPROP-issues#127]
Is there a way to install REFPROP 10 to a user chosen directory?  Also, is there a way to install REFPROP where system environmental variables do not need to be changed?

It appears that the current installation package is trying to do both of these things. 

It would be desirable to install in a user defined location and to use User Variables instead of System Variables.

Thanks

**Comment by ianhbell** [comment]
Yup, you are offered an installation path option when you install REFPROP.  It is not currently possible to install without changing environment variables at all because the path to the DLL needs to get onto at least the user environment PATH variable.  We set RPPREFIX as well for convenience, but that could be optional.  You also don’t strictly need to use the installer, and can just copy the files to right place and manage the environment variables yourself, but that’s not what we recommend; there might be some unpleasant surprises.

**Comment by EricLemmon** [comment]
You could also make your own installer.  If you wish to do this, please email us (eric.lemmon@nist.gov and ian.bell@nist.gov) and we can send you the installer make file that we used.

**Comment by snyderdj4** [comment]
Thank you Eric and Ian for your timely help on this.  

Providing the REFPROP files in a zip file solved the problem.  I was able to update the PATH variable to locate the REFPROP files.  I was also able to define the variable RPPrefix.  I was able to do both of these with the user environmental variables.  The internal documentation in the REFPROP.xls was pretty clear on implementing the add-ins and making the location of REFPROP a trusted location.  The updated documentation in REFPROP v10 is much appreciated.

**Comment by ianhbell** [comment]
@snyderdj4 I'm glad you were able to get this working.  To be honest though, I'm surprised that you were able to fiddle with your user environment variables.  On my computer, I need to authenticate to even access the user environment variables.  Is there an alternative place to access the user system variables than through "Advanced System settings"?

**Comment by ianhbell** [comment]
A little bit of googling takes me to: http://www.kscodes.com/misc/how-to-set-path-in-windows-without-admin-rights/ .  That's interesting, didn't know about that.

**Comment by ianhbell** [comment]
Another thought for future Ian is that it should be possible to make the installer run without admin rights by judicious use of this flag in the InnoSetup: http://www.jrsoftware.org/is6help/index.php?topic=setup_privilegesrequiredoverridesallowed

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by snyderdj4** [comment]
Yes.  Thanks for your help.
