### ISSUE TITLE
Bug in autofill for values in a column

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#130]
I was using the feature in the GUI in a Specified State Points table where a right-click on a column heading lets you auto-fill many rows in that column with a given increment.  In this case, I wanted to give a pressure of 101325 Pa with increment 0 for rows 1 to 5001.  It only fills to row 1000, and then it stops (without giving the user any warning).  It appears that it does not allow "Last Row" values to exceed 1000 -- for example if I tell it to fill from row 1234 to 5000 it will put the value in row 1234 but nowhere else.

**Comment by EricLemmon** [comment]
I believe this one is fixed now, but of course more testing will only tell if that is really true.  The maximum you can add to the table with this option was increased to 10000.  Above that a message will appear to indicate that.

**Comment by nist-aharvey** [comment]
Something is still a little funny.
I bring up Specified State Points, right-click on pressure, and ask it to fill in from rows 1 to 11111 with .101325 with increment of 0.
It fills in the numbers and tells me that there is a maximum of 10000 rows, which is fine.
But then it shows the “Calculating” window for maybe 5-10 seconds, as though it is trying to calculate the points.  When in this case it should not be calculating anything yet since I have only specified one column.

---------------------------------------------------------------
Dr. Allan H. Harvey | aharvey@boulder.nist.gov
Applied Chemicals and Materials Division
National Institute of Standards and Technology
325 Broadway, Boulder, CO  80305-3337
Phone: 303-497-3555

**Comment by EricLemmon** [comment]
That is necessary because the GUI does not know if you have entered anything else and it must search through each line to see if a second input has been entered.  And yes, it would be possible to write code that would keep track if anything has been entered into a table already, but there are too many other requests requiring our time that keep us from making the GUI do everything.  Sorry!
