### ISSUE TITLE
Failure of large paste in Specified State Points

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#131]
Pasting a large amount of input into a Specified State Points table fails, and not very graciously.
I changed pressure units to Pa, and then did Specified State Points.
For T and P, I pasted in columns C and D from the attached spreadsheet (50001 rows).
It gave a spinning circle for 5 or 10 minutes, then started calculating, eventually giving a "Selected inputs are not allowed" error.  Inspecting the results, it appears to have calculated the first 21200 points correctly, and then something went wrong.  After which it will not calculate any more points in that table, even if I type them in individually, even if I clear out results and start from scratch.
[PasteBug.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2968857/PasteBug.xlsx)

**Comment by EricLemmon** [comment]
This bug is fixed now, it limits the maximum number of rows to 10000 (for pasting data in, not for adding a few more points at the end of the table).  A new GUI is up in the same place as before.
