### ISSUE TITLE
How is Critical Point of a mixture defined?

### ISSUE THREAD

**Issue by zxh109** [usnistgov/REFPROP-issues#137]
I have a fundamental question about mixtures: What is the definition of critical point for a mixture? 

I expected that the definition of a critical point for a mixture is the same as a pure fluid. But it seems that I am wrong.

For a pure fluid, the critical pressure is the dividing pressure of whether 2-phase state exists or not: when P<Pc, two phase region exists; when P>Pc, 2-phase does not exist. On the T-s diagram, the isobaric line of critical pressure is tangent to the saturation line, and the critical point is the tangent point between the two curves. In other words, critical point is where the vapor saturation line meets the liquid saturation line, as shown below:
![Critical point on T-s diagram - Water](https://user-images.githubusercontent.com/48798228/54767593-d7126380-4bd3-11e9-809d-6d7f6b46e69a.PNG)
      Figure 1: Critical Point of Water on T-s Diagram 
 
For a mixture, the T-s diagram shows a different picture: shown below is for the Typical Natural Gas (critical point: Pc=777.22psia, Tc=-99.723°F; picked up from the Substance menu in REPFROP).  
![Critical point on T-s diagram - Typical NG](https://user-images.githubusercontent.com/48798228/54780953-742fc500-4bf1-11e9-979b-a9225a80d335.PNG)
      Figure 2: Critical Point of Typical Natural Gas on T-s Diagram

On this diagram, the isobaric line @ Pc intersects with the saturation line: when T<Tc, the fluid is subcooled; when T>Tc, but <-28.65°F, it becomes 2-phase; when T>28.65°F, it enters in the gas region. At another pressure of about 962 psia, the isobaric line is almost tangent to the saturation line. In my understanding, the critical point should be around the **red dot**, instead of the **black star point**, shown on the diagram. 

Just wondering why this happens? What is the exact definition of critical point of a mixture? Can you recommend some reference book on this topic for me?

Thanks.

ZXH109, a user of REFPROP 10.0

**Comment by ianhbell** [comment]
Good question, and one close to my heart!  The critical point of mixtures is indeed something challenging to wrap our head around.  I would recommend that you take a look at my paper in FPE about the calculation of critical points : https://www.sciencedirect.com/science/article/pii/S0378381216305349 (preprint: http://ws680.nist.gov/publication/get_pdf.cfm?pub_id=920895).

For mixtures, all bets are off with critical points.  In the most generality, you can have zero, one, or more critical points for a given composition; sometimes you can have 3 or more.

You might also want to check out Ulrich Deiters' book on high-pressure phase behavior for an alternative (and recommended) means of calculating the critical point(s): 
Deiters, Ulrich K., and Thomas Kraska. High-Pressure Fluid Phase Equilibria : Phenomenology and Computation, Elsevier, 2012. ProQuest Ebook Central, https://ebookcentral.proquest.com/lib/noaalabs-ebooks/detail.action?docID=892233.

REFPROP does not calculate the thermodynamically-consistent critical point; rather it interpolates the isopleth of the phase envelope, which yields a very good, but not perfect, _estimation_ of the critical point.  Another warning: REFPROP only returns one critical point, even if there are more than one.

**Comment by zxh109** [comment]
Thanks for the comments. It sounds that there is much more knowledge than I imagined to completely understand this issue.

For now, I only want to know if there exists such a "critical point" for a mixture, which has the same physical meaning as that of a pure substance on the T-s (or other type of ) diagram, i.e., the meeting point of **dew point line** (vapor saturation line for pure substances) and **bubble point line** (liquid saturation line for pure substances), or the **red dot point** in Figure 2 of my original post of this thread.

If such a point exists, I wonder if you could present it as an output?

**Comment by EricLemmon** [comment]
The calculation of the critical point for a mixture is far more complex than that of the critical point of a pure fluid.  The articles Ian pointed to explain that.  Graphically you can view the point (at least for a simple Type 1 mixture) as the location where the liquid and vapor densities cross.  Below are two pictures for a methane/hexane mixture.  The first one contains a table calculated from the Calculate/Phase Boundary option in the Refprop GUI.  To get all the compositions as shown, go to Options/Properties and turn on the option labeled Bulk, Liquid, and Vapor Properties.  Notice how in the table that between 4.5 and 4.7 mol/dm^3, the densities meet and then cross.  This corresponds to a temperature between 480.2 and 482.3 K.  Then in the second picture is a plot showing the compositions plotted against density from this table.  The vertical line in the plot is simply all the calculations in the table at 0.5/0.5 composition.  I hope this helps!

![image](https://user-images.githubusercontent.com/42392984/54872264-f271a000-4d86-11e9-8230-e2a887fc14f0.png)
![image](https://user-images.githubusercontent.com/42392984/54872272-0fa66e80-4d87-11e9-9d40-23b9d91d9a6c.png)

**Comment by ianhbell** [comment]
Can we close this issue for now?

**Comment by zxh109** [comment]
Thanks Ian and Eric for the comments. From your comments I understand that calculation of the critical point of a mixture is very complicated, and there might be no, one or more critical points for a mixture. 

For engineering application purposes, I may not need to know how those points are calculated, but I want to know if a point similar to a pure fluid's critical point exists. On a T-s diagram, this is the point where the dew point line and the bubble point line meets, or it is the tangent point between the isobaric line of Pc (critical pressure) and the saturation line (combination of bubble point line and the dew point line, assuming such a line is continuous and smooth at the meeting point). If such a point exists, is there a way to calculate in REFPROP?

Thanks again.

**Comment by EricLemmon** [comment]
There is no similarity between the definitions of the critical point for a pure fluid and that for a mixture.  The mixture definition requires derivatives of properties with respect to composition to calculate, and a pure fluid requires derivatives with respect to density only.  The critical point for a mixture is also not the point where Pc and the saturation line are tangent.  In fact for many mixtures there is no such point.  Take a look at the attached picture for a 50/50 mole fraction mixture of methane and decane, which shows how the critical isobar enters the two-phase region after passing through the critical point.  The blue line represents bubble-points and the red line represents dew-points.  Note how at entropies above the critical entropy there are two solutions for the dew point.  The upper solution is generally referred to as being a retrograde state.

![image](https://user-images.githubusercontent.com/42392984/55005230-39d37880-4fa1-11e9-9764-c79d9b539728.png)

**Comment by zxh109** [comment]
Understand. Thanks for the explanation.

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by zxh109** [comment]
Yes. Thanks.
