### ISSUE TITLE
Strange T limits for mixtures

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#139]
The temperature limits for mixtures don't seem rational compared to the pure-component equations of state.
For example, both the CO2 and He EOS have Tmax = 2000 K, but when I make a mixture it gives errors and warnings telling me that Tmax = 1459.7.
If my mixture is CO2 and N2, they both also have Tmax = 2000, but there the Tmax for mixture calculations is 2007.53 K.
For the predefined mixture "air" all the pure EOS have Tmax = 2000, but the mixture uses Tmax = 1993.69.
It seems to me that the logical thing would be to use the Tmax that is lowest of the components in the mixture, or maybe a mole-fraction weighted average of the Tmax of the components.  But clearly it is doing some different calculation, which at least in the case of CO2/He seems unnecessarily restrictive.

**Comment by EricLemmon** [comment]
Tmax is calculated as:

Tmax(mix) = Tred(mix) / Sum [x(i) * tau_max(i)]

where Tred is the reducing value of the mixture and tau_max(i)=Tc(i)/Tmax(i).  The value of Tred comes from the mixture model - for some mixtures without fitted interaction parameters, it can be viewed as a mole fraction weighted sum of the critical points of the pure fluids.

With this method, the limits of each EOS are never exceeded.  For example, at 50/50 helium/CO2, a temperature of T=2000 K would be equivalent to a tau of Tred/T, where Tred might be 0. 5 * 5.19 K + 0.5 * 304 K = 155 K and thus tau=155/2000=0.0775.  This translates to using a temperature on the CO2 equation of state of T = Tc/tau = 304 K/0.0775 = 3922 K.  Thus a state point at 2000 K for the mixture exceeds the pure fluid EOS of CO2 by a factor of nearly two.
