### ISSUE TITLE
REPPROP 10 Beta - P/T Plot Incorrect.

### ISSUE THREAD

**Issue by CallieAYYC** [usnistgov/REFPROP-issues#147]
Unable to replicate the same chart as Issue #146 using Beta files.

My mol% mixture is as follows
Nitrogen 2.32%
Carbon Dioxide 0.01%
Methane 97.66%
Ethane 0.01%

P/T curves seems incomplete.

### Versions

**REFPROP Version:** [10.0.0.61]  
**Operating System and Version:** [Win10]  
**Access Method:** [Standard REFPROP GUI]  

10.0
![image](https://user-images.githubusercontent.com/39857380/55225822-6e4a6d00-520b-11e9-996c-0f8b11a8e56d.png)

10.0.0.61
![image](https://user-images.githubusercontent.com/39857380/55226072-034d6600-520c-11e9-85d6-aac01841f21b.png)

**Comment by CallieAYYC** [comment]
Just realised the composition defaults to mass fraction instead of mole fraction when REFPROP dll is updated. Reverted back to mole fraction and results are as expected.

**Comment by EricLemmon** [comment]
Glad to hear all is working now.  And even though you figured it out, your post will help others that have similar problems.  The mole/mass fraction issue has caught many people by surprise.  I have done it myself often.

Best wishes,
Eric
