### ISSUE TITLE
REFPROP 10.0 - Water/Hydrocarbon Mixture Dew Point EOS

### ISSUE THREAD

**Issue by CallieAYYC** [usnistgov/REFPROP-issues#148]
### Description

Cannot replicate water hydrocarbon P/T phase diagrams according to http://www.jmcampbell.com/tip-of-the-month/2007/10/water-sweet-natural-gas-phase-behavior/ 

The water dew point curve shifts right instead of staying static where the water content has not changed. Quadruple points should be expected.

### Versions

**REFPROP Version:** [10.0]  
**Operating System and Version:** [Win10]  
**Access Method:** [Standard REFPROP GUI]  

### Additional Information

Mixture 1
![image](https://user-images.githubusercontent.com/39857380/55227825-5fb28480-5210-11e9-9db2-f9201600dbce.png)

Mixture 3
![image](https://user-images.githubusercontent.com/39857380/55227867-7f49ad00-5210-11e9-8259-30cb10d441e1.png)

Expected Behaviour - Red Line
![image](https://user-images.githubusercontent.com/39857380/55227936-a7d1a700-5210-11e9-999e-0103921c20f3.png)

**Comment by ianhbell** [comment]
Sadly the inclusion of hydrate phase equilibria is outside the scope of NIST REFPROP.  This is supported in the TREND software developed out of the Thermodynamics group of the Ruhr-Universitat Bochum in Bochum Germany.

**Comment by CallieAYYC** [comment]
Hi Dr Bell, forgive my lack of knowledge, this is the first time I have come across this terminology. Just to clarify, wouldn't that still suggest the Mixture 3 phase diagram produced by REFPROP (minus the hydrocarbon phase envelope I overlaid for illustration) be incorrect? I was actually looking at water content in hydrocarbon mixtures rather than hydrate formation, and my research led me to the above. It peaked my interest as I have not seen that shape phase envelope before. 
Is it possible to manually overlap two separate outputs, one for water and one for the HCDP and pick the highest value and plot that to get the phase diagram, but I am thinking none of the internal calculations would then match if I was to calculate enthalpies and densities for these mixtures. 
![image](https://user-images.githubusercontent.com/39857380/55360874-83eeb980-54cd-11e9-9c92-dc3e587bf7eb.png)

**Comment by ianhbell** [comment]
I'm not sure I totally follow your idea, but if you wanted for graphical purposes to overlap a normal isopleth of the phase envelope and the saturation pressure curve for water that is doable.  But internally, I don't think we could apply a similar logic inside REFPROP.  It wouldn't jive with our standard approach for phase equilibrium.  My understanding of that paper is that it only serves as a heuristic guideline, but not a thermodynamically-consistent approach.
