### ISSUE TITLE
DOI missing when getting info from fluid list

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#149]
In the GUI, go to substance, Pure Fluid. Select a fluid (e.g., ethane).  Click the info button.  The resulting info window does not have the DOI link:

![image](https://user-images.githubusercontent.com/11966765/55345993-91288b80-546e-11e9-9aef-75e7db6282e1.png)

**Comment by EricLemmon** [comment]
This one was also fixed in the update I did for #134.  The update is on my q drive.

**Comment by ianhbell** [comment]
I know -- that’s the one I used ☹

**Comment by ianhbell** [comment]
Fixed
