### ISSUE TITLE
GUI display issue (9.4.4.43)

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#15]
the status bar at the bottom of the main screen of the REFPROP GUI has partially cut off text, see attached screen shot

my system and display info:
Win7 Pro SP1
display text size "Medium - 125% (default)"
screen resolution: 1920x1080

![refprop - nist reference fluid properties dll version 9 1](https://user-images.githubusercontent.com/39253715/39977983-b4898b08-570b-11e8-9e83-840fd5932a9b.png)

**Comment by HightopRaven** [comment]
The truncated text issue is always there whether the window is maximized or not.

When changing my system display settings to "smaller - 100%" the issue is resolved. So there is a work around, however the "medium - 125%" setting is the default setting for Windows7.

I previously worked with Eric to resolve dozens of similar text size issues throughout all the various windows. This is one that was previously fixed in an earlier build but has returned.

The root cause seems to be some quirky behavior with how Win7 handles system text display. The solution seems to be adding a few more pixels of space to avoid overlapping display objects.

![image](https://user-images.githubusercontent.com/39253715/40009207-61654066-576f-11e8-9f71-ef43f3fcd47d.png)

**Comment by HightopRaven** [comment]
This issue has gone away now that I am running a clean copy of 9.4.4.43 (without conflict due to a copy of 9.1 that was also installed on the same computer). It appears that I was actually (somehow?) running v9.1 instead of v9.4.4.43.

This is what I now see when display setting is "medium - 125% (default)".

![image](https://user-images.githubusercontent.com/39253715/40191199-b7b51840-59ce-11e8-8ba4-96347bb7b877.png)

**Comment by ianhbell** [comment]
Good, can you please close the issue then?
