### ISSUE TITLE
R1336mzz(Z) properties

### ISSUE THREAD

**Issue by Houpei** [usnistgov/REFPROP-issues#151]
I have noticed disagreement between calculation from RefProp and measurements in the literature.

The zip file contains a python code and a csv data file. They are generated by Dr. Bell.

[r1336mzzZ.zip](https://github.com/usnistgov/REFPROP-issues/files/3045561/r1336mzzZ.zip)

Tanaka, K., Akasaka, R., Sakaue, E., Ishikawa, J., & Kontomaris, K. K. (2016). Thermodynamic Properties of cis -1,1,1,4,4,4-Hexafluoro-2-butene (HFO-1336mzz(Z)): Measurements of the pρT Property and Determinations of Vapor Pressures, Saturated Liquid and Vapor Densities, and Critical Parameters. Journal of Chemical & Engineering Data, 61(7), 2467–2473. https://doi.org/10.1021/acs.jced.6b00169

I noticed this in RefProp 9.0, in Windows 10, from matlab access.
Dr. Bell's access RefProp 10, with python.

**Comment by ianhbell** [comment]
Thinking about this data for a few seconds more, it seems like REFPROP is doing the right thing: it is giving liquid densities when the TP inputs correspond to the liquid phase.  If you look at the 88 kg/m^3 pseudo-isochore, the saturation temperature is just about 400 K:

![image](https://user-images.githubusercontent.com/11966765/55650660-9d308800-57a3-11e9-96d4-9b7562990362.png)

Therefore, along the isochore, any values for lower temperatures correspond to the liquid phase.  I suspect that is the behavior throughout the data.

**Comment by Houpei** [comment]
I see. The disagreement only happens when the state is very close to the two-phase.
When it is subcooled or superheated, the calculation is correct.
I am still using RefProp 9 now and I will upgrade to v10 and try it again.

**Comment by ianhbell** [comment]
It is not only near the phase boundary that the problem exists; it is also a problem for any temperature below the saturation temperature for the given density, which is given in in the table (Table 7) in their paper.  I think this is not a REFPROP question per se.  They could have done a better job in their paper of describing which points are metastable, and which are homogeneous.  PT inputs will only work for homogeneous phases.

**Comment by mingle147** [comment]
Excuse me, I want to ask maybe a very simple question. Why can't I find R1336mzz in the REFPROP software? How to add R1336mzz on my own?

**Comment by ianhbell** [comment]
@mingle147 Please don't hijack existing issues. Please open a new one with your question

**Comment by ianhbell** [comment]
But in this case, you just need to upgrade to version 10.0
