### ISSUE TITLE
Two-phase transport properties from low-level coolprop calls

### ISSUE THREAD

**Issue by lorbek** [usnistgov/REFPROP-issues#157]
### Description
Hello,

When using low-level CoolProp calls it is possible to obtain two-phase transport properties such as cp and viscosity. As far as I know these values are generally obtained from empirical models. I am wondering if that is the case behind this calculation? Or if not, should I consider this output as incorrect?

**Comment by ianhbell** [comment]
CoolProp should not return values for c_p or viscosity for vapor qualities Q in the range 0 < Q < 1.   REFPROP correctly does not return values for values between saturated liquid and vapor.  Both return the correct values *at* saturation (Q=0 and Q=1)

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:\Program Files (x86)\REFPROP'
RP = REFPROPFunctionLibrary(root+'/REFPRP64.DLL') ;
RP.SETPATHdll(root)
MOLSI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum

for Q in [0, 0.5, 1]:
    print(Q)
    r = RP.REFPROPdll('PROPANE','QT','R;CP;VIS',MOLSI, 0, 0, Q, 300, [1.0]+[0.0]*19)
    print(list(r.Output[0:3]))

    import CoolProp.CoolProp as CP
    AS = CP.AbstractState('HEOS', 'PROPANE')
    AS.update(CP.QT_INPUTS, Q, 300)
    print([AS.gas_constant(), AS.cpmolar(), AS.viscosity()])
```
yields
```
0
[8.3144598, 120.80455872500039, 9.527447177875316e-05]
[8.314472, 120.80473982443115, 9.527919021165042e-05]
0.5
[8.3144598, -9999990.0, -9999990.0]
[8.314472, 143.14837257703974, 8.823587088650505e-06]
1
[8.3144598, 89.98884725666883, 8.245087141573396e-06]
[8.314472, 89.98898313949046, 8.339784250450826e-06]
```
