### ISSUE TITLE
Refprop requires the R134a fluid file to be present when loading other fluids.

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#158]
### Description

An error message with error number -101 came back when calling SETUP that it couldn't find R134A.FLD when loading other fluids

When I put R134A.fld in the same folder the problem goes away.

**Expected behavior:**

I should only need to include the files I use in my FLUIDS folder.

**Actual behavior:**

Refprop wants other fluids.

### Versions

**REFPROP Version:  10.0**

**Comment by EricLemmon** [comment]
There are many fluids for which the transport properties use a method called Extended Corresponding States (ECS) to calculate the properties.  The basic idea is that every fluid behaves in a similar manner to some other similar fluid if the properties of the inputs (temperature and density) of the two fluids are reduced by the values of their critical points (Tc and Dc).  For example, R143a might have similar transport properties as those of R134a, except that the values might be expanded by some factor (sub-example: perhaps the viscosity might be 20% bigger along the saturation line, but still follow the same trend).  Thus if a fluid has very limited data, using such an approach allows us to develop a model to obtain properties at all state points simply by a few adjustable parameters that scale the two equations.  We then try to find a similar fluid that has a dedicated transport equation and use that as our base.  Over the years we have found that typically the following fluids have worked quite well for this process:  nitrogen, propane, R134a, and dodecane.  There are a few other oddballs that have been used, but they have all been replaced except for octane that is used for isooctane.  Thus if a fluid uses ECS for the transport properties, it will need to have one of these four files available.  If it is not there, then the transport routines will fail.  

There are a few cases where a fluid has dedicated transport equations, but with limits that do not cover the full surface.  In those cases, the ECS model kicks in when the dedicated equation is out of bounds.  Generally this only happens at low temperatures (near the triple point).
