### ISSUE TITLE
NIST REFPROP - Mixture Gas properties Near Super critical States

### ISSUE THREAD

**Issue by audigr** [usnistgov/REFPROP-issues#159]
I am using the NIST REFPROP (DLL version 9.1; Operating System Windows 7 Enterprise). My question is regarding the method used in ref prop to calculate mixture gas properties. I have a mixture of hydrogen and helium in a tank. (mass fraction of hydrogen is 0.9 and mass fraction of helium is 0.1) . The partial pressure of helium is 4.5 psia and the total pressure of the tank is 46 psia. The tank temperature is 85 K. In order to calculate the mixture gas property, say for instance specific heat i would first evaluate the individual gas property (usually done at tank gas pressure and temperature). But for my particular case if i try to evaluate the individual gas property of helium at 46 psia this would be at its super critical state. Instead of throwing me an error nist still gives me estimates of this mixture. What is the procedure Nist uses to proceed with this calculation?

**Comment by ianhbell** [comment]
The calculation for the mixture is far from the same thing as considering the two components individually.  A common example of where that kind of thinking can end up in troubles is to consider a gas dissolved in a liquid (for instance nitrogen dissolved in water).  If you were to consider the fluid to be pure nitrogen, you would be easily fooled.

The long and the short of it is that mixtures are not simply mixtures of pure fluids in a lot of very important ways.

In REFPROP, multi-fluid mixture models are used (based on a formulation like that described here: http://www.gerg.eu/public/uploads/files/publications/technical_monographs/tm15_04.pdf), and in these models, you can evaluate directly mixture properties without invoking the properties of pure fluids at the same temperature and pressure

Here is an example of doing your example in the Python programming language.

``` python
# Setup
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:\Program Files (x86)\REFPROP'
RP = REFPROPFunctionLibrary(root+'/REFPRP64.DLL') ;
RP.SETPATHdll(root)
MOLSI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum

# Do calculation
p = 317159 # [Pa] <-- 46 psia
T = 298 # [K]
r = RP.REFPROPdll('H2*He|0.9*0.1 mass','PT','D;CP', MOLSI, 0, 0, p, T, [0.0]*20)
assert(r.ierr == 0)
Dmolar, Cpmolar = r.Output[0:2]
print('Dmolar:', Dmolar,' mol/m^3')
print('Cpmolar:', Cpmolar, ' J/(mol*K)')
```
yielding
```
Dmolar: 127.75675294782098  mol/m^3
Cpmolar: 28.422429602015683  J/(mol*K)
```

**Comment by audigr** [comment]
Thank you very much. That really helps

**Comment by ianhbell** [comment]
Glad to hear! If I have answered your question to your satisfaction, can you please close the issue?
