### ISSUE TITLE
predefined blend load error (9.4.4.43)

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#16]
the following fatal error occurs when selecting the predefined blend R515A; the REFPROP application terminates after the error; the component fluids can be selected and properties generated without error

![image](https://user-images.githubusercontent.com/39253715/40007808-c4ab4656-576b-11e8-868b-ad5d4edc1b8f.png)

![image](https://user-images.githubusercontent.com/39253715/40007737-98adb52a-576b-11e8-9c84-51809ce732ab.png)

**Comment by ianhbell** [comment]
Thanks for the report, I have made an internal note of this, and will add tests to try to load all mixture: https://github.com/ianhbell/REFPROP-tests

**Comment by HightopRaven** [comment]
Found three other predefined mixtures with the same problem: R459A, R460A, and R460B. The common theme is that the problem component seems to be R1234ze(E).

=====
![image](https://user-images.githubusercontent.com/39253715/40008162-aae5ec2a-576c-11e8-8a0a-532863d8b30b.png)

![image](https://user-images.githubusercontent.com/39253715/40008176-b41df27e-576c-11e8-8bc4-2407251638a5.png)

=====
![image](https://user-images.githubusercontent.com/39253715/40008707-f672d6fc-576d-11e8-808d-d7c6d5116f10.png)

![image](https://user-images.githubusercontent.com/39253715/40008633-c78fb01c-576d-11e8-88b8-f4407ce0c011.png)

**Comment by ianhbell** [comment]
Yikes...  Weirdly they all load fine for me (some others don't load, but don't crash), but I am calling the REFPROP DLL from C++, so, that might make the difference.  Eric and I will diagnose.  Thanks for the report.

**Comment by ianhbell** [comment]
Hmmm... they load fine for me from the GUI.

**Comment by ianhbell** [comment]
Just for fun, could you perhaps uninstall your beta, make sure all the fluid files are deleted, and try again?  My suspicion is that a slightly older fluid file is hanging out that REFPROP can't read since it works fine for me.

**Comment by ianhbell** [comment]
Yes, your files are definitely out of date.  This is what my predefined mixture dialog looks like:

![image](https://user-images.githubusercontent.com/11966765/40010278-79bd3ef6-5761-11e8-8128-25d93d11e78d.png)

**Comment by HightopRaven** [comment]
That is strange... not only had I uninstalled 9.4.4.x from my system (9.4.4.39?), I had deleted the C:\Program Files (x86)\REFPROP folder before installing 9.4.4.43. I know that I did so, because the uninstall could not remove the Excel add-in files, so I first uninstalled the add-in from Excel and removed from the add-in list and then manually deleted the REFPROP folder. One possibility... I had not uninstalled 9.1.x from my system (still shows up in Windows Conrtol Panel list of programs) and all I had done was renamed the old v9.1 REFPROP folder (so that it could be renamed to quickly restore v9.1 if I needed to use it).

I will repeat the process again and report back what happens. If the 9.4.4.43 problem persists then I will also uninstall 9.1.x.

**Comment by HightopRaven** [comment]
just documenting what shows up in Win7 control panel, programs & features, while I have both 9.1 (with 9.11 patch install) and 9.4.4(.43) installed; perhaps this blend load error is related to a conflict between 9.1 and 9.4.4

![image](https://user-images.githubusercontent.com/39253715/40188869-eecf0954-59c8-11e8-88d5-8b539a7e7c9d.png)

**Comment by HightopRaven** [comment]
After uninstalling both 9.4.4 and 9.1 and 9.11... and deleting the folder \REFPROP, then re-installing 9.4.4.43 as the only copy of REFPROP on my computer, this issue with predefined blend load errors disappears and is completely resolved.

So the instructions to beta testers that "there is no need to uninstall v9.1" may need to be qualified to determine under what conditions that is true (such as what path is used for the install directory).

![image](https://user-images.githubusercontent.com/39253715/40190675-7f652300-59cd-11e8-91f9-dc75c4c25a79.png)
