### ISSUE TITLE
Uncertainty R134a Equation of State

### ISSUE THREAD

**Issue by cberghuis13** [usnistgov/REFPROP-issues#161]
I am measuring the capacity of a heat exchanger in a system running R134a and need additional fluid information to complete an uncertainty analysis for the experiment. 

The available REFPROP fluid information shows:

Typical uncertainties are 0.05% for density, 0.02% for vapor
pressure, 0.5-1% for heat capacity, 0.05% for vapor speed of sound,
and 1% for liquid speed of sound, except in the critical region.

What should be assumed for the uncertainty contribution of the equation of state for enthalpy?

### Versions

**REFPROP Version:** 9.1

**Comment by ianhbell** [comment]
A very good question!  Here is one possible (semi-) solution: http://orbit.dtu.dk/ws/files/149534023/Perdue_conference_uncertainty_EoS_vs_exp_FINAL_1.pdf

If in fact what you care about is a _change_ in enthalpy (as I suspect given the application), then you can (very roughly) approximate the change in enthalpy as
h_2-h_1 = c_p(T_2-T_1)
and therefore the uncertainty could be approximated as the uncertainty in c_p.  Maybe you want to take an average value for the c_p uncertainty if the temperature changes significantly through the HX.

This is a question with no easy answer....
