### ISSUE TITLE
vagueness of British thermal unit

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#17]
My apologies for what amounts to a feature request this late in the cycle of REFPROP v10... I understand if it is too late to make a change at this point in time, perhaps this becomes a feature request for v10.1.

For the users working in "English" units of measure, it is not clear which variant of "Btu" is used. The thermochemical variant uses an average of the heat required to raise one pound of water by one degree, averaged over a temperature range from the freezing point to the boiling point. However other variants are based on either a single reference temperature at which the specific heat is used to define the Btu, or other convention such as the International Table variant.
https://en.wikipedia.org/wiki/British_thermal_unit

Setting the REFPROP application Preferences to check or uncheck "Use steam conversion value for Btu and cal" is described in the user manual, but to most users the implications of checking this box or not is totally obfuscated.
  
![image](https://user-images.githubusercontent.com/39253715/40196313-1dacc346-59de-11e8-942e-e84b5408cb25.png)

from the User Manual:
"The steam conversion option will use the conversion 1 cal = 4.184 J when not selected, and the conversion 1 cal = 4.1868 J when selected. The latter value is generally used with the calculation of water and steam properties. The former value (4.184) should be used with all other fluids and mixtures."

And this issue is very much hidden for the Excel add-in users, who must edit a line of VBA code to change the conversion factor between calorie and joule.

The request is to modify the unit symbols and add support for both of these units:
Btu(IT)
Btu(th)

or alternatively, if subscripts are possible then the following where the last two letters are subscripts:
BtuIT
Btuth

1 Btu(IT) = 1055.05585262 J
[based on 1 cal = 4.1868 J]

1 Btu(th) = 1054.350 J
[based on 1 cal = 4.184]

These proposed unit symbols are found in NIST Special Publication 811 (2008).
https://physics.nist.gov/cuu/pdf/sp811.pdf

Distinguishing between which variant of Btu is being used becomes important when engineers are working with multiple fluids, such as water and refrigerant in a heat exchanger, and should take care that fluid properties from both sides of the device are using the same units of measure. Right or wrong, good or bad, AHRI Standard 550/590-2015 requires the use of Btu(IT) with the intent to reduce the incidence rate of small errors (~0.067%) due to inconsistent units of measure. No doubt that choice was influenced by the fact that a "ton of refrigeration" was originally defined in terms of water and the energy required to melt 1 ton of ice over a 24 hour time period. However, the choice by the AHRI committee that developed that particular standard is contrary to the REFPROP recommendation to use the thermochemical definition for all fluids other than water.
http://www.ahrinet.org/App_Content/ahri/files/STANDARDS/AHRI/AHRI_Standard_550-590_I-P_2015_Add1_Oct_17.pdf

Some examples to illustrate:

**Btu (IT) basis** 
1 kW = 3412.141635 Btu/h
12000 Btu/h= 3.51685284 kW
1 ton of refrigeration = 1 tonR = 12000 Btu/h = 200 Btu/min
0.0001000 h·ft²·°F/Btu(IT) = 0.01761 m²·K/kW

**Btu (th) basis**
1 kW = 3414.42595 Btu/h
12000 Btu/h= 3.5145 kW

The numerical values of the unit conversions above demonstrate that certain unit of measure conversion constant used throughout the industry assume Btu(IT), such as how the "ton of refrigeration" has been defined, while occasionally some such as 3414.(...) show up that have assumed Btu(th).

**Comment by ianhbell** [comment]
I'll pass this along to Eric, but at the very least we could update the docs.  What should we add to them?  I'm in charge of the docs now.  The relevant page is up here: https://github.com/usnistgov/REFPROP-docs/blob/master/doc/GUI/Menu%20Commands/Options%20Menu/preferences.rst

**Comment by ianhbell** [comment]
Or you could just always use SI units :)

**Comment by HightopRaven** [comment]
I'm at least bilingual when it comes to units of measure! While I like SI my chosen industry uses a mish-mash-hodge-podge of unit systems.

**Comment by ianhbell** [comment]
Can we close this issue now thanks to your update to the docs?
