### ISSUE TITLE
Cannot generate saturation tables for R453A for temperatures -8oC and below

### ISSUE THREAD

**Issue by luckyoneputt** [usnistgov/REFPROP-issues#170]
### Description

Cannot generate saturation tables for R453A for temperatures -8oC and below

### Steps to Reproduce

1. Select R453A as a predefined mixture from the Substance Menu
2. Select SI with Celsius as the Units
3. Select Calculate Saturation Tables.
4. Use defaults (i.e. liquid and vapour at same composition and vary Temperature).
5. Use an initial temperature of -8oC or below (Ideally we want to go to -60oC). Other defaults are left as they are (Final temperature of 80oC, Increment 5oC.
6. Run calculation

**Expected behavior:** [What you expect to happen]

Saturation tables for R453A

**Actual behavior:** [What actually happens]

Error Status popup. With error message:

[SATT error 124] Iteration for saturation state did not converge for T = 153.150K.

### Versions

**REFPROP Version:** [REFPROP version you are using]  
10.0

**Operating System and Version:** [OS you are running REFPROP on] 
Windows 10 Pro with latest OS updates.

**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  
Using the Refprop application itself

### Additional Information

This used to work in Refprop 9 i.e. we have generated the saturation table for R453A using Refprop 9.

**Comment by ianhbell** [comment]
Have you enabled initialization of the phase envelope in the preferences? If so, these calculations should be quite reliable.  Perhaps that had been enabled in REFPROP 9.x?

**Comment by ianhbell** [comment]
I cannot reproduce this problem, works fine for me.  What version of REFPROP 10 do you have? It will show in the splash screen (or Help->About).  I have the option "Initialize saturation boundaries for mixtures enabled", for what it's worth. I'm using REFPROP 10.0.0.68.

**Comment by luckyoneputt** [comment]
Help about shows : DLL version number 10.0

I also have option “Initialize saturation boundaries for mixtures enabled”.

**Comment by ianhbell** [comment]
In that case, can you please email me (ian.bell@nist.gov) for a patch?

**Comment by luckyoneputt** [comment]
I have added those DLLs (replaced the originals). Help About shows the DLL version number at 10.0.0.2. Unfortunately I still get the same error.

**Comment by ianhbell** [comment]
I sent you an updated link to a newer version.

**Comment by luckyoneputt** [comment]
Help About shows : DLL version number 10.0

I also have option “Initialize saturation boundaries for mixtures enabled”.

**Comment by ianhbell** [comment]
I don't think you successfully applied the patch then, it should read something like:
![image](https://user-images.githubusercontent.com/11966765/58672548-b158b780-8304-11e9-8625-29402ab63b32.png)

**Comment by luckyoneputt** [comment]
It works! The latest patch (10.0.0.68) results in saturation tables being calculated for R453A down to at least -80oC. Is there any danger in my using a beta patch (i.e. instability, incorrect results etc...)? For both Refprop and Refleak I can't find an update site to use i.e. I would have to email NIST directly and ask if there is a new version available. Is that correct? Basically this is a long winded way of asking how would I know to download the latest version of Refprop after your beta version goes final!

**Comment by ianhbell** [comment]
No real danger, but as the website indicates, the beta do expire later on this year. That's the only primary limitation.
