### ISSUE TITLE
Possible Error in REFPROP1 Quality Input

### ISSUE THREAD

**Issue by mbaldwin8** [usnistgov/REFPROP-issues#173]
Hi,

I am calling the REFPROP1 subroutine for methane at its saturation pressure.  My inputs are pressure and quality 'PQ'.  When I set Q = 0.0, I do not get the saturated liquid properties found in the REFPROP saturation property tables.  Furthermore, when I set Q = 1.0, I get the correct saturated LIQUID property values instead of the saturated vapor values.  Any idea what the problem could be?  My apologies for any potential obvious oversights on my end.

My test case is Methane at P_sat = 479.9 kPa.  rho_L should be 386.3 kg/m^3 and I am receiving 279.05 kg/m^3

Thank you.

**Comment by ianhbell** [comment]
Can you please fill out the entire template, especially showing your code.

**Comment by mbaldwin8** [comment]
```
SUBROUTINE SATURATED (P_SAT,THETA,DIAM,DIAM_NXT,QFLX,
     +                     MDOT,LENGTH,T_NXT,P_NXT,QUAL, X_SAT)
      INCLUDE 'CONSTS.INC'
      
      
      DOUBLE PRECISION OUTPUT(IPROPMAX),Z(NCMAX),X(NCMAX)
      DOUBLE PRECISION TEMP, PRES, MDOT, G, PI, QUAL, X_SAT
      DOUBLE PRECISION R_RHO, R_MU, R_PR, R_K, R_H, R_CP, H_NXT
      DOUBLE PRECISION VEL, FRAC_LIQ, FRIC, HTC, QFLX, DELTA_Z
      DOUBLE PRECISION NODE_TEMP(14), NODE_PRES(14), NODE_QUAL(14)
      DOUBLE PRECISION P_HEAT, G_FLUX
      CHARACTER*255 HFMIX, HF(NCMAX), HOUT, HERR              
      CHARACTER*3 HRF
      CHARACTER*50 HUNITSARRAY(IPROPMAX)
      INTEGER IUNITS,IMASS, IFLAG, NC, IERR, IUCODEARRAY(IPROPMAX)               
      INTEGER I_REGIME
      PARAMETER (G = 9.80665,PI = 3.14159)
      
      
      ICOMP = 1
      NC=1                    
      HF(1)='C:\Users\mbaldwin8\Desktop\Boil\REFPROP\FLUIDS\METHANE.FLD'      !Fluid name
      HFMIX='C:\Users\mbaldwin8\Desktop\Boil\REFPROP\FLUIDS\HMX.BNC'          !Mixture file name
      HRF='DEF'                 
      CALL SETUP (NC,HF,HFMIX,HRF,IERR,HERR)
      
      IUNITS = 21
      IMASS = 1
      IFLAG = 0
      DZ = LENGTH/1000.0
             DO III = 1,10000
                 P_SATTT = 479900.0
                CALL REFPROP1 ('PQ','D',IUNITS,IMASS,P_SATTT, 0.0,
     +                         1.0,OUTPUT,QUAL,IERR,HERR)
                IF (IERR .NE. 0 ) THEN 
                   PRINT *,'SATURATED ERROR CALLING REFPROP1: ', HERR
                   STOP
                END IF
                R_RHO_F = OUTPUT(1)
                PRINT *, OUTPUT
```

The Output from the print statement is the following vector:

```
279.050292618361 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
...
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
386.301068538940
```
The 386 is what I am looking for!  Also, when this runs standalone and not in a subroutine, I get the expected output vector:
```
386.301068538940 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
...
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
```
Thank you.

**Comment by mbaldwin8** [comment]
Forgive me, first output above should be:

```
279.050292618361 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
...
0.00000000000000 0.00000000000000 0.00000000000000
0.00000000000000 0.00000000000000 0.00000000000000
```
The 386.301068538940 was an extra print statement not included in OUTPUT

**Comment by ianhbell** [comment]
Couple of comments here (I cannot reproduce this error from Python).  My Python code is below.

1) The unit system should never be hardcoded, they should always be retrieved from a call to GETENUM
2) You should construct an array ``z`` with the first entry (only) with the value 1.0, and all others zero.  Maybe REFPROP is getting confused because you passed an array fully-populated with ones.


``` python
import os; os.environ['RPPREFIX'] = r'D:/Program Files (x86)/REFPROP'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

## Setup Refprop
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])

## Model Inputs
print(RP.SETFLUIDSdll('METHANE'))
MASS_BASE_SI = RP.GETENUMdll(0,'MASS BASE SI').iEnum
z = [1.0]+[0.0]*19
P = 479.9e3
Q = 0
IMASS = 1
print(RP.REFPROP1dll('PQ','D',MASS_BASE_SI,IMASS,P,Q,z))
```
yielding
```
0
REFPROP1dlloutput(z=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), c=386.301187992552, q=0.0, ierr=0, herr='kg/m^3')
```

**Comment by mbaldwin8** [comment]
### Description

Getting inconsistent property values when calling REFPROP1 subroutine from a subroutine

**Expected behavior:** I expect to get a density of 386.3 kg/m^3 when providing the following inputs:
P = 479.9 kPa,   quality = 0

**Actual behavior:** I actually get a value of 279.05 kg/m^3 for density (all saturated liquid properties are wrong)

### Versions

**REFPROP Version:** REFPROP Version 10.0
**Operating System and Version:** Windows 7 
**Access Method:** REFPROP Fortran files are being called from a Fortran program

**Comment by mbaldwin8** [comment]
Ian,

Thank you for your comments.  You were correct; instead of a z vector, I just entered 1.0 as the input.  After creating the z vector, the resulting value is now correct!

**Comment by ianhbell** [comment]
Excellent!  *phew*
