### ISSUE TITLE
REFPROP database limitation

### ISSUE THREAD

**Issue by JoaoSilvaPereira** [usnistgov/REFPROP-issues#174]
Hello,

Currently, I am working in a mathematical model to simulate the CO2 sublimation from biomass combustion gases. This research is for academic purposes. 

I'm using REFPROP v9 in Matlab 2019a. 

However, when the combustion gases are below 0ºC. The water part appears to be solid independent of the pressure that I defined. I think this is connected to the REFPROP temperature limitation. Nonetheless, this isn't correct because I know that I had water vapor at temperatures below 0ºC in my specific pressure conditions.

How can I solve this issue?

Regards

**Comment by ianhbell** [comment]
Please fill out the complete issue template so that we can more efficiently help you.

Please provide an example code showing the failure.
