### ISSUE TITLE
broken link (missing file) on documentation web page

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#176]
The REFPROP documentation web page (https://pages.nist.gov/REFPROP-docs/#help-file) has a broken link (https://trc.nist.gov/refprop/REFPROP.CHM). The updated help file is missing.

![screenshot_2019-06-21](https://user-images.githubusercontent.com/39253715/59953332-82d68400-944d-11e9-8b7a-a02bf1610a41.png)

**Comment by ianhbell** [comment]
Thanks for the comment, I just pushed up the CHM to the right location, might take a few minutes to update.  Please try in an hour or so.

**Comment by HightopRaven** [comment]
Resolved

**Comment by ianhbell** [comment]
Could you please close the issue in the github webpage if you are satisfied?
