### ISSUE TITLE
refrigerant calculations - R453 & R437A

### ISSUE THREAD

**Issue by uSpiwoks** [usnistgov/REFPROP-issues#179]
We use the newest version of refprop 10 and by the calculations of R453 and R437A it seems there are some issues.

Used function:
![grafik](https://user-images.githubusercontent.com/52311357/60324672-b3ef1100-9985-11e9-91d4-73bdff6c037f.png)

R453
Calculation (6 components) causes problems near vacuum (<0,1bar). A lot of error messages, it is  worse than before in version 9. Probably errors in the calculation algorithm or 'dynamic' material size behavior by using 6 components.

R437A
At some point for example pressures of 12.9 bar and 13.1 bar and also at other values, the vapor phase temperature is equal to the liquid phase temperature.
This can not be and is limited to fixed values, even with different increments.

![grafik](https://user-images.githubusercontent.com/52311357/60323785-5e196980-9983-11e9-9bc2-ae8f7df8b24b.png)

![grafik](https://user-images.githubusercontent.com/52311357/60324178-68883300-9984-11e9-93c5-317b1cc61727.png)

**Comment by ianhbell** [comment]
Thank you for your report!  Have you enabled the preference to initialize the saturation boundary?

![image](https://user-images.githubusercontent.com/11966765/60362648-bc077a80-999e-11e9-9577-535635694080.png)

For R453A, I can get down to pretty low pressures (well below atmospheric) without problems:
![image](https://user-images.githubusercontent.com/11966765/60362812-199bc700-999f-11e9-82d6-23cfd4deaae1.png)

For R437A, I made a saturation table at equilibrium, with pressures from 1.2 MPa to 1.4 MPa, and found no failures:
![image](https://user-images.githubusercontent.com/11966765/60362862-3801c280-999f-11e9-913e-157da68d7fd0.png)

**Comment by ianhbell** [comment]
What precise version of REFPROP do you have?  You can see by going to Help->About

**Comment by uSpiwoks** [comment]
Dear Mr. Bell

Sorry for the long delay.

Here our used version:
![Refprop_Version](https://user-images.githubusercontent.com/52311357/63490622-6a1e3500-c4b5-11e9-93b6-30f0f766cb34.jpg)

Yes, we enabled the saturation boundary item. This are the base settings of the program.

We are using the units of °C and bar instead of K and MPa for calculation. Maybe there is some difference in the unit.

We get a similar failure by trying to calaculate the new refrigerant R466A.
Our results have a jump in the refrigerant curve.
![R466A](https://user-images.githubusercontent.com/52311357/63493712-748ffd00-c4bc-11e9-8a22-fd606eacf5c4.jpg)
![R466A mixture information](https://user-images.githubusercontent.com/52311357/63493723-78bc1a80-c4bc-11e9-9ee3-73b464a34669.jpg)

**Comment by ianhbell** [comment]
Two comments:
1) You got a warning about missing interaction parameters for this mixture, please heed that warning.  You shouldn't blindly trust the model where placeholder values are being used
2) The temperatures you are looking at are VERY low.  Perhaps the model is predicting LLE, which is why you see this jump.  Nonetheless, you are in no-man's-land with this model.  When I do Calculate->Phase Boundary in the GUI, I don't see this jump, but I do when I do direct calculations:
![image](https://user-images.githubusercontent.com/11966765/63540102-b4fd7400-c4d8-11e9-91c9-44aa57d7235a.png)

**Comment by uSpiwoks** [comment]
Thanks for your feedback.
We saw this phenomenon and would like to ask about it to get a better understanding.

The point is still the jumping of individual values of R437A. There is no warning by start.
We interpolieren these value so that is not a real issue for us.

**Comment by ianhbell** [comment]
Can you please show an example with R437A?  

If you are going to interpolate anyway, then I recommend you construct the isopleth of the phase envelope with Calculate->Phase Boundary.  That should be pretty reliable in general.

**Comment by EricLemmon** [comment]
I've tried several times over the past year to fix this problem (and several like it), but I could not come up with a solution that had the potential to damage calculations for other mixtures.  This is a very tricky problem in that one algorithm is used for the calculation of the saturation states for any mixture, and thus changes can (and will) seriously impact the calculations elsewhere.  However, this week I think I've found something that works, and while plotting the phase diagram for all 150 predefined mixtures, I did not notice any problems.  

I was actually working on the issue in #146 to find a solution, but I knew that this was also a problem and was using it as a test case to the changes I made there.

If you would like an updated DLL with the new changes, please let me know (eric.lemmon@nist.gov).  However, keep in mind that you will need to watch carefully when working with other mixtures to make sure they have not been affected.  This is something that will require many beta testers to ensure that what I implemented is working properly.
