### ISSUE TITLE
blank view of help file contents

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#185]
using the most recent version of the Windows help file (downloaded from https://pages.nist.gov/REFPROP-docs/#help-file after issue #176 was closed) I can search for a term and see a list of help pages containing the search term... or browse the contents tree... but none of the help file page contents are displayed

OS=Win10 Enterprise

![2019-07-10 18_23_51-Clipboard](https://user-images.githubusercontent.com/39253715/61009286-35f51780-a340-11e9-8914-43aac57d4161.png)

![2019-07-10 18_25_14-Clipboard](https://user-images.githubusercontent.com/39253715/61009332-56bd6d00-a340-11e9-8b64-6cb2365275d7.png)

**Comment by ianhbell** [comment]
Super weird, thanks for the report.  This works fine on windows 7, though that doesn't help you with this issue.  Do you have another windows 10 machine you can test this on to identify whether it is the machine or windows 10 in general?  We haven't had any similar reports, for what it's worth.

**Comment by EricLemmon** [comment]
I noticed on the webpage you pointed to the following text:

> The most recent help file from Refprop is available below. You should download it to your machine before launching it, otherwise the help file will appear blank. 

Perhaps that is the problem?

I have a brand new Windows 10 machine, I went to that website, clicked on the link, opened it (without downloading it first, against what the instructions say), and it still worked.  I'm not sure how I can debug this to make it work for you.

**Comment by HightopRaven** [comment]
Okay, just figured out that the issue is due to Windows security for downloaded files. The solution is to check the file properties (from Windows Explorer), tick the box to "Unblock" and Apply the change, then the contents are displayed as normal. Screenshot below.

![2019-09-23 11_40_14-Clipboard](https://user-images.githubusercontent.com/39253715/65441018-aa940a00-ddf7-11e9-96bd-0463d806afb8.png)

**Comment by EricLemmon** [comment]
This is great information, thanks for providing it!
