### ISSUE TITLE
Solid phase thermal-physical properties of Carbon Dioxide

### ISSUE THREAD

**Issue by SunRuiTJU** [usnistgov/REFPROP-issues#186]
Hello, sir,

I am currently engaged in theoretical research on cryogeic CO2 capture, which depends on the freezing point of CO2 (which is determined by Gas-Solid Equilibrium) and the basic physical properties below the three-phase point of pure CO2. 

According to my experience in using REFPROP, when calling REFPROP in MATLAB, CO2 physical properties, including enthalpy, entropy and so on, can not be invoked at less than three-phase point (216.592 K). Recently, I found the paper "**Jäger, A., Span, R., 2012. Equation of State for Solid Carbon Dioxide Based on the Gibbs Free Energy. Journal of Chemical & Engineering Data 57, 590-597.**" which described how to calculate Solid Carbon Dioxide physical properties in detail.  Under the guidance of this article, I wrote the call function, which is already available.

 What I want to know is whether REFPROP plans to provide solid phase properties of CO2 (including other common substances such as WATER) below its three-phase point in future versions (or high-level versions that have been published) for more people to study. 
Which is highly appreciated by researchers like me.

Your database is very helpful to my research.
Thanks for your work!

### Versions

**REFPROP Version:9.1
**Operating System and Version:Win 7 64bit

**Comment by EricLemmon** [comment]
Adding solid properties to Refprop such as those described by the Jaeger and Span paper is definitely an item on our list of future updates to the program.  A time frame for such a project, however, has not been set, as this will require an incredible amount of work to implement, evaluate, and test.
