### ISSUE TITLE
Does Refprop 9 support and calculate correct values for refrigerants R407H and R454A?

### ISSUE THREAD

**Issue by krushnaeicp** [usnistgov/REFPROP-issues#188]
Just wanted to confirm if Refprop 9 dll supports refrigerant R407H and R454A? We are already supporting other refrigerants and want to extend support to this two new refrigerants in our software. We use Microsoft C#/VB.net. Any example would be appreciated.

Regards,
Krushna

**Comment by ianhbell** [comment]
REFPROP 9 does not (as delivered), but REFPROP 10 does.

**Comment by EricLemmon** [comment]
Take a look at the following website:

https://pages.nist.gov/REFPROP-docs/#hfo-1234yf-1234zee-1234zez-1233zde-and-refrigerant-mixtures

These can be used in version 9.1, but not 9.0.  9.1 is a free upgrade to 9.0, if you do not have this, please send me a personal email at eric.lemmon@nist.gov
