### ISSUE TITLE
DQ input support

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#189]
I would like to construct the saturation lines from density. Density values smaller than critical density can only be saturated vapour; density values larer than critical density can only be saturated liquid.
Currently, the GUI just gives me a warning "Selected inputs are not allowed", at least from the "Calculate -> Specified state points" table, but it works well from the "Calculate -> Saturation points" table. I also read https://github.com/usnistgov/REFPROP-wrappers/issues/152#issuecomment-478073646 like this is already implemented, it just is not yet available as input.

**Comment by ghost** [comment]
Try entering a density followed by an L or V.  You can do this in the temperature or pressure columns as well.  Also look at the Calculate/Phase Boundary option that allows you to enter a density range and obtain properties along the entire saturation boundary.

**Comment by thorade** [comment]
Very nice, thank you, closing this issue.

**Comment by thorade** [comment]
Reopening. While right now I am mostly interested in the saturated states, corresponding to Q=0 and Q=1, it might make sense to also support DQ input with any valid Q.

**Comment by EricLemmon** [comment]
Are you applying this to pure fluids or mixtures?  For a pure fluid this could be easily implemented, but for a mixture it would require some fairly intense new code to solve for the DQ state point when Q>0 and Q<1.

**Comment by thorade** [comment]
For now only pure fluids, later maybe pseudopures. Only the easy part, please!

**Comment by EricLemmon** [comment]
It's been quite a while since you submitted this and we haven't put it together yet.  Are you still in need of this feature, or can we postpone it till after version 10.1 comes out (which will be mostly just a bug fix release)?

**Comment by nist-aharvey** [comment]
Thermodynamically, it is not guaranteed that the combination of D and Q will uniquely specify a state point, even for a pure fluid.
If you do a p-d or p-v plot in REFPROP and tell it to draw lines of constant quality, you will see that they can bend over near the critical point.

**Comment by ianhbell** [comment]
For _saturated_ states with Q=0 or Q=1, I believe the functions should be monotonic, and therefore invertible, but I do agree about lines of quality in the two-phase region

e.g. for nitrogen:

![image](https://user-images.githubusercontent.com/11966765/87586633-ce8a4a00-c6ae-11ea-89f2-ef3a5d54781e.png)

**Comment by EricLemmon** [comment]
It's incredible how a picture can bring back memories unlike anything else.  I tried to implement this several years ago and discovered the same problem (via the same picture), and thus dropped the attempt and forgot about it.  

I guess this means that we should close the issue?

**Comment by ianhbell** [comment]
If it were me, I would implement the DQ solver for saturated states for pure fluids, but not touch anything else I think.

**Comment by nist-aharvey** [comment]
Can't you already get that functionality by entering a density and telling it you want saturated vapor or liquid?
It seems sort of clunky and likely to lead to confusion to allow an input combination that only works if one of the variables is exactly 0 or 1.

________________________________

**Comment by thorade** [comment]
Sorry for replying late, I am on vacation. The interesting part for me for now would be to specify the saturated state using density, from a Python script (using CoolProp as a wrapper). Currently we construct the saturation lines with p or T, but especially close to the critical point d would be nicer. 
This seems to work already from the GUI,  not sure if anything needs to be added at all.
From my side, please only do the easy part, at any time it suits you.

**Comment by EricLemmon** [comment]
This issue has the "feature request" label on it that we put there for items that we should revisit someday but that don't need to be on the list of open issues.  I am going to close this now and will return to it when time is available.

**Comment by ianhbell** [comment]
This is a very useful feature, for instance when making P-T plots and you want to plot along isotherms, and you need to know at what density your isotherm crosses the phase boundary.

**Comment by EricLemmon** [comment]
I believe it is all working now anyway, I just need to check and make sure there are no dumb ways of getting answers that you should not be getting.  It's still in the list of items that I'll show you privately.

**Comment by xjvheule** [comment]
Hello,
Has this feature been implemented? and if so in what version?
I stumbled across this DQ-input error with Q=1 which let me here.
