### ISSUE TITLE
Ammonia-water thermo mismatch in v9.1

### ISSUE THREAD

**Issue by BPFirth** [usnistgov/REFPROP-issues#19]
From email chain:

From me:
> I’m sure you’re aware that there were issues with ammonia in v9.1. I just bought a copy of 10 to try and use with SimSci’s PRO/II. Unfortunately it’s not compatible.
> 
> My question is this: Is it possible to use the v10 fluid file for ammonia with v9.1, in order to get the enthalpy of ammonia corrected? We’re trying to model an ammonia/water absorption, and it’s coming out too cold because of the issues in 9.1.

Reply from NIST:

> Is this simply an issue of reference state?  What reference state do you need for ammonia?
> 
> Also, in the future, please open queries like this as issues at github so that everyone may learn from our correspondence: https://github.com/usnistgov/REFPROP-issues/ .  That is our new support mechanism for REFPROP 10+

My response:

> I suspect it is reference state, though I don’t think I can do anything on my end – when we start at pure water, it matches literature data, but when we shift over to pure ammonia, we’re significantly above. I would assume this means that there’s an offset for the ammonia reference state compared with water, but I can only change the shared reference state in Pro/II. See below, Refprop values are the blue dots:

![refprop ammonia-water issues](https://user-images.githubusercontent.com/39774359/40735303-bda01278-6432-11e8-947d-2bb88d41dc98.png)
[source](https://www.researchgate.net/publication/229130195_Thermodynamic_properties_of_ammonia-water_mixtures_for_power-cycle_applications)

I suppose the questions are:
1) Is there something on my end causing this issue?
2) If not, has it been resolved in v10
3) If it has been resolved, is it possible to use the v10 fluid file in v9.1 for ammonia to get the correct enthalpy, as I can't currently use v10 with Pro/II?

Thanks,
Ben

Edit to add: The VLE data is all spot on. It's just the enthalpy that's out.

**Comment by ianhbell** [comment]
Where does the IGT data come from?  Can you tell me what else is held constant in your figure and I will try to reproduce with version 10 and we can see what it looks like?

**Comment by BPFirth** [comment]
The link to the paper is below the graph.
The constant here is pressure - it's the saturated liquid enthalpy at 34.47 bara.

Just to clarify: Refprop is the only thermo package giving these kind of answers. Using UNIQUAC or modified Peng Robinson come much closer to the literature data (see graph below). It appears there is an inconsistency between the ammonia and water reference states, so the pure enthalpies used in mixing aren't correct relative to each other.
![refprop ammonia-water issues_2](https://user-images.githubusercontent.com/39774359/40769194-45b3b09e-64af-11e8-8264-cc1fae5c2bbd.png)

**Comment by BPFirth** [comment]
Update:
Had a deeper dive into this, and have cobbled together a rough heat of mixing (based on the pure enthalpies at either end of the graph, ignoring the fact that it's different temperatures as we move across). Then found the difference between the enthalpy and the "ideal" predicted enthalpy, which is effectively the heat of mixing.

![differences in heat of mixing](https://user-images.githubusercontent.com/39774359/40775043-07e96d48-64bf-11e8-9f23-f8fa91226123.png)

So I think we're actually OK? For some reason Refprop is using a different reference state for Ammonia from everyone else, but digging far enough in, the heat of mixing comes pretty close.
