### ISSUE TITLE
WATER+CO2 in two-phase

### ISSUE THREAD

**Issue by imanlas** [usnistgov/REFPROP-issues#191]
Hi, 

I am facing two issues regarding REFPROP calculation of  WATER+CO2 mixture in two-phase:

1. Considering the mass fraction of 28.49/71.51 at 9 bara, I am reducing the temperature from 147C down to 125C. I am observing the first phase change (Gas to 2-Phase) at around 146 C, the second (2-Phase to Gas) at around 139 C and the third (Gas to 2-Phase) around 131 C. Can we explain this behaviour? (see the attachment)  

![REFPROP_CO2_STEAM1](https://user-images.githubusercontent.com/22888594/62057144-574e7280-b21f-11e9-9caa-da7db43f578c.PNG)

2. Considering an isentropic expansion from 9bara to 1bara (see the first attachment where in the second raw I use entropy and pressure as inputs), I get different values for outlet isentropic enthalpy than those that I get from EXCEL or MATLAB wrapper which are connected to the same version of REFPROP (hout,s = 1010 kJ/kg vs 1030.7 kJ/kg). Other parameters such as initial enthalpy, specific volume and entropy (hin, vin, sin) are the same. 

![REFPROP_CO2_STEAM2](https://user-images.githubusercontent.com/22888594/62057359-cfb53380-b21f-11e9-81eb-9786861b90e0.PNG)

![REFPROP_CO2_STEAM3](https://user-images.githubusercontent.com/22888594/62057372-d479e780-b21f-11e9-846b-2bf3aacfe471.PNG)

### Versions

**REFPROP Version:** [REFPROP 10]  
**Operating System and Version:** [Windows 7]  
**Access Method:** [ REFPROP interface and MATLAB and EXCEL wrapper]

**Comment by ianhbell** [comment]
1. Can you please show a phase envelope ?

2. The GUI uses a different scheme for the reference state by default than Excel. Please see this section: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

**Comment by imanlas** [comment]
1. It is not so easy to extract a meaningful phase envelope from GUI. I send you one try of P-H diagram  with curves of entropy, temperature and quality. Not the nicest plat in fact;) 

![REFPROP_CO2_STEAM4](https://user-images.githubusercontent.com/22888594/62129104-2bda8f00-b2d6-11e9-8b47-f1464aa2c51e.PNG)


2. I assume that regardless of the reference state, the difference between the inlet enthalpy and the isentropic outlet enthalpy should be the same for GUI, MATLAB and Excel. However, this is not the case for this mixture.

**Comment by ianhbell** [comment]
Probably, in hindsight, better to open two separate issues, but let's proceed...

1. This is an open-phase-envelope composition, so the normal rules don't apply

In the GUI, do Plots->"P-T Diagram", Turn on "Draw saturation lines", turn off all others

![image](https://user-images.githubusercontent.com/11966765/62146496-bc06dd00-b2b2-11e9-8292-bdd555a2359d.png)

At 9 bara, the dew point is around 170 C.  There is no bubble-point because this is an open phase envelope.  Your temperatures are all two-phase it would seem.  I wonder why the GUI tells you they aren't.  Are you using the default model or GERG?

2. I have to think about your second point a bit, because it is indeed confusing.  But once you no longer have a homogeneous state, I think the normal rules about enthalpy and entropy don't apply.

**Comment by imanlas** [comment]
1. I have just modified the open-phase envelope, because the desired composition is actually 28.49/71.51 WATER/CO2 and not CO2/WATER. Here comes the plot. Unfortunately, it is not still explaining the phase-change behavior.  Also, I am using the default model and not GERG.

![REFPROP_CO2_STEAM5](https://user-images.githubusercontent.com/22888594/62195698-d4432e80-b37c-11e9-9191-fee9c679b539.PNG)

2. I will update you If I find out something.

**Comment by ianhbell** [comment]
Actually, it all makes sense now.  The dew point is as you indicate.  Then for lower temperatures along 9 bara, there is no further phase transition.  Any other apparent phase transitions are failures of the calculations.

**Comment by EricLemmon** [comment]
Mixtures with water and CO2 involve two of the most complex equations of state in Refprop, both of which have multiple loops in the two-phase (which are not visible to the ordinary user, but have to be dealt with by the equation of state developers).  The loops are extremely large (or should I say without exaggeration "extremely<sup>2</sup>"?) compared to today's modern equations.  These loops cause many problems and we are slowly working to replace the equations.

I have come back to this issue many times over the past year to either try to find the problems or to see if other changes have fixed them.  It appears that work I have done over the summer has at least fixed the problems you are seeing in the first table above.  However, the p-h plot still has some strange behavior along lines of constant quality.  I am not sure that we will ever get those fixed until our new equations of state become available.

As for the calculations, look at the table below.  It shows how the program is functioning now.  All appears to be correct.  If you still have need for a new DLL, let me know (eric.lemmon@nist.gov) and I'll send you a new beta version.

![image](https://user-images.githubusercontent.com/42392984/90974200-2dc94e80-e4e6-11ea-8026-f3fde27d0ddb.png)
