### ISSUE TITLE
Phase Envelop - CO2 rich mixture

### ISSUE THREAD

**Issue by SeptemTamuda** [usnistgov/REFPROP-issues#192]
System: Refprop10 on windows10 64bit

I get a strange shape for the phase envelop of this mixture
![image](https://user-images.githubusercontent.com/53512249/62196387-37819080-b37e-11e9-9a02-669b0fe115ab.png)

here is the PT diagram:
![image](https://user-images.githubusercontent.com/53512249/62196485-6bf54c80-b37e-11e9-8354-82e9f650546e.png)

Any comment?

**Comment by ianhbell** [comment]
What do you think is strange? The fact that it crosses?  If you were to see the actual points, I think you would see they it is simply a linear line segment connecting the points.  You can make a more detailed calculation of the isopleth of the phase envelope (line of constant composition) with the Calculate->"Phase Boundary" menu option

**Comment by SeptemTamuda** [comment]
Got it!
Thanks
