### ISSUE TITLE
Liquid Prandtl number less than one for R515A and GERG-2008 model 

### ISSUE THREAD

**Issue by MarkKed** [usnistgov/REFPROP-issues#193]
The GERG-2008 model produces a liquid Prandtl number (Prl) that is less than one for R515A.  (All liquid Pr should be greater than 1.)  Please see comparison of various REFPROP 10.0 model results below.  The GERG-2008 model results are shown in the last row where Prl = 0.067.  
![515apropProb9](https://user-images.githubusercontent.com/53514837/62200806-26bc2500-b354-11e9-8cd1-29848f1d875f.jpg)

**Comment by ianhbell** [comment]
This is sort of a bug in REFPROP, but also a question of usage.

The key issue is that the GERG-2008 model is only valid for the components in natural gas, and REFPROP should error out aggressively if you have selected the GERG-2008 model and try to use something that is definitely not part of GERG-2008 (e.g., refrigerants).

**Comment by ianhbell** [comment]
Also, I haven't the foggiest idea how viscosity is calculated when the GERG-2008 model is selected and a non-GERG fluid is included.  You'll note that the densities are similar with all the models (ok, at least the same order of magnitude mostly), but the funky Prandtl number is a consequence of the funky viscosity.

**Comment by EricLemmon** [comment]
This bug has now been fixed.  It turned out to be an initialization problem where the full array for the transport properties was reinitialized rather than just the fluid being read in.  If you want a new DLL (which will be a beta version with many other changes), please send me a personal note:  eric.lemmon@nist.gov
