### ISSUE TITLE
 Unexpected Values of Internal Pressure for Saturated Liquid and Saturated Vapor and in the Two-Phase Region

### ISSUE THREAD

**Issue by jakehofgard** [usnistgov/REFPROP-issues#195]
### Description
The REFPROP saturation table and isoproperty table data calculators produce different values of internal pressure for saturated liquid and saturated vapor at the same temperature. In addition, points along a given isotherm in the two-phase region also have different values of internal pressure. I did not expect this because the definition of internal pressure, P_int = T(dP/dT)_v - P, indicates that internal pressure should remain constant along an isotherm in the two-phase region (P and (dP/dT)_v should both be constant at a given temperature in the two-phase region).

### Steps to Reproduce

1. Select water as the substance for which values are calculated in the REFPROP GUI.
2. Select temperature, density, pressure, and internal pressure as the properties that are calculated.
3. Produce a saturation data table that varies temperature (it doesn't matter what range you select).
4. It is also possible to see the discrepancy on a point-by-point basis by using the "Specified State Points" feature to calculate points near the saturation curves and directly inside the two-phase region.

**Expected behavior:** The definition of internal pressure indicates that along a given isotherm, internal pressure should remain constant inside the two-phase region. Because (dP/dT)_sat is the same for both saturated liquid and saturated vapor at a given temperature, I also expected saturated vapor internal pressure to equal saturated liquid internal pressure at said temperature.

**Actual behavior:** Along a given isotherm, internal pressure varies significantly inside the two-phase region and between the saturated liquid and vapor curves.

### Versions

**REFPROP Version:** Version 10
**Operating System and Version:** Windows 10
**Access Method:** REFPROP GUI

### Additional Information

Points just outside the two-phase region corresponds to the definition of internal pressure, but points just inside the two-phase region do not as illustrated by the data below.
![REFPROPIntPressure](https://user-images.githubusercontent.com/53575125/62318976-31f97880-b45a-11e9-9d2a-60422b8a4c06.PNG)

The discrepancy between saturated vapor internal pressure and saturated liquid internal pressure is shown in a saturation table.
![SatIntPressure](https://user-images.githubusercontent.com/53575125/62318926-13937d00-b45a-11e9-8468-db198f94d9c9.PNG)

**Comment by ianhbell** [comment]
I'm not so sure about your expectation about internal pressure for two phase states....  How do you want to evaluate dp/dT|rho for a two-phase state?  Which density are you holding constant?  A metastable density or the two-phase density?  They are quite different in character.  

The derivative dp/dT|rho, where the rho is the homogeneous density and dp/dT is evaluated directly from the EOS, is _decidedly_ not constant within the two-phase region. For that matter, neither is the pressure for metastable states, and therefore we should not expect the internal pressure to be constant either.  

If you ask REFPROP for dp/dT|rho, and skip the phase calculation, you will get the metastable derivative.  If you really want the derivative dp/dT|rho, where rho is the two-phase density, that *can* be calculated (even analytically, see https://doi.org/10.1007/s12665-013-2394-z) but is not calculated normally by REFPROP.

The derivative dp/dT[sat] indicated is also not a derivative at constant density, so should not be used to calculate the internal pressure. It is the change in vapor pressure as a function of temperature, as you can see by taking numerical derivatives of the values in your second table.

**Comment by jakehofgard** [comment]
Thank you for your response. We better understand calculations of internal pressure inside the two-phase region and at saturation now. Because this does not seem to be an issue with REFPROP, I will now close the issue.

**Comment by ianhbell** [comment]
Sounds good.  Feel free to reach out via email for further clarifications.
