### ISSUE TITLE
Creating a Table of Thermodynamic Properties of Superheated gases

### ISSUE THREAD

**Issue by VES-ES** [usnistgov/REFPROP-issues#196]
I would like to create a table Superheated Vapor properties such as enthalpy, entropy and Volume based on P (x-axis) and temperature (y-axis). How do I do that in the program?

Thanks

**Comment by ianhbell** [comment]
Do you mean a plot or a table?  If a table, please see Calculate->"Specified State Points" in the GUI.  You can have it automatically fill in a column with linearly or logarithmically spaced data, and then evaluate whatever properties you want.

Also, I can provide Python examples of doing this more automatically if you are a MATLAB or Python user.

**Comment by VES-ES** [comment]
Thanks Ian, I am not a MATLAB or Python user. I am looking for a table for my simple lookup calcs in Google Sheets. Fro example, if I would like to look up enthalpy of superheated gas, I would look up given pressure in the row header (x-axis) and temp in first column (y-axis) to get my enthalpy value.

**Comment by ianhbell** [comment]
Got it - Excel is your best bet then (Google sheets are unlikely to be a workable solution).  You could also do it in LibreOffice, but its a bit trickier to get working.

**Comment by VES-ES** [comment]
Ok thank you.
