### ISSUE TITLE
Refprop10

### ISSUE THREAD

**Issue by isultan1** [usnistgov/REFPROP-issues#201]
### Description

I use the fortran code included in refprop 9.1 in a large fortran project to perform my calcs, is it beneficial for me to upgrade to refprop10? If the fortran code hasn't changed, I will not need to upgrade. Please let me know your thoughts.

**Comment by ianhbell** [comment]
I cleaned up the formatting of your issue...

Yes, indeed, there are significant improvements to the Fortran code in REFPROP 10.  It is strongly recommended to upgrade.

**Comment by isultan1** [comment]
Thanks for your reply. I upgraded to Refprop10.
