### ISSUE TITLE
Erroneous triple point temperatures

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#203]
For the following fluids, the triple point temperatures differ by more than 0.1 K from the values from TDE.  Sometimes the differences are small, othertimes, not so small.  It would be nice to fix the triple point temperatures where they are definitively wrong and the TDE values are definitively correct (to be determined).

In each row, the entries are:
1) TTRP (from REFPROP)
2) TTRP (from TDE)
3) TMIN (from REFPROP) as a sanity check

Big differences (> 0.5 K):
```
D5 226.0 232.65339883869382 226.0
HEXANE 177.83 178.07120756082435 177.83
IPENTANE 112.65 113.5605750174863 112.65
MLINOLEN 218.65 222.3536153679654 218.65
MPALMITA 242.0 302.6574591098134 302.71
MD2M 205.2 197.00508035062086 205.2
MD3M 192.0 189.1934 192.0
NF3 66.36 56.5 85.0
R123 166.0 145.68 166.0
R1234ZEE 169.0 150.60222222222222 169.0
R1234YF 122.77 121.62757983253057 122.77
R227EA 146.35 145.173381294964 146.35
R236EA 170.0 126.7 240.0
R40 175.51 175.41097960832465 230.0
RC318 233.35 232.9900157051052 233.35
```

Small differences (< 0.5 K):
```
22DIMETHYLBUTANE 174.2 173.79021646356074 174.2
BUTANE 134.895 134.74579556691654 134.895
ACETONE 178.5 178.1626147013477 178.5
ACETYLENE 191.75 192.00354301661807 191.75
3METHYLPENTANE 110.263 110.48606400000001 110.263
C11 247.541 247.62011303114042 247.606
C1CC6 146.7 146.82106127908713 146.7
C6F14 187.07 186.92877502933376 187.07
CO 68.16 68.04897368421052 68.16
CYCLOHEX 279.86 279.7563505206901 279.86
CYCLOPEN 179.7 179.319130405597 179.7
CYCLOPRO 145.7 145.6996301173765 273.0
D2O 276.969 276.9223961962993 254.415
D4 290.25 290.08925891459967 290.25
D6 270.2 269.21312360902243 270.2
DEE 156.92 156.82479609452616 270.0
DMC 277.06 276.7207017476128 277.06
IBUTENE 132.4 132.12392727926073 132.4
ISOBUTAN 113.73 113.5771872065745 113.73
MDM 187.2 186.9102785399918 187.2
MEA 283.7 283.5008745 283.7
MLINOLEA 238.1 237.665373559377 238.1
MOLEATE 253.47 253.35670347875657 253.47
MSTEARAT 311.84 311.5162862686275 311.84
NEOPENTN 256.6 256.75230627981455 256.6
PROPYLEN 87.953 87.85216725052669 87.953
PROPYNE 170.5 170.02744222810873 273.0
R32 136.34 136.58860906625347 136.34
EGLYCOL 260.6 260.73429456428295 260.6
R125 172.52 172.78647320000806 172.52
R14 89.54 89.55955227658517 120.0
R114 180.63 180.63020210876803 273.15
R143A 161.34 161.57818699690404 161.34
SF6 223.555 223.72 223.555
SO2 197.7 198.0217297933867 197.7
TOLUENE 178.0 178.10170151485727 178.0
```

**Comment by nist-aharvey** [comment]
I would guess that much of the time it would be the TDE values that are wrong.  Triple points have not been a main focus of TDE data collection, and as far as I know their recommended value is just a simple average of all the values they have collected.  Meaning that one bad value, maybe from an impure sample in 1922, can throw off the number.
For example, for D2O TDE has 3 values, 2 of which essentially match the REFPROP value and one of which is off (and they are missing probably the best recent study).  The SF6 triple point temperature has been studied very carefully, but none of those careful measurements is in TDE, just a single less accurate value from a study that was mainly measuring something else.  NF3 is strange; the value you quote as coming from TDE is "Rejected" when I look at TDE and the one non-rejected value is 64.705.
On the other hand, for R236EA, it looks like the TDE value is good and the number in REFPROP (which does not appear to be in the underlying EOS paper) is wrong.
So the differences (at least the big ones) are worth investigating, but my guess is that often the problem will lie with TDE, not REFPROP.

There is also the secondary issue that, for many of the compounds you list, the actual triple point has not been measured at all, but instead it was a measurement of the melting temperature at 1 atm pressure.  That is then assumed to be the same as the triple-point temperature, which is usually a good assumption to within 0.01 K or so.

**Comment by ianhbell** [comment]
I'm 100% with you @nist-aharvey .  I'm not trying to claim that one is necessarily correct or incorrect, only that in some cases they are rather different, and from that standpoint it is important to try to figure out which of the two numbers is more likely to be correct.  I don't think we want to do a replace all with the values from TDE, but to be selective. I'm not too worried about differences at the level of 0.1 K, but differences at the level of 60 K warrant a deeper investigation.

**Comment by EricLemmon** [comment]
I've updated the fluid files as follows.  The ones that were suspect (in Refprop) were replaced with the values from TDE.  Some of the values had not been measured at the time of publication and values were obtained from different methods (R1234zee, for example, see the publication for details).  The following were changed:

```
              Old value  TDE value         New value
R123          166.0      145.68            145.68
R236EA        170.0      126.7             126.7
R40           175.51     175.410979        175.41
MLINOLEN      218.65     222.353615        222.35
R227EA        146.35     145.173381        145.17
RC318         233.35     232.990015        232.99
MPALMITA      242.0      302.657459        302.66
R1234YF       122.77     121.627579        121.63
R1234ZEE      169.0      150.602222        150.60
IPENTANE      112.65     113.560575        113.56
```

For the following, the references were added:
```
MD2M          205.2      197.005080        205.2
MD3M          192.0      189.1934          192.0
HEXANE        177.83     178.071207        177.83
D5            224.65     232.653398        224.65
```

The value for NF3 was left as is since it was reported by Younglove and the TDE number appears to be in error.
