### ISSUE TITLE
Error for placeholder Ttrp

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#204]
When a fluid has an unknown triple-point temperature, REFPROP still returns the placeholder value without error or warning.  It would be nice to error or warn when a placeholder value is being returned.

**Comment by EricLemmon** [comment]
In the fluid files, the following format has been added when the triple point value  is either approximated (where the 150 below is just an example) or unknown (which was used only for the POE oils):
```
150.0                !Triple point temperature [K]; {{"note": "APPROXIMATE"}}
```
```
250.0                !Triple point temperature [K]; {{"note": "UNKNOWN"}}
```
If the reference is given in the fluid file for this state, a similar format is used, for example:
```
144.0                !Triple point temperature [K]; {{"reference": "Reid, Prausnitz, & Poling, McGraw-Hill (1987)"}}
```
In addition to the triple points, all other comments in the main headers at the top of the fluid files were put into such format, especially for the Dipole moments, for example:
```
2.88                 !Dipole moment [Debye]; {{"reference": "R.D. Nelson, D.R. Lide, and A.A. Maryott, 'Selected Values of Electric Dipole Moments for Molecules in the Gas Phase,' NSRDS-NBS 10, National Reference Data Series, US Government Printing Office, Washington, 1967."}}
```

**Comment by EricLemmon** [comment]
SETUP is now programmed to recognize if the triple point is unknown or approximated, and calling the REFPROP subroutine to obtain the triple point temperature will return a warning in such a case:

[REFPROP warning -671] Triple point is either unknown or approximated.
