### ISSUE TITLE
huge difference between v10 and v9.1 on mixture properties

### ISSUE THREAD

**Issue by admcryo** [usnistgov/REFPROP-issues#205]
Hello,
I'm an engineer and use REFPROP daily to design cryogenic system. Few days ago I downloaded and installed the v10 of the SW. Then I try to calculate the properties of the following mixture:

CH4 = 0.53648; CO2 = 0.44104; N2 = 0.017982; O2 = 0.0044955 (molar fraction)
 
The results obtained were very different from those obtained from v9.1 (see the attached screenshots) and also "strange" (the enthalpy of vapor less than the enthalpy of liquid in equilibrium, the boiling temperature decreases when the pressure increases)

After that I try to eliminate from my mixture N2 and O2 (their concentrations are low) and the results obtained from two version of REFPROP became almost the same and consistend 

Could you help me to understand this difference of behavior of v10 and v9.1?

Thank's a lot

Attached two screenshots of the tables with the calculated data.

![image](https://user-images.githubusercontent.com/54681629/63963530-87469b00-ca95-11e9-8fa9-05e3bc04683a.png)
![image](https://user-images.githubusercontent.com/54681629/63963564-9decf200-ca95-11e9-9004-9d671339e97a.png)

**Comment by ianhbell** [comment]
1) Have you enabled the flag to initialize phase boundaries in both cases?

2) What does your phase envelope look like for REFPROP 9.1 and 10?  Are they similar?

**Comment by admcryo** [comment]
Yes, I enabled the flag in both case.

I verified that if I choose the GERG-2008  model in v.10 and default equations in v9 the problem seems almost solved

**Comment by ianhbell** [comment]
Can you please calculate a phase envelope with 9.1 and 10?  In the menu: Calculate->"Phase Boundary"

**Comment by admcryo** [comment]
Attached you can find the "Phase Boundary"calculated by V9.1 and v10 (default equations and GERG-2008). As you can see, the table of v10 with "default equations" selected option is not complete because the program is not be able to calculate them (I used the function that you suggested me, but the table produced was not complete)


[COMPARE V9_1 TO V10.xlsx](https://github.com/usnistgov/REFPROP-issues/files/3565067/COMPARE.V9_1.TO.V10.xlsx)

**Comment by ianhbell** [comment]
The only mixture parameters for this mixture that have changed are those of Gernert and Span for O2 + CO2:
J. Gernert and R. Span, J. Chem. Thermodyn., 93:274-293, 2016. https://doi.org/10.1016/j.jct.2015.05.015

Code to check:
```python
import itertools
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

fluids = 'CO2.FLD|METHANE.FLD|NITROGEN.FLD|OXYGEN.FLD'.split('|')
print(RP.SETUPdll(len(fluids), '|'.join(fluids), 'HMX.BNC', 'DEF'))
print(RP.PQFLSHdll(101, 1, [0.25]*len(fluids)+[0.0]*16,2))
for i, j in itertools.permutations(range(1,5), 2):
    print(i, j, list(RP.GETKTVdll(i, j).fij))
```

**Comment by ianhbell** [comment]
If you switch both 9.1.1 and 10 to GERG you should get quasi-identical results.  Open-phase-envelope mixtures (like this one) are hard to reliably calculate.
