### ISSUE TITLE
New fluid mixture model doesn't work in REFPROP 10 GUI

### ISSUE THREAD

**Issue by jaktk** [usnistgov/REFPROP-issues#207]
Despite implementing the new Helmholtz EOS in HMX.BNC file, the GUI does not allow for plotting any property with this equation. However, it is possible to use the model with python wrapper.

The error message in GUI:
![screenshot](https://user-images.githubusercontent.com/39903829/64239668-ee82a600-cf00-11e9-9c62-264057eaafb7.jpeg)

**Comment by EricLemmon** [comment]
If you change the reference state option in the menu Options/Reference State to Each Pure Component, then this message will not occur.  In fact, this is generally the best option to use when working with fluids of very different boiling points.

![image](https://user-images.githubusercontent.com/42392984/64369566-e185b580-cfd9-11e9-8e48-2bf80190952a.png)
