### ISSUE TITLE
Melting and sublimation calculations

### ISSUE THREAD

**Issue by nainanoo** [usnistgov/REFPROP-issues#208]
I am trying to look at the phase diagrams of different molecules (water, H2S, CO2, etc) and am particularly interested in the low pressure regions (~6 Pascals). I have the Refprop add on in Excel, but am getting errors when I look for the sublimation or melting temperatures of some of these molecules (NH3, C2H4, CH3OH) at low pressures. Is there a better way for me to find this information? Being able to visually see the solid-liquid-vapor phase diagrams at low pressures would be ideal.

**Comment by ianhbell** [comment]
Please fill out the issue template and don't put the entire issue in the subject heading

**Comment by EricLemmon** [comment]
In Excel, use the commands Tsubl and Tmelt to request sublimation and melting line properties, such as these:

=REFPROP("P","CO2","Tsubl","SI",200)
=REFPROP("P","CO2","Tmelt","SI",250)
