### ISSUE TITLE
How to specify mixing rule in REFPROPdll

### ISSUE THREAD

**Issue by mccoys** [usnistgov/REFPROP-issues#214]
Hi,

I am new to REFPROP and I am unable to understand how I am supposed to specify a mixing rule when calling the REFPROPdll subroutine. It seems that some parts from the legacy dll are needed (SETKTVdll?), but it is unclear which ones are necessary, and in which order to call them.

This is an example with python:
```python
 RP.REFPROPdll(
  "Oxygen;CARBON DIOXIDE", # hFld
   "", # hIn
  "FIJMIX", # hOut
  RP.GETENUMdll(0,"MASS SI").iEnum, # iUnits
  0, # iMass
  1, # iFlag
  1, # a
  2, # b
  [0.1,0.9] # z = composition
)
```

This returns the `KW0` rule, although I would like to set it to `XR0`.
How is this supposed to be done ?

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10
**Access Method:** python wrapper

**Comment by mccoys** [comment]
I have also tried the following, without success:
```python
RP.FLAGSdll("GERG",1)
RP.SETFLUIDSdll("Oxygen;CARBON DIOXIDE")
RP.SETKTVdll(1,2,'XR0',[],'')

 RP.REFPROPdll(
  " ", # hFld
   "", # hIn
  "FIJMIX", # hOut
  RP.GETENUMdll(0,"MASS SI").iEnum, # iUnits
  0, # iMass
  1, # iFlag
  1, # a
  2, # b
  [0.1,0.9] # z = composition
)
```

This now returns `KW1` ?! I don't understand how this might have happened.

**Comment by ianhbell** [comment]
To make this work properly, you need to first call GETKTVdll to load the model, then call SETKTVdll to load it back.  That's always how I have done it.  See for instance: https://github.com/ianhbell/binfit/blob/master/binary_fitter.py#L147-L155

**Comment by mccoys** [comment]
Ok thank you for your help. Now it works.

The point was that I had to specify by hand the parameters, as you do in your example. I thought they would have been taken automatically from the HMX.BNC file.

For those interested, here is my example:
```python
RP.FLAGSdll("GERG",1)
RP.SETFLUIDSdll("Oxygen; CARBON DIOXIDE")
RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'')
```

**Comment by ianhbell** [comment]
You DEFINITELY should not need to set parameters manually for this mixture.  If so, that is a bug, and please provide an example demonstrating this problem.

**Comment by mccoys** [comment]
Ok.

The behaviour is very strange actually. Here are exactly my commands used in python
```python
In [1]: import os
   ...: from numpy import *
   ...: from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
   ...:
   ...: os.environ['RPPREFIX'] = 'C:/Program Files (x86)/REFPROP'
   ...: RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
   ...: RP.SETPATHdll(os.environ['RPPREFIX'])
   ...: units = RP.GETENUMdll(0,"MASS SI").iEnum
   ...:

In [2]: RP.FLAGSdll("GERG",1)
   ...: RP.SETFLUIDSdll("Oxygen; CARBON DIOXIDE")
   ...:
Out[2]: 0

In [3]: RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'')
Out[3]: SETKTVdlloutput(ierr=0, herr=u'')

In [4]: RP.GETKTVdll(1,2)
Out[4]: GETKTVdlloutput(hmodij=u'KW1', fij=array('d', [0.996336508, 1.049707697, 0.997547866, 1.006617867, 1.0, 0.0]), hFmix=u'HMX.BNC', hfij=u'BetaT   GammaT  BetaV   GammaV   Fij   not used', hbinp=u'The binary parameter(s) for (Oxygen+Carbon dioxide) have been modified from their original values.', hmxrul=u'KW1  Kunz and Wagner model for the methane-ethane mixture')

In [5]: RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'')
Out[5]: SETKTVdlloutput(ierr=0, herr=u'')

In [6]: RP.GETKTVdll(1,2)
Out[6]: GETKTVdlloutput(hmodij=u'XR0', fij=array('d', [0.98876, 1.02354, 1.0, 1.0, 0.0, 0.0]), hFmix=u'HMX.BNC', hfij=u'BetaT   GammaT  BetaV   GammaV not usednot used', hbinp=u'The binary parameter(s) for (Oxygen+Carbon dioxide) have been modified from their original values.', hmxrul=u'XR0  Reducing functions only')

In [7]: RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'')
Out[7]: SETKTVdlloutput(ierr=0, herr=u'')

In [8]: RP.GETKTVdll(1,2)
Out[8]: GETKTVdlloutput(hmodij=u'XR0', fij=array('d', [1.0, 1.032, 1.0, 1.0845, 0.0, 0.0]), hFmix=u'HMX.BNC', hfij=u'BetaT   GammaT  BetaV   GammaV not usednot used', hbinp=u'The binary parameter(s) for (Oxygen+Carbon dioxide) have been modified from their original values.', hmxrul=u'XR0  Reducing functions only')
```

I call SETKTV 3 times with the same exact arguments each time.
You can see that the first call sets incorrectly the mode `KW1`, then the second call sets `XR0` but with the wrong parameters !
Only after the third call the parameters are correct.

**Comment by ianhbell** [comment]
I very much doubt it is your problem, but it is a pretty bad idea to star import from numpy.  It brings a LOT of functions into the main namespace, and it is possible (though very unlikely) that this is resulting some sort of corruption.

**Comment by ianhbell** [comment]
In the GERG model, the parameters are indeed all ones (see the GG0 model below from the HMX.BNC).  Setting the parameters, as you did, should work.  

I think the problem is somehow related to the combination of GERG and setting parameters, which, in my opinion, should not be allowed at all.  Once you have specified GERG, I think that should be the end of it.  And if you want the pure fluids of GERG, you can obtain them.  And then specify the interaction parameters.

My code:
``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

os.environ['RPPREFIX'] = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
units = RP.GETENUMdll(0,"MASS SI").iEnum

RP.FLAGSdll("GERG",1)
r = RP.SETFLUIDSdll("Oxygen; CARBON DIOXIDE")
print(r)
print(RP.GETKTVdll(1,2))

print(RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'HMX.BNC'))
print(RP.GETKTVdll(1,2))

print(RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'HMX.BNC'))
print(RP.GETKTVdll(1,2))

print(RP.SETKTVdll(1,2,'XR0',[1.,1.032,1.,1.0845,0.,0.],'HMX.BNC'))
print(RP.GETKTVdll(1,2))
```
yields
```
GETKTVdlloutput(hmodij='KW0', fij=array('d', [1.0, 1.0, 1.0, 1.0, 0.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV   Fij   not used', hbinp='Oxygen/Carbon dioxide\r\nJ. Gernert and R. Span, J. Chem. Thermodyn., 93:274-293, 2016.  DOI:10.1016/j.jct.2015.05.015', hmxrul='KW0  Kunz and Wagner model for hydrocarbon mixtures')
SETKTVdlloutput(ierr=0, herr='')
GETKTVdlloutput(hmodij='KW1', fij=array('d', [0.996336508, 1.049707697, 0.997547866, 1.006617867, 1.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV   Fij   not used', hbinp='The binary parameter(s) for (Oxygen+Carbon dioxide) have been modified from their original values.', hmxrul='KW1  Kunz and Wagner model for the methane-ethane mixture')
SETKTVdlloutput(ierr=0, herr='')
GETKTVdlloutput(hmodij='XR0', fij=array('d', [0.98876, 1.02354, 1.0, 1.0, 0.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV not usednot used', hbinp='The binary parameter(s) for (Oxygen+Carbon dioxide) have been modified from their original values.', hmxrul='XR0  Reducing functions only')
SETKTVdlloutput(ierr=0, herr='')
GETKTVdlloutput(hmodij='XR0', fij=array('d', [1.0, 1.032, 1.0, 1.0845, 0.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV not usednot used', hbinp='The binary parameter(s) for (Oxygen+Carbon dioxide) have been modified from their original values.', hmxrul='XR0  Reducing functions only')
```
```
?Oxygen/Carbon dioxide                                     [O2/CO2]
?J. Gernert and R. Span, J. Chem. Thermodyn., 93:274-293, 2016.  DOI:10.1016/j.jct.2015.05.015
  edc36840/77c8bee0
                   GG0      1.             1.             1.             1.             0.             0.             0. 0. 0. 0. 0. 0.
    XR0      1.             1.031986       1.             1.08446        0.             0.             0. 0. 0. 0. 0. 0.
    TC2    143.50606     -415.55821     2047.2334     -4206.532       2648.0917         0.             0. 0. 0. 0. 0. 0.
    VC2      0.034999957   -0.51142673     1.2403567     -1.8026811      0.83407525     0.             0. 0. 0. 0. 0. 0.
```

**Comment by mccoys** [comment]
In the extract of HMX.BNC you provided, the reference is from 2016 and it represents an extension to the GERG-2008 model. However, the first line `GG0` contains parameters that do not appear in that article for O2/CO2. Instead, they are the correct parameters for O2/CO. The second line `XR0` does contain the correct parameters for O2/CO2.

- Is this an error ?
- If, as you say, I am not supposed to change the parameters after setting the `GERG` flag, how am I supposed to select the second line `XR0` ?
- A related question: I tried reproducing similar steps in the GUI in order to investigate this behaviour, and I noticed that, when GERG is set, then the critical P,T,D are not available under `fluid information`. Is this expected ?

**Comment by EricLemmon** [comment]
In the GERG-2008 document, I see the following:
CO2–O2 1.000000000 1.000000000 1.000000000 1.000000000
O2–CO 1.000000000 1.000000000 1.000000000 1.000000000
These match what is in the HMX.BNC file for the GG0 line.

Here's information at the top of the file about how it uses the lines:

 Selection of mixture model when more than one is present:
   If the GERG-08 model is off, The last line in the HMX.BNC for a given
   binary pair will always be the one used.
   If the GERG-08 option is on, the line containing GG is used if available.
   New mixture models always follow the lines with GG in the HMX.BNC.

Thus, XR0 is used by default unless you turn the "full GERG-2008" option on.

When a critical point is not reported in the GUI, then it means that either the phase boundary calculation failed or that there is no critical point.  To see which one, make a P-T diagram and see if any funny behavior happens.

**Comment by mccoys** [comment]
Thank you very much for these information. It makes more sense now.

The critical-point calculation seems to fail indeed, as the P-T diagram shows erratic lines. Is there some access to parameters to try and fix this calculation?

**Comment by EricLemmon** [comment]
There are a few mixtures that are failing and it is something I need to work on.  I'll let you know when this is fixed.

**Comment by EricLemmon** [comment]
In response to some other posts, I've written up some information about mixing parameters in Refprop, which can be found here:

https://github.com/usnistgov/REFPROP-issues/issues/248
