### ISSUE TITLE
Mixtures Errors: Binary interaction parameters are not presently available for this mixture

### ISSUE THREAD

**Issue by pkennedy78** [usnistgov/REFPROP-issues#219]
Version: REFPROP V10:
Called Via LabView Interface
Function: ABFLSH_Test.vi

**Result:**
REFPROP_ErrorConverter.vi<ERR>
[SETUP warning -117] Binary interaction parameters are not presently available for this mixture; alternative mixing rules from a similar substance have been used.  

Mixture:
MyMix
117.484604061483 382.034985872748 3583.8896810002 4.18450213571032
2 
R1234ZEE.FLD
R227EA.FLD
.938503794229568
6.14962057704319E-02
0

**Comment by ianhbell** [comment]
I'm not sure that there is much we can do here.... There is currently no experimental data of any kind for this mixture in the NIST TDE database, as you can see by checking: https://trc.nist.gov/thermolit/main/home.html#home .  If and when that data comes available, we will be able to provide a better mixture model with fitted parameters.  For now, you're stuck with the estimation scheme.

**Comment by pkennedy78** [comment]
Thanks, Ian, I know what to do from here.
