### ISSUE TITLE
Ammonia viscosity Refprop 9.1/10 for 273.15 differs

### ISSUE THREAD

**Issue by mayersre** [usnistgov/REFPROP-issues#226]
Hello,

when I pull the viscosity from Refprop 10 Windows App for Ammonia at 273.15 saturation I get 164,83 µPas.
The same with Refprop 9.1 (latest) gives 170.09 µPas. 
Coolprop gives 170.08 µPas.

Why is that so?

Kind regards 
Reiner Mayers
Bundesfachschule Kälte-Klima-Technik Maintal

**Comment by EricLemmon** [comment]
The two versions use different correlations and thus the numbers are different.

Refprop v10 uses this model:

Monogenidou, S.A., Assael, M.J., and Huber, M.L.
Reference Correlation for the Viscosity of Ammonia from the Triple Point to 725 K and up to 50 MPa
J. Phys. Chem. Ref. Data, 47(2), 023012, 2018.

Refprop v9.1 uses a different, older model:

Fenghour, A., Wakeham, W.A., Vesovic, V., Watson, J.T.R., Millat, J., and Vogel, E.
The Viscosity of Ammonia
J. Phys. Chem. Ref. Data, 24:1649-1667, 1995.

This information is in the fluid information screen.
