### ISSUE TITLE
Binary mixture properties not on bubble point or dew point curves

### ISSUE THREAD

**Issue by UMCFDgitadmin** [usnistgov/REFPROP-issues#229]
### Description
We are using REFPROP for a properties for a CFD model of film condensation from a binary mixture of condensing vapours. Up to now we have been evaluating the enthalpy of the mixture by supplying two of the following:  temperature, pressure, and mass fraction. We understand this to mean that we are obtaining a property at equilibrium conditions (on either the bubble point line or the dew point line).

Is it possible to obtain and enthalpy by supplying all three of  temperature, pressure, and mass fraction? In other words, find the properties at a state not on the bubble point or dew point lines?

REFPROP Version: 10  
Operating System and Version: Linux (Red Hat 7) 
Access Method: Fortran 95 in-house code calling the library

**Comment by ianhbell** [comment]
For sure that is possible, just provide the T,P and bulk Z to ``REFPROPdll``, out comes the properties you want.

**Comment by UMCFDgitadmin** [comment]
Just for confirmation, can the state point be superheated or subcooled, or must it be in between the bubble point and dew point lines (i.e., two-phase)?

**Comment by ianhbell** [comment]
Yes definitely!  As you can see by doing a calculation at equilibrium, and then moving into the single-phase region.
