### ISSUE TITLE
carboxymethyl cellulose

### ISSUE THREAD

**Issue by omidne** [usnistgov/REFPROP-issues#23]
Hello Dear Ian

I have one question about some Non0newotonina fluid, I need the properties of carboxymethyl cellulose. Do you know any references for it?
I know that this is not related to Refprop, Just ask as a consult.

.
sincerely yours
Omid

**Comment by ianhbell** [comment]
Good question, but no, that is pretty far outside the scope of REFPROP, which is most focused on very well measured fluids.
