### ISSUE TITLE
Deviations in EOS calculations between v10 and v9.1

### ISSUE THREAD

**Issue by dcawley15** [usnistgov/REFPROP-issues#236]
I am not sure if this is intentional or a bug but if intentional I did not see any documentation on this.

I am seeing deviations in EOS calculations in REFPROP 10 compared to REFPROP 9.1 after about 6 significant digits for most fluids (but not water and CO2).  While the deviations are very small relative to the fluid model uncertainty these deviations are numerically significant and would be relevant for anyone using REFPROP in numerical simulations. 

I work on software for heat exchanger simulation and we have programmed our own fluid property calculations according to the published literature. I use REFPROP in unit testing our code to verify that our own calculations are correct.  Our software matches the calculations of REFPROP 9.1 to at least 12 significant digits so the deviations in REFPROP 10 represent a very large reduction in precision.

It seems like REFPROP 10 is using single precision arithmetic instead of double precision arithmetic (but only for certain fluids?). If this is true and intentional then is there an option to get the double precision calculations back in REFPROP 10?

This image shows the deviations in pressure but the same is true for the other thermodynamic properties as well. In all of these cases, our own software exactly matches what REFPROP v9.1 is showing here. The mixtures are the pseudo-pure models.
![RefpropCompare100to91](https://user-images.githubusercontent.com/59836161/72269078-982d1e80-35e8-11ea-9fa9-222e7fdbb726.png)

**Comment by ianhbell** [comment]
Just for fun, I tried to see what numbers come out of CoolProp, which for all these fluids in theory implements the same models as REFPROP (see below).  I  get the REFPROP 9.1 values from CoolProp. We will investigate and get back to you.

Code:
``` python
import CoolProp.CoolProp as CP
for fluid in ['R134a','R32','propane','R22','R410A','R407C']:
    Dmass = 600 if fluid == 'propane' else 800
    print(fluid, CP.PropsSI('P','Dmass',Dmass,'T',400,fluid)/1e6)
```
yielding
```
R134a 9.808459194114539
R32 32.729799651637165
propane 191.23062212252074
R22 12.272178700270603
R410A 21.302399453200056
R407C 15.062212424859268
```

**Comment by EricLemmon** [comment]
Please see the information I just uploaded here to help answer this question:

https://github.com/usnistgov/REFPROP-issues/issues/239

**Comment by dcawley15** [comment]
Thank you for the great explanation, it is much appreciated. I can certainly understand the benefits of this change; I just wasn't expecting it and didn't see it mentioned.  We can use the FLAGS subroutine in our case.
