### ISSUE TITLE
Truncation in long fluid names without warning

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#240]
In the case of NOVEC649 (and perhaps others), the LONGNAME gets truncated without any warning:

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll('NOVEC649','','longname',RP.MOLAR_BASE_SI,0,0,0,0,[1.0])
if r.ierr != 0:
    raise ValueError(r.herr)
longername = r.hUnits.strip().lower()
print(longername)
```
yielding
```
1,1,1,2,2,4,5,5,5-nonafluoro-4-(trifluoromethyl)-3
```
but should instead yield
```
1,1,1,2,2,4,5,5,5-Nonafluoro-4-(trifluoromethyl)-3-pentanone
```

**Comment by EricLemmon** [comment]
Funny, I was just reading the following section two days ago in the Refprop.for file:
```
c    - ``FDIR``:       Return the location (directory) of the fluid file.  The directory is returned in both the
c      hUnits string and in herr if no other error occurred (paths that are more than 50 characters long are
c      truncated in hUnits).  For mixtures, send FDIR(2), etc., to get the path of the second fluid and so on.
```
Does the full string come back in ``herr`` for the long name as well?

**Comment by ianhbell** [comment]
Nope, just an empty string.

**Comment by EricLemmon** [comment]
I've fixed this so that the name comes back in herr as well and added this to the documentation:
```
c    - ``LONGNAME``:   Return the long fluid name given on the 3rd line of the fluid files.
c      The length of some fluid names may exceed the length of the hOut string, and thus the name is also returned in
c      herr if no other error occurred.
```

**Comment by ianhbell** [comment]
Do you set an error/warning code as well?  I was just thinking that maybe ``hUnits`` should read ``"Name too long! see herr"`` when truncation is applied?

**Comment by EricLemmon** [comment]
No, for ierr and herr this would be similar to the case above for FDIR, and about 4 other properties where long strings are returned in herr.  But I like your idea of setting hUnits to the message you wrote above and will make that change now.

**Comment by ianhbell** [comment]
I think I would definitely make it a negative ``ierr`` to warn that something funny just happened.  It was totally unclear from the issue at the top of this thread that anything weird took place, and only an eagle-eyed reviewer of my paper made me realize there was a problem at all.  I got really "lucky" that my fluid truncated at just the right place.

**Comment by EricLemmon** [comment]
Will do.  -999 coming up.

**Comment by EricLemmon** [comment]
This is now fixed.  A negative warning number is returned in ierr, the fluid name is sent back in herr, and hUnitsArray is loaded with "Name too long, string returned in herr"

**Comment by ianhbell** [comment]
Perfect!
