### ISSUE TITLE
GERG-2008 is not turned off when component list changed leading to inconsistent results using REFPROP 10

### ISSUE THREAD

**Issue by AndreasGrenner** [usnistgov/REFPROP-issues#243]
I got inconsistent results for e.g. “ideal gas enthalpy” in REFPROP 10 while switching back and forth between REFPROP default EOS and GERG-2008 using different component list

One can reproduce that using the REFPROP 10 GUI performing the following steps:

1.	Define component list N2, Ar, O2, H2O
2.	Set composition to x_N2= 1, x_Ar= 0, x_O2= 0, x_H2O=0
3.	Calculate “specified state point”  Table 1
4.	Table 1  T = 85 K and P =  1 bar:  Result: H0 = 2465.4 kJ/mol
5.	Define component list N2, Ar, O2
6.	Set composition to x_N2= 1, x_Ar= 0, x_O2= 0
7.	Change under preference to “full GERG-2008”
8.	Calculate “specified state point”  Table 2
9.	Table 2  T = 85 K and P =  1 bar:  H0 = -6204.4 kJ/mol
10.	Going back to table 1 
11.	Table 1  perform again the specified state point at T = 85 K and P =  1 bar:  Result: H0 = -6204.4 kJ/mol

Or use the attached rfp file to load in REFPROP 10 GUI.  

1.	Perform a calculation in Table 1 at T = 85 K and P =  1 bar:  Result: H0 = 2465.4 kJ/mol
2.	Perform a calculation in Table 2 at T = 85 K and P =  1 bar:  Result: H0 = -6204.4 kJ/mol
3.	 Going back to table 1 and perform a calculation in Table 1 at T = 85 K and P =  1 bar: Result: H0 = -6204.4 kJ/mol

I recognized that issue in the implementation of the REFPROP 10 code in our software landscape. Note, the issue only appears if the component list is different.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Win 10
**Access Method:** REFPROP NIST FORTRAN code but the issue can be reproduced using the REFPORP 10 GUI
[refprop_issue_GERG_using_different_component_lists.zip](https://github.com/usnistgov/REFPROP-issues/files/4138248/refprop_issue_GERG_using_different_component_lists.zip)

**Comment by EricLemmon** [comment]
This bug appears to have already been fixed, I'll send you a link to a new GUI that you can try to make sure.

**Comment by EricLemmon** [comment]
Hi Andreas,

Have you been able to test the new code to see if all is fixed?

Eric

**Comment by AndreasGrenner** [comment]
Hi Eric,

Yes, with the new code the issue is fixed.



Best Regards,
Andreas
