### ISSUE TITLE
Mixture performance REFPROP (vs. CoolProp)

### ISSUE THREAD

**Issue by ciwstevie** [usnistgov/REFPROP-issues#246]
Is there some information/paper/document evaluating REFPROP (and ideally comparing to experimental results as well as CoolProp) with respect to refrigerant mixtures (user-defined mixtures!) ? I haven't found anything so far. What is the level of error using CoolProp instead of REFPROP for mixtures given the simplified handling in CoolProp....I am well aware that the answer to this question is case-dependent....but some hints would be of interest...am mainly looking into mixtures of linear (and possible branched) alkanes for the moment. 
Would it be for example possible to compare the data in NIST ThermoDataEngine against all the models in REFPROP? This would give a sense how things stand...
Or has this already been done and is published somewhere? Thanks for hinting about it in that case...

Best regards,

Stefan

**Comment by ianhbell** [comment]
Here is a first (admittedly ugly) go at this problem, the process is fully automated, but needs some fine-tuning:

![image](https://user-images.githubusercontent.com/11966765/73690638-6c0c3700-4696-11ea-9c96-ddd6a716952f.png)

**Comment by EricLemmon** [comment]
Hi Stefan,

Perhaps the information given here might help:

https://github.com/usnistgov/REFPROP-issues/issues/248

Eric
