### ISSUE TITLE
Hydrogen and Ethylene mixture

### ISSUE THREAD

**Issue by SanjeevSesh** [usnistgov/REFPROP-issues#247]
I am a novice at using REFPROP and am trying to create a mixture that includes hydrogen, ethylene and many other different gases.
Since I constantly saw [SETUP error 117], I removed gases one by one and isolated the issue to hydrogen and ethylene. 
I have attached a screenshot that shows the mixture definition screen and the resulting error.
Is there a known workaround for this problem?
I use REFPROP 9.1 on Windows 10 Pro

Thank you
![Capture](https://user-images.githubusercontent.com/60671107/73782573-2a879480-4747-11ea-9c7c-5fa020fb4cee.JPG)

**Comment by EricLemmon** [comment]
I just submitted a lengthy issue about this and many other mixture related items, you'll find it here:
https://github.com/usnistgov/REFPROP-issues/issues/248

**Comment by SanjeevSesh** [comment]
Dr.Lemmon,
 Thank you for taking the time to post a detailed reply.

Sanjeev
