### ISSUE TITLE
Mixture parameters in Refprop

### ISSUE THREAD

**Issue by EricLemmon** [usnistgov/REFPROP-issues#248]
When you define a mixture in Refprop (any version from version 6 till now), the program opens a file called HMX.BNC to obtain the interaction parameters for each binary in the mixture.  The model used in this file was originally developed several decades ago (in my Ph.D. work) and was published in three papers:

https://trc.nist.gov/refprop/Documents/Air.pdf
https://trc.nist.gov/refprop/Documents/NG_Mixtures.pdf
https://trc.nist.gov/refprop/Documents/Refrigerant_Mixtures.pdf

As we developed this model, there was much discussion about whether ternary interactions would be required.  However, to our surprise and relief, we learned that once the binary interaction parameters were developed, and done correctly, that the ternary parameters were not needed.  For the fluids in these three papers, a substantial amount of data is available both for the binary pairs as well as many of the ternaries.  For the natural gas paper, data for mixtures of 10 components or more are also available.  All comparisons showed that multicomponent mixtures are represented within their uncertainties once the binary interaction parameters were developed.

This work has continued over the past 20 years by my colleagues, one, in particular, who refit all of the natural gas mixtures over a 10-year period and published an impressive document with details far beyond my own work:

https://www.gerg.eu/wp-content/uploads/2019/10/TM15.pdf

There have been many other binary pairs fitted, such that the HMX.BNC now has parameters for nearly 1000 pairs of fluids.  For binary pairs that had not been fitted, we developed predictive schemes and automatic fitting methods, such as those described in the publications below:

https://trc.nist.gov/refprop/Documents/Refrigerant_Prediction_Scheme.pdf
https://trc.nist.gov/refprop/Documents/Automatic_Fitting_Methods.pdf

The first, done back in the 90’s, has been pushed far past its limits.  It is most certainly not valid for mixtures containing water, ethanol, helium, and so on, and in fact for most mixtures outside the realm for which it was developed.  The second publication fit parameters for most of the binaries that have available experimental data (the data were taken from the TDE database of TRC, one of the groups in our NIST division).

Back in 2018, my colleague Ian Bell developed two additional schemes that we have not yet published.  The first fills in the holes for hydrocarbon binary mixtures that are not already in the HMX.BNC file.  The second scheme estimates parameters for components with either nitrogen, carbon dioxide, or methane (excluding those already covered in his first scheme).  Because there are so few data for mixtures of fluids with either oxygen, argon, carbon monoxide, and fluorine, and because these four are similar to the first three, we extended this scheme to include these four as well mixed with other compounds.

So far we have not developed predictive methods to estimate parameters for the “oddball” fluids, such as water, alcohols, helium, and hydrogen.  In version 10 of Refprop, this was dealt with in an entirely different manner than those above.  An addition was made to most of the fluid files where we added a line with a hash number that points to an alternate fluid that is, in some fashion, similar.  For example, ethane became the alternate for ethylene, octane for ethylbenzene, hydrogen for parahydrogen, and so on.  Thus, if propylene and oxygen are mixed, the interaction parameters for propane and argon are used.  The two most important factors for the alternate are a fluid that already has been fitted with many other fluids (such as nitrogen, R134a, and methane) and the proximity of the critical points of the two fluids.  

All of these schemes are by no means the best that could be done (since that would be the work of someone’s Ph.D. due to the amount of time required for such a project), but it is the best alternative that we currently have.  The uncertainties are unknown for properties calculated with these predicative methods, so you must take care in their use to find other sources that might indicate how well they work.  When you use the Refprop program, you will be given warnings about this.  You would be wise to take the warnings seriously. 

Finally, one of the most important warnings that we can give you deals with an unfortunate situation where many binary pairs for the 21 fluids in the Kunz and Wagner publication described in the GERG document above used ideal mixing parameters for many of the oddballs, especially either water or helium with the other substances.  This is an issue that has caused us a lot of concern and for which we are working to correct by fitting parameters for these systems.  No warning is given about this, something that we should change.  The GERG model was developed for natural gas mixtures where water, helium, and several others are only present in small quantities.  But its use in Refprop is often extended outside of these limits to any composition, often for systems that are completely unrelated to natural gas.  To determine if your mixture belongs in this class, go to the Substance/View Mixing Parameters in the GUI as shown below and check to see if all the interaction parameters are set to one.  If this is the case, you should compare calculations with other sources to verify that they are similar.

If you have further questions, please open up a new issue.

![image](https://user-images.githubusercontent.com/42392984/73978670-0b753800-48ea-11ea-8e26-3cda18db36e9.png)

**Comment by ianhbell** [comment]
The GERG 2004 Monograph is now available at https://www.gerg.eu/wp-content/uploads/2019/10/TM15.pdf
