### ISSUE TITLE
Uninstallation issue, corrupted exe

### ISSUE THREAD

**Issue by ColdPipes** [usnistgov/REFPROP-issues#252]
### Description

When I go to uninstall Refprop 10, it leaves 2 seemly corrupted exe files in the Program Files (x86)/Refprop folder.  I have elevated privileges on my computers, but can’t remove these files manually.  Until I can get them deleted, I can reinstall Refprop 9.1.

### Steps to Reproduce

1. Install 10
2. Uninstall 10
3. Junk exe in program files

Refprop 10.0

![ScreenShot](https://user-images.githubusercontent.com/61239309/74843558-b70e8700-52f1-11ea-841d-cf7ec036cb6b.jpg)

**Comment by ianhbell** [comment]
Interesting, not seen this kind of "feature" before.  If you delete these two files, can you install and then uninstall REFPROP?

My general approach is to never install REFPROP in c:/Program Files (x86), I always install somewhere that I have full read/write capabilities.  Avoids a lot of permissions problems.

**Comment by ColdPipes** [comment]
Yes.  I actually had to restart (bc some unknown process running) then rename the folder before I was able to delete.

**Comment by EricLemmon** [comment]
One thing I've noticed when files get locked up is that a crash usually happened somewhere along the way, and even through you think you exited the crash, in the background it is still running.  When I go to my task manager sometimes I can see the crashed program still lurking around in the background, but often I have to go to the details section and search carefully there to find something that appears to have locked my application.  But killing something like that may have other consequences so I often just reboot.  It's another one of our favorite Microsoft "features".

And definitely follow Ian's advice and reinstall it outside of the Microsoft directories.  If you don't have read/write privileges to the Program Files directories, Windows will start making ghost directories in your Users folder to store your changed files, often duplicating them, and then all sorts of odds things start happening when it doesn't know which file to use later on.

If everything is working for you, can you close the issue?

**Comment by ColdPipes** [comment]
Thanks for the info.  Yes, I can close it.  As I may have mentioned, I uninstalled 10 and reinstalled 9.1, so everything is working for me.  I may try 10 again and others will, so working these issues is still a good thing for our group.

Thanks again,
Richard
