### ISSUE TITLE
Run-time error for big table

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#254]
Start REFPROP.
With default fluid nitrogen, do Saturation Table, keeping the defaults but changing the temperature increment to 0.001 K.  After calculating for a while, REFPROP crashes with:
Run-time error '6':
Overflow
Presumably it is calculating beyond the maximum number of rows allowed in the table, and not handling things gracefully when it runs over the end.

**Comment by ianhbell** [comment]
If you are open to using Python, you could do your problem as:
``` python
import CoolProp.CoolProp as CP
import numpy as np
Tc, Tt = [CP.PropsSI(k, 'REFPROP::Nitrogen') for k in ('Tcrit', 'Ttriple')]
T = np.arange(Tt, Tc, 0.0001)
p = CP.PropsSI('P', 'T', T, 'Q', 0, 'REFPROP::Nitrogen')
print(p)
```
which yields
```
[  12519.78184862   12520.01213523   12520.24242765 ... 3395750.68531928
 3395767.1232264  3395783.56157273]
```

**Comment by EricLemmon** [comment]
This one's fixed now, it was just a matter of generating more than 32,767 points with a counter defined as an integer.  I put an upper limit of 20,000 on it, beyond that it may seem to get hung up, even though it is usually just chugging along.  I checked most of the other places where this number may also get exceeded and hopefully found them all.
