### ISSUE TITLE
REFPROP upgrade from v9.X to v10 - Are any fluids deprecated, if so which ones?

### ISSUE THREAD

**Issue by nathan-kamphuis** [usnistgov/REFPROP-issues#256]
Hi REFPROP team,

I want to say thanks for the amazing work you all have done.

Six months ago when RP v10 was installed, it was noticed that the fluid list was much shorter than RP v9. I assumed that the team simply hasn't had a chance to upgrade all the fluid files yet. Some of the missing fluids are older refrigerants that are no longer used by industry, yet may be used in research. Would the team share what fluids are currently missing and which ones they intend to depreciate for RP v10.

Nate

**Comment by nathan-kamphuis** [comment]
Thanks for the response gents. I'm so impressed with your herculean efforts.

For the few of us who like to keep up on the total list of fluid files available as that number grows. I'm looking for an easy to test if the complete set is installed. Thought: the number of files in the fluid folder might be a good indicator (navigating to the fluids folder inside the REFPROP folder right click, select properties and read the total number of files in the folder (one must subtract any custom files they added to their install)). In the case of the current install on my local machine, there are 153 files (.ppf .fld . hmx etc...) and not custom files. What should the number be if one has the master set? Maybe, having somewhere users and developers can check on the webpage from time to time would cut down on the number of inquires about this.

**Comment by EricLemmon** [comment]
The fluids that are contained in Refprop are all listed at www.nist.gov/srd/refprop.  The list is updated every time a new version is released.  You can find on this page the following:

> Version 10.0 includes 147 pure fluids, 5 pseudo-pure fluids (such as air), and mixtures with up to 20 components.

I am also slowing going through common questions and writing up lengthy items for those that are interested.  You can find these by searching for the label "documentation".  One of these days I'll have to do something like you have requested here; note the label "request" I added to your issue as a reminder to myself.
