### ISSUE TITLE
CO2 Mole Mass not maching NIST Webbook

### ISSUE THREAD

**Issue by CallieAYYC** [usnistgov/REFPROP-issues#26]
### Description

The mole mass given by REFPROP for CO2 is 44.0098, the value given by NIST webbook is 44.0095
Adding individual mole mass of components from 
https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl
also gives 44.0095

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** WIN10
**Access Method:** REFPROP GUI

**Comment by ianhbell** [comment]
You’re not wrong, but we maintain consistency with the equation of state for each fluid.  For instance here for CO2: https://aip.scitation.org/doi/10.1063/1.555991 .  So in this case it’s based on the understanding at the time of the development of the EOS.  Some things that are “constant” (like the universal gas constant) have shifted over the years by small amounts.

**Comment by CallieAYYC** [comment]
Thank you for the clarification.
