### ISSUE TITLE
Error in mixture bubble and dew enthalpy near critical pressure

### ISSUE THREAD

**Issue by Yaykhel** [usnistgov/REFPROP-issues#267]
### Description

When using REFPRP64.dll, Excel and REFPROP GUI, the enthalpy values (bubble & dew) of mixtures (R410A, R32/R1234yf) near the critical pressure are different. Call from C++ gave significantly larger values; Excel gives SATP error 144 and GUI gives values close to the last converged point (below the enthalpy at the critical point).

Not sure whether someone has already reported this issue and any fix.

Besides, can we know what the difference between GUI (the inner working) and the source code (FORTRAN or via wrappers) is?
It seems GUI can provide the results for all scenarios provided the inputs are within limits.

### Steps to Reproduce

1. C++ wrapper
2. Excel (REFPROP function)
3. GUI (define new mixture/predefined mixture)

**Expected behavior:** 
A consistent result from three methods

**Actual behavior:**
The C++ wrapper seems to give a random value.
Excell call gave SATP error 144 (iteration for saturation state did not converge.)
GUI seems to give a reasonable result.

### Versions

**REFPROP Version:**
REFPROP 10.0

**Operating System and Version:** 
Windows 10
 
**Access Method:** 
C++ wrapper, Excel, REFPROP GUI

### Additional Information

Please see the attached
![Mixture Excel](https://user-images.githubusercontent.com/45446429/76036893-c693fe00-5f88-11ea-890c-0f688d732583.PNG)
![Mixture GUI](https://user-images.githubusercontent.com/45446429/76036896-c72c9480-5f88-11ea-8777-51d212c054a4.PNG)

**Comment by ianhbell** [comment]
Excel evaluates the cells in a semi-random order, so that's not going to be especially helpful for debugging.  But the C++/GUI comparison is interesting.  Did you enable initialization of phase envelopes in C++?

**Comment by ianhbell** [comment]
Also, please show your inputs and outputs for C++

**Comment by Yaykhel** [comment]
This is how I called REFPROP in C++:

`
      setREFPROP.setFluid(fldName); // need to do this since the mixture composes of these fluids
      setREFPROP.setFluidMix(fldName, pHi);
      setREFPROP.setRef("DEF");           // may need to change to IIR depending on the fluid
      
setREFPROP.setEnum("MASS BASE SI"); // set the unit system
`

Not sure with "enable initialization of phase envelopes in C++".

Then I called ABFLSHdll.

The following is the data for R32/R1234yf (42/58 %mass).


4.5 | 349.6727 | 615.0914
-- | -- | --
4.51 | 615.0914 | 615.0914
4.52 | 350.6724 | 615.0914
4.53 | 615.0914 | 615.0914
4.54 | 351.7049 | 615.0914
4.55 | 615.0914 | 615.0914
4.56 | 352.7773 | 400.5776
4.57 | 353.3305 | 615.0914
4.58 | 615.0914 | 615.0914
4.59 | 354.4759 | 615.0914
4.6 | 355.0705 | 398.4246
4.61 | 615.0914 | 615.0914
4.62 | 615.0914 | 615.0914
4.63 | 615.0914 | 396.6004
4.64 | 615.0914 | 615.0914
4.65 | 358.3341 | 395.2131
4.66 | 615.0914 | 394.4689
4.67 | 359.8264 | 615.0914
4.68 | 615.0914 | 615.0914
4.69 | 615.0914 | 615.0914
4.7 | 362.3904 | 390.9484
4.71 | 615.0914 | 389.9171
4.72 | 615.0914 | 388.736
4.73 | 615.0914 | 615.0914
4.74 | 615.0914 | 379.1256
4.75 | 615.0914 | 615.0914
4.76 | 615.0914 | 615.0914
4.767553 | 378.314 | 378.314

**Comment by ianhbell** [comment]
Please provide a minimal, runnable example in C++ that I can copy-paste and run.

**Comment by Yaykhel** [comment]
Please see the following python code (a slightly modified version of yours).

```
# Setupe6
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'C:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root) ;
RP.SETPATHdll(root)
MOLSI = RP.GETENUMdll(0,'MASS BASE SI').iEnum

for fld in ['R410A.MIX']:
    if 'MIX' in fld:
        z, ierr = RP.SETMIXTUREdll(fld)
        # RP.SETREFdll('IIR',1,z,-1,-1,-1,-1)
        z = z[0:2]
        RP.SETREFdll('IIR',2,z,-1,-1,-1,-1)
    else:
        RP.SETFLUIDSdll(fld)
        z = [1.0]+[0.0]*19
        RP.SETREFdll('IIR',2,z,-1,-1,-1,-1)

    # Do calculation
    p = 4.59e6 # [Pa]
    T = 281.52 # [K]
    iMass = 0
    r = RP.REFPROP1dll('PQ','H', MOLSI, iMass, p, 0, z)
    print(r)
```

The output is: 

```
REFPROP1dlloutput(z=array('d', [0.697614699375863, 0.302385300624138, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), c=-9999990.0, q=999.0, ierr=144, herr='[SATP error 144] Iteration for saturation state did not converge for P = 4.59000 MPa.')
```

**Comment by ianhbell** [comment]
Please either try calling RP.SATSPLNdll() or enable phase envelope construction when calling RP.REFPROPdll().  This works now:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

for fld in ['R410A.MIX']:
    if 'MIX' in fld:
        z, ierr = RP.SETMIXTUREdll(fld)
        # RP.SETREFdll('IIR',1,z,-1,-1,-1,-1)
        z = z[0:2]
        RP.SETREFdll('IIR',2,z,-1,-1,-1,-1)
    else:
        RP.SETFLUIDSdll(fld)
        z = [1.0]+[0.0]*19
        RP.SETREFdll('IIR',2,z,-1,-1,-1,-1)

    # Do calculation
    p = 4.59e6 # [Pa]
    T = 281.52 # [K]
    iMass = 0
    RP.SATSPLNdll(z)
    r = RP.REFPROP1dll('PQ','H', RP.MOLAR_BASE_SI, iMass, p, 0, z)
    print(r)
```
yielding
```
REFPROP1dlloutput(z=array('d', [0.697614699375863, 0.302385300624138, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), c=24269.578989888636, q=0.0, ierr=0, herr='J/mol')
```

**Comment by Yaykhel** [comment]
Thanks, I got it. Works with C++ as well. This dll (SATSPLNdll) should be called like setfluid in Excel/python/other by default, shouldn't? Is that the case with GUI? Is there any problem if SATSPLNdll is called every fluid set up?
By the way, I do not understand/know how to enable phase envelope construction. Could you explain it?

**Comment by ianhbell** [comment]
In the GUI, the option in the preferences about initializing the phase boundary calls the SATSPLNdll function internally at setup. It can be the case that if calling SATSPLNdll with a particular composition can result in the wrong solution sometimes in phase equilibrium calculations. So it doesn't solve all problems, but generally its better than to not turn it on.

Calling the SATSPLNdll function or using the flag in REFPROPdll builds the isopleth of the phase envelope (conventionally called the phase envelope).

**Comment by Yaykhel** [comment]
Thanks. I found that calling REFPROPdll very fast from a loop crashes out of REFPROP and I needed to use ABFLSHdll. Anyway, it might be it is what it is.

**Comment by ianhbell** [comment]
Can you please provide your script that causes REFPROP to crash?  That should not happen, and I would like to figure out why, or if there is another kind of error.

**Comment by Yaykhel** [comment]
Please give me some time to write a minimal version. Meanwhile, my compiler detected an error/warning in REFPROP_lib.h for C++ in line number 752. I have updated as follows.

```
std::wstring wStr = t; // Original
std::wstring wStr = L"t"; // updated 
```

I don't think it was the issue for REFPROP() to crash out.

**Comment by ianhbell** [comment]
That's a warning...  Shouldn't be the cause of error.  More likely you have a read outside the buffer, most common problem with REFPROP interfacing.

**Comment by EricLemmon** [comment]
I've transferred your issue to the Refprop-wrappers site since this deals with calling the DLL.
