### ISSUE TITLE
Failure to calculate cricondentherm and dew/bubble points for some binary mixtures

### ISSUE THREAD

**Issue by Enantiomeer** [usnistgov/REFPROP-issues#268]
**_Failure to calculate cricondentherm and dew/bubble points temperatures for some binary mixtures_**

**Description:**

When using REFPROP GUI, I get a failure when trying to calculate the cricondentherm of a binary mixture of 13 mole % CO2 & 87 mole % CH4. This can be observed when viewing Substance → Fluid Information:

![RefProp Cricondentherm](https://user-images.githubusercontent.com/61894526/76137025-8f7d2580-6038-11ea-93a8-a2845a4c7607.JPG)

When I try to use this mixture to calculate Saturation points (bubble and dew points at same composition) I get the following error at pressures near cricondenbar/critical point::

[SATP error 141] Pressure input to saturation routine is greater than critical or maxcondentherm pressure: P = 5.00000 MPa, Pc = 4.96035 MPa.     
                                                                                                   
The critical pressure that is shown here does not match the critical pressure shown in the Fluid Information (5.5029 MPa). 

I plotted the bubble and dew lines using the excel wrapper and obtained the below plot:
![Saturation lines](https://user-images.githubusercontent.com/61894526/76137066-09adaa00-6039-11ea-8192-9dad2223d7e8.JPG)

In this case I get the following error when trying to calculate dew/bubble point temperature using any pressure above 4.96035 MPa:

#[PQFLSH error 141] Pressure input to saturation routine is greater than critical or maxcondentherm pressure: P = 5.00148 MPa, Pc = 4.96035 MPa.

When I use the excel wrapper to calculate the Cricondentherm I get the following results (without any error message):

- T: 300.00000000000 K
- P: 0 MPa
- d: 0 mol/m³

I’m guessing these values are not real but just the initial guesses the algorithm uses and then these are reported due to the fact that the calculation fails.

I experimented with the composition of the mixture and the issue only occurs when CO2 concentration is between 7.84 & 14.57 mole %. With compositions outside of this range it is possible to calculate the cricondentherm and bubble and dew lines.

I am using the default equations for the calculation of properties. I also tried all other options  (GERG-2008, AGA8, Peng Robinson, Peng Robinson without Volume Translation) with below results:

- GERG-2008: Cricondentherm is also unknown, slightly different values for critical point and Cricondenbar
- AGA8: Cricondentherm and Cricondenbar are unknown, slightly different values for critical point
- PR: Cricondentherm could be calculated (T = 209.01 K, P = 5.4204 MPa, d = 6844.2 mol/m³), slightly different values for critical point and Cricondenbar. However calculation of dew and bubble point still fails at pressures near cricondentherm/cricondenbar/critical point:

![Peng Robinson](https://user-images.githubusercontent.com/61894526/76137208-68275800-603a-11ea-8771-2073e5f58182.JPG)

- PR w/o VT: Cricondentherm could be calculated, slightly different densities for critical point, Cricondentherm and Cricondenbar vs. PR, calculation of dew and bubble points still fails at pressures near cricondentherm/cricondenbar/critical point.

I have performed some more experimenting using the GUI. If I create a T-p plot of the saturation lines I can observe that there are two inflection points in the vapour saturation line. One of those appears to at/near the pressure of 49.6035 bar which is mentioned in the error message I got:

![TP diagram](https://user-images.githubusercontent.com/61894526/76139883-1cce7300-6055-11ea-8038-2f40fbd40a6b.JPG)

Could this possibly be related to the reason the calculations failed?

Can anybody tell me what the cause of this issue is?
Is there anything I can do to prevent this issue?
Is there a way to recognize this issue using the Excel (or C#) wrappers so that I can perform some form of error trapping?

**Steps to Reproduce:**

1. GUI (define new mixture/predefined mixture)
2. Specify binary mixture of CO2 & CH4
3. Use CO2 mole fraction between 7.84 & 14.57 mole %
4. View fluid information
5. Calculate Saturation points (bubble and dew points at same composition)

**Expected behavior:**

- Ability to calculate cricondentherm for any mixture
- Error message to wrapper in case of failure to calculate cricondentherm

**Actual behavior:**

- Not possible to calculate cricondentherm for some mixtures
- No error message to wrapper

**Versions:**

REFPROP Version:
10.0

Operating System and Version:
Windows 10, 64 bit, version 10.0.18363 build 18363

Access Method:
REFPROP GUI, Excel       

**Additional information:**

When using REFPROP GUI, I also observe what appears to be an abnormality/instability in the calculation of the critical point of a mixture of CO2, CH4 and toluene, where the critical point, when plotted in a T-p diagram is not on the saturation line.

Here you can see the Fluid information: 
![Mixture 1](https://user-images.githubusercontent.com/61894526/76149915-03551780-60a5-11ea-8159-dc2597e8c648.JPG)

And the resulting T-p diagram:
![Critical 1](https://user-images.githubusercontent.com/61894526/76149922-149e2400-60a5-11ea-856d-f603223ff0d4.JPG)

Remarkably, when I make a very minor change in the composition, the calculated values of Pc & dc change considerably:
![Mixture 2](https://user-images.githubusercontent.com/61894526/76149933-37303d00-60a5-11ea-8ba5-6c393f2d8495.JPG)

And so does the T-p diagram:
![Critical 2](https://user-images.githubusercontent.com/61894526/76149941-4c0cd080-60a5-11ea-9f0d-4ea370bbaebb.JPG)

As can be observed, there is also a minor irregularity in the transition between the vapour and liquid saturation lines. 

Using the excel wrapper I checked the effect of composition on the calculated Pc:
![Concentration](https://user-images.githubusercontent.com/61894526/76149966-8c6c4e80-60a5-11ea-8f83-dde419488021.jpg)

For this calculation I fixed the CO2 concentration to 13 mole %, varied the Toluene concentration form 0.0800 mole % to 0.0900 mole % in steps of 0.0001 mole % and added methane to 100 %.

As can be observed there are many irregular jumps in this graph, which to me suggests some type of instability in the calculation/convergence method.

I was wondering if these effects might all be related to the same, underlying cause?

**Comment by ianhbell** [comment]
Yes, all this comes down to the model itself. In theory you can get the isopleth directly from the REFPROP dll, but that seems to be broken currently (https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb#Flash-Calculations)

CoolProp (implementing the same model) has the same "problem":
```python
import matplotlib.pyplot as plt

z = [0.13, 0.87]

import CoolProp.CoolProp as CP 
AS = CP.AbstractState('HEOS', 'CO2&Methane')
AS.set_mole_fractions(z)
AS.build_phase_envelope('')
pe = AS.get_phase_envelope_data()
plt.yscale('log')
plt.plot(pe.T, pe.p)
plt.xlabel('$T$ / K')
plt.ylabel('$p$ / Pa')
plt.ylim(bottom=1e6)
plt.xlim(left=200)
plt.show()
```
yielding
![image](https://user-images.githubusercontent.com/11966765/76353010-684b8000-62e6-11ea-908d-b6140ea315d7.png)

The short answer is : algorithms for mixtures are hard, and producing flash calculations that don't fail (or yield the wrong answer) is very difficult indeed. That is why we use tracing, rather than blind calculations, for the most reliable phase equilibria: https://aiche.onlinelibrary.wiley.com/doi/full/10.1002/aic.16074 (but only for binary mixtures).  Similarly, looking at the criticality contours can give an idea of how "weird" the behavior is in the critical region: https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=13569104234681582828 .  The weirder the behavior, the more of these wiggles you are likely to see.

**Comment by ianhbell** [comment]
Further confirmation that the problem is the model.  REFPROP and CoolProp isopleths overlaid:
```python
import matplotlib.pyplot as plt
import pandas

z = [0.13, 0.87]

# With CoolProp
import CoolProp.CoolProp as CP 
AS = CP.AbstractState('HEOS', 'CO2&Methane')
AS.set_mole_fractions(z)
AS.build_phase_envelope('')
pe = AS.get_phase_envelope_data()
plt.yscale('log')
plt.plot(pe.T, pe.p)

# With REFPROP
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root) ;
RP.SETPATHdll(root)
RP.SETFLUIDSdll('CO2 * METHANE')
# Construct the saturation spline
RP.SATSPLNdll(z)
# Now we programatically extract the nodes of the isopleth...
Nnodes = RP.REFPROPdll("","SPLINENODES","",0,0,0,0,0,z).iUCode
data = []
for i in range(1,Nnodes+1):
    rho_vap,T,p,rho_eq,z0,z1 = RP.REFPROPdll("","SPLINENODES","",0,0,i,0,0,z).Output[0:6]
    data.append(dict(rho_vap = rho_vap,T=T,p=p,z0=z0,z1=z1))
# Convert the data points into a pandas DataFrame
df = pandas.DataFrame(data)
# And plot them...
plt.plot(df['T'],df.p*1000,'o',mfc='none')

plt.xlabel('$T$ / K')
plt.ylabel('$p$ / Pa')
plt.ylim(bottom=2e6, top = 1e7)
plt.xlim(left=200, right=208)
plt.show()
```
yielding
![image](https://user-images.githubusercontent.com/11966765/76354089-36d3b400-62e8-11ea-9676-a47ac86c5751.png)

**Comment by Enantiomeer** [comment]
Thank you for the answers. If I interpret it all correctly the most reliable vapour and liquid saturation lines can be generated by calling and interpreting the SATSPLNdll by using the python code you provided, right?

Doing the same using C# shouldn't be an issue either I assume, is that correct?

Besides having the plot of the saturation lines I also wanted to use the  PHASE or QMOLE property to check whether or not at a given temperature & pressure my mixtures are in a two-phase state. I tried this for a rather complicated and weird 10 component mixture:

![Complex mixture](https://user-images.githubusercontent.com/61894526/76413405-a653ad00-6395-11ea-8b3c-dce14a3bf133.JPG)

As you can see for several points (both inside and outside the two-phase region) this fails due to non-convergence. Is there a better way to determine whether or not my mixture is in a two-phase state, given I only know the temperature and pressure?

**Comment by EricLemmon** [comment]
It appears that we have missed answering this question, I apologize for the long delay.

But unfortunately there's not a good answer to give you anyway.  The multitude of mixture complexities, varieties, poor models, and so forth means that we will never be able to correctly solve the saturation states for all cases.  In my personal opinion, life is much easier if you just stick with pure fluids!  (sorry, bad joke)

With time the models and root solving routines in Refprop will get better, but this will be a slow process.  As you've seen, plotting the phase diagrams in Refprop always makes at least understanding the problem a bit easier.

If there is not anything further, could you close this issue?

**Comment by Enantiomeer** [comment]
Thank you for the feedback. For now I think I have the information I need so I'll close the issue.
