### ISSUE TITLE
SETFLUIDS hides estimation on second call

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#269]
If I call ``SETFLUIDSdll`` for a mixture with estimated interaction parameters, the first call clearly indicates that the interaction parameters are estimated by returning a negative value for ``ierr``.  If I call ``SETFLUIDSdll`` again, with the same arguments, then I get a return value of ``0``.  One could argue whether or not that is the correct value to return because the ``0`` indicates that everything went fine, which from a certain standpoint it did, because it did nothing.  But yet the ``ierr`` of ``0`` also in general indicates that the parameters were taken from ``HMX.BNC``.  I was tripped up by this behavior in my code, and the only solution was to call ``SETFLUIDS`` again with another fluid to reset.

This code
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
print(RP.RPVersion())
fld0 = 'R23'
fld1 = 'R1234YF'
for fldA, fldB in [(fld0, fld1), (fld0, fld1)]:
    print(RP.SETFLUIDSdll(fldA + '*' + fldB))
```
yields
```
10.0072
-117
0
```

**Comment by EricLemmon** [comment]
I think I would argue for leaving it as is.  Adding additional common block variables to keep track of what error happened and the fluids requested during the previous call to setup, and then producing the code that will know when that error should be returned will ultimately lead to a case or two where a user finds an interesting path where the tracking doesn't catch the problem.  We've seen that happen before.  The better solution would be to add additional warnings in the manual that the best practice is to call it once with the desired fluids and then to never resend the fluid names until a change is requested.  Perhaps even return a warning to that effect when the fluids are sent a second time so as to persuade users to follow this recommendation.

**Comment by ianhbell** [comment]
Yeah, I buy this argument, it is not that common an issue, but perhaps we could add it to the "could be nice" pile.

**Comment by EricLemmon** [comment]
I've marked it with the "feature-request" label so that we will remember to return to this at a later date.
