### ISSUE TITLE
CO2 SOLUBILITY IN LIQUID WATER

### ISSUE THREAD

**Issue by gernotrother** [usnistgov/REFPROP-issues#27]
### Description

I am writing you to ask for help with a calculation I want to perform using Refprop 10. I am trying to calculate the solubility of CO2 in liquid water at 35 C and 0-150 bar, but I cannot figure out how to do this. Is it possible to calculate this curve, and if so could you please point me in the right direction?

### Steps to Reproduce

I followed the instructions in the manual.
 

**Expected behavior:** 

Solubility curve calculated

**Actual behavior:** 

I get error messages and the temperature gets turned up to over 500 K.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** refprop software 

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
What error messages do you get?  Screenshot would be helpful too

**Comment by EricLemmon** [comment]
Refprop does not directly calculate the solubility, but we will add this to a future version.
