### ISSUE TITLE
Fluid synonym for CF3I

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#271]
According to the ASHRAE standard, the name for CF3I should be FIC-13I1, rather than HFC-13I1 in the fluid file.  The HFC- prefix would imply that all atoms are fluorine, hydrogen, or carbon, but the presence of iodine changes the fluid class from HFC- to FIC-.

**Comment by EricLemmon** [comment]
This change has now been made and is up on the Q drive in the Install/Alpha directory.

**Comment by ianhbell** [comment]
Thanks!
