### ISSUE TITLE
REFPROP allows invalid hOut of XLIQ(0)

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#275]
The input ``XLIQ(0)`` is allowed in REFPROPdll, but it should not be.  The correct input is ``XLIQ``

```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll('CO2*METHANOL','QT', 'XLIQ(0)', RP.MOLAR_BASE_SI,0,1,1,298.15,[0.1,0.9])
print(r)
```

**Comment by EricLemmon** [comment]
This one is now fixed and will catch any instance of an input value less than 1 or greater than nc, and not only for xmass and xmole, but for all others that have composition number inputs, such as Tnpb(1).
