### ISSUE TITLE
Mixture Phase Calculation Issues

### ISSUE THREAD

**Issue by HCSpin** [usnistgov/REFPROP-issues#277]
I have confirmed this issue in Excel (MacOSX 2019) and in the NIST Refprop executable (10.0.0.02)

I am trying to generate the enthalpy for mixtures of Kr and He, with mole fractions ranging between 0 and 1.

P=1200kPa
T=350K

As the mole fraction of Kr is reduced from 1 to 0.1, the phase is calculated to be superheated gas.
At 0.05, the phase = Saturated liquid
Between 0.01 -> 1e-6, a warning appears, indicating that the state appears to be 2-phase.
At 0.0, the state shows as supercritical

How can I force the calculations to assume a single (gas) phase?

Here is a screenshot from the REFPROP executable: 
![image](https://user-images.githubusercontent.com/60363654/78152684-2060da00-7408-11ea-9725-ee58c4b53d50.png)

**Comment by ianhbell** [comment]
You want < on the last quantity you enter to force a gas solution:
![image](https://user-images.githubusercontent.com/11966765/78170854-958cd900-7421-11ea-814a-42ddb15107a4.png)

More generally, that model seems to give totally incorrect VLE behavior, so I would be very cautious in using it.  The experimental data (markers) has phase envelopes that transition from open to closed (like other cryogen mixtures), but the model in REFPROP doesn't show that behavior at all:
![KRYPTON_NEON](https://user-images.githubusercontent.com/11966765/78171177-16e46b80-7422-11ea-9e83-0c822ed3fc0d.png)

**Comment by HCSpin** [comment]
Thanks!  Is there a similar adjustment to '<' that can be used in Excel and/or Python?

**Comment by ianhbell** [comment]
In Python, in ``REFPROPdll``, it's also ``<``, or ``TP<`` for instance.

I don't remember in Excel, I don't ever use it, but I think its something similar.  Have you looked through the sample workbook?

**Comment by HCSpin** [comment]
Looks like the Input code is 'TD&<', for example, in Excel, but it doesn't solve the problem above.  There must be something strange about the He model that's causing this.  x[He]=0.95 being associated with a liquid state at 350K/1200kPa just seems odd.

**Comment by ianhbell** [comment]
Can you plot the pressures along the 350 K isotherm as a function of density?  That should show a monotonic curve with no local minima I think, and otherwise, something funky is going on.

**Comment by EricLemmon** [comment]
In Excel you can use the letters L and V after the input properties for your application.  For example, you can use TDV or TDL.  This would be the same method you would use when you call the REFPROPdll function.

**Comment by HCSpin** [comment]
Setting T=350K: 
If I disable SATSPLN, I get: 
![image](https://user-images.githubusercontent.com/60363654/78176332-4c8d5280-742a-11ea-83e9-3b1b8f00cce8.png)
Re-enabling SATSPLN yields:
![image](https://user-images.githubusercontent.com/60363654/78176468-84949580-742a-11ea-8bc4-463592accfe5.png)

**Comment by ianhbell** [comment]
You'll want the TDL option so it doesn't do a phase equilibrium calculation, just does the calculation of pressure directly.

**Comment by HCSpin** [comment]
Thank you very much.  Consistent use of TPV or TDV seems to have gotten rid of the erratic behavior.  Is there a reason you suggested TDL rather than TDV?  I would think we'd want to specify vapor phase.

**Comment by ianhbell** [comment]
If the inputs are T,D, those are the natural variables of the equation of state.  If you put in either TDL or TDV, no iterative calculation is required (the source of the failure), and the EOS is just evaluated at the given temperature and density (though you should be aware that your inputs might be silently two-phase and you might not know it from your outputs).  For TPV, you still have an iterative calculation to do to find T,D, but you have simplified the problem by ignoring the possibility of phase equilibria.  Again, same caveats as TDL, and TDV apply.
