### ISSUE TITLE
Unusual Mixture Reference State Changes

### ISSUE THREAD

**Issue by HCSpin** [usnistgov/REFPROP-issues#278]
Using the Excel Wrapper on a Mac (Excel 2019), the enthalpy calculated for a mixture of Kr/He changes unexpectedly as follows.

Define the mixture to be (by mole fraction)
Kr (.70), He (0.3)
at T=350K, P=1200kPa, H = 36.91 kJ/kg

If the mixture is changed to (by mole fraction)
Kr (.70), He (0.3), Propane (0.0)
at T=350K, P=1200kPa, H = 197.26 kJ/kg

Why does the reference state change for the two "different" mixtures?

Calculating ∆H between two different temperatures/pressures is unaffected and is consistent for both representations of the above mixtures.

**Comment by ianhbell** [comment]
Indeed, that seems like a bug. 

Changes in enthalpy for mixtures is tricky, to say the least, and doesn't always operate the way you think it might in a thermodynamic model.  It is a topic that I myself don't fully understand.

**Comment by EricLemmon** [comment]
This is actually not a bug, but comes about by us humans desiring nice, easy-to-work with numbers for enthalpy and entropy.  If we were to get rid of all reference states except nature's true reference, which is h and s equal zero at 0 K, then these problems would go away.  For more details, see:

https://github.com/usnistgov/REFPROP-issues/issues/222
