### ISSUE TITLE
Multi Mixture Calculation Error

### ISSUE THREAD

**Issue by chiaracorazzol** [usnistgov/REFPROP-issues#279]
### Description

we have found and fixed an issue in Labview caused by calling "setup" multiple times. We found this document, and acted consequentially:

https://pages.nist.gov/REFPROP-docs/#changing-fluids-and-calling-setup-multiple-times

but we found another problem with the proposed solution.

We have a plant using R448a and water-glycol, the same software controls both parts of the plant, and it needs to calculate properties for both mixtures. So we loaded all fluids, and set the composition to 0 for those not involved each time, as stated on the document. We noticed that the results are not as expected: the numbers are considerably different. The software is developed in LabVIEW, but we easily reproduced the problem in excel, as you can see in the picture attached.

![image003](https://user-images.githubusercontent.com/63414227/78972099-46276680-7b0d-11ea-90f0-17a26bffb380.png)

Also, you will find attached the .xls example. About error 117: in the example linked to the document we read that it can be ignored, because we are not actually mixing R448a and water-glycol:

https://trc.nist.gov/refprop/FAQ/EX-MULTI.FOR

We don’t have evidence of this behavior using other mixtures (e.g. CO2 and water-glycol).

Any suggestion you may give us will be highly appreciated.

[MultiMixture_Calc_Error (1).xlsx](https://github.com/usnistgov/REFPROP-issues/files/4460395/MultiMixture_Calc_Error.1.xlsx)

### Versions

**REFPROP Version:** [REFPROP 10.0]  
**Operating System and Version:**  
**Access Method:** Labview and Excel

**Comment by EricLemmon** [comment]
There's a good possibility this has been fixed from other changes I have been making to update the Fortran code over the last few weeks.  I ran the code below and got the same answer for both D1 and D2, for both the top section for R448A and the bottom section for water+ethylene glycol.  Can you send me a personal email and I'll send you the updated DLL?  (eric.lemmon@nist.gov)

```
c  R448A

      T=278.15d0
      P=.434d0
      hfld='R32;R125;R1234yf;R134a;R1234zee;Water;EGlycol|'//
     &'0.43122;0.18691;0.15132;0.17759;0.05296;0;0'
      call REFPROP2 (hFld,' ',' ',0,0,0d0,0d0,z,Ou,q,ierr,herr)
      call REFPROP1 ('TP','D',2,0,T,P,z,D1,q,ierr,herr)

      hfld='R32;R125;R1234yf;R134a;R1234zee|'//
     &'0.43122;0.18691;0.15132;0.17759;0.05296'
      call REFPROP2 (hFld,' ',' ',0,0,0d0,0d0,z,Ou,q,ierr,herr)
      call REFPROP1 ('TP','D',2,0,T,P,z,D2,q,ierr,herr)
      
c  Water+ethylene glycol

      hfld='R32;R125;R1234yf;R134a;R1234zee;Water;EGlycol|'//
     &'0;0;0;0;0;.4;.6'
      call REFPROP2 (hFld,' ',' ',0,0,0d0,0d0,z,Ou,q,ierr,herr)
      call REFPROP1 ('TP','D',2,0,T,P,z,D1,q,ierr,herr)

      hfld='Water;EGlycol|0.4;.6'
      call REFPROP2 (hFld,' ',' ',0,0,0d0,0d0,z,Ou,q,ierr,herr)
      call REFPROP1 ('TP','D',2,0,T,P,z,D2,q,ierr,herr)
```

**Comment by EricLemmon** [comment]
I haven't received an email yet.  Have you resolved this issue?  If not, please email me (and ignore my out-of-office message).

**Comment by EricLemmon** [comment]
Because I believe this bug has been fixed and we have not heard back, I've closed the issue.  If you are still interested in the updated DLL, then you can write to me personally, or you can continue to post messages here or reopen the issue.
