### ISSUE TITLE
ALLPROPS - 2nd Derivatives H, S, E (and 1st for E)

### ISSUE THREAD

**Issue by paarfi** [usnistgov/REFPROP-issues#28]
Feature request to add more derivative outputs to the ALLPROPS methods.
1st derivatives on internal energy
DEDT_D, DEDT_P, DEDD_T, DEDD_P, DEDP_T, DEDP_D
2nd derivatives on enthalpy, entropy, and internal energy
D2HDT2_D, D2HDD2_T, D2HDP2, D2HDTD, D2HDPT, D2HDPD
D2SDT2_D, D2SDD2_T, D2SDP2, D2SDTD, D2SDPT, D2SDPD
D2EDT2_D, D2EDD2_T, D2EDP2, D2EDTD, D2EDPT, D2EDPD

These would be helpful in generating interpolation tables.

**Comment by ianhbell** [comment]
Feature request logged.  Seems reasonable.

In the meantime, you can get access to these derivatives analytically from CoolProp with the REFPROP backend: http://www.coolprop.org/coolprop/LowLevelAPI.html#partial-derivatives

**Comment by thorade** [comment]
@paarfi Shameless self-promotion:
The tables on pages  141 and 142 might also help, Refprop should be able to calculate all required derivatives:
https://tubdok.tub.tuhh.de/bitstream/11420/1209/1/Thorade_2014_EntropieBewertung.pdf
https://doi.org/10.15480/882.1207

**Comment by EricLemmon** [comment]
Ironically, and very many thanks to Matthias Thorade and the document he wrote, this routine was written before version 10 went out, but was not considered fully finished to distribute with the program.  However, Ian has given a solution that works for now, and we will integrate the new but unfinished routine into the next minor release of Refprop once it is deemed ready to go.

**Comment by EricLemmon** [comment]
I've closed this issue, but the "feature request" label will remind us about it till it is done.

**Comment by ianhbell** [comment]
Yeah, that’s fine
