### ISSUE TITLE
Determination of the GWP-value (Global Warming Potential) of refrigerant fluids with RefProp V. 10.0

### ISSUE THREAD

**Issue by vve-Venzik** [usnistgov/REFPROP-issues#280]
Hallo,
 
I hope you can help me. I use the RefProp database version 10 with Excel and would like to check the GWP value of different refrigerant fluids in Excel. The command I use is as follows: =REFPROP("GWP"; "R454C"; "C"). I get the value 675 back. But if you look in the literature, the GPW value of R454C is just 146. What am I doing wrong?
 
Thank you very much for your help!
 
Best Regards

**Comment by ianhbell** [comment]
Can you please provide a reference for your value for R454C?

**Comment by ianhbell** [comment]
The GWP of the mixture should be the mass-fraction-weighted average of the pures, so R-32 has a GWP of 675, and R-1234yf circa 1, and therefore, for a 21.5/78.5 (mass) mixture, the value should be, as you correctly write:

```
>>> 0.215*675 + 0.785*1
145.91
```

**Comment by ianhbell** [comment]
This is also touched on in our paper: https://doi.org/10.1016/j.ijrefrig.2019.05.035

**Comment by vve-Venzik** [comment]
Hello,

thank you for the quick help and the reference to your publication.

Best regard,
Valerius Venzik

**Comment by EricLemmon** [comment]
This is an interesting "error".  In the manual, the label "GWP" is described in a section where each possible input will return the values for the pure fluids, not for the mixture.  Most of them are strings, such as "INCHI", "FAMILY", "HASH", and so on.  Only "GWP" and "ODP" are actual numbers, but the routine does the same with them as with the other items in this section and sends back the GWP for each pure fluid, not for the mixture.  When I ran your example, the item in the first cell was 675, which is the value for R32, and the value in the second cell was -1, an indicator that either the value is unknown or that the fluid file simply does not have the number in it, which is the case for R1234yf.  Additionally, a warning number of -852 was returned in ierr along with this message in herr:

> [ALLPROPS warning -852] Additional properties are included in the output array, the input string and output array do not line up.

There are a few places in the manual that discuss the issue about additional values returned, such as this segment:

> Some properties will return multiple values, for example,  hOut='F,Fc,XMOLE' will return 12 properties for a four component system, these being F(1), F(2), F(3), F(4), Fc(1), Fc(2), etc.  To retrieve the property of a single component, use, for example, hOut='XMOLE(2),XMOLE(3).

But the description for GWP is quite vague about this.  I think the solution might be to add a new entry, such as GWPMIX, that would return the value for the mixture, and a comment under the GWP section that the values for all pure fluids will be returned.

**Comment by EricLemmon** [comment]
The string GWPMIX has been added and will return the GWP of the mixture.  If one of the GWP's for the pure fluids is not known (i.e., set to -1 in the fluid file), an error code will be returned.  A comment has been added in the section that describes the codes that the string GWP is for pure fluids only, and that the array returned from the REFPROP routine will contain all of the values for each pure fluid.
