### ISSUE TITLE
Relationship between NIST 14 and Refprop

### ISSUE THREAD

**Issue by toshiko-k** [usnistgov/REFPROP-issues#281]
Hi, I have recieved a question about supercritical CO2 density and phase calculation.
I can calculate them using Refprop10 beautifully, but customer requests us to use NIST 14 database.
https://www.nist.gov/publications/nist-14-nist-mixture-property-database

What is the relationship between NIST14 and Refprop10?
Is NIST14 equation included into Refprop?
I appreciate your help.

**Comment by EricLemmon** [comment]
NIST14 was discounted over a decade ago after being merged with Refprop.  Many of the equations of state used in that program were out-of-date, and the change to Refprop meant that the equations were updated with the most recent and most accurate ones available.  For CO2, if I remember right then NIST14 was using the equation of Ely et al.:

Ely, J.F., Magee, J.W., and Haynes, W.M., "Thermophysical Properties for Special High CO2 Content Mixtures," Research Report RR-110, Gas Processors Association, Tulsa, OK, 1987.

At the time of the merger, that equation had already been superseded (for many years) by the equation of Span and Wagner:

Span, R. and Wagner, W., "A New Equation of State for Carbon Dioxide Covering the Fluid Region from the Triple-Point Temperature to 1100 K at Pressures up to 800 MPa," J. Phys. Chem. Ref. Data, 25(6):1509-1596, 1996.  doi: 10.1063/1.555991  

Thus the merger automatically changed the calculations from the equation of Ely et al. to that of Span and Wagner, along with properties of mixtures containing CO2.

**Comment by toshiko-k** [comment]
Thank you for your quick reply. It is clear now!
