### ISSUE TITLE
The enthalpy change (Δh) given by GUI and DLL is different for mixture

### ISSUE THREAD

**Issue by djs97** [usnistgov/REFPROP-issues#286]
### Description
I have been using REFPROP 10 to calculate the state of predefined mixture like R454C.
I have read about some previous issue like https://github.com/usnistgov/REFPROP-wrappers/issues/238, which mention about the different reference state between GUI and DLL. So here I focus on the enthalpy change, which should have nothing to do with a reference state.

### Here is my python code
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
import os

rp = REFPROPFunctionLibrary(os.environ['RPPREFIX'] + '\REFPRP64.dll') #REFPRP64
rp.SETPATHdll(os.environ['RPPREFIX'])
print(rp.RPVersion())

z = rp.SETMIXTUREdll('R454C.MIX')[0][0:2]
print(z)

r0 = rp.ABFLSHdll('TQ', 253.15, 1.0, z, 2)
print('h0 = '+str(r0.h), 'p0 = '+str(r0.P))

r1 = rp.ABFLSHdll('TQ', 263.15, 1.0, z, 2)
print('h1 = '+str(r1.h), 'p1 = '+str(r1.P))
print('h1-h0 = '+str(r1.h-r0.h))

r2 = rp.ABFLSHdll('TQ', 273.15, 1.0, z, 2)
print('h2 = '+str(r2.h), 'p2 = '+str(r2.P))
print('h2-h1 = '+str(r2.h-r1.h))

r3 = rp.ABFLSHdll('TQ', 283.15, 1.0, z, 2)
print('h3 = '+str(r3.h), ' p3 = '+str(r3.P))
print('h3-h2 = '+str(r3.h-r2.h))
```
### Python output
```
10.0076
array('d', [0.375149546574766, 0.624850453425234])
h0 = 443.3807371705113 p0 = 218.2954712168571
h1 = 450.26246616346106 p1 = 319.57677293721815
h1-h0 = 6.881728992949775
h2 = 456.86864261009384 p2 = 453.6934002258921
h2-h1 = 6.606176446632787
h3 = 463.1080320059498  p3 = 627.1441545960005
h3-h2 = 6.239389395855937
```
### GUI output
![image](https://user-images.githubusercontent.com/56409735/80275791-d952c580-86e3-11ea-99ca-e5a75c9a67ed.png)

We can see that the GUI and DLL landed on the same state point (based on the same pressure). However, the enthalpy change given by DLL is higher than the change from GUI, which should be the same. And the difference between them is already considerable.

### Versions

**REFPROP Version: 10.0076**
**Operating System and Version: Windows 10** 
**Access Method: Python 37-64bit**

**Comment by ianhbell** [comment]
I think, if I remember correctly, there is some reason why mixtures have different changes in enthalpy, and only if you use the absolute zero reference state there is no problem.  But @EricLemmon will have to chime in here.  This has always been very confusing to me.

**Comment by ianhbell** [comment]
And maybe the difference only happens when you mix streams of different compositions.  I too would think that the change in enthalpy at the same composition should be the same in the GUI and the Python code.

**Comment by EricLemmon** [comment]
Take a look here and see if this answers your questions:

https://github.com/usnistgov/REFPROP-issues/issues/222

**Comment by EricLemmon** [comment]
Can you send me a personal email to eric.lemmon@nist.gov (ignore my out-of-office message for the moment).  I believe we have a new solution that will fix this, but it will require some careful checking to make sure all is working.

**Comment by EricLemmon** [comment]
This has been fixed as part of an update dealing with multiple github issues reporting the same thing.  Additional details will be given in https://github.com/usnistgov/REFPROP-issues/issues/650 and others.
