### ISSUE TITLE
SETREF should yield error code when no fluids loaded

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#287]
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
print(RP.SETREFdll("NBP", 1, [1.0], -1, -1, -1, -1))
```
yields 
```
SETREFdlloutput(ierr=0, herr='')
```
but should yield an error code because no fluid has been loaded.  The docs (https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETREFdll) say you should call this after SETUP, so if you do it before, that should be an error.

**Comment by EricLemmon** [comment]
This one has been fixed now.  I'll upload the files next time I log in to the NIST system.
