### ISSUE TITLE
Wet air

### ISSUE THREAD

**Issue by RRusanov** [usnistgov/REFPROP-issues#290]
Hello,
 
I'd like to ask you about mixtures properties in REFPROP v.10. I want to create a mixture of wet air. I know how to create such mixture. But I can add water to this mixture in gaseous state (steam), without phase transition of water. Can you tell me how to create mixture of wet air with phase transition. 
 
Kind regards,
Roman Rusanov

**Comment by ianhbell** [comment]
I don't fully understand this question.  You can make a mixture in REFPROP by specifying the components and their compositions. Then any phase change will be predicted by the model if one exists.  Please see also: https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=2411728801845017631 for a discussion of psychrometrics with multi-fluid models.

**Comment by EricLemmon** [comment]
We have not heard back on this issue, has it been resolved?
