### ISSUE TITLE
Inconsistent results for R410A.MIX between GUI and Python ctREFPROP interface

### ISSUE THREAD

**Issue by crlaugh** [usnistgov/REFPROP-issues#294]
I discovered some unexpected behavior for R410A.MIX today when I was using the ctREFPROP Python interface, in which I found that state calculations using TPRHO produce results for R410A.MIX that don’t agree with the results obtained from the GUI.  I am using REFPROP dll version 10.0.0.76 on a Windows 10 machine.  As an example, here is my Python code that calls the REFPROP dll:

``` python
import os 
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print(RP.RPVersion())
RP.SETPATHdll(os.environ['RPPREFIX'])
r = RP.SETMIXdll("R410A.MIX", "HMX.BNC", "DEF")

TTest = 281.8168292682927
PTest = 1011.8994781214569
wm = RP.WMOLdll(r.z)
rhoTest = RP.TPRHOdll(TTest, PTest, r.z, 2, 0, 0).D
rhoOut = rhoTest*wm
thermOut = RP.THERM2dll(TTest, rhoTest, r.z)
hTest = thermOut.h
sTest = thermOut.s
hOut = hTest*1000.0/wm
sOut = sTest*1000.0/wm
print(hOut*1e-3, sOut*1e-3)
```
The results produced by this code are hOut = 425.8253720279707 kJ/kg, and sOut =  1.8706482640901794 kJ/kg-K.  However, as you can see from the inline image, the REFPROP GUI produces h=424.611541908 kJ/kg, and s=1.79991885462 kJ/kg-K.  I also tried using TPFLSH to do the same calculations in Python, but obtained identical results as with TPRHO (as I would expect).  I also tried providing an initial density guess to TPRHO by using Dv from SATP, but that also made no difference. 

![REFPROPSnip](https://user-images.githubusercontent.com/9616147/81871244-69e32f80-9545-11ea-9364-6d6b7cd90cd7.png)

These differences are surprisingly large.  I tried switching the fluids to R32, and the output of ctREFPROP and the GUI are very consistent, matching to at least 6-7 decimal places.  

Suggestions?

**Comment by ianhbell** [comment]
Try changing the reference state for mixtures in the GUI.  For historical reasons, the default reference states for the GUI and the DLL are not the same.  For these sorts of issues, you always want to check the density as well, and they match perfectly, so it must be a reference state problem.

**Comment by crlaugh** [comment]
Setting the ctREFPROP reference state to IIR took care of it.  Thanks!

**Comment by ianhbell** [comment]
Good to hear!
