### ISSUE TITLE
Build phase envelope for pure fluid with refprop backend

### ISSUE THREAD

**Issue by raphaeltimbo** [usnistgov/REFPROP-issues#3]
I am using CoolProp with REFPROP as backend and I am trying to build the phase envelope for a pure fluid but I am not able to get the results. 

```
import CoolProp.CoolProp as CP

REFPROP = CP.AbstractState('REFPROP', 'Pentane')
REFPROP.build_phase_envelope('dummy')
p_e = REFPROP.get_phase_envelope_data()
p_e.T
```
Code above does not raise an exception and p_e.T gives an empty list.

I have tried different things, and the code below does work:
```
REFPROP = CP.AbstractState('REFPROP', 'Pentane&Pentane')
REFPROP.set_mole_fractions([0.5, 0.5])
p_e = REFPROP.get_phase_envelope_data()
p_e.T
```

**Comment by ianhbell** [comment]
Verdict seems to be that REFPROP cannot handle phase envelopes for pure fluids; request has been passed along.

**Comment by ibell** [comment]
Is this still a problem?

**Comment by raphaeltimbo** [comment]
I have just tried the code with the following config:
```
3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
CP - 6.1.1dev
REFPROP - 9.4.4.38 (021)
```
I am still getting the same results. 

I don't consider it to be a problem (Maybe an unexpected behavior?) since I am using the workaround shown:

```
REFPROP = CP.AbstractState('REFPROP', 'Pentane&Pentane')
REFPROP.set_mole_fractions([0.5, 0.5])
p_e = REFPROP.get_phase_envelope_data()
p_e.T
```

So feel free to close the issue!
