### ISSUE TITLE
dew point calculation of Ammonia-Water mixture did not converge in Refprop9.1

### ISSUE THREAD

**Issue by Satinelamp** [usnistgov/REFPROP-issues#301]
I am using Refprop9.1 to calculate the ammonia-water mixture, the mass fraction of ammonia is 0.993.
But I got a convergence error when setting pressure as 1MPa, temperature as 300.65K.
Is this a bug in Refprop9.1?
Is this bug fixed in Refprop10?
If I wanna buy Refprop10, could I get an invoice for the payment?

![0](https://user-images.githubusercontent.com/62006565/83015711-6aa2b800-a053-11ea-899a-028314eb0465.jpg)
![1](https://user-images.githubusercontent.com/62006565/83015718-6e363f00-a053-11ea-8be6-bc8893102e98.jpg)

**Comment by ianhbell** [comment]
![image](https://user-images.githubusercontent.com/11966765/83019873-aad34d80-9ff5-11ea-844e-c6f9955f7af9.png)

Also, make sure you try to turn on phase boundary initialization, that may help for you too:

![image](https://user-images.githubusercontent.com/11966765/83019925-c0487780-9ff5-11ea-99ef-271046851d84.png)

**Comment by Satinelamp** [comment]
Could I get an invoice if I pay for Refprop 10 with a credit card? 

https://www-s.nist.gov/srd_online/index.cfm?fuseaction=home.main&productID=SRD23V10

**Comment by ianhbell** [comment]
Yes I believe so, though I don’t handle the payments.
