### ISSUE TITLE
How to use fluid data of Hydrogen?

### ISSUE THREAD

**Issue by JHulk5623** [usnistgov/REFPROP-issues#302]
Hi guys,

 I have one question. 
 When I make hydrogen liquefaction process using refprop, how do I consider ortho-para reaction?

 Ortho-para reaction is an exothermic reaction and I don't know amount of  heat ingress.

 Can you help me?

**Comment by ianhbell** [comment]
Our colleague Dr. Jacob Leachman at Washington State University has a nice discussion of this question: https://hydrogen.wsu.edu/2015/06/22/why-equilibrium-hydrogen-doesnt-exist/

**Comment by JHulk5623** [comment]
Thank you for quick reply.
Would you mind if I ask you to make ortho-para reactivity process in excel using refprop?
I will study how to make ortho-para reactive model but it seems like too hard to make process model.

My goal is to get the process model of liquefaction and re-gassification of hydrogen.

Thank you.

**Comment by ianhbell** [comment]
I'm afraid that you might want to contact Dr. Leachman about that, perhaps he could share his EES files he used?

**Comment by JHulk5623** [comment]
Oh, i think that is the best solution what I can do now.
Do you have any way to contact him and share his powerful EES files?

**Comment by ianhbell** [comment]
His email is all the way at the bottom of the page I linked.

**Comment by JHulk5623** [comment]
Thank you so much :) I have contacted him and wait for positive reply.
