### ISSUE TITLE
Flash Tolerance in Graphical Interface

### ISSUE THREAD

**Issue by TE42** [usnistgov/REFPROP-issues#303]
Is there a way to access the setting for flash tolerance in the Graphical User Interface?

**Comment by EricLemmon** [comment]
What exactly are you referring to?  Can you show a picture of what needs better convergence?

**Comment by TE42** [comment]
Eric:

 

Sorry I wasn’t more specific in my question. I and working with/using the recommended NIST Rec: FEQ Helmholtz equation of state for helium of Ortiz-Vega et al. (2015).

 



 

I am mapping enthalpy and entropy values between the Graphical User Interface of REFPROP 10.0 and enthalpy and entropy values that I’ve generated using Aspen Properties/Aspen Plus. I have successfully mapped enthalpy values between the two software platforms, but I have encountered a small discrepancy when mapping entropy values.

 

The implementation of REFPROP in Aspen Properties/Aspen Plus is essentially self-contained meaning that all of the pure component scalar properties (e.g., MW, TC, PC, VC) are provided by the REFPROP .dll,  and all the thermodynamic and transport properties are also computed by calls to the .dll. The only property that needs to be inputted in Aspen Properties is the pure component ideal gas heat capacity, which I’ve aligned exactly with the 5/2R = 20,786.1495 J/(kgmol K) value used for helium in the GUI version of REFPROP 10.0. Nonetheless, enthalpy and entropy in Aspen Properties/Aspen Plus are reported with a reference of the Gibbs energy and enthalpy of formation of the pure component in the ideal gas state at 1 atm and 298.15 K from the constituent elements in their standard state at 1 atm and 298.15 K. Since helium is an element that is a gas at 1 atm and 298.15 K, the reference conditions within Aspen Properties/Aspen Plus are DHFORM = 0 J/kgmol and (DHFORM-DGFORM)/298.15 = 0 J/kgmol for the ideal gas state at 1 atm and 298.15 K.

 

The Ortiz-Vega et al. (1985) equation uses reference conditions where the enthalpy and the entropy are both set to 0 for the saturated liquid at 1 atm. In order to do the mapping, I need the GUI REFPROP 10.0 to compute accurate values for the ideal gas enthalpy and ideal gas entropy of helium at 1 atm and 298.15 K since that is the reference condition used by Aspen Properties/Aspen Plus. Below is the output from a TP flash in GUI REFPROP 10.0 that shows the ideal gas entropy is 111,868.490388 J/(kgmol K):

 



 

When I do the reverse exercise in Aspen Properties/Aspen Plus, I get the entropy for the saturated liquid at 1 atm as -111,864.4786 J/(kgmol K)….so I am off by ~4 J/(kgmol K) somewhere. Right now I’m thinking this small difference might be caused by a small non-closure in the TP flash performed in GUI REFPROP 10.0.

 

So with that background, here’s my question again: Is there a way to set the tolerance for flash closures in GUI REFPROP 10.0? Or are flash tolerances only accessible when making direct calls to the REFPROP .dll?

 

If the source of the discrepancy isn’t the flash calcs in GUI REFPROP 10.0, then maybe the issue is related to different values used for the molar gas constant R. Aspen Properties/Aspen Plus uses a fixed value of R = 8,314.33 J/(kgmol K) for its internal calculations but the value used in the REFPROP .dll is R = 20,786.1495*2/5 = 8,314.4598 J/(kgmol K). The difference in R values could account for about half of the discrepancy I’m observing.

 

I appreciate any other thoughts you have….

Thanks!

Tim Eggeman

**Comment by EricLemmon** [comment]
Hi Tim,

Have you tried the option in the GUI of setting the reference state to something other than a predefined value set by Refprop?  Take a look at the picture below to see what I mean.  You can set the reference state to be exactly that used by Aspen.

Eric

![image](https://user-images.githubusercontent.com/42392984/83607438-78b37580-a538-11ea-8fb5-bf5ab1ef296c.png)

**Comment by TE42** [comment]
Eric:

Thank you for your suggestion…changing the reference conditions for GUI REFPROP to match those of Aspen Properties/Aspen Plus is a great idea!

Please consider this issue closed.

Sincerely,

Tim Eggeman
