### ISSUE TITLE
Calculating the derivate of density w.r.t. pressure and enthalpy while keeping the other property constant

### ISSUE THREAD

**Issue by choeges** [usnistgov/REFPROP-issues#304]
Hello,
I need to calculate the derivative of the density with regards to pressure and enthalpy (while keeping the other property constant). I want to use the Refprop version 10 GUI (and later on the python wrapper) but the specific options I need are not available. 
Therefore, I'd like to ask whether it is somehow possible to derive the needed values by using the availabe derivatives.
The values I need are:
- dd/dp at constant h
- dd/dh at constant p

Thank you very much for your help!
Best regards.

**Comment by ianhbell** [comment]
Hello! In the GUI, no, but in the Python code, yes.  In Python, you can get it to work, see the paper from Matthis Thorade for instance to explain how the derivative combinations operate: https://link.springer.com/article/10.1007/s12665-013-2394-z

All combinations of single-phase derivatives are implemented in CoolProp according to Matthis' approach: http://www.coolprop.org/coolprop/HighLevelAPI.html#partial-derivatives and you can also call REFPROP in the same manner through the CoolProp interface.

**Comment by choeges** [comment]
Thanks a lot for your response, Ian! The paper solves all my problems!

Since you mentioned the CoolProp Interface as possiblity to call REFPROP: Is there any specific reason to use the CoolProp-Python Interface instead of the REFPROP-Python interface, e.g. computation speed, available properties that can be calculated or so? Currently, I use the Python-wrapper for REFPROP to do all my calculations.

**Comment by ianhbell** [comment]
It depends on what you need/want. For instance, the partial derivatives are all exposed in a consistent and nice way in CoolProp's interface to REFPROP, but not in REFPROP proper.  But on the other hand, if you only ever need REFPROP, and don't care about humid air properties, or incompressible fluid properties, or tabular lookup, then I would stick to the REFPROP native wrapper.  Some things (quite a few, but less common) are only available through the native Python interface to REFPROP.

**Comment by choeges** [comment]
Thanks a lot!
