### ISSUE TITLE
Can't calculate the sound speed and viscosity of the ammonia/water mixture?

### ISSUE THREAD

**Issue by Satinelamp** [usnistgov/REFPROP-issues#308]
As the following screenshot shows, there is a warning when I try to calculate the speed of sound and viscosity when the molar concentration of water is greater than 5%.
Is this a limitation of the current physical model used in Refprop? Or it is a software bug?

![0](https://user-images.githubusercontent.com/62006565/84313499-2f4ad200-ab99-11ea-89a0-23c42f72fd9e.jpg)

![1](https://user-images.githubusercontent.com/62006565/84312737-06760d00-ab98-11ea-879e-9fbae22a3796.jpg)

![2](https://user-images.githubusercontent.com/62006565/84313516-340f8600-ab99-11ea-94c3-ac5005b36a2a.jpg)

**Comment by ianhbell** [comment]
This is a current constraint of the range of validity of the model for viscosity of ammonia + water.

**Comment by Satinelamp** [comment]
What about the speed of sound? 
Is there a reference book of a journal for the ammonia/water mixture model in Refprop?

**Comment by ianhbell** [comment]
For the current ammonia + water model, alas, no not yet, that is something that I am supposed to be working on :) The approach is similar to that of Tiller-Roth and Friend: https://aip.scitation.org/doi/abs/10.1063/1.556015

**Comment by EricLemmon** [comment]
When you press OK on that message (actually I'm not sure what that button says!), the speed of sound will appear, but the transport properties will come back with "Not calculated".

**Comment by Satinelamp** [comment]
@ianhbell So for ammonia-waster mixture, there are physical models and formulas, but the formula hasn't been validated so far when molar concentration of water is higher than 5%? Is it possible to calculate the sound speed and viscosity of a two-phase state with some simple formula and the results of a single-phase state?

**Comment by Satinelamp** [comment]
@EricLemmon. As shown in the 3rd screenshot above, when clicking OK, the speed of sound doesn't appear, either.

**Comment by ianhbell** [comment]
@Satinelamp For two-phase states, there are two answers for the viscosity, one for the equilibrium liquid phase, and another for the equilibrium vapor phase, and then you have to decide what "effective" value you want for the mixture. There is no unambiguous answer to that question, so we leave it up to you.

**Comment by nist-aharvey** [comment]
@Satinelamp For the sound speed, It is similar to what Ian said for the viscosity concerning 2-phase states.
Thermodynamically, the sound speed of a 2-phase mixture cannot be defined, just like the viscosity of a 2-phase state is not a meaningful concept.  All you could get would be the sound speed for the individual liquid and vapor phases.  Any calculation for the 2-phase mixture (for example, a choking velocity, or a pressure drop in a pipe) has to bring in additional engineering assumptions specific to your process, and REFPROP cannot do that.
P.S. In your screenshot, to get the values for the vapor and the liquid, you would (before generating the table) go under Preferences, Properties, and choose the option for "Bulk, liquid, and vapor properties"

**Comment by EricLemmon** [comment]
Has this issue been resolved now?  If so, could you close this?
