### ISSUE TITLE
HMX.BNC not re-read on call to FLAGSdll with hflag="HMX" and jflag=1

### ISSUE THREAD

**Issue by Thuke11** [usnistgov/REFPROP-issues#31]
### Description

When using REFPRP64.dll with Python calling the subroutine ``FLAGSdll`` with hflag="HMX" and jflag=1 does not result in the program re-reading HMX.BNC upon the next call to SETMIXdll. Instead, Eric Lemmon has provided me with the following work-around.

call setfluids('argon;nitrogen',i)
call FLAGS('hmx',1,j,i,herr)
call FLAGS('nc',1,j,i,herr)
call setfluids('argon;nitrogen',i)

Thanks, Eric!

### Steps to Reproduce

1. [First Step] call setfluids('argon;nitrogen',i)

2. [Second Step] call FLAGS('hmx',1,j,i,herr)

3. [and so on...] Write a new hmx.bnc  file with new parameters for the mixture in question.

4. call setfluids('argon;nitrogen',i)

5. A check on the mixing parameters shows that they are the same as the original hmx.bnc.

**Expected behavior:** [What you expect to happen]

The parameters for the mixture should be updated to the new hmx.bnc values on the second call to SETMIXdill.

**Actual behavior:** [What actually happens]

The original hmx.bnc file values are persistent.

**Comment by EricLemmon** [comment]
This has been fixed now, but there are many ways to call the setup routines, and it is possible that not all methods have been correctly updated.  Please watch carefully as you use the new code for new mistakes!

**Comment by EricLemmon** [comment]
See #80
