### ISSUE TITLE
Follow-up on REFPROP call from Fortran95 to get properties not on the dew/bubble point curves

### ISSUE THREAD

**Issue by UMCFDgitadmin** [usnistgov/REFPROP-issues#316]
Last year (November 29), I received an answer about getting properties of a binary mixture at a given P, T and bulk Z.
Iain said that I just give those values to the Refpropdll. I just assumed that we would be able to do it once we needed to (which is now, 7 months later), but we cannot  determine which specific routines to call.  Is it one of the two-phase routines?
Can you please guide us?
Thanks.
Scott Ormiston

**Comment by ianhbell** [comment]
We ask users to please fill out at least the bottom of the template so that we know what environment we need to be providing information for.  Also useful is to know what you have already tried before asking for help.

In Fortran, there is a function called REFPROP, which behaves in most ways like the REFPROPdll function exposed from the shared library: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

**Comment by UMCFDgitadmin** [comment]
Thank you for the pointer to the information.
We are using Red Hat Linux 7 with the gcc fortran compiler (although we would like to use Intel).
We are using the legacy libraries for Fortran that were generated using the Cmake-based procedure in May 2018.
We have not tried anything with the Fortran calls for the three-point (P,T,Z; where Z is mass or mole fraction) input because we do not know which routines to use.
We have been able to do the evaluations as selected state points using the Windows interface.

Is the three-point input possible with the older library that we have?

**Comment by ianhbell** [comment]
What version of REFPROP do you use?

**Comment by ianhbell** [comment]
In either REFPROP 9.x or 10, the ``TPFLSH`` function should do what you desire.

**Comment by UMCFDgitadmin** [comment]
Thank you. I will ask my Ph.D. student to try that.
I believe that  we are using 9.x (built using Cmake in May 2018), but I do not know where to look to be sure.
Should we be moving to the more general API?  And if so, how would we proceed?
Thanks.

**Comment by ianhbell** [comment]
First step is to upgrade to REFPROP 10, much easier interface to work with.

**Comment by UMCFDgitadmin** [comment]
For Windows, we have Version 10.0 from 2018-06-05 16:06.  The files that were used to build the Fortran library are from
test_nix3.zip dated 2018-05-28.  Do we need to upgrade?

**Comment by ianhbell** [comment]
Should be fine.  

So, either call the ``TPFLSH`` function from the legacy API with your T,p,z, or call the new ``REFPROP`` function.  Up to you.

**Comment by UMCFDgitadmin** [comment]
Okay. Thank you. We will try it.

**Comment by EricLemmon** [comment]
I've closed this message, but if new questions arise, you can still continue to post them, or you can reopen the issue.
