### ISSUE TITLE
SI Base units for Kinematic Viscosity

### ISSUE THREAD

**Issue by MathieuAssemat31** [usnistgov/REFPROP-issues#317]
Hello there,

Just to warn you, I think there is a small confusion on kinematic viscosity units. 

Referencing to the Excel file "REFPROP.XLS", kinematic viscosity should be given in 'cm2/s' for 'SI' units. 

But if you convert it to 'MASS BASE SI' Units, nothing change whereas it should be converted in 'm2/s'. 

Repeating the same process for dynamic viscosity ('uPa.s' -> 'Pa.s') and density ('kg/m3' -> 'kg/m3') and everything works fine. 

According to Wikipedia, kinematic viscosity should be given in 'm2/s' for either 'SI' units or 'MASS BASE SI' units. 

Thanks a lot for your amazing work. 

Kind regards,

Mathieu

**Comment by EricLemmon** [comment]
Hi,

I transferred your issue over to the REFPROP-issues site since it did not deal with wrappers.

Your comments were submitted by someone else a while back, see #118.

Eric

**Comment by MathieuAssemat31** [comment]
Alright, sorry for that !

I will close it tomorrow if you don't have it done already.

Thanks a lot,

Mathieu
