### ISSUE TITLE
Question on reference for ammonia EOS

### ISSUE THREAD

**Issue by John02139** [usnistgov/REFPROP-issues#323]
### Description

I'm preparing a reference list in which I'll cite REFPROP-10's EOS for ammonia.  Is this reference is still current?

K. Gao, J. Wu, I. H. Bell, and E. W. Lemmon. Thermodynamic properties of
ammonia for temperatures from the melting line to 725 K and pressures
to 1000 MPa, to be submitted to J. Phys. Chem. Ref. Data, 2018.

### Versions

**REFPROP Version:  10 **

**Comment by ianhbell** [comment]
Yeah, afraid so.  The manuscript is still under development.
