### ISSUE TITLE
GETKTVdll and SETKTVdll in mixtures

### ISSUE THREAD

**Issue by mina-shahrooz** [usnistgov/REFPROP-issues#327]
Hello,
I have a question regarding mixtures in REFPROP. If the correct interaction parameters exist in HMX.BNC, can I just call REFPROPdll like:
          RP.REFPROPdll(fluids,"TQ","P",iUnits, iMass, iFlag,T1,Q1,z); 
or do I need to use GETKTVdll and SETKTVdll before?

Thanks.

**Comment by EricLemmon** [comment]
There's no need to do anything to use the default parameters, it will set up everything for you.  The only thing to consider is calling the SATSPLN routine.  The information in the issue below talks some about it.  Although it is written for application in Excel, it would work the same in all other wrappers.

https://github.com/usnistgov/REFPROP-wrappers/issues/106

You can search for "SATSPLN" in both the REFPROP-issues and REFPROP-wrappers github sites and read more about this.

**Comment by mina-shahrooz** [comment]
Thank you very much.

So when should GETKTVdll and SETKTVdll be used? I have seen some codes from Ian Bell that he uses GETKTVdll and then SETKTVdll. So the first one retrieves interaction parameters from HMX.BNC and the second one sets these parameters. That is why I was confused why both routines should be called if the the interaction parameters are available in HMX.BNC.

**Comment by ianhbell** [comment]
GETKTVdll and SETKTVdll are needed if you have interaction parameters other than the default values that you would like to use.  For instance from my paper: https://doi.org/10.1021/acs.jced.6b00257 .  But for most cases, you can use the default ones and don't need to set custom interaction parameters.
