### ISSUE TITLE
REFPROP10 PHFLSH having a lot more errors than REFPROP9.1

### ISSUE THREAD

**Issue by ajain-gtisoft** [usnistgov/REFPROP-issues#328]
In our organisation, we incorporate REFPOP10.0 into our code for accessing refrigerant properties for use in system simulations.
 
To facilitate the speed of simulations we preprocess refrigerants to generate property maps which are used in subsequent simulations. For this we do PHFLSH (Pressure and Enthalpy lookup) to obtain all other properties.
 
When trying to use REFPROP10.0 PHFLSH to calculate properties for the same refrigerant the number of P and H combinations for which PHFLSH fails are a very high compared to the same refrigerant in REFPROP9.1, e.g. (10 errors over the whole map vs 2000 errors in 10.0) for refrigerant R123. 

Were there some fundamental changes made in the property calculations that we are not aware of that might mitigate these errors?

I have a full list of refrigerants where the errors are increased in REFPROP10 vs REFPROP9.1, but for this post I have attached the list of Pressures(kPa) and Enthalpies (kJ/mol) for R123. 

[err_input.txt](https://github.com/usnistgov/REFPROP-issues/files/5163685/err_input.txt)

I have also attached the python code for doing the PHFLSH calculations 

[refrig_error_checks_10.txt](https://github.com/usnistgov/REFPROP-issues/files/5163687/refrig_error_checks_10.txt)

**Comment by ajain-gtisoft** [comment]
The same errors were also found when using a standalone FORTRAN code.

**Comment by ianhbell** [comment]
Do the errors occur tend to occur in a particular location in P-H space?  

You can also use the consistency plots of CoolProp with REFPROP backend (with a tiny bit of modification) to get a graphical sense for where problems are hiding: http://www.coolprop.org/fluid_properties/fluids/R125.html#consistency-plots

**Comment by EricLemmon** [comment]
Would you like to try the beta version?  We would love to have some feedback on whether the updates helped, and if additional updates are necessary.  Please send me a private email at eric.lemmon@nist.gov

**Comment by ajain-gtisoft** [comment]
Hi Ian and Eric

Here are some maps that might help with the issue. These are temperature contours on a PH map with the liquid, 2-phase, vapor and supercritical regions of R123 with the error zone zoomed in (occurring between 0-200 bar and 104-120 kJ/kg) (Image 1). 

![image](https://user-images.githubusercontent.com/70655839/92036646-2e5bb380-ed36-11ea-80a5-aad642d478c3.png)

Then I have plotted the same region for R123 with REFPROP9.1 which does not show any errors (Image 2). 

![image](https://user-images.githubusercontent.com/70655839/92036685-3c113900-ed36-11ea-861f-041c80d3d9e5.png)

The third image is just the region with the error points for R123 with REFPROP10. (Image 3)

![image](https://user-images.githubusercontent.com/70655839/92036748-521ef980-ed36-11ea-85ab-53fb2a2868fd.png)

P.S.: The errors for other refrigerants aren't confined to this region e.g. (R404A:  RefProp10.0 - Liquid - 160 errors, 2-phase - 2k errors, REFPROP9.1 - 20 errors.  in the 2-phase region)

**Comment by ianhbell** [comment]
Can you please overlay the phase equilibria curves on all the figures? Otherwise it is hard to know where we are in the phase diagram.

**Comment by ianhbell** [comment]
Also, aren't you WAY into the solid phase at these enthalpies?

**Comment by ajain-gtisoft** [comment]
Hi Ian, except for the Image 1 (right side image) all other zones are solely liquid and supercritical (on the left side of the two phase region)

No the maps ensure that they start generating properties based on pressure and enthalpy only if the temperature is above the triple point temperature. Also the bounds of the maps are defined by the melting point lines on the liquid and supercritical side so I think we avoid the solid phase.

**Comment by ianhbell** [comment]
This is one reason why overlaid phase equilibria are so useful... What melting curve do you use? REFPROP doesn't have a melting curve for R123.  Can you please also show the enthalpy associated with the liquid at the triple point?

A log of inputs and error messages would also be helpful.

**Comment by ajain-gtisoft** [comment]
Hi Ian. As further proof that the point is not in the solid phase here is an output from Refprop 9.1

![image](https://user-images.githubusercontent.com/70655839/92044180-4685ff80-ed43-11ea-8c71-441a721b9ba3.png)
 
And here is the same point with Refprop 10.0

![image](https://user-images.githubusercontent.com/70655839/92044370-bbf1d000-ed43-11ea-941f-f724ab5eeb86.png)

**Comment by ianhbell** [comment]
You're really close to the maximum density of the EOS: 1774.0 kg/m³.  Likely the iterative routine just jumps out of range during the iterative routine, causing this error.  Please email Eric (email above) to get the beta which might help with this error.

**Comment by ajain-gtisoft** [comment]
Thanks Ian. Yes the majority of the errors occur for the reason you say: See attached file
[R123_Refprop10_error_snippet.docx](https://github.com/usnistgov/REFPROP-issues/files/5165199/R123_Refprop10_error_snippet.docx)


However, problems occur in other regions for R404A (In the 2-phase). We have a compilation of the number of errors for all refrigerants for the same map regions in Refprop 9.1 vs Refprop 10.0 but I guess testing with the beta version is the way to go. I have sent an email to Eric.

Thanks for the help

**Comment by ianhbell** [comment]
For R404A, if you use pseudo-pure EOS, two-phase inputs are not allowed at all; see https://github.com/usnistgov/REFPROP-issues/issues/324. Only if you use predefined mixture for R404A can you do two-phase inputs, but then you have a different set of problems.

**Comment by ajain-gtisoft** [comment]
We do use predefined mixture for R404A.

**Comment by ianhbell** [comment]
Right, then please make sure to read the issue I linked just above in its entirety.

**Comment by EricLemmon** [comment]
Could you send me your email address again if you have already done so (or if you have not sent it either!)?

eric.lemmon@nist.gov

**Comment by ajain-gtisoft** [comment]
Hi Eric

I have sent you an email from my official account.
