### ISSUE TITLE
Install v10 from v9.1

### ISSUE THREAD

**Issue by grgrynlds** [usnistgov/REFPROP-issues#33]
I have upgraded to REFPROP v10, but when I install it using the NIST2310.EXE install utility, I end up with version 9.1 (what I was running before).  This is evident in the REFPROP.XLS file which is dated 4/6/2013. 
 
![image](https://user-images.githubusercontent.com/41301795/42772794-232c82a6-88f1-11e8-9f0f-ee38b5cb6270.png)

I'm using W7 and Office 2010, and I uninstalled the version 9.1.
Any idea what in the world I'm doing wrong here?

Thanks,

Greg

**Comment by ianhbell** [comment]
Thanks for the report!  I'll post back here once I have the recommended solution

**Comment by ianhbell** [comment]
REFPROP 9.1 doesn't seem to get properly overwritten by our version 10 installer "thanks" to some vagaries of windows that we haven't been able to track down.  The most reliable solution seems to be

1. Re-install REFPROP 9.1
2. Uninstall REFPROP 9.1
3. Install REFPROP 10.0

If you need the installer for version 9.1 for the reinstall, please email me at ian.bell@nist.gov and I can send you the link.

**Comment by grgrynlds** [comment]
OK, v10 is now installed and seems to be working.  This is what I did...

- 9.1 was working from when I previously tried to install v10

- I uninstalled 9.1 by running the inins.exe in the REFPROP folder

- when trying to reinstall 9.1, I ran _nist2391.exe_ which I still had in my download folder.  This gave me an uninstall option, so I did that first.  It gave me this option:
![image](https://user-images.githubusercontent.com/41301795/42780706-929e4436-8909-11e8-8697-b7470cdb8ba5.png)
which I had not previously done. So I had the uninstaller remove this file, and completed the uninstall (which obviously never been fully completed).

- Since it was evident that the uninstall was now actually properly completed. I went ahead and tried to install v10.  This was successful.  

So it appears that the problem was due to incomplete uninstall of 9.1.

**Comment by ianhbell** [comment]
Yet another interesting datapoint regarding installation of 10.  Thank you for your excellent feedback!

**Comment by grgrynlds** [comment]
Thanks much for all your help Ian!  
I have some of my Excel tools working now with the new v10 command format.  I was able to use the translator utility to clean that up (once I removed the 'REFPROP.XLA!Enthalpy(...)' prefix from my cells).  Now off to make sure my LabVIEW utilities are still working... THEN I want to play with developing a design tool in Python! Looking forward to that.
Greg

**Comment by ianhbell** [comment]
When you get around to the Python wrapper, let me know!  Closing for now as this seems fixed(ish).
