### ISSUE TITLE
GUI heat capacities wrong for "unitless" units

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#330]
In REFPROP 10, it looks like values of heat capacities (Cp, Cv, Cp0) are off by a factor of 1000 if "unitless" units are chosen in the GUI.  These unitless quantities are in units of "R".
For example, choose argon as the fluid, with "unitless" units, and Cp, Cv, and Cp0 as properties.
Cp0 for argon should be exactly 2.5*R, while Cp should be in that ballpark and Cv should be about 1.5.
Instead, for a reduced T of 1, a reduced P of 0.1, it gives Cp0=0.0025, Cv=0.0015402, Cp=0.0026816.
So these appear to be off by a factor of 1000.
If I choose other unit systems like molar SI, these quantities appear to be OK.

**Comment by ianhbell** [comment]
Thanks for the report @nist-aharvey

**Comment by EricLemmon** [comment]
This is fixed now.  It was only a problem for unitless values of "/R" (Cp, Cv, entropy) but not for "/RTc" (enthalpy).

One thing I have always wondered is whether enthalpy should be reduced by Tc or just T.  The underlying equations of state use "/RT", which makes the reducing parameter a function of T.  Thus, when I built the graphical interface, I changed the reducing value to "/RTc", which then means a fixed value.  The reducing value for entropy is always a constant (just R), so having a temperature dependent reducing value for enthalpy does not make sense.  I assume still that this would be correct, perhaps you have some additional comments?

**Comment by nist-aharvey** [comment]
I agree that if you are giving dimensionless properties, then Tc is the right reducing parameter, just like things with density get reduced with rho_c and things with pressure get reduced with pc.
In principle I think you also can combine these to develop unitless versions of the sound speed, viscosity, etc., but it probably isn't worth the trouble (and you might end up with messy things like cube root of the critical density).

**Comment by ianhbell** [comment]
For a "unitless" unit system, I think the appropriate might be the real temperature, rather than the critical one, since if you think about something like J=-a/T, which is the Massieu potential, and is what we actually use as our "reduced Helmholtz energy", it wouldn't make sense there to use the critical temperature.

I would instead call that unit system "reduced", since all properties are relative to the critical point (except for lots of other things like transport properties, speed of sound, etc.) which are still dimensional.

**Comment by nist-aharvey** [comment]
I agree that "reduced" is probably a better word for all this.  "Unitless" leaves room for ambiguity since, especially for some properties, there would be different ways to make them unitless.
But using the real temperature, pressure, or density as reducing variables would mean, for example, that the (unitless) temperature at every point is "1", which isn't very useful. 
Of course some dimensionless quantities reduced by T are useful, like a/RT.  Or the use of V instead of Vc in defining the isothermal compressibility (though that isn't quite dimensionless).  But I don't think you can base the full system of displayed properties on it.

**Comment by EricLemmon** [comment]
Good points!  I'm going to close this now, this discussion could go on forever and we can talk about it offline.
