### ISSUE TITLE
Isentropic calculation of Helium/Neon mixture

### ISSUE THREAD

**Issue by torunagasaka** [usnistgov/REFPROP-issues#331]
### Description

[Description of the issue]
Isentropic  calculation can not be done for Helium(0.8;mole fraction)/Neon(0.2) mixture. 
T1=300K, P1=0.4MPa, S1=14.5442 kJ/(kgK)
P2=0.5MPa,S2=14.5442 kJ/(kgK)

### Steps to Reproduce

1. [First Step]Substance/Define New Mixture Helium(0.8)/Neon(0.2)
2. [Second Step]Helium/Neon Specified state points(0.8/0.2)
3. [and so on...]T1=300K, P1=0.4MPa, S1=14.5442 kJ/(kgK)
P2=0.5MPa,S2=14.5442 kJ/(kgK)

**Expected behavior:** [What you expect to happen]T2=328.0K,S2=14.5442 kJ/(kgK)

**Actual behavior:** [What actually happens]T2=319.833K,S2=14.4717kJ/(kgK)

### Versions

**REFPROP Version:** [REFPROP version you are using]  REFPROP10
**Operating System and Version:** [OS you are running REFPROP on]  Win10
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  REFPROP10 GUI

**Comment by ianhbell** [comment]
I don't think I understand. Do you mean to say that you specified an isentropic point, but you ended up with a different entropy?  Where did the expected results come from?

Are you using the default model, or the updated one from Tkaczuk: https://aip.scitation.org/doi/full/10.1063/1.5142275 ?

**Comment by ianhbell** [comment]
I did this in python and got the expected result: 
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
r1 = RP.REFPROPdll('Helium*Neon','TP','S',RP.MASS_BASE_SI,0,0,300,0.4e6,[0.8,0.2])
s1 = r1.Output[0]
r2 = RP.REFPROPdll('Helium*Neon','PS','T',RP.MASS_BASE_SI,0,0,0.5e6,s1,[0.8,0.2])
T2 = r2.Output[0]
print(T2)
```
yielding
```
328.002537862666
```

**Comment by nist-aharvey** [comment]
I can confirm that this is a problem (at least in the GUI), but there is a simpler way to look at it.
You enter one P-S Specified State Point, and the S value returned changes from what is input.
1) Specify mixture 80/20 helium/neon (mole fraction)
2) Specified state points, P=0.5 MPa, S=14.5442 kJ/(kg-K)
3) The point that comes back has the specified P, but S (supposedly fixed) comes back as 14.472 which is not what was specified.
[Nothing special about this point -- enter P=1 and S=14.5 and it comes back with S=13.608]

It gives a warning when you specify the mixture about the reference state calculation not converging -- could that have something to do with it?

**Comment by ianhbell** [comment]
So the issue seems to only occur in the GUI I think, which is likely an easier fix than to fix the underlying iterative routines.

**Comment by EricLemmon** [comment]
This bug appears to have already been fixed, could you send me a personal email and I'll send you a patch?  eric.lemmon@nist.gov

![image](https://user-images.githubusercontent.com/42392984/92772675-2795f780-f359-11ea-9cb7-2fc9fafafa82.png)

**Comment by torunagasaka** [comment]
Dear Dr. Lemmon
Thank you for your comment.
I sent you my personal e-mail yesterday.
I would appreciate it if you could send me a patch.
