### ISSUE TITLE
Fluid properties of moist flue gas-reg

### ISSUE THREAD

**Issue by ambrish16** [usnistgov/REFPROP-issues#332]
Help Required in estimating the accurate properties of moist flue gas:

We are working on a analysis of waste heat recovery turbine where thermodynamic properties of moist flue is required to estimate accurately.

 Flue gas consists a mixture of CO2, CO, N2, O2, H20 and the flue gas mixture is always saturated with water vapour.

 As the flow progresses across the turbine temperature of flue gas comes down and simultaneously water vapour also condenses. In this process the latent heat of vaporization is transferred to the rest of flue gas. The estimated temperature from the Refprop are quite lower than expectation.

You are requested to suggest how accurately we can estimate the fluid properties of flue gas while considering condensation taken into account.

 Fluid properties required for calculation are density, enthalpy, entropy, sp. heat capacity, viscosity, speed of sound and thermal conductivity.

 Further, it is requested to suggest, any program/software modules are available to estimate these properties accurately.

**Comment by ianhbell** [comment]
What does "accurately" mean for your application? 

You might want to check out my paper, it covers this sort of analysis for psychrometric calculations: https://www.sciencedirect.com/science/article/pii/S014070071730381X . Supporting information includes the code.

Can you please provide some numerical values for "the estimated temperature from the Refprop are quite lower than expectation"?  This  might not be all that surprising, as I made the point in my paper that the models in REFPROP don't do a great job for humid air mixtures. The mixture models need to be refit to be made more accurate, but this is far from a small task.

**Comment by EricLemmon** [comment]
Here's a link to another document that has a lot of information:

https://trc.nist.gov/refprop/Documents/Humid_Gases_and_CCS_Mixtures_Gernert.pdf

**Comment by ambrish16** [comment]
Dear  Sh. Eric,

Link is not working. you are requested to send through attachment.

Ambrish

**Comment by EricLemmon** [comment]
You are right, the file was not even there!  I've uploaded it, please try again.
