### ISSUE TITLE
Methane-Carbon Dioxide mixtures

### ISSUE THREAD

**Issue by BFE614** [usnistgov/REFPROP-issues#333]
### Description
MIxtures of Methane and Carbon Dioxide near 0.5, 0.5 mol% give strange results for critical point, statepoint calculations, as well as PT diagrams.

### Steps to Reproduce
1. set fluid to 50/50 mol% mixture of methane and carbon dioxide in REFPROP10 gui
2. check critical point in fluid information. (it is different than version 9.1)
3. calculate state point for 70 degrees F and 1700 psia
4. plot PT diagram with defaults
5. repeat above steps with 47/53 mol% mixture

**Expected behavior:** 
1. for 50/50 mol% and 47/53 mo % mixtures
2. step 3 above should be in supercritical range
3. PT curves should be smooth
4. critical point should be on saturation curves

**Actual behavior:**
1. for 50/50 mol% mixture
2. there is a "dip" in liquid saturation curve
3. critical point is not connected to saturation curves
![image](https://user-images.githubusercontent.com/63927731/93356013-4d614780-f804-11ea-8ed9-784c9cda8853.png)
4. the statepoint for 70 degrees F and 1700 psia does not converge in state point table

5. for 47/53 mol% mixture
6. all results look normal (as expected)

### Versions
REFPROP veresion 10 gui  (but similar issues are seen in EXCEL 2016 version)
Satspln is turned on
Windows 10

### Additional Information
All these calculations worked properly in REFPROP version 9.1 in EXCEL

**Comment by EricLemmon** [comment]
Can you send me a personal email (eric.lemmon@nist.gov).  I believe this has been fixed and I'll send you a patch.
