### ISSUE TITLE
Truncation of coefficients for argon

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#336]
The coefficients for argon were truncated at 12 digits, while the publication (https://aip.scitation.org/doi/pdf/10.1063/1.556037) gives 14 digits.  It's a small difference, but will change the results. The values in CoolProp 6.4.1 are not truncated, so we can pull the coefficients from there.

**Comment by EricLemmon** [comment]
The argon.fld file has been updated to match the publication and will be uploaded soon.
