### ISSUE TITLE
PQFLSH Mixture Convergence

### ISSUE THREAD

**Issue by paarfi** [usnistgov/REFPROP-issues#34]
I ran a series of PQFLSH calcs on R438A at 100 psia (689.48 kPa) running Qmolar from 0 to 1 at increments of 0.001, and it seems like there are some convergence issues. This is a plot of T (in C) vs Qmolar. There are gaps where the iteration failed, and there are also a number of points that did return but don't look right.

![r438a](https://user-images.githubusercontent.com/7852089/42817039-d7c696ee-899a-11e8-84f1-be67e85fcc76.jpg)

That was all using RefProp 10 (the 04Jun18 version, which I think is current). When I do this same set of calculations with 9.1, I don't see these convergence issues.

This was just the first case I ran, so this issue may be more general. Is there anything that can be done to improve this?
edit to add: I also tried calling SATSPLN first, but it didn't seem to make any difference for this.

**Comment by ianhbell** [comment]
Indeed, calling SATSPLN first should help a lot for cases like this.  Did you get any error from SATSPLN?

Can you post your code?

**Comment by paarfi** [comment]
No error from SATSPLN. C# code below.

`        [DllImport("Refprop.dll", EntryPoint = "SETPATHdll")]
        public static extern void SetPath(
            //inputs
            StringBuilder path,
            int lenPath
            );

        [DllImport("Refprop.dll", EntryPoint = "SETMIXdll")]
        public static extern void SetMix(
            //inputs
            StringBuilder mixture, 
            StringBuilder mixtureCoeffs, 
            StringBuilder referenceState,
                                          //outputs
            ref int numComponents,
            StringBuilder components,
            [MarshalAs(UnmanagedType.LPArray, SizeConst = 20)]
                        double[] moleFraction,
            ref int errorCode,
            StringBuilder errorMessage,
            int lenMixture,
            int lenMixtureCoeffs,
            int lenReferenceState,
            int lenComponents,
            int lenErrorMessage
            );

        [DllImport("Refprop.dll", EntryPoint = "SATSPLNdll")]
        public static extern void SatSpln(
            //inputs
            [MarshalAs(UnmanagedType.LPArray, SizeConst = 20)]
                        double[] moleFraction,
            //outputs
            ref int errorCode,
            StringBuilder errorMessage,
            int lenErrorMessage
            );

        [DllImport("Refprop.dll", EntryPoint = "PQFLSHdll")]
        public static extern void PQFlsh(
            //inputs
            ref double p,
            ref double q,
            [MarshalAs(UnmanagedType.LPArray, SizeConst = 20)]
                        double[] moleFraction,
            ref int qualityBasis,
            //outputs
            ref double t,
            ref double rho,
            ref double rhoL,
            ref double rhoV,
            [MarshalAs(UnmanagedType.LPArray, SizeConst = 20)]
                        double[] moleFractionL,
            [MarshalAs(UnmanagedType.LPArray, SizeConst = 20)]
                        double[] moleFractionV,
            ref double u,
            ref double h,
            ref double s,
            ref double cv,
            ref double cp,
            ref double acousticVelocity,
            ref int errorCode,
            StringBuilder errorMessage,
            int lenErrorMessage
            );


        public static void TestRefPropSaturatedProblems()
        {
            int lenPath = 255;
            StringBuilder filePath = new StringBuilder(System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), lenPath);
            SetPath(filePath, lenPath);

            string mixtureFile = "mixtures\\R438A.mix";
            int numComponents = int.MinValue;
            double[] molFraction = new double[20];
            string mixtureCoeffsFile = "fluids\\hmx.bnc";
            int lenMixture = 255;
            int lenMixtureCoeffs = 255;
            int lenReferenceState = 3;
            int lenComponents = 10000;
            int lenErrorMessage = 255;
            StringBuilder mixture = new StringBuilder(mixtureFile, lenMixture);
            StringBuilder mixtureCoeffs = new StringBuilder(mixtureCoeffsFile, lenMixtureCoeffs);
            StringBuilder referenceState = new StringBuilder("DEF");
            StringBuilder components = new StringBuilder(new string('\0', lenComponents));
            int errorCode = int.MinValue;
            StringBuilder errorMessage = new StringBuilder(new string('\0', lenErrorMessage));
            SetMix(mixture, mixtureCoeffs, referenceState, ref numComponents, components, molFraction, ref errorCode, errorMessage, lenMixture, lenMixtureCoeffs, lenReferenceState, lenComponents, lenErrorMessage);
            if (errorCode > 0)
            {
                throw (new Exception("Nist Refprop SETMIX Error: " + errorMessage.ToString().Trim()));
            }

            lenMixture = 255;
            errorCode = int.MinValue;
            errorMessage = new StringBuilder(new string('\0', lenErrorMessage));
            SatSpln(molFraction, ref errorCode, errorMessage, lenErrorMessage);
            if (errorCode > 0)
            {
                throw (new Exception("Nist Refprop SATSPLN Error: " + errorMessage.ToString().Trim()));
            }

            using (FileStream fs = new FileStream(@"C:\Users\User\Documents\Temp\satline.csv", FileMode.Create, FileAccess.Write))
            using (StreamWriter rs = new StreamWriter(fs))
            {
                for (int i = 0; i <= 1000; i++)
                {
                    double p1 = 689.475478950958; // 100psia
                    double q1 = (double)i / 1000;
                    int qualityBasis = 1; // molar
                    double t1 = double.MinValue;
                    double rho1 = double.MinValue;
                    double rhoL = double.MinValue;
                    double rhoV = double.MinValue;
                    double[] moleFractionL = new double[20];
                    double[] moleFractionV = new double[20];
                    double u1 = double.MinValue;
                    double h1 = double.MinValue;
                    double s1 = double.MinValue;
                    double cv1 = double.MinValue;
                    double cp1 = double.MinValue;
                    double acousticVelocity1 = double.MinValue;
                    lenMixture = 255;
                    errorCode = int.MinValue;
                    errorMessage = new StringBuilder(new string('\0', lenErrorMessage));
                    try
                    {
                        PQFlsh(ref p1, ref q1, molFraction, ref qualityBasis, ref t1, ref rho1, ref rhoL, ref rhoV, moleFractionL, moleFractionV, ref u1, ref h1, ref s1, ref cv1, ref cp1, ref acousticVelocity1, ref errorCode, errorMessage, lenErrorMessage);
                        if (errorCode > 0)
                        {
                            throw (new Exception("Nist Refprop PQFLSH Error: " + errorMessage.ToString().Trim()));
                        }
                        rs.WriteLine(q1 + "," + t1);
                    }
                    catch
                    {
                    }
                }
            }
            Console.WriteLine("Done");
            Console.ReadKey();
        }
`

**Comment by paarfi** [comment]
I ran this same code on every "A" blend from R438A to R460A, and the only ones that showed the "bad" result points were R438A and R453A, though R453A showed fewer of those. Not surprising given the similar constituents in those two blends. I must have got lucky trying R438A first, and the problem is less common than that made it appear. Thanks for looking into this, and I hope you can fix.

**Comment by EricLemmon** [comment]
Can you contact me directly to get an updated version of the code, this may be fixed now.  (eric.lemmon@nist.gov)

**Comment by paarfi** [comment]
I tried both 10.0.0.2 patch and 10.0.0.57 beta, and both showed the same issues with R438A. So whatever you changed did not seem to fix this issue.
