### ISSUE TITLE
Fix gas constant for SO2

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#342]
Although the paper of the EOS of Gao (https://pubs.acs.org/doi/10.1021/acs.jced.6b00195) uses 8.3144621 J/mol/K as the gas constant, the REFPROP 10.0 fluid file uses 8.3144598 J/mol/K. Snip from the paper:

![image](https://user-images.githubusercontent.com/11966765/96040111-c40b5800-0e37-11eb-9296-72fe3393bccf.png)

REFPROP 10.0 fluid file has:

![image](https://user-images.githubusercontent.com/11966765/96040229-f1580600-0e37-11eb-9bba-8ba087aff03a.png)

**Comment by EricLemmon** [comment]
The value has been changed to 8.3144621 in both the FEQ and CPP sections, and the two constants in the PX0 section where updated to match this value of R.  The fluid file will be uploaded next time I log in.

**Comment by ianhbell** [comment]
Thanks
