### ISSUE TITLE
Suspicious variable in the subroutine 'SATT' of REFPROP 10

### ISSUE THREAD

**Issue by BRIAN-YJ-YOON** [usnistgov/REFPROP-issues#344]
Hello.
I'm reviewing REFPROP 10 Fortran files. 

At ‘SAT_SUB.FOR’ file >> subroutine SATT >> Line#177, I can find the code:
`call PRESS (T,Dv,z,pp)`
The code changes ‘**_pp_**’, but after ‘**_pp_**’ is changed this variable is not used until the end of the subroutine.
According to ‘_the flow of the logic_’, I assume that ‘**_P_**’ is better than ‘**_pp_**’. 
Can I ask your opinion about it? 

Brian Yoon

**Comment by ianhbell** [comment]
I don't think there is a problem here, because I believe this line is just an orphan line that calculates the variable pp for debugging purposes.  I think the line could be deleted without any other ill effects.  @EricLemmon can you please confirm?

**Comment by EricLemmon** [comment]
That was my thought as well last night.  The only other possibility I could think of would be in the situation where the density is extremely small and this call may have ensured that all cached variables were set correctly, which would apply for perhaps just a very few fluids such as R124.  But this is most likely not correct - the orphan idea seems more plausible.

**Comment by BRIAN-YJ-YOON** [comment]
Thanks for the comments!
