### ISSUE TITLE
Docosane source

### ISSUE THREAD

**Issue by John02139** [usnistgov/REFPROP-issues#345]
### Description

The equations for docosane are from this as-yet-unpublished source:

Romeo, R., & Lemmon, E. W. (2017). [Helmholtz equation of state for docosane, personal communication to E.W. Lemmon, NIST, Boulder].

I am seeking a correlation for the saturated vapor density of docosane, which I thought might have been developed in the above source.  Is such a correlation available?

### Versions

**REFPROP Version: 10

**Comment by EricLemmon** [comment]
Every fluid file has ancillary equations in them, at the bottom before the END statement.  For C12 and saturated vapor, here's what it shows:

```
#DV    !---Saturated vapor density---
DV3    !Saturated vapor density equation for dodecane of Lemmon (2010).
?
?```````````````````````````````````````````````````````````````````````````````
?Lemmon, C.K. and Lemmon, E.W., 2010.
?
?Functional Form:  D=Dc*EXP[SUM(Ni*Theta^ti)] where Theta=1-T/Tc, Tc and Dc are
? the reducing parameters below, which are followed by rows containing Ni and ti.
?
!```````````````````````````````````````````````````````````````````````````````
0.                 !
10000.             !
0.                 !
0.                 !
658.1   1.33       !Reducing parameters
6 0 0 0 0 0        !Number of terms in equation
-1.7859    0.298
-7.5436    0.91
-22.848    2.8
-81.355    6.0
 92.283    9.0
-217.25    11.0
```

**Comment by John02139** [comment]
Super!  That answers my question.  I'll look up the corresponding one for docosane.

Thanks for the quick response.
