### ISSUE TITLE
Getting ierr = -852 warning

### ISSUE THREAD

**Issue by jadepgit** [usnistgov/REFPROP-issues#346]
### Description
Don't know if I've run into a problem (probably on my part) or a feature.  I'm new to REFPROP and I'm experimenting with a simple Propane/Butane mix.  I called REFPROPdll() and got expected results.  I checked ierr and found -852.  Details below.  

### Steps to Reproduce

1. Called REFPROPdll where hIn = {"TP"}  hOut = {XMOLEVAP}  Other variables should not be a factor.

**Expected behavior:** 
Same results I got, except ierr = 0.

**Actual behavior:** 
1. printed output[] and it matched y[] as expected.  I was asking for XMOLEVAP.
2. Printed hUnits and got "XMOLE".
3. Printed ierr and got -852.
4. Printed herr and got [ALLPROPS warning -852] Additional properties are included in the output array.  the input string
and output array do not line up.
5. Printed 8 elements of output.  First 2 used to store XMOLEVAP (propane/butane) and the other 6 were -9999990 as expected.  However there were no additional properties.
6. x[], y[], and q were fine.

Comment:  Is this just a friendly reminder that I'm asking for more properties than the standard q, x, y, etc...?  If so, could you recommend an error trap such as if( (ierr <0) && (ierr > -xxx) ) that would ignore such warnings? 

### Versions

**REFPROP Version:** 10
**Operating System and Version:** [Artix Linux]  
**Access Method:**  C.  Calling using the header file and librefprop  

### Additional Information
Seems straight forward.  I'm getting the expected results, the only problem is the -852 warning.  If this is just a reminder that I'm generating additional properties, I'd appreciate some guidelines for error trapping.  I'm picky and hate seeing warnings.  I also tried an experiment with hOut = {"XMOLEVAP XMOLELIQ"}.  REFPROP returned the expected results in the first 4 elements of output but gave me the same warning -852.

**Comment by jadepgit** [comment]
Digging through the FORTRAN code I found the warning generation in refprop.for in ALLPROPS:
`if (iAllWarn.ne.0) goto 852      !If inputs that require multiple outputs were sent, send back a warning about this.`

and this: 
`852  call ERRNUM (-852,0,' ',' ',0d0,0d0,0d0,ierr1,herr1)           !Warning about more outputs than inputs`

So I'm assuming this is expected behaviour.  If so, I'll close the issue.

**Comment by EricLemmon** [comment]
This behavior is correct.  To get rid of the error messages, you can request the compositions like this:

hOut = {"XMOLEVAP(1) XMOLEVAP(2) XMOLEVAP(3) XMOLELIQ(1) XMOLELIQ(2) XMOLELIQ(3) "}

The way you did it is just a convenient method to return all mole fractions at once.  There are quite a number of these, they should all be documented in the help file or in the Fortran headers.

**Comment by jadepgit** [comment]
Thanks.  I like the fix, I can see how it works.  Closing this issue.
