### ISSUE TITLE
Pure fluids in Refprop

### ISSUE THREAD

**Issue by mary977** [usnistgov/REFPROP-issues#348]

**Comment by mary977** [comment]
I have Refprop version 9.1, but it doesn't have R1234ze?
What is the problem?

**Comment by ianhbell** [comment]
Do you mean R1234ze(E) or R-1234ze(Z)?

**Comment by mary977** [comment]
> Do you mean R1234ze(E) or R-1234ze(Z)?

R1234ze(E)

**Comment by ianhbell** [comment]
For R1234ze(E), please see https://pages.nist.gov/REFPROP-docs/#hfo-1234yf-1234zee-1234zez-1233zde-and-refrigerant-mixtures

**Comment by mary977** [comment]
> For R1234ze(E), please see https://pages.nist.gov/REFPROP-docs/#hfo-1234yf-1234zee-1234zez-1233zde-and-refrigerant
Can you help me to use this website?

**Comment by ianhbell** [comment]
Please read the text at the linked URL first
