### ISSUE TITLE
Automatically create a matrix of temperature and pressure data

### ISSUE THREAD

**Issue by chuckinlcf** [usnistgov/REFPROP-issues#349]
**Expected behavior:** Capability to automatically create a data file that includes both pressure and temperature changes as opposed to manually having to change one of the parameters

**Actual behavior:** I'm unable to figure out how to perform automatic data sets

**REFPROP Version:**   V10
**Operating System and Version:** Parallels for Mac.  Mac is 10.14.6, Parallels uses Windows 10

**Comment by ianhbell** [comment]
Are you using the GUI?  Are you aware that you can right-click on the column heading to fill in values in specified ranges?

**Comment by EricLemmon** [comment]
You can also simply copy two columns from Excel or some other data entry program and then just paste them into the tables in the Refprop GUI.  If you wish to change the order of the properties in the table, go to Options/Property Order.  For example, if your Excel grid contains pressure first and then temperature, you can change the Refprop column order, make a new table, and then just paste them in.  Likewise if your inputs are P and H, you can put those two together at the beginning of the table.

**Comment by chuckinlcf** [comment]
Hi thanks for responding.  Yes I know there is a GUI for manually changing one of the parameters, and that I can manually copy and paste multiple results where i have manually changed a parameter.  But i have about 1000 runs do do if I change a single parameter manually.  What I was asking for is, is there a way to automate the process so that I dont have to manually perform 1000 different runs where i am manually changing a single parameter.  For example, if I need to create a matrix of 100 different temperatures and 100 different pressures, how can that be done in an automated process instead of performing 100 runs, all done manually?  Results can then be pasted into Excel and sorted as needed.  Please let me know, thanks.

**Comment by ianhbell** [comment]
Do you have any programming background?  If so, this is a question calling out for a small routine in the programming language of your choice.  Can you provide a concrete example and I can show you how you might do that in code?

**Comment by chuckinlcf** [comment]
Thanks.  I dont have programming background but I do use Igor, which has programming subroutines. However, to use Igor, I would need a complete equation of state that provides all the information needed for me to do a matrix calculation of density (I bought REFPROP because somewhere in the bowels of the program is all that Eq. of State info to calculate density, which would be hard for me as a non-Fortran person to find).   A simple example would be to get xenon density with 4 different temperatures and 3 different pressures. That is 12 results, done manually 3 times, and I'm looking for a solution where it is done on one try.
Temp,oC  Pressure, psia  Density calculated by REFPROP
20.0         100                   xxx
20.0         105                   xxx
20.0         110                   xxx
21.0         100                   xxx
21.0         105                   xxx
21.0         110                   xxx
22.0         100                   xxx
22.0         105                   xxx
22.0         110                   xxx
23.0         100                   xxx
23.0         105                   xxx
23.0         110                   xxx

**Comment by chuckinlcf** [comment]
I can see the page formating is confusing.  i meant for example 20.0 deg C, 100 psia, and REFPROP calculates density xxx in TBD units

**Comment by ianhbell** [comment]
Here is a small example in Python, output density in mol/m^3:

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

for T_C in [20, 21, 22]: # Or this could be an array via numpy.linspace
    T_K = T_C+273.15
    for p_bar in [7, 8, 9]: # Or this could be an array via numpy.linspace
        p_Pa = p_bar*1e5
        r = RP.REFPROPdll('Argon','TP','D',RP.MOLAR_BASE_SI,0,0,T_K,p_Pa,[1.0])
        if r.ierr == 0:
            print(T_C,p_bar,r.Output[0])
        else:
            print(r.herr)
```
yielding
```
20 7 288.5470303874732
20 8 329.98683300731904
20 9 371.4805907296918
21 7 287.5439947864215
21 8 328.8361284721344
21 9 370.1811177637723
22 7 286.5480500260277
22 8 327.6936069793317
22 9 368.89094031097903
```
```

**Comment by EricLemmon** [comment]
I spoke directly with this person and discussed the use of Excel for his situation.  All appears to be working now.
