### ISSUE TITLE
Densities under the steam curve

### ISSUE THREAD

**Issue by KaiThorben** [usnistgov/REFPROP-issues#350]
### Steps to Reproduce

1. Choose R449A at "predefined mixtures" 
2. Calculate specified state points 
3. Type in temperature = -25,7°C or 248K 
5. Go to specified state points and type in Temperature = -25,7°C and Enthalpy 251,8 (use options to display quality), Quality is 0,37823, save the density (25,247 kg/m3)
6. Go to Calculate and "saturation tables" 
7. vary pressure from 2,25 to 2,27 bar with 0,01 increments (2,26 bar has a density of the liquid of 1292,2 kg/m3 and the vapor one of 10,173 kg/m3. 
8. take the quality from step 5. (You have 37,823% gas and 62,277% liq)
9. Calculate the density at 37,823% gas with the densities from 7. => 804,9 kg/m3
10. The density from the state point from step 5 => 25,247 kg/m3) 

Questions

A) Why do the densities from 10 and 5 differ? 
B) We have made some curves and the density shows a logarithmic behavior if you make a chart over the quality (x-axis). Why?

**Expected behavior:** I would have expected other densities. I tried it for carbon dioxide as well that behaves not like this manufactured mixture R449A but it shows the same behavior. 

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP 10]  
**Operating System and Version:** [Windows 10]  
**Access Method:** directly  

### Additional Information

![image](https://user-images.githubusercontent.com/74057098/98372329-dabf5c00-203d-11eb-855d-9639c65be548.png)

**Comment by ianhbell** [comment]
A couple of points:
1) Your first calculation is for a mixture, hence the equilibrium liquid and vapor phases do not have the same composition
2) You should use the exact same pressure and vapor quality in second calculation

At the moment you are not checking consistent statepoints.

How did you calculate the bulk density given the equilibrium densities?  You did a quality weighted calculation of the mixture specific volume, right?

**Comment by KaiThorben** [comment]
Hi Ian, 

1. yes! the mixture's components evaporate at different temperatures. Here the ratio is: 32% liquid, 68% gas. 
2. Is this possible? The second is a saturated values calculation to find out about the liquid density and the gas density at the boundaries. 


I did this: 

Density_liq*quality + density_gas*(1-quality) => bulk density 

I am quite certain that this is not true. The intent of my question is to find out which equation is taken to calulating the density. In your Refprop.xls you write that some details in the welcome section of the sheet in "equations of state". Is the density derived from a long term research project? 

I will call you next week on this, okay?

**Comment by ianhbell** [comment]
To calculate the bulk densities given the equilibrium densities, you want:

rho_bulk  = 1/(x/rho_g + (1-x)/rho_l)

or in other words

v_bulk  = x*v_g + (1-x)*v_l


1) That's not quite right - once you talk about the mixture, you no longer have individual components, everything is linked.
2) Yes, put in the pressure and vapor quality in rows in the GUI.  That should give you back the same density.

I prefer to handle support via issues on github so that there is a record, and that others may learn from our correspondence.

**Comment by KaiThorben** [comment]
Ian, 

thank you for your answer. The problem we are facing is the following:

If we select "Calculate" => "Saturation Tables" there is no possibility to display a mean viscosity for an evaporation. 

If we take the mean of the viscosity on the gas and liquid saturation line, again, we are doing something wrong. But we will need visosity for an evaporation to properly calculate alpha (heat transfer between evaporating fluid and tube). 

How can we display a viscosity as described in the attachement? 

Thank you in advance 

Kai 
![image](https://user-images.githubusercontent.com/74057098/98800102-390a8700-2410-11eb-9070-0422c0b25371.png)
![REFPROP (Carbon dioxide) - NIST Reference Fluid Properties (DLL version 10](https://user-images.githubusercontent.com/74057098/98800168-52133800-2410-11eb-97f9-fb74c7f18411.jpg)

**Comment by ianhbell** [comment]
There is no "right" answer to this question.  Fundamentally, a mixture at point A is two separate phases, so there are two different answers, one for the liquid, and another for the vapor.  There are MANY estimation methods for getting at an effective mixture viscosity for a two-phase mixture such as this, but all these approaches are approximations.  A possible method would be:

1/eta_mix = x/eta_vap + (1-x)/eta_liq

(vapor-quality-weighted fluidities of the liquid and vapor phases).

**Comment by KaiThorben** [comment]
Hi Ian, 

thank you very much. What is the source of this inverse method? I would like to learn more about these calculations. 

I have tried the approximation approach you described and it looks good. 

Best regards

Kai

**Comment by ianhbell** [comment]
I did a five second google search and I came up with : https://www.researchgate.net/publication/258788115_Effect_of_Void_Fraction_and_Two-Phase_Dynamic_Viscosity_Models_on_Prediction_of_Hydrostatic_and_Frictional_Pressure_Drop_in_Vertical_Upward_Gas-Liquid_Two-Phase_Flow

**Comment by nist-aharvey** [comment]
I will add to Ian's comment that the "viscosity" of a 2-phase mixture is not a physically meaningful concept.  If you are talking about flow in a pipe, for example, the "effective" viscosity depends on the details of the flow (whether you have bubbles in continuous liquid, annular flow, slug flow, etc.).
If you are using some sort of two-phase viscosity for a boiling heat transfer problem, I think you are probably not using a correct approach.  Boiling heat transfer is a problem that has been studied by many people, and while I am not an expert I think a correct description may involve the vapor viscosity and/or the liquid viscosity, but not any sort of 2-phase effective viscosity (just like you would separately use the thermal conductivity of the liquid and of the vapor).

**Comment by EricLemmon** [comment]
Is this issue resolved?  If so, could you close it?

**Comment by KaiThorben** [comment]
Yes, we now know how to calculate the densities. Thank you!
