### ISSUE TITLE
Using REFPROP within a Fortran programme

### ISSUE THREAD

**Issue by WalterAmbrosini** [usnistgov/REFPROP-issues#352]
Dear All,

I need to link NIST subroutines with a FORTRAN Program. I knew how to do with REFPROP 7, but with REFPROP 10 I do not understand where to find the components (e.g., the .fld files, if they are still necessary, or any FORTRAN routine that may be used for the purpose). 

Is there anybody who has an understandable example? 

Thanks in advance,

WA

**Comment by ianhbell** [comment]
The new functions in the user-friendly API are found in the ``REFPROP.FOR`` file, and the FLD files are still needed. You can do most everything with the REFPROP function.  Here are some examples in Python: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb ; nearly perfect mapping to FORTRAN.

What operating system are you running on?

**Comment by WalterAmbrosini** [comment]
Thanks for inquiring.

I am running under Windows with an Intel Fortran 
compiler under Microsoft Visual Studio.

         One point is that I have no REFPROP.FOR 
file... where can I find it. The only downloaded file was the NIST2310.EXE.

         Sincerely,

         Walter

**Comment by ianhbell** [comment]
Once you install REFPROP, there will be a FORTRAN folder in your installation.

Also please note that your email signature appears in email responses, it is therefore recommended to respond in the web interface.

**Comment by WalterAmbrosini** [comment]
Done, after uninstalling REFPROP7 I saw 
the FORTRAN folder. So the idea is that I should 
include all the .FOR files in my Fortran project. Isn't it?

         If so, I will try.

**Comment by ianhbell** [comment]
Please respond via the web interface or delete the rest of the email thread.

Yes, once you install REFPROP 10 with the installer, the files in the FORTRAN folder are what you need.

**Comment by EricLemmon** [comment]
Have you been able to successfully get things working?

**Comment by WalterAmbrosini** [comment]
Yes, thank you, I was. Now I have the 
program working under fortran... the new frontier 
for us will be Matlab... let's see.

         Thanks for your kindness and support.

         WA

**Comment by EricLemmon** [comment]
Great!  

Feel free to reopen this issue if needed, or start another one if a new problem comes up and you need help.  Be sure to open the issue in the wrappers github website:

https://github.com/usnistgov/REFPROP-wrappers/issues

There is an enormous amount of information in the issues posted there that can help with Matlab.
