### ISSUE TITLE
SURFT for pure fluid in mixture

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#36]
I have a mixture of ethanol + benzene, and I need to calculate pure-component surface tensions.  When I call ``SURFTdll`` with ``[0.0,1.0]`` composition I obtain the error

```
[SURFT error 518] Surface tension calculations for mixtures with water or alcohols are not currently supported.
```

Is there any way to calculate pure-component properties without re-initialization refprop for each calculation?

**Comment by ianhbell** [comment]
The “right” solution to this problem is to call ``PUREFLDdll`` to set the fluid you want from the mixture that you have loaded. Please see the link on the FAQ: https://pages.nist.gov/REFPROP-docs/#changing-fluids-and-calling-setup-multiple-times 

That said, this is basically a bug, because REFPROP should be smart enough to realize that you have passed a composition that is a pure fluid.

**Comment by ianhbell** [comment]
Also, see the documentation for ``PUREFLD``: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html?highlight=PUREFLD#f/_/PUREFLDdll

**Comment by EricLemmon** [comment]
This bug is now fixed and will become available with the next minor release of the program.

**Comment by cstroh76** [comment]
In the very early work on simulating reciprocating compressor performance, use was made of a compressibility factor Z along with pv^k=const for  an alleged  path of constant entropy.

Am I safe to say that I no longer need the compressibility factor or an exponent K  but merely use the specific volume and entropy at suction conditions provided by mixture data and the specific volume at discharge conditions along with the same entropy found at suction conditions using the same mixture data available today?
