### ISSUE TITLE
R-1132a for Refprop V10.0?

### ISSUE THREAD

**Issue by Yannikzahrt** [usnistgov/REFPROP-issues#360]
Hello everybody,

is it possible to get the refrigerant data of R-1132a for Refprop?
Can anybody help?

Greetings

Yannik

**Comment by ianhbell** [comment]
At present there is an exceptionally limited amount of experimental data for this fluid.  Until that situation changes, no, we won't be able to develop a multiparameter EOS for this fluid.  

These are the references that NIST TDE knows about for this fluid: 

```
{1955 fog lam 0} Fogg, P. G. T.; Lambert, J. D. Proc. R. Soc. London, Ser. A, 1955, 232, 537
{1955 mea sta 0} Mears, W. H.; Stahl, R. F.; Orfeo, S. R.; Shair, R. C.; Kells, L. F.; Thompson, W.; McCann, H. Ind. Eng. Chem., 1955, 47, 1449
{1964 ott tho 0} Otto, J.; Thomas, W. Int. J. Heat Mass Transfer, 1964, 7, 41-7
{1967 tsi pro 0} Tsiklis, D. S.; Prokhorov, V. M. Zh. Fiz. Khim., 1967, 41, 2195-2199
{1971 haw sut 0} Haworth, W. S.; Sutton, L. E. Trans. Faraday Soc., 1971, 67, 2907
{1974 gra par 0} Gray, P.; Parkinson, C. J. Chem. Soc., Faraday Trans. 1, 1974, 70, 560-571
{1992 kos leh 0} Koschine, A.; Lehmann, J. K. Meas. Sci. Technol., 1992, 3, 411-17
{2004 len bac 0} Lentz, D.; Bacher, A.; Buschmann, J.; Luger, P.; Messerschmidt, M. Chem. Eur. J., 2004, 10, 5059-5066
```

**Comment by Yannikzahrt** [comment]
Hello everybody, 

are there any news of implement of R-1132a into Refprop 10.0?

Greetings

**Comment by ianhbell** [comment]
Nope, we have measured some mixtures containing R-1132a.  There is no timeline for when we might have an EOS.

**Comment by Yannikzahrt** [comment]
What kind of mixtures do you have measured?

**Comment by ianhbell** [comment]
Please email me (ian.bell@nist.gov) and I can forward your question to the relevant party
