### ISSUE TITLE
Number of Components Programmatically

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-issues#361]
### Description

**SETUP()** takes `ncomp= -2` and returns `nc` (number of components).   This is a handy way to programmatically get `nc` when a mixture (.MIX) file is loaded.

The problem is that **SETUPdll** actually calls **SETUP0** (for other reasons).  However, **SETUP0** checks for `ncomp= -1` (version number returned), but does not check for `ncomp = -2` before calling **SETUP** and instead throws an error 109.

### Steps to Reproduce

1. Use SETUPdll to load a mixture file (.MIX) - any one.
2. Call SETUPdll with `ncomp = -2` to try and get the number of components programmatically

**Expected behavior:** **SETUPdll** returns `ierr = 109`

**Actual behavior:** **SETUPdll** (**SETUP0**) should return `ierr = nc` just like **SETUP**

### Versions

**REFPROP Version:** REFPROP 10.0.0.2  
**Operating System and Version:** Windows 10  
**Access Method:** Mathcad and Mathematica wrappers being developed, but any wrapper will do. 

### Additional Information

**SETUP0** should probably contain the same check for `ncomp = -2` that **SETUP** does.

If there is another way to programmatically extract `nc`, I can't find it.

I realize I should not be using the legacy API, but It's being used for wrapper backward compatibility with RefProp 9.x

**Comment by henningjp** [comment]
Well, I remembered I gotta call ``SETMIXdll`` for .MIX files, which returns ``ncc``.  This still might be a handy feature to get ``nc`` arbitrarily when needed.  Your call.

**Comment by EricLemmon** [comment]
I like easy changes such as this one!  It's updated, let us know if you want the patch.

**Comment by henningjp** [comment]
I have no immediate need...yet.  I can probably wait until the next version.  Thanks!
