### ISSUE TITLE
RefProp 10.0 - PH case does not converge on identical PS case

### ISSUE THREAD

**Issue by fabienwahl** [usnistgov/REFPROP-issues#366]
### Description

PH case cannot converge on identical valid PS case

### Steps to Reproduce

1. Molar composition

CO2 | 0.00000
Nitrogen | 0.93820
Methane | 97.45960
Ethane | 1.37420
Propane | 0.01900
Isobutane | 0.00160
Butane | 0.00000
Isopentane | 0.00120
Pentane | 0.00000
Hexane | 0.20620

2. unit = "si with c"

3. inlet condition T = -165C; P=0.35MPa
get S_in, H_in

4. isentropic discharge. This is the valid PS case
P = 2.35MPa; S = S_in
Refprop with PS
get H_out

5. actual discharge.
impose isentropic efficiency eff
calculate H_out = H_in + (H_out_is - H_in)/eff
Refprop with PH

**Expected behavior:** [What you expect to happen]
With eff = 1, expect to find the PS case

**Actual behavior:** [What actually happens]
PHFLSH error 248

calculation works with very low eff, like 0.1

### Versions

**REFPROP Version:** [REFPROP version you are using]  
10.0
**Operating System and Version:** [OS you are running REFPROP on]  
windows 10
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  
Excel, Refprop dll 10.0

### Additional Information

[Refprop10.0 test.xlsx](https://github.com/usnistgov/REFPROP-issues/files/5674707/Refprop10.0.test.xlsx)

**Comment by EricLemmon** [comment]
Please try this again with the files I just uploaded to see if the problem still exists.

**Comment by fabienwahl** [comment]
Hi Eric,
The .89 works better. When i open Refprop.xls and go on the mixture page, i still have errors. but as i go in the cell and hit "enter", it eventually calculates. Not always however, it takes a few "enter" to eventually get it.

on the example in this thread, the PH case now works. But as above, it needs manual "enter" on faulty cells which do not calculate after the file is opened. And then, re-enter from a good calculation generates an error (One or more inputs are out of range [...]). then re-enter on the error cell, and it goes back to a good calc. 

It's actually erratic, just moving a cell (prompting Excel to recalculate) ends up in global errors, and the faulty cells need to be re-entered to get rid of the error. is that an excel problem? or a seed in a solving algorithm?

**Comment by ianhbell** [comment]
Can you reproduce this outside Excel?  The order of operations in Excel makes it nearly impossible to debug what is going on.

**Comment by EricLemmon** [comment]
I had noticed this earlier as well before you wrote that, clicking in the cells would fix it, only to have it disappear when you did something else.  By far Excel is not the ideal solution for linking with complex programs due to the erratic way it just jumps around and processes things.  For single fluid or mixture applications it seems to work well, it's only when you put together a spreadsheet as complex as the Refprop.xls file that things can go ways that you don't expect.

Having said that, there are ways to make Excel work well, but these require code development inside an Excel module (with the use of VBA) that includes some human logic to process things in an orderly manner.  But without programming skills, this is not a possibility for many.

**Comment by fabienwahl** [comment]
Hi,

i have ran the sequence described above from within python instead of excel.
inlet is step 3.
out_is is step 4.
out is step 5.

execution with .89 works.
#####
RefProp Version 10.0089
inlet
0  array('d', [-165.0, 0.34999999999968107, -9999990.0, 436.89839942515636, -20.62123278793382, -0.037320400888695385, 16.499147426519997])
out_is
0  array('d', [-164.52059096826778, 2.349999999648834, -9999990.0, 437.9457487619468, -16.049004652712927, -0.03732040088869807, 16.499147426519997])
out
0  array('d', [-164.52059099130685, 2.350000051731533, -9999990.0, 437.9457488389267, -16.049004652713865, -0.03732040198348157, 16.499147426519997])
#####

execution with .00 does not work, see last set after "out".
#####
RefProp Version ******
inlet 
0  array('d', [-165.0, 0.34999999999999715, -9999990.0, 436.8983994253933, -20.621232948049915, -0.03732039743867798, 16.499147426519997])
out_is
0  array('d', [-164.520590967656, 2.3499999996477707, -9999990.0, 437.945748762634, -16.04900481283339, -0.03732039743866276, 16.499147426519997])
**out
248 [PHFLSH error 248] Single-phase iteration did not converge for P = 2.35000 MPa and H = -264.795 J/mol. array('d', [-9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, 16.499147426519997])**


##### code, coded for clarity, not efficiency.
``` python

    import os
    from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
    
    RP = REFPROPFunctionLibrary(os.environ["RPPREFIX"])
    print('RefProp Version', RP.RPVersion())
       
    hFld = "nitrogen; methane;ethane;propane;isobutane;isopentane;hexane"
    RP.SETFLUIDSdll(hFld)
    
    print("inlet ")   
    hIn = "PT"
    hOut = "T;P;QMASS;D;H;S;M"
    iUnits = RP.GETENUMdll(0,"SI WITH C").iEnum
    iMass = 2
    iFlag = 0
    a = 0.35
    b = -165
    z = [0.93820, 97.45960, 1.37420, 0.01900, 0.00160, 0.00120, 0.20620]
    r = RP.REFPROPdll(hFld, hIn, hOut, iUnits, iMass, iFlag, a, b, z)
    print(r.ierr, r.herr, r.Output[:len(hOut.split(';'))])
    
    T_in, P_in, QMASS_in, D_in, H_in, S_in, M_in = r.Output[:len(hOut.split(';'))]
    
    DP = 2.
    eff = 1
    
    print("out_is")
    hIn = "PS"
    P_out = P_in+DP
    a = P_out
    b = S_in
    r = RP.REFPROPdll(hFld, hIn, hOut, iUnits, iMass, iFlag, a, b, z)
    print(r.ierr, r.herr, r.Output[:len(hOut.split(';'))])
       
    T_is, P_is, QMASS_is, D_is, H_is, S_is, M_is = r.Output[:len(hOut.split(';'))]
        
    print("out")
    hIn = "PH"
    a = P_out
    H_out = H_in + (H_is-H_in)/eff
    b = H_out
    r = RP.REFPROPdll(hFld, hIn, hOut, iUnits, iMass, iFlag, a, b, z)
    print(r.ierr, r.herr, r.Output[:len(hOut.split(';'))])
   
    T_out, P_out, QMASS_out, D_out, H_out, S_out, M_out = r.Output[:len(hOut.split(';'))]
    
```

**Comment by ianhbell** [comment]
Tidied up a bit, check out my edits to see what I did.

**Comment by fabienwahl** [comment]
Hi 
i have to admit that until now, i never had this kind of behavior. The .86 was behaving well. It was slow for heavy problems, but not bugging. Like the night before .86 obsoleted, i ran successfully a time marching calc over a couple hours with multiple calls to the Excel solver involving refprop. I am wondering whether there was an Excel update somewhere that came in play.

 

This may sound going backwards, but could you recompile a .86 without obsolescence just so i can restart from something i know worked, and then see what happens. 

 

My issue is that i have a lot of old stuff running in excel i rely on, and i just don't have the time to transfer and rewrite all in python. Moreover without the known case in Excel as a debugging case in python, there is a certain rebuild in the dark...

Thanks in advance,

**Comment by fabienwahl** [comment]
Hi,

I solved it...
in Refprop.xla
in function REFPROP

comment out the line handling hFld and hFldOld. the portion __Then hFld = ""__ sends an empty string to the dll which returns with an error.

cases described above now run ok, including with two different fluids on the same sheet.

"""
'Call the REFPROPdll subroutine to obtain the requested properties.
__'Fab 20201215  If hFld = hFldOld And hFldOld <> "" Then hFld = "" Else hFldOld = hFld__
  If c > 0 Then hOut = Trim(hOut) + "(" + Trim(CStr(c)) + ")"   'Convert something like x that requires a component number into 
 x(1), x(2), x(3), etc., where the number comes from the last input to this routine.
  Call REFPROPdll(hFld, hIn, hOut, iUnitNumb, iMass, iFlag, a, b, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
  REFPROP = Output(1)   'Load the requested property into the function value.
"""

**Comment by EricLemmon** [comment]
I've opened a new issue to address the problems you reported in the section directly above for further consideration in the updates to the Refprop Excel worksheet.  The issue can be found here:  https://github.com/usnistgov/REFPROP-wrappers/issues/365
