### ISSUE TITLE
LIN mixtures rule

### ISSUE THREAD

**Issue by Fanch84103** [usnistgov/REFPROP-issues#368]
Hello, 

Can you explain what LIN mixtures rule is? 
(for example in the case of Argon/Helium mixtures)

What Kt and Kv means and how (if) can they be changed?

BR

**Comment by EricLemmon** [comment]
Before explaining this, you should be aware that changing the mixing rules is a very dangerous game!  I most definitely do not recommend it and warn you that many undesired consequences could happen with such a change.  The best thing to do is to make a request here to see if we have something available for the mixture you are interested in.  Often there is something, or if data are available we can fit those for you and send you and updated HMX.BNC file, which contains all the mixture parameters.

With that understanding, you should look closely at the GERG monograph given here:
https://www.gerg.eu/wp-content/uploads/2019/10/TM15.pdf
This document explains most of the mixing rules, and perhaps even the linear one.  The mixing rules are the underlying piece used as the reducing parameters in the mixture model (they are just reducing parameters, not the critical point or any other such state point).  

The linear mixing rule (LIN) is simply a mole fraction weighted sum of the pure fluid critical points.  For temperature, this would be

T<sub>red</sub>=SUM[x<sub>i</sub>*T<sub>ci</sub>]

To modify this functional form a bit, you can add a mixing parameter, kT, to the sum, as shown below for a binary mixture:

T<sub>red</sub>=x<sub>1</sub>T<sub>c1</sub>+x<sub>2</sub>T<sub>c2</sub> + x<sub>1</sub>x<sub>2</sub>(1-kT)[T<sub>c1</sub>+T<sub>c2</sub>]

For the density reducing parameter, the same would apply except that you mix the critical volumes of the pure components, use kV to modify the function, and then invert the whole expression to obtain Dred.

Everything else follows the formulations given in the GERG document.

**Comment by Fanch84103** [comment]
Thank you for your explanations and the document
