### ISSUE TITLE
Valid fluid name for Natural Gas

### ISSUE THREAD

**Issue by guptap1** [usnistgov/REFPROP-issues#369]

**Comment by guptap1** [comment]
Using REFPROP version 10, I am trying to generate properties of liquified natural gas in Excel spreadsheets. I do have REFPROP.xla open. However, the name "Typical Natural Gas", does not work in the name field. Does anyone know what name should I be using. 
When running REFPROP directly I can select Typical Natural Gas as a substance, and the the properties can be calucalated successfully.

**Comment by EricLemmon** [comment]
If you look in your Refprop\Mixtures directory you will see all the file names of the mixture files.  For your case, the one you want is called "NGSAMPLE.MIX".  Try that and hopefully all works for you.

**Comment by EricLemmon** [comment]
I've moved your issue to the wrappers website.
