### ISSUE TITLE
Difference between REFPROP results for GUI and spreadsheet

### ISSUE THREAD

**Issue by RickJefferys** [usnistgov/REFPROP-issues#37]
I have read documentation, FAQs etc.

I'm using REFPROP 10.0 under Windows 10 to evaluate enthalpies of a 4 component NGL stream at varying temperatures under constant pressure. As expected, the reported enthalpy values differ between the GUI and Excel (up to date Excel 2016 32 bit) interfaces since they use a different reference value. However, I was expecting the differences in enthalpy as temperature varies (ie effective Cp) to be the same - and they are not
I'm a "naive user" so apologies in advance if (as is likely) this is something blindingly obvious.
Example to follow (original example posted contained error).

**Comment by RickJefferys** [comment]
Corrected example attached.
[Example.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2257808/Example.xlsx)

**Comment by ianhbell** [comment]
Did you intend to close this issue?  If so, what was the resolution?  If not, can you please re-open it?

**Comment by RickJefferys** [comment]
Oops, no, thanks for asking. I must have blundered while editing, will fix
right away.
Regards
Rick

**Comment by RickJefferys** [comment]
Reopened, Close accidentally (thought I was closing the window, not the issue).

**Comment by ianhbell** [comment]
See also here: https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fusnistgov%2FREFPROP-issues%2Fissues%2F37

**Comment by RickJefferys** [comment]
Interesting but my issue is not inconsistency between refprop and other authorities, but the difference between the spreadsheet and the gui versions - but maybe I misunderstand ( would not be first time!). Thanks

**Comment by ianhbell** [comment]
The basic issue is reference states, and how they are defined for mixtures (very non-trivial).  There are a number of options, and they all give different answers.  The GUI and Excel do things differently, please see the note in the XLAM file.  There is a flag you can unset in the XLAM to make everything agree. We are constrained by an unfortunate decision years ago that we have to stick with in perpetuity. :(

**Comment by RickJefferys** [comment]
Thanks. Does that mean that the delta-h/delta-T figures from the gui version are correct ie near to physical reality, while the Excel version is ‘wrong’ until I reset the flag?
Thanks for your help, very much appreciated.

**Comment by ianhbell** [comment]
Neither is "right" or "wrong", just different.  What happens when you change the flag?  Are the results different between GUI and Excel?  They should be the same at that point.

**Comment by RickJefferys** [comment]
I've changed the flag from 2 to 1 in refprop.xls (which was what popped up when I hit alt-f11) but could not save it back to the c:\Program-x86\refprop directory, will re read docs and figure it out. But if neither is 'right', both 'just different', how do I know what I'll see in the physical world?
Thanks

**Comment by RickJefferys** [comment]
I changed the menu item in Refprop gui, thinking that should make it consistent with the spreadsheet, avoiding the need to figure out how to save the VBA in a place that would connect to excel. The enthalpies change as do the dh/dT, but not in a way that makes them consistent with Excel refprop.

**Comment by ianhbell** [comment]
Hrm...  Maybe this is a bug then.  Do the enthalpies line up correctly when the flags are aligned?  I'm away from my computer currently, so I have difficulties in testing your example directly.

**Comment by RickJefferys** [comment]
I'm not clear that the flags are aligned - current VBA shows value of 2 in SETREF, cannot figure out how to save the edited version so stuck with that. In gui refprop, I left reference state at default and changed the bottom right option to apply to pure fluids, not the current mixture, not at all sure that I'm doing the right thing there. Let's not waste your time, I can wait till you get back to your computer and can take a look.
Thanks

**Comment by ianhbell** [comment]
You can also move the XLAM to somewhere where you have read access (your home folder for instance).  That should allow for more reliable testing I hope.

**Comment by RickJefferys** [comment]
One additional point; I'm having a hard time understanding how a difference in definition of zero enthalpy can affect delta_h/delta-T for the mixture? Surely the zero points will just subtract out? Or is it more complicated / nonlinear than I think? Thanks.

**Comment by ianhbell** [comment]
Is your composition constant for all the calls?  If so, it is indeed the case that dh/dT|p should be the same as c_p.  

This may be a bug in REFPROP.  I have forwarded this to Eric Lemmon.  Hopefully he can comment or fix the bug if needed.

**Comment by RickJefferys** [comment]
Yes, I'm using the same mixture, newly installed Refprop (Coolprops falls
over with the defined mixture so I had to man up and buy it), hope you and
others can reproduce the numbers in the spreadsheet.

Best regards

Rick

**Comment by EricLemmon** [comment]
Hi Rick,

I entered your mixture and conditions into the graphical interface and got the same values as in your Excel sheet.  It is possible that you had a different set of units loaded or some other input such as using propadiene instead of propane (which I do all the time because of the order in the list of fluids).  I uploaded the image from my machine and hope that helps to understand the problem.

Eric
![example](https://user-images.githubusercontent.com/42392984/44360604-8e959a80-a478-11e8-9e2b-01906e681bba.png)

**Comment by RickJefferys** [comment]
Thanks for this - your numbers certainly agree with my spreadsheet but I
don't get the same enthalpies in gui Refprop

[image: image.png]

The enthalpy figures are the same as I showed in the example spreadsheet;
my deltaH over 4 degrees is 331.29-284.26,ie about 47kJ/kg, an effective Cp
of around 11.76. I have the same composition as you do, but maybe there is
some other setting / switch that I don't know about?

Many thanks for your help.

Regards

Rick

**Comment by EricLemmon** [comment]
Your picture did not come through, can you resubmit it?  Be sure to use the github web interface to do this.

**Comment by RickJefferys** [comment]
Hi Eric, sorry about that, previous post was via gmail. Here it is:

![refprob_pic](https://user-images.githubusercontent.com/38585523/44362869-48612b00-a4ba-11e8-8781-62cf1b1c20d3.PNG)

Not sure you will see this - I'm seeing an https//etc address, maybe will show when I post, will try again if it fails.

Regards

Rick

**Comment by EricLemmon** [comment]
Thanks, now it's visible.  The problem that has occurred is a difference between mole fractions vs. mass fractions.  Your calculations in the GUI are being done on a mass basis.  You can tell this because the title shows "(33/34/33)".  On a molar basis it would show "(0.33/0.34/0.33)".  You can change this by going to the Substance/Specify Composition menu and changing the option under "Components".

**Comment by RickJefferys** [comment]
Eric, many thanks and sorry to bother you on something so elementary. I'd thought I was operating on a mass basis in the spreadsheet as well, had not realised that the mixture spec was molar.
All the best
Rick

**Comment by EricLemmon** [comment]
This is a very easy mistake to make, I have done it many times.  It is good that you were using the GUI to verify the results coming from Excel, that is probably one of the best tests that should be done often to verify proper calculations.

**Comment by RickJefferys** [comment]
All works fine now, many thanks, will close. Paranoia is certainly a virtue (some of the time)!
Thanks again to you and Ian.
