### ISSUE TITLE
Peng-Robinson Mixing Parameters

### ISSUE THREAD

**Issue by bbefort** [usnistgov/REFPROP-issues#372]
### Description

I am trying to use the Peng-Robinson EoS to reproduce the phase diagram of R-32/R-125. However, when I choose to use the PR EoS for all calculations, I cannot find the mixing rules associated with the PR model. Which mixing rules are being used for these calculations? Do I need to choose my own from the drop down (i.e. the Lemmon and Jacobsen model for refrigerant mixtures)? 

### Versions

**REFPROP Version:** DLL version 10.0 
**Operating System and Version:** Windows
**Access Method:** Desktop
### Additional Information

<img width="627" alt="Screen Shot 2021-01-04 at 12 20 26 PM" src="https://user-images.githubusercontent.com/61247654/103567017-a4a92780-4e88-11eb-9fd9-4b7c19a64b89.png">
<img width="1032" alt="Screen Shot 2021-01-04 at 12 19 57 PM" src="https://user-images.githubusercontent.com/61247654/103567020-a5da5480-4e88-11eb-85b4-7c01f1541047.png">

**Comment by EricLemmon** [comment]
Can you send me a personal email and I'll send an update to see if it works?  I'm at eric.lemmon@nist.gov
