### ISSUE TITLE
Incorrect values for enumerators

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#373]
There are two problems with the enumerators for unit systems.

1) "MOLE SI" is not an accepted input to GETENUMdll (same problem with alpha and beta):
``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
os.environ['RPPREFIX'] = 'C:/Program Files (x86)/REFPROP'
root = os.environ['RPPREFIX']
RP = REFPROPFunctionLibrary(root)
print(RP.GETENUMdll(0,'MOLE SI'))
```
yields
```
GETENUMdlloutput(iEnum=-9999970, ierr=811, herr='[GETENUM error 811] Input string not recognized: MOLE SI')
```

Edit: the correct string is "MOLAR SI", docs in ``REFPROP.FOR`` need to be updated.

2) The enumerator values for MOLAR BASE SI and MASS BASE SI have been changed at some point, and the documentation gives incorrect values for the enumerated values. The docs currently show 100 and 101:

![image](https://user-images.githubusercontent.com/11966765/104033724-e9410580-519d-11eb-8b91-763dd4f9bdf5.png)

but the values in the code in ``CONSTS.INC`` are 20 and 21:

![image](https://user-images.githubusercontent.com/11966765/104033792-037ae380-519e-11eb-843e-e8db250d4cd5.png)

It would be wise to remove the numerical values entirely from the docs so that there is no possible confusion in the future.

**Comment by EricLemmon** [comment]
I looked through the code and we never did call it "mole si" but rather "molar si".  However, I think your idea is good so I added it, as well as a version without a space: "molesi".  I also added "masssi" to be consistent with other available enumerators such as "SIwithC" and "SI with C" (both of which are already available in 10.0).  For base units, the molar enumerator is "molar base si", should I also add "mole base si"?

**Comment by ianhbell** [comment]
In the docs (as I wrote above), it is listed as MOLE SI. That's the core problem I am mentioning here.

**Comment by ianhbell** [comment]
I wouldn't include the version without spaces if it were me.  There should be ideally only one way to do things, and that way should be documented.

**Comment by EricLemmon** [comment]
Most of the ones without spaces have been there since the beginning, so we can't delete them now.  But I think we have now covered all the bases and am good to go.  In fact those go clear back to about version 8 when I put together the Excel spreadsheet as requested by a few people.  I never imagined it would grow to be the monster it is today.

**Comment by ianhbell** [comment]
The issue is that the enumerators are coming from the FORTRAN file, so the values need to get fixed there, and then I will regenerate the documentation
