### ISSUE TITLE
Deviating results with self-defined mixtures in Refprop Excel add-in.

### ISSUE THREAD

**Issue by VanHalteren** [usnistgov/REFPROP-issues#374]
I am using Refprop as an Excel add-in for several years now to great satisfactory (for the predefined mixtures).

However the results of the self-defined refrigerants do not agree with the manufacturer's data.
Deviations from 0.2 to 0.5 bar have been determined when converting the temperature to pressure. 
This has been observed with R513A (not yet defined in version 9.1), but also with R407C (already defined in version 9.1).

![Refprop mixture](https://user-images.githubusercontent.com/77403006/104481103-ab8d1400-55c5-11eb-9072-bd2fde80c7ec.PNG)

How can this be explained and more important how can I resolve this/ make it more accurate? 

Kind Regards,

VanHalteren

**Comment by ianhbell** [comment]
First question: where did the manufacturers get their data from? This is a question of binary interaction parameter sets, and different manufacturers base their models on different data, and as a result,  get different results. These are "classical" HFC blends, so let's first check whether your baseline agrees with the experimental data.

**Comment by EricLemmon** [comment]
You need to add the word "mass" at the end of your fluid definition line to indicate that the compositions are mass fractions.  Something like this:

"R32;.5;R125;.5 mass"

**Comment by VanHalteren** [comment]
Dear Eric,

Many thanks for your fast reply.

The addition of the word “mass” I tried earlier for R513A, but it didn’t change the outcome, therefore I thought it didn’t work/ it had no added value.
I see that for R407C the result has changed and is correct now. Thank you for that.

As said the results of R513A are still off by ca. 0,3 bar at 10°C and it increases to over 1 bar at temperatures above 70°C
The results given be Refprop are different from the results given by different apps (e.g. Danfoss and Bitzer) and the different PT charts I have found on the internet, including that of the manufacturer (Opteon) .
On the other hand it is of course likely that all the other PT charts and apps are based on the data provided by the manufacturer. So if the manufacturer chart is not correct …, but I cannot imagine that as the refrigerant is already on the market for several years.

[cid:image001.jpg@01D6EA3C.9521DC90]

[cid:image002.jpg@01D6EA3C.9521DC90]


Any ideas?



Met vriendelijke groet / With kind regards / Mit freundlichen Grüßen,


Jan-Rients Sinnema
R&D Engineer

[Logo Van Halteren Naval Technologies]

P.O. Box 659, 8000 AR Zwolle
Hanzelaan 95, 8017 JE Zwolle
The Netherlands
M: +31 (0)6 – 132 15 966
T: +31 (0)38 - 425 43 38
E: jan-rients.sinnema@vanhalteren.com<mailto:jan-rients.sinnema@vanhalteren.com>
I: http://www.vanhalteren.com<http://www.vanhalteren.com/>

Van: Eric Lemmon <notifications@github.com>
Verzonden: donderdag 14 januari 2021 00:41
Aan: usnistgov/REFPROP-issues <REFPROP-issues@noreply.github.com>
CC: Jan-Rients Sinnema <jan-rients.sinnema@vanhalteren.com>; Author <author@noreply.github.com>
Onderwerp: Re: [usnistgov/REFPROP-issues] Deviating results with self-defined mixtures in Refprop Excel add-in. (#374)


You need to add the word "mass" at the end of your fluid definition line to indicate that the compositions are mass fractions. Something like this:

"R32;.5;R125;.5 mass"

**Comment by VanHalteren** [comment]
Hello Ian,

Thank you for your reply.

For the classic HFC blends (e.g. R407C) my problem has been solved.
The word “mass” had to be added in the mixture definition.

Unfortunately the results for R513A are still off/ remain unchanged (with regard to my baseline data).
My base line data are the apps of Danfoss and Bitzer and the PT chart of the manufacturer (Chemours/ Opteon).
They all match, but that could be explained by the fact that all data are likely to be based on the data provided by the manufacturer of the refrigerant.

R513A is on the market now for quite some years and therefore my first feeling is that data of the manufacturer should be correct.
Deviations of 0.2/ 0.3 bar at 10°C and over 1 bar at temperatures above 70°C could not go unnoticed when applied in practice.

[cid:image002.jpg@01D6EA3E.DA42EF60]

[cid:image004.jpg@01D6EA3E.DA42EF60]


Any ideas what the cause could be?

**Comment by EricLemmon** [comment]
Your pictures did not come through, can you upload them again?

**Comment by ianhbell** [comment]
You will need to add the photos in the github web interface

**Comment by VanHalteren** [comment]
Thank you for your reactions (and patience).

Below the pictures:

![Refprop(4)](https://user-images.githubusercontent.com/77403006/104596493-578d3880-5674-11eb-9c49-80889bdfdb1d.PNG)
![Refprop(5)](https://user-images.githubusercontent.com/77403006/104596514-5bb95600-5674-11eb-86ea-32ec48828196.PNG)

![Refprop(2)](https://user-images.githubusercontent.com/77403006/104595966-9b337280-5673-11eb-8024-90796218eefa.PNG)
![Refprop(3)](https://user-images.githubusercontent.com/77403006/104595978-9ff82680-5673-11eb-8fad-dceb67991faf.PNG)

**Comment by EricLemmon** [comment]
Try removing the semicolon before the word "mass" and see if that works.  I tried it here and got the same answer as the manufacturer has on their sheet.

**Comment by VanHalteren** [comment]
Good morning Eric, 

Thanks again for your reply.
Removal of the semicolon does not give a change in results.

Are you using version 9.1 als or version 10?
I thought that I have read somewhere that there is "a bug" in version 9.1 with mixtures containing both R134a and R1234yf.

**Comment by EricLemmon** [comment]
I looked back at the mixture file for version 9.1, and it does not have the binary interaction parameters in it for R134a with R1234yf.  If you will send me a private email (eric.lemmon@nist.gov), I'll send you a new file that fixes this.

**Comment by EricLemmon** [comment]
Has this issue been resolved, and if so, would you close the issue?

**Comment by EricLemmon** [comment]
I've moved your issue to the wrappers site.
