### ISSUE TITLE
Error in THERM0 code

### ISSUE THREAD

**Issue by pjh16** [usnistgov/REFPROP-issues#377]
In the new (RP10.0) version of subroutine THERM0, the speed of sound calculation includes initialization of variable "w" which should be "w0". This looks like a cut'n'paste hangover from THERM. The perils of implicit typing!

**Comment by EricLemmon** [comment]
Thanks for pointing this out!  Fortunately, with today's equations of state, there are no places within the region of validity where this would impact calculations.  Some of the older formulations such as that for NF3 may possibly have a few very isolated spots, but I don't remember of any.  This error would only come into play with our EOS development outside of the region of validity (for example, less than the triple point temperature) or within the two-phase region looking at metastable and unphysical states.  In those regions, if one, but not both, of the heat capacities (isochoric and isobaric) is less than 0, then speed of sound would be an imaginary number.

**Comment by EricLemmon** [comment]
P.S.  Even though I didn't explicitly say it, I did fix the code.
