### ISSUE TITLE
Mixtures information about REFPROP

### ISSUE THREAD

**Issue by AleDroid93** [usnistgov/REFPROP-issues#379]
Hello, hoping to write in the right section, I would like to have information about REFPROP features with mixtures. Anyone could help me?

### Description

I'm evaluating to purchase REFPROP for an ongoing project. In particular I would like to know if it's right for mixtures and what are current issues with them.
I already read FAQs at https://pages.nist.gov/REFPROP-docs/ without finding relevant information.

**Expected behavior:** Given a <pressure,entropy> pair, obtain temperature for R452A and other mixtures.

### Versions

**Operating System and Version:** Windows 10
**Access Method:** I'm evaluating REFPROP with MATLAB or Python wrappers.

### Additional Information

Docs reference or snippet code for such mixture are welcome.

**Comment by ianhbell** [comment]
Yes, R452A is included in REFPROP:

![image](https://user-images.githubusercontent.com/11966765/107541702-698bc980-6b95-11eb-8b7f-8a6ac4707993.png)

**Comment by EricLemmon** [comment]
Here's a fun picture to show a pressure-entropy graph.  The lines are isotherms, isochores, and isenthalps.

![image](https://user-images.githubusercontent.com/42392984/107548760-49a3d800-6b8c-11eb-954d-884a00d32a14.png)
