### ISSUE TITLE
Changing R507a ppf file and Refprop shortcut on desk top

### ISSUE THREAD

**Issue by Kandadaisrinivasan** [usnistgov/REFPROP-issues#380]
I have been using version 9.1 all along, which I purchased a few years back. I just purchased the upgrade from version 9.1 to 10
1. When I installed NIST2310.exe, it was successful. But REFPROP.exe file still shows 9.1 (but 2018) in the desktop short cut. However, when I opened from shortcut it says DLL version 10.0. Has the installation been correct?
2.The upgrade says to replace R507a.ppf file with a new one. I am not able to replace it in the fluids folder because it says I dont have permission and must contact the vendor. Can you plese let me know how to overcome this problem? Actually, I see that there is only one small difference. In the terms in eqn. of state it should be 22 instead of 21. I tried to correct it but unable to save.

**Comment by ianhbell** [comment]
1. It is recommended to fully uninstall REFPROP 9.1 prior to installing version 10.  That means to run the uninstaller (via the standard windows route), as well as deleting the ``c:\program files\REFPROP`` folder, and also unsetting the ``RPPREFIX`` environment variable.  Then and only then, install REFPROP 10.
2. That step is no longer needed with REFPROP 10, REFPROP 10 includes the necessary (correct) file.
