### ISSUE TITLE
Issue in linking REFPROP with Excel

### ISSUE THREAD

**Issue by calculuspro** [usnistgov/REFPROP-issues#381]
![image](https://user-images.githubusercontent.com/79392690/108618755-94aace80-745b-11eb-8e69-5b6d6bed0447.png)
trying to link my RefProp file to excel but it wont work

I am using MS EXCEL 2016 and REFPROP v 9.0

**Comment by EricLemmon** [comment]
This is most likely because you have a 64 bit version of Excel and version 9.0 of Refprop does not contain a file compatible with it.  Can you send me a personal email address and we can update you from 9.0 to 9.1 (this is a free upgrade)?  I'm at eric.lemmon@nist.gov

**Comment by calculuspro** [comment]
> This is most likely because you have a 64 bit version of Excel and version 9.0 of Refprop does not contain a file compatible with it. Can you send me a personal email address and we can update you from 9.0 to 9.1 (this is a free upgrade)? I'm at [eric.lemmon@nist.gov](mailto:eric.lemmon@nist.gov)

my bad, upon checking it says 9.1

**Comment by calculuspro** [comment]
hello sir eric, upon checking my file it says 9.1 my bad that I didnt checked thoroughly

**Comment by EricLemmon** [comment]
In this, case, check that the directory it gave is correct.  Perhaps the Refprop folder is in a different place.

Also, have you gone through these instructions carefully?

https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel

**Comment by calculuspro** [comment]
I also tried using this link https://github.com/usnistgov/REFPROP-docs/blob/nist-pages/index.md#resolving-problems-linking-with-excel

But im using v 9.1 with Excel 2016

**Comment by calculuspro** [comment]
Go to the Refprop.xla file (assuming that it has already been selected as an Add-in) by pressing Alt-F11. Open up the item labeled REFPROP.XLA in the list on the left, click on Modules, and then on Refprop10Code. Near the top you will find …Sub REFPROPdll Lib “REFPRP64.DLL”… Change this to …Sub REFPROPdll Lib “c:\Program Files (x86)\Refprop\REFPRP64.DLL”… If using a 32 bit version of Excel, add the same path to the line two lines below this one.

I think my modules didnt show this one, i will try using other paths that arent from the Program files or Prog file x 86, tried both, the one with x86 does not permit me with admin rights or something that I saw that someone has the same issue. I will try again ty sir. will message asap

**Comment by EricLemmon** [comment]
Many of the instructions on that webpage also apply to 9.1.

However, because the error message you received gave a message that came from the DLL, then it appears that the connection has been made and that it simply cannot find the fluid file.  Did you check to make sure the water.fld file is in the exact directory it mentioned?

**Comment by calculuspro** [comment]
this sir is the folder proper : )

**Comment by calculuspro** [comment]
my bad, it was program files that didnt permit me to edit stuff like what https://trc.nist.gov/refprop/LINKING/Linking.htm#ExcelApplications says me to do

**Comment by EricLemmon** [comment]
Is it working now for you?

**Comment by calculuspro** [comment]
On Sunday, February 21, 2021, 04:34:36 PM GMT+8, Eric Lemmon <notifications@github.com> wrote:  
 
 


Is it working now for you?

**Comment by calculuspro** [comment]
sir still not working for me.

**Comment by EricLemmon** [comment]
Perhaps I can log into your computer to see what is wrong.  Can you send me an email at eric.lemmon@nist.gov, but also post here that you have sent the email so that I know to check my NIST computer.
