### ISSUE TITLE
Use of SATSPLNdll

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-issues#383]
### Description

Not an issue, but a question about usage of SATSPLN when making calls to the DLL.  It can be called directly in the Legacy API or switched on with a flag in the new High-Level API.  What is the benefit and purpose of calling SATSPLN?  I've only recently gotten into mixture properties.   What behavior does it change in REFPROP?  I don't see much, if any change in behavior with or without it.

I'm guessing it creates a spline through the combined saturation curves, but my binary mixtures work without it.  Is it for speed?  Does it only help noticeably with many-component mixtures?

The doc PDF says it calculates the phase boundary along with the **_mixture critical point_**, **_cricondentherm_**, and **_cricondenbar_**.  I think I understand the concepts on what those points are, but how do I extract those quantities for the mixture?

### Steps to Reproduce

n/a

### Versions

**REFPROP Version:** REFPROP 10.0.0.02  
**Operating System and Version:** 64-bit Windows 10 
**Access Method:** Building my own wrappers in Mathcad and Mathematica to call the DLL API functions.  

Thanks in advance!

**Comment by ianhbell** [comment]
Well, for "simple" mixtures, far from the respective critical point, VLE calculations aren't too tricky and are quite reliable.  Once you get into very asymmetric mixtures, everything changes and "blind" VLE calculations become difficult/impossible.  For instance something like this from https://doi.org/10.1063/1.5142275 gives you a sense for what is possible : 
![image](https://user-images.githubusercontent.com/11966765/109319141-8a525100-781c-11eb-95e7-f568521ff60d.png) 

In this case, you need to create a curve of constant composition crossing through the entire phase envelope to know how to initialize your desired iterative solution for phase equilibrium.  This is what SATSPLN does for you.  It is essential for calculations with challenging mixtures.

**Comment by ianhbell** [comment]
Here is an example of programmatically extracting the things you asked about:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

root = 'C:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

import matplotlib.pyplot as plt
import pandas

# Set up the fluids we want
mix = RP.SETMIXdll('AMARILLO.MIX',"HMX.BNC","DEF")
# Construct the saturation spline
print(RP.SATSPLNdll(mix.z))
# Get values from the spline
r = RP.REFPROPdll("","","TMAXT;PMAXT;TMAXP;PMAXP;TC;PC",RP.MOLAR_BASE_SI, 0,0, 0,0, mix.z)
TMAXT,PMAXT,TMAXP,PMAXP,TC,PC = r.Output[0:6]

# Now we programatically extract the nodes of the isopleth...
Nnodes = RP.REFPROPdll("","SPLINENODES","",0,0,0,0,0,mix.z).iUCode
data = []
for i in range(1,Nnodes+1):
    rho_vap,T,p,rho_eq,z0,z1 = RP.REFPROPdll("","SPLINENODES","",0,0,i,0,0,mix.z).Output[0:6]
    data.append(dict(rho_vap = rho_vap,T=T,p=p,z0=z0,z1=z1))
# Convert the data points into a pandas DataFrame
df = pandas.DataFrame(data)
# And plot them...
plt.plot(df['T'],df.p,'o-')

plt.plot(TC,PC/1e3,'*')
plt.plot(TMAXT,PMAXT/1e3,'h')
plt.plot(TMAXP,PMAXP/1e3,'s')

plt.yscale('log')
plt.xlabel('T [K]')
plt.ylabel('p [kPa]')
plt.show()
```
yielding
![image](https://user-images.githubusercontent.com/11966765/109321047-b79ffe80-781e-11eb-8941-c0363095c559.png)

**Comment by henningjp** [comment]
Excellent, @ianhbell !  Thank you!

**Comment by henningjp** [comment]
I'm going to re-open this with a follow on question.  Is there ever a time when defining a mixture, either through REFPROPdll or SETMIXTUREdll, then you **_wouldn't_** want to call SATSPLNdll?  Does it come at a cost for simple mixtures away from the critical point that one might not want to carry?  Why don't SETMIXTUREdll and REFPROPdll (when a mixture is detected) call SATSPLN automatically (i.e. override with `iFlag` = 1 when a mixture is being set, `ncomp` > 1)?

**Comment by EricLemmon** [comment]
For simple mixtures, SATSPLN is quite fast considering that it is calculating the entire phase diagram, including the critical region.  In the GUI, it is on by default and it is rare to notice a delay when setting up binary mixtures.  For complex mixtures, either for binaries that contain water, methanol, helium, or hydrogen, or for multicomponent mixtures of five or more components, the time required by this routine could be a second or more.  You can test this with the GUI.  Set up any mixture and then hit the OK button.  Generally it takes less than a second for it to finish, but a few mixtures will take two or three seconds.

Just out of curiosity, I ran the code below, which calls this routine 1001 times for the R32/R1234yf binary mixture.  The total time was 16 seconds on my machine, or 0.016 seconds per call to SATSPLN.  I tried this again with water+ethane and it took 0.06 seconds per call.  The complex Amarillo natural gas mixture took about 0.25 seconds to call.  Not bad!

The only time you wouldn't want to call this is when you are making millions of calls to the DLL with constantly and drastically changing compositions.  With small changes in composition, the splines can be called once and they will work for a range of values near the inputs sent to the routine, with that range depending on the complexity of the mixture.  In such a situation, you could monitor the compositions and then recall the splines when your composition changes by more than 5 to 20% for any of the components.  Tests like that below will reveal just how far away the state can go before failures in the saturation routines start.

```fortran
      open (unit=2,file='d:\data.dat')
      call cpu_time (istart)
      call setfluids('r32;r1234yf',ierr)
      do i=0,1000,1
        z(1)=DBLE(i)/1000d0
        z(2)=1d0-z(1)
        call SATSPLN (z,ierr,herr)
        if (ierr.gt.100) pause 'Error in Splines setup'
        T=300d0
        call SATT (T,z,1,P,Dl,Dv,x,y,ierr,herr)        
        if (ierr.gt.100) pause 'Error in calculation'
        write (2,*) T,P,z(1)
      enddo
      call cpu_time (iend)
      write (*,*) iend-istart
      pause
      stop
```

**Comment by ianhbell** [comment]
My experience has been that construction of the splines just makes the VLE calculation less reliable, in some cases.  But generally, it is a good idea to have them on.

**Comment by EricLemmon** [comment]
We haven't heard back, is this issue resolved now?

**Comment by henningjp** [comment]
Oh, yes.  Just needed some clarification for some wrapper documentation
I’m working on.

Thanks!

**Comment by JosvantWestende** [comment]
I have two questions related to this, so I add this to this issue. 
- 1 : Do you need to call SATSPLN with z specified on molar-base?
- 2 : If you set the flag after iMass to 1, do you enforce SATSPLN to be called again?
e.g. Hgsat = RP.REFPROPdll('', 'PQ', 'H', RP.MASS_BASE_SI, iMass, 1, P, 1, z).Output[0]
