### ISSUE TITLE
Creating FLD files for new compounds

### ISSUE THREAD

**Issue by ahfazahmed** [usnistgov/REFPROP-issues#384]
Hi there,
I am trying to create .fld files for a few compounds with Version 9.1 and have a question reg the ideal gas heat capacity function.

For example, when looking at Ioctane.fld. (I do not have access to the cited paper: Blackham, T.M. and Lemmon, E.W. Fundamental equation of state for isooctane)

The coefficients are:

1  3    0  0    0  0  0              !Nterms:  polynomial, exponential, cosh, sinh
10.76      0.0
15.48    775.0
34.42   1900.0
21.42   5100.0

I would be grateful if you explain the following queries:

1.	If I intend to use this info manually, how can I calculate Cp?
2.	When creating .FLD file for a new compound. How can I get these parameters? Since its gas phase, can I use NASA polynomials coefficients (for Low T range) for this calculation using the following expression?

![coeff](https://user-images.githubusercontent.com/14311599/109618001-58e8c680-7b37-11eb-8b59-6ab1d37202c1.png)
![eq](https://user-images.githubusercontent.com/14311599/109618005-59815d00-7b37-11eb-954f-cd65020789c2.png)
3. My last and most pressing concern is I created a .FLD for 2-methyl-1-butene (attached) using Peng Robinson EOS but I am getting very poor estimates of density with 20% error. Is it possible to create another more accurate EOS for this compound and -methyl-2-butene, 2,4,4-trimethyl-1-pentene, 2,4,4-trimethyl-2-pentene and MTBE 
[2 methyl 1 butene.txt](https://github.com/usnistgov/REFPROP-issues/files/6067135/2.methyl.1.butene.txt)

**Comment by ianhbell** [comment]
I would start with propane for which you can get the paper about its EOS.

Regarding density, you can enable volume translation in REFPROP (or apply it yourself), but that is not a perfect solution; this is the primary weakness of the cubic EOS. You might consider a PC-SAFT based EOS, but they are not implemented in REFPROP.  PC-SAFT generally (though certainly not always) provides a better representation of density.

**Comment by ahfazahmed** [comment]
Thanks Ian for your response, I will go through the Propane paper. Could you please comment on how to apply volume translation when I am calling Refprop through MATLAB?

**Comment by ianhbell** [comment]
Please see https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/PREOSdll

**Comment by ahfazahmed** [comment]
Hi Ian, in order to use this will I need this dll (preos), if so could you please help?
Also it would be helpful if you can share some sample lines of code to use it.

**Comment by ianhbell** [comment]
That method is exposed in the REFPROP dll.  If you are using the Python interface to REFPROP in MATLAB (which you should be!) then you call something like:
```
RP.PREOSdll(2)
```

**Comment by ahfazahmed** [comment]
I am using MATLAB

**Comment by ianhbell** [comment]
Right, but how do you call the REFPROP dll?

**Comment by ahfazahmed** [comment]
refpropm('P','T',373.15,'Q',0,'Water')

**Comment by ianhbell** [comment]
Right, you have to use this interface : https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

The refpropm interface is deprecated and no longer supported.

**Comment by ahfazahmed** [comment]
I followed all the steps and get
 RP.RPVersion()

ans = 

  Python str with no properties.

    9.1

Upon further testing
>> MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;
Error using ctREFPROP>GETENUMdll (line 1544)
Python Error: ValueError: The function GETENUMdll could not be loaded from the shared library.
 
>> iMass = int8(0); % 0: molar fractions; 1: mass fractions
>> iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
>> z = {1.0};
>> r = RP.REFPROPdll('Water','PQ','T',MOLSI,iMass,iFlag,101325,0.0,z)
Unrecognized function or variable 'MOLSI'.
 
Could you please advise how to fix this?

**Comment by ianhbell** [comment]
Right, with REFPROP 9.1 (you should upgrade to version 10!) the ``GETENUMdll`` function is not exposed.  So you need to go the conventional ``SETUPdll``, ``PREOSdll``, ``TPFLSHdll`` route.  The new interface is much easier to use...

**Comment by ahfazahmed** [comment]
I will try to buy the ver 10, in the meantime could u please provide some reference lines of code to use ver 9.1

**Comment by ianhbell** [comment]
In Python:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'C:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

# With the full EOS
RP.SETUPdll(1,'CO2','HMX.BNC','DEF')
RP.PREOSdll(0)
print(RP.TPFLSHdll(300, 100, [1.0]))

# With the cubic EOS
RP.SETUPdll(1,'CO2','HMX.BNC','DEF')
RP.PREOSdll(2)
print(RP.TPFLSHdll(300, 100, [1.0]))
```
yielding
```
TPFLSHdlloutput(D=0.040287081679073515, Dl=0.040287081679073515, Dv=0.040287081679073515, x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=998.0, e=19849.678497665653, h=22331.863749915967, s=120.78897634742388, Cv=29.01634564815618, Cp=37.519833656581696, w=269.392865342243, ierr=0, herr='')
TPFLSHdlloutput(D=0.0403058768731869, Dl=0.0403058768731869, Dv=0.0403058768731869, x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=998.0, e=19654.209821145985, h=22135.25249459392, s=119.97334368091938, Cv=28.942848135541166, Cp=37.44168534860221, w=269.32991000749604, ierr=0, herr='')
```

**Comment by ahfazahmed** [comment]
Thanks for sharing, is also possible to have it in MATLAB?

**Comment by ianhbell** [comment]
You're on your own for that, I don't use MATLAB.  But the translation from Python to MATLAB is close to one-to-one in this case.  Please see the examples: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#use

**Comment by ahfazahmed** [comment]
Hi Ian, I have arranged for purchasing a license for Refprop 10. 
I have two questions, I hope you can help.
1. The original question where I asked about adding NASA polynomials for calculating Cp?
2. As I specified earlier I have made new files for few compounds using Peng Robinson EOS. I understand that Peng Robinson EOS does not gives density estimates, could you please suggest a some fix to improve density prediction?

**Comment by ianhbell** [comment]
1. Recommend to read the propane paper and model your implementation on that, as I recommended above.
2. Volume translation is what you want to google.  It's not a perfect fix, from from it in fact.  But it's the best I know of for "patching" the cubic EOS
