### ISSUE TITLE
Water + Glycol Mixture Property Look Up

### ISSUE THREAD

**Issue by mnotarnicola** [usnistgov/REFPROP-issues#385]
I am trying to use 50/50 water/glycol in Refprop using Excel and/or MATLAB.  When I do a PH lookup for a property like Temperature I am receiving errors about the mixture being over the max density and under the minimum temperature.  However if I reverse the problem (do PT and look for Enthalpy) for the same conditions it has no problem.  I'm trying this at room temperature and atmospheric pressure.

### Steps to Reproduce

1. refpropm('T','P',101.325,'H',-2.632e5,'Water','Eglycol',[0.5 0.5]) % Should return T = 270K
2. refpropm('H','T',270,'P',101.325,'Water','Eglycol',[0.5 0.5]) % Returns -2.632e5 J/kg
3. [and so on...]

**Expected behavior:** Line 1 should return T = 270K

**Actual behavior:** Error using refpropm (line 519)
[PHFLSH error 3] One or more inputs are out of range; Temperature below triple-point or minimum temperature: T = 193.565 K, Tmin = 239.401 K;
Density above upper limit: D = 50.0606 mol/L, Dmax = 48.7256 mol/L.

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10
**Access Method:** MATLAB

**Comment by EricLemmon** [comment]
I believe that this is a bug that has already been fixed, can you please send us an email so we can send a patch?  eric.lemmon@nist.gov or ian.bell@nist.gov

**Comment by EricLemmon** [comment]
Here's the associated post about the bug:

https://github.com/usnistgov/REFPROP-issues/issues/270
