### ISSUE TITLE
Windows Dew point and Bubble point curves for R134a/R123 mixture don't match MATLAB and Fortran data

### ISSUE THREAD

**Issue by UMCFDgitadmin** [usnistgov/REFPROP-issues#386]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites
We are using V10 of REFPROP on Windows 10.
We are also using v10 on Linux CentOS 7 with gfortran (Fortran 95).

### Description
When we plot the dew point and bubble point curves in the Windows version 10 for a mixture R134a and R123 at P=500 kPa, the curves produced from the Windows interface do not match the values that are obtained using MATLAB and Fortran.

### Steps to Reproduce

Here is the MATLAB:
```matlab
%==================================================!
clear;
n=41;
TK=273.15;
W=linspace(0,1,n);
TV=zeros(1,n);
TL=zeros(1,n);
HV=zeros(1,n);
HL=zeros(1,n);
RhoV=zeros(1,n);
RhoL=zeros(1,n);
CpV=zeros(1,n);
CpL=zeros(1,n);
F1='R134a';
F2='R123';
P=500;
for i=1:n
    [TV(i),HV(i),RhoV(i),CpV(i)]=refpropm('THDC','P',P,'Q',1,F1,F2,[W(i) 1-W(i)]);
    [TL(i),HL(i),RhoL(i),CpL(i)]=refpropm('THDC','P',P,'Q',0,F1,F2,[W(i) 1-W(i)]);
end
writematrix([W' TV' TL' HV' HL' RhoV' RhoL' CpV' CpL'],'R134aR123_Matlab.txt','Delimiter','tab');
plot(W,TV,'r'); hold on;
plot(W,TL,'g');
xlabel(strcat('mass fraction of{ }',F1));
ylabel('Temperature K');
%==================================================!
```

Here is the Fortran:
```fortran
!     Example program using routines in REFPROP
!       Units are K, kPa, mol/dm^3, mole fraction, J/mol, J/mol-K, m/s
!       uPa-s, W/m-K, and N/m
!   *** See the file MANUAL.TXT in the FORTRAN directory for more routines ***
      program EXAMPLE
      implicit double precision (a-h,o-z)
      implicit integer (i-k,m,n)
      parameter (n=41) !number of computed points
      parameter (ncmax=41)   !max number of components in mixture
      dimension x(ncmax),xliq(ncmax),xvap(ncmax),f(ncmax),xm0(ncmax),xm(ncmax),w(n),xmW(ncmax)
      character hrf*3, herr*255
      character*255 hf(ncmax),hfmix
      dimension xdew(ncmax),ybub(ncmax)  !Only used for TQFL2 below
      character*255 rfppath
      character*80 fname, cline
      logical fxist
     common /prnterr/ iprnterr
     iprnterr=1
     rfppath='/home/mecfd/umleqt/cucula/refprop-10-R01/build/'
     call SETPATH(rfppath)
!...For a mixture, use the following setup instead of the lines above.
     nc=2
     hf(1)='R134a.FLD'
     hf(2)='R123.FLD'
     hfmix='HMX.BNC'
     hrf='DEF'
     call SETUP (nc,hf,hfmix,hrf,ierr,herr)
     if (ierr.ne.0) write (*,*) herr
     Open(Unit=55,File='R134aR123_code.txt')
     p=500  !pressure kPa
     write (*, '(3a15,f12.4,a3)') '#Fluid = ',hf(1),hf(2),p,'kPa'
     write (55,'(3a15,f12.4,a3)') '#Fluid = ',hf(1),hf(2),p,'kPa'
     w(1)=0 
     w(n)=1
     do i=2,n-1
       w(i)=w(i-1)+w(n)/(n-1)
     end do
!...Get saturation properties given t,x; for i=1: x is liquid phase
!.....                                   for i=2: x is vapor phase
      write(55,'(10a20)') '#W','Tv','Tl','Hv','Hl','rhov','rhol','Cpv','Cpl'
      do i=1,n
        xm(1)=w(i)
        xm(2)=1-w(i)
        call XMOLE(xm,x,wm)
        call SATP(p,x,2,tv,rholJ,rhov,xliqJ,xvap,ierr,herr) !get vap tv,rhov at p
        call SATP(p,x,1,tl,rhol,rhovJ,xliq,xvapJ,ierr,herr) !get liq tl,rhol
        call THERM (tl,rhol,x,pl,el,hl,sl,cvl,cpl,wl,hjtl) !liquid
        call THERM (tv,rhov,x,pv,ev,hv,sv,cvv,cpv,wv,hjtv) !vapor
        write (55,1010) w(i),tv,tl,1000*hv/wm,1000*hl/wm,rhov*wm,rhol*wm,1000*cpv/wm,1000*cpl/wm
      end do
      close(55)  
      stop
 1010 format (10es20.12)
      end
```
!==================================================!
A plot of the sets of files (Windows REFPROP, MATLAB, Fortran, and journal article) is attached.

![T-W-graph](https://user-images.githubusercontent.com/33630281/109743815-f0c9cd00-7b96-11eb-8fda-bab65070ae5e.png)

**Expected behavior:** [What you expect to happen]
Expect all curves to match within a reasonable tolerance. The MATLAB and Fortran curves do match well.
So to curves from a journal article.

**Actual behavior:** [What actually happens]
Windows curves don't match.

### Versions
REFPROP Version: 10.0
Operating System and Version: Windows 10 64 bit. For Fortran: CentOS 7.  
Access Method: Windows GUI , MATLAB on Windows, gfortran on Linux.  

### Additional Information
I can supply the data files if needed.

**Comment by ianhbell** [comment]
What journal article?

**Comment by ianhbell** [comment]
I'm trying to find the issue, but I believe someone else already reported that there was a bug in the GUI with mass fractions somewhere.  Can you please do the same example, but with mole fractions everywhere?  I think it will work out.

**Comment by UMCFDgitadmin** [comment]
Here is the article (attached). We were comparing with Figure 1.
Scott

________________________________

**Comment by ianhbell** [comment]
Doesn't attach via email.  Please provide URL to paper.

**Comment by UMCFDgitadmin** [comment]
Sorry.
Here is the DOI.

https://doi.org/10.1016/S0140-7007(02)00043-9
[https://ars.els-cdn.com/content/image/1-s2.0-S0140700720X00132-cov150h.gif]<https://doi.org/10.1016/S0140-7007(02)00043-9>
Prediction of in-tube condensation heat transfer characteristics of binary refrigerant mixtures<https://doi.org/10.1016/S0140-7007(02)00043-9>
This study presents a prediction model for the condensation heat transfer characteristics of binary zeotropic refrigerant mixtures inside horizontal s…
doi.org

I will also put an image of the figure we were using on github in case you cannot get a pdf of the original article.
Scott

**Comment by UMCFDgitadmin** [comment]
Here is the graph we were comparing with.
![jin-etal-fig-1](https://user-images.githubusercontent.com/33630281/109814325-fefa0680-7bf3-11eb-8285-d8bf7e721ecb.png)

**Comment by UMCFDgitadmin** [comment]
We will also try it with mole fraction and let you know.

**Comment by ianhbell** [comment]
Yes, please try with mass fraction. How did you do the calculations in the GUI?

**Comment by UMCFDgitadmin** [comment]
I will see the student in a Teams meeting later today, so I will confirm the GUI approach, but I think that he just specified the fluid pair and asked for a T-W graph.
We could also try the mole fraction approach at that time.
Scott

**Comment by ianhbell** [comment]
Aha, if a graph, then you might have the same bug as in #371

**Comment by UMCFDgitadmin** [comment]
Could be, but the data exported from the graph are in error, not just the graph.
Scott

**Comment by ianhbell** [comment]
Right - I wonder if the GUI doesn't convert the results to mass fractions, even if it says it did.

**Comment by UMCFDgitadmin** [comment]
My student tried it and he said that he found the same curves for both mass fraction and mole fraction, so it looks like the GUI
is not converting to mass fraction, as you thought.

**Comment by ianhbell** [comment]
Well, that's good and bad.  Good because we know what the problem is, bad because there is a problem.

**Comment by EricLemmon** [comment]
Can you send me a private email (eric.lemmon@nist.gov)?  I'd like to send you the current alpha version and a new GUI to let you try them and see if the problems are gone.

**Comment by NickAtNight62** [comment]
The curve that looks to be calculated using mole%.  Example:
![image](https://user-images.githubusercontent.com/58614082/119869862-58698d00-bee6-11eb-974b-3b5a9a87d77e.png)

**Comment by NickAtNight62** [comment]
[R134avR123Dewpoi.xlsx](https://github.com/usnistgov/REFPROP-issues/files/6555747/R134avR123Dewpoi.xlsx)

**Comment by ianhbell** [comment]
You'll need the fix from Eric

**Comment by UMCFDgitadmin** [comment]
I did get a newer version from Eric some time ago. My graduate student has not taken the time to test it yet.
I reminded him yesterday, so I hope he will let me know soon.

**Comment by UMCFDgitadmin** [comment]
Here is the feedback from my graduate student:

The new Beta version works: the mass fraction - temperature curve from REFPROP program matches our code (and MATLAB). But a new mixture must be defined to get it working properly.
If I open a saved *.rfp, the T-w curve will not update, ie: still wrong. Then if I try to update it or setup a new plot, the "Composition" from the pull down menu is not there, but use a "blank" then it works. It is weird.

**Comment by ianhbell** [comment]
That makes sense.  The RFP doesn't know anything about the fix in the GUI.

**Comment by NickAtNight62** [comment]
So something like this...

![image](https://user-images.githubusercontent.com/58614082/120399848-6cf0bf80-c302-11eb-9b9c-1eccbb009370.png)

**Comment by EricLemmon** [comment]
What do you mean by:

> "Composition" from the pull down menu is not there, but use a "blank" then it works

Can you include a picture?

**Comment by UMCFDgitadmin** [comment]
Eric:
Here are some screenshots that my graduate student provided to show what he is talking about.
The way he explained it is that when he first tries to re-do a plot, the menu item for "Composition"
is missing (i.e., "blank").  When he creates a new mixture and does the plot from scratch, Composition is in the menu.
Scott

________________________________

**Comment by ianhbell** [comment]
I think you need to add the screenshots in the github web interface to get them to show up properly

**Comment by UMCFDgitadmin** [comment]
What I sent a short while ago was a pdf document with screen shots and a few lines of text that are in a Word document sent to me by my graduate student. I don't see a way to attach the document here, so I will try to emulate it.

When he opened the saved .rfp file, the "mass fraction" is still "mole fraction" (incorrect curves):
![image](https://user-images.githubusercontent.com/33630281/120804937-ce837a80-c50a-11eb-80cd-7aad7e294d8d.png)
![image](https://user-images.githubusercontent.com/33630281/120804957-d2af9800-c50a-11eb-85ad-6afe3b35e534.png)

Then, when he went to do a new T-x plot, Composition does not appear in the pull down menu. It is blank, but he chose that.
![image](https://user-images.githubusercontent.com/33630281/120805056-f2df5700-c50a-11eb-84a5-d5aadabd069b.png)

Now the new graph is correct. He has what he expects (left side graph) and the one created with "blank" (right side graph). The new graph is correct, but the title is "Temperature vs".
![image](https://user-images.githubusercontent.com/33630281/120805295-4487e180-c50b-11eb-9d43-c03502143fb0.png)

If he defines a new mixture and creates the plot from scratch, it works fine.

**Comment by ianhbell** [comment]
Interesting, seems like a bug in the GUI.

Can your student use other programming environments like Python or MATLAB? They could call the tracing routines directly, which would avoid this and allow for a wider range of capabilities.

**Comment by UMCFDgitadmin** [comment]
The student is developing an in-house CFD code for binary vapour condensation in a vertical pipe and is accessing the
REFPROP routines via Fortran 95.  He also programs in MATLAB. Both those approaches yield consistent results. 
It was just the Windows GUI that we identified as having a problem.

Is this what you meant by allowing for a wider range of capabilities?  I am not sure what you mean by tracing routines.

**Comment by ianhbell** [comment]
The p-x diagram you are looking at is traced with: https://github.com/usnistgov/isochoric (see also the link in the GUI). There is a Python wrapper that can either be called directly from Python, or the Python wrapper can be called from MATLAB.  Avoids the GUI entirely and gives you a lot more power.

**Comment by UMCFDgitadmin** [comment]
Thank you for that pointer. It may be helpful in the future for small projects, and probably with MATLAB. We have not yet embraced Python for research use.

Our CFD codes are computationally intensive and require high performance (run times for one simulation can be anywhere from a few hours with one core to several weeks using 30 cores), so we have not considered Python. Perhaps our choice of Fortran seems outdated, but is working for us.

Also, we found that the overhead of calling the REFPROP routines dynamically while doing the iterative solution of our discretized governing equations was not feasible. A run of 30 minutes went to 13 hours. So the student pre-computes entries of a look-up table and interpolates in that table during the actual flow computations. Still, we are very grateful for the REFPROP property library because it allows us to examine the heat and mass transfer behaviour of different zeotropic binary mixtures of refrigerants easily.

**Comment by ianhbell** [comment]
C++ is another option if you care about speed. There are open-source CFD libraries in C++, for instance: https://www.openfoam.com/  

Nevertheless, I agree that the full EOS will probably be too slow.  I added tabular interpolation methods in CoolProp for just this reason: http://www.coolprop.org/coolprop/Tabular.html and other options exist.
