### ISSUE TITLE
Properties file of Iodine (I2)

### ISSUE THREAD

**Issue by JRuizT** [usnistgov/REFPROP-issues#387]
I am interested in modeling Iodine, but REFPROP does not include an .FLD file for it. In this way, I have two questions:

- Does someone know about some reference to create my own .FLD file applied to Iodine? I have in mind to take "Blackham, T.M. and Lemmon, E.W. Fundamental equation of state for isooctane" as reference for such task.

- Does someone know whether NIST would consider interesting to include it in future version of REFPROP?

Thanks in advance for your time and consideration!

**Comment by ianhbell** [comment]
I would rather than the EOS from Blackham use a more recent and well-tested EOS, perhaps the new one for one of the refrigerants.  

What is the data situation for iodine?  In order to make a multiparameter EOS, you need rather a lot of high-quality data, as well as expertise in controlling the extrapolation behavior of the EOS where no data exist (which is most of the challenge of building these models).  For that we recommend that you partner with one of the groups that is already doing this sort of work.

If we had a model for iodine that met our quality metrics, we would certainly consider to add it in REFPROP.

**Comment by JRuizT** [comment]
Many thanks for your swift reply, Ian.

Following your advice, I will take a look to the more recent EOS for refrigerants. Any reference publication to analyze as for the case of Blackham EOS? 

I am mainly interested in modeling Iodine sublimation and, afterwards, to simulate the gas through a fluid system (coupled with the thermal modeling to avoid clog formation). I fully agree with your remarks regarding both quality data and extrapolation behavior. In my case, my group has already developed methods for such extrapolation behavior. But the showstopper in my case is to have access to thermodynamic data of Iodine based on .FLD file format (or another format).

Do you think that you could have access to iodine model meeting your quality metric in the short term? 

Thanks again for your helpful comments.

**Comment by ianhbell** [comment]
This is a non-small job to make a multiparameter EOS.  Think weeks or months, not hours, to generate something of good quality.  If data is limited, what about something like PC-SAFT or a cubic EOS?  They generally behave at least ok.  

This paper gives a flavor of the kind of work that is required: https://trc.nist.gov/refprop/FAQ/R125.PDF

**Comment by JRuizT** [comment]
Many thanks for the reference and comments. 

I agree that it will take several months to generate. I was just asking in case NIST would have previous Iodine databases which could be applicable for REFPROP.

**Comment by ianhbell** [comment]
Data situation for iodine is rather poor, I took a quick glance at ThermoDataEngine.

**Comment by JRuizT** [comment]
I had mind ThermoDataEngine as the best-potential solution for obtaining this thermodynamic data (but I have no access).

Many thanks for taking a glance. According to our conversation, I think it would be so difficult to obtain this data. This topic will be a very interesting research area for the future. In case I find some references with such data in the future, I will keep you informed via Github. I would highly appreciate some feedback from your side whether you find something out in the future.

All the best,

Jorge

**Comment by nist-aharvey** [comment]
If you only care about vapor-phase properties, what is the pressure range of interest?
If you stay below 0.5 MPa or so, the ideal gas law will probably be good enough for engineering purposes.  I think it would be relatively easy to construct a REFPROP fluid file for an ideal gas -- you would only need the ideal-gas heat capacity and that could be fitted to the values given in the JANAF tables.
If your pressures get a little bit higher, then an equation at the level of the second virial coefficient could be sufficient, but I don't know offhand if those data exist for iodine. That would be a little bit of work to put into a REFPROP fluid file, but much easier than fitting a full equation of state.

**Comment by JRuizT** [comment]
Yes, my pressure range will be below 5 bar. 
I will follow the proposed approach (our internal tools are compatible with JANAF tables). For that, I will create a fluid properties file based on JANAF tables available online, following an ideal gas law. On the other hand, I will try to create a more detailed properties files based on additional data available online. I will keep you informed if I succeed in such tasks. 

Many thanks for your support.
