### ISSUE TITLE
Hydrogen thermal conductivity discrepancy between Refprop and Webbook

### ISSUE THREAD

**Issue by arnaudcharolais** [usnistgov/REFPROP-issues#389]
### Description

Looking at the thermal conductivity of hydrogen in Refprop 9.1 and the NIST Webbook website, I find it varies by up to 12%. I didn’t find any other issue resolving the problem, but it may be related to issue #376.

### Steps to Reproduce

1. Load values for hydrogen from the NIST Webbook (for example at [225 K](https://webbook.nist.gov/cgi/fluid.cgi?T=225&PLow=1&PHigh=901&PInc=20&Digits=5&ID=C1333740&Action=Load&Type=IsoTherm&TUnit=K&PUnit=bar&DUnit=kg%2Fm3&HUnit=kJ%2Fkg&WUnit=m%2Fs&VisUnit=Pa*s&STUnit=N%2Fm&RefState=DEF) or [350 K](https://webbook.nist.gov/cgi/fluid.cgi?T=350&PLow=1&PHigh=901&PInc=20&Digits=5&ID=C1333740&Action=Load&Type=IsoTherm&TUnit=K&PUnit=bar&DUnit=kg%2Fm3&HUnit=kJ%2Fkg&WUnit=m%2Fs&VisUnit=Pa*s&STUnit=N%2Fm&RefState=DEF))
2. Load the same values from REFPROP (in my case, I think is 9.1)
3. Compare

**Expected behavior:** Get the same results

**Actual behavior:** Differences between the two methods appear, increasing with the temperature

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Windows 10
**Access Method:** Python CoolProp wrapper

### Additional Information

Index | T (K) | P (bar) | lambda (Webbook) (W/m/K) | lambda (refprop) (W/m/K) | diff (refprop - Webbook)/refprop (%)
------ | ------- | -------- | --------- | ------ | -------
1 | 225 | 1 | 0.1468795 | 0.14765285 | 0.52%
2 | 225 | 21 | 0.1489713 | 0.150601804 | 1.08%
3 | 225 | 41 | 0.1510298 | 0.152989846 | 1.28%
4 | 225 | 61 | 0.1531067 | 0.155031646 | 1.24%
5 | 225 | 81 | 0.1552062 | 0.15688305 | 1.07%
6 | 225 | 101 | 0.1573289 | 0.158653637 | 0.83%
7 | 225 | 121 | 0.1594743 | 0.160417224 | 0.59%
8 | 225 | 141 | 0.1616419 | 0.16222059 | 0.36%
9 | 225 | 161 | 0.1638307 | 0.1640906 | 0.16%
10 | 225 | 181 | 0.1660398 | 0.166039898 | 0.00%
11 | 225 | 201 | 0.1682682 | 0.168071346 | -0.12%
12 | 225 | 221 | 0.1705151 | 0.170181416 | -0.20%
13 | 225 | 241 | 0.1727794 | 0.172362726 | -0.24%
14 | 225 | 261 | 0.1750602 | 0.174605888 | -0.26%
15 | 225 | 281 | 0.1773566 | 0.176900819 | -0.26%
16 | 225 | 301 | 0.1796676 | 0.179237646 | -0.24%
17 | 225 | 321 | 0.1819924 | 0.181607292 | -0.21%
18 | 225 | 341 | 0.18433 | 0.184001842 | -0.18%
19 | 225 | 361 | 0.1866795 | 0.186414739 | -0.14%
20 | 225 | 381 | 0.18904 | 0.18884085 | -0.11%
21 | 225 | 401 | 0.1914109 | 0.191276465 | -0.07%
22 | 225 | 421 | 0.1937912 | 0.193719232 | -0.04%
23 | 225 | 441 | 0.1961802 | 0.196168057 | -0.01%
24 | 225 | 461 | 0.1985772 | 0.198622985 | 0.02%
25 | 225 | 481 | 0.2009816 | 0.201085074 | 0.05%
26 | 225 | 501 | 0.2033926 | 0.203556263 | 0.08%
27 | 225 | 521 | 0.2058096 | 0.20603925 | 0.11%
28 | 225 | 541 | 0.2082322 | 0.208537366 | 0.15%
29 | 225 | 561 | 0.2106597 | 0.211054469 | 0.19%
30 | 225 | 581 | 0.2130917 | 0.213594842 | 0.24%
31 | 225 | 601 | 0.2156126 | 0.2161631 | 0.25%
32 | 225 | 621 | 0.2197397 | 0.218764113 | -0.45%
33 | 225 | 641 | 0.2238501 | 0.221402932 | -1.11%
34 | 225 | 661 | 0.2279438 | 0.224084726 | -1.72%
35 | 225 | 681 | 0.2320207 | 0.226814736 | -2.30%
36 | 225 | 701 | 0.236081 | 0.22959822 | -2.82%
37 | 225 | 721 | 0.2401248 | 0.232440423 | -3.31%
38 | 225 | 741 | 0.2441521 | 0.235346539 | -3.74%
39 | 225 | 761 | 0.248163 | 0.238321687 | -4.13%
40 | 225 | 781 | 0.2521578 | 0.241370889 | -4.47%
41 | 225 | 801 | 0.2561366 | 0.244499053 | -4.76%
42 | 225 | 821 | 0.2600995 | 0.247710956 | -5.00%
43 | 225 | 841 | 0.2640469 | 0.251011239 | -5.19%
44 | 225 | 861 | 0.2679788 | 0.254404393 | -5.34%
45 | 225 | 881 | 0.2718956 | 0.257894758 | -5.43%
46 | 225 | 901 | 0.2757974 | 0.261486517 | -5.47%
47 | 350 | 1 | 0.210323 | 0.20968734 | -0.30%
48 | 350 | 21 | 0.2117453 | 0.211903211 | 0.07%
49 | 350 | 41 | 0.2131138 | 0.213742215 | 0.29%
50 | 350 | 61 | 0.2144847 | 0.215302188 | 0.38%
51 | 350 | 81 | 0.2158644 | 0.216662264 | 0.37%
52 | 350 | 101 | 0.2172547 | 0.217885904 | 0.29%
53 | 350 | 121 | 0.2186567 | 0.219023467 | 0.17%
54 | 350 | 141 | 0.2200709 | 0.220114415 | 0.02%
55 | 350 | 161 | 0.2214974 | 0.221189186 | -0.14%
56 | 350 | 181 | 0.2229365 | 0.222270796 | -0.30%
57 | 350 | 201 | 0.2243882 | 0.223376204 | -0.45%
58 | 350 | 221 | 0.2258525 | 0.224517461 | -0.59%
59 | 350 | 241 | 0.2273294 | 0.225702681 | -0.72%
60 | 350 | 261 | 0.2288188 | 0.226936856 | -0.83%
61 | 350 | 281 | 0.2303207 | 0.228222534 | -0.92%
62 | 350 | 301 | 0.2318349 | 0.229560384 | -0.99%
63 | 350 | 321 | 0.2333614 | 0.230949659 | -1.04%
64 | 350 | 341 | 0.2349 | 0.23238858 | -1.08%
65 | 350 | 361 | 0.2364505 | 0.233874644 | -1.10%
66 | 350 | 381 | 0.2380128 | 0.235404877 | -1.11%
67 | 350 | 401 | 0.2395868 | 0.236976036 | -1.10%
68 | 350 | 421 | 0.2411723 | 0.238584766 | -1.08%
69 | 350 | 441 | 0.242769 | 0.240227731 | -1.06%
70 | 350 | 461 | 0.2443768 | 0.241901705 | -1.02%
71 | 350 | 481 | 0.2459956 | 0.243603651 | -0.98%
72 | 350 | 501 | 0.2476251 | 0.245330768 | -0.94%
73 | 350 | 521 | 0.2492651 | 0.247080536 | -0.88%
74 | 350 | 541 | 0.2509154 | 0.248850738 | -0.83%
75 | 350 | 561 | 0.2525759 | 0.250639475 | -0.77%
76 | 350 | 581 | 0.2542463 | 0.252445174 | -0.71%
77 | 350 | 601 | 0.2560486 | 0.254266586 | -0.70%
78 | 350 | 621 | 0.260178 | 0.256102783 | -1.59%
79 | 350 | 641 | 0.2643062 | 0.257953148 | -2.46%
80 | 350 | 661 | 0.2684328 | 0.259817365 | -3.32%
81 | 350 | 681 | 0.2725576 | 0.261695401 | -4.15%
82 | 350 | 701 | 0.2766804 | 0.263587496 | -4.97%
83 | 350 | 721 | 0.280801 | 0.265494141 | -5.77%
84 | 350 | 741 | 0.2849192 | 0.267416063 | -6.55%
85 | 350 | 761 | 0.2890347 | 0.269354212 | -7.31%
86 | 350 | 781 | 0.2931476 | 0.271309734 | -8.05%
87 | 350 | 801 | 0.2972575 | 0.273283964 | -8.77%
88 | 350 | 821 | 0.3013644 | 0.275278405 | -9.48%
89 | 350 | 841 | 0.3054681 | 0.27729471 | -10.16%
90 | 350 | 861 | 0.3095685 | 0.279334671 | -10.82%
91 | 350 | 881 | 0.3136656 | 0.281400201 | -11.47%
92 | 350 | 901 | 0.3177591 | 0.283493324 | -12.09%

**Comment by ianhbell** [comment]
I believe the implemented models are not the same. The webbook uses a rather old version of REFPROP behind the scenes

# Metadata from the webbook

Equation of state and auxiliary model
Leachman, J.W.; Jacobsen, R.T.; Lemmon, E.W., Fundamental Equations of State for Parahydrogen, Normal Hydrogen, and Orthohydrogen, to be published in J. Phys. Chem. Ref. Data, 2008. [all data]

Auxiliary model and surface tension
McCarty, R.D.; Hord, J.; Roder, H.M., Selected Properties of Hydrogen (Engineering Design Data), NBS Monograph 168, National Bureau of Standards, Boulder, CO, 1981, 0. [all data]

Thermal conductivity and dielectric constant
Kunz, O.; Klimeck, R.; Wagner, W.; Jaeschke, M., The GERG-2004 Wide-Range Reference Equation of State for Natural Gases and Other Mixtures, to be published as a GERG Technical Monograph, Fortschr.-Ber. VDI, VDI-Verlag, Düsseldorf, 2006. [all data]

Additional Information
Equation of state
The uncertainty in density is 0.1% at temperatures from the triple point to 250 K and at pressures up to 40 MPa, except in the critical region, where an uncertainty of 0.2% in pressure is generally attained. In the region between 250 and 450 K and at pressures from 0.1 to 300 MPa, the uncertainty in density is 0.04%. At temperatures between 450 and 1000 K, the uncertainty in density increases to 1%. At pressures between 300 and 2000 MPa, the uncertainty in density is 8%. Speed of sound data are represented within 0.5% below 100 MPa. The estimated uncertainty for heat capacities is 1.0%. The estimated uncertainties of vapor pressures and saturated liquid densities calculated using the Maxwell criterion are 0.2% for each property.

Thermal conductivity
The uncertainty in thermal conductivity below 100 K is estimated to be 3% below 150 atm and up to 10% below 700 atm. For temperatures around 100 K at low densities, the uncertainty is about 1%. Above 100 K, the uncertainty is estimated to be on the order of 10%.

Viscosity
The uncertainty in viscosity ranges from 4% to 15%.

# And from REFPROP 10:

Assael, M.J., Assael, J.-A.M., Huber, M.L., Perkins, R.A., and Takata, Y.,
 "Correlation of the Thermal Conductivity of Normal and Parahydrogen
 from the Triple Point to 1000 K and up to 100 MPa,"
 J. Phys. Chem. Ref. Data, 40(3), 033101, 2011.

The estimated uncertainty is less than 4% from 100 K to 1000 K at pressures to 100 MPa.
 For temperatures from the triple point to 100 K, at pressures
 to 12 MPa, we estimate the uncertainty to be 7%, except near the critical point.
 The model behaves in a physically reasonable manner for extrapolations to pressures above
 12 MPa at temperatures below 100 K, but will be subject to larger uncertainties.

**Comment by arnaudcharolais** [comment]
Thank you ianhbell for your quick answer.

I will consider the Refprop values then.

Have a nice day.
