### ISSUE TITLE
Pressure range of Acetylene in REFPROP 10

### ISSUE THREAD

**Issue by FaisalUOA** [usnistgov/REFPROP-issues#390]
Hello, 

I need to study the phase diagram of acetylene at lower temperatures (-70C & lower) and lower pressures (20 Torr and below). Unfortunately REFPROP v9 doesn't have acetylene in it and thus we are considering to upgrade to v10. Could you please let me know what's the minimum pressure of acetylene that can studied in the REFPROP v10?

Thanks.

**Comment by ianhbell** [comment]
In the gas phase you could go to zero pressure. You might need to specify the phase, but the EOS is valid to the ideal-gas limit of zero pressure.  At such a low pressure, the ideal gas law is pretty acceptable too.
