### ISSUE TITLE
CO2 and water mixture problems

### ISSUE THREAD

**Issue by AsimmWood** [usnistgov/REFPROP-issues#392]
Hi,

I am trying to model a CO2, hydrocarbon and water mixture to calculate critical pressure and temperature and plot a PT diagram with lines of entropy using version 9.1.

If I omit water I can correctly model the below mixture:

CO2 0.956, N2 0.01, Ar 0.01, CH4, 0.011599, H2, 0.01, O2 0.0000001, CO 0.002, H2S 0.0004

This gives me (using GERG 2008 option)

Critical Pressure 8.3011 MPa
Critical Temperature 302.68 oK

I also get a nice PT plot with the defined 2 phase region and entropy lines I need plotted.

However I also want to add a small amount of H20 to the above spec  and this is where I have issues, if I add just 0.0004 mol frac H20 to the above spec (deducting from CH4 to normalise to 1), my critical point is not being calculated and my PT plot starts ok but then seems to give up.

Is this a software bug or am I missing something fundamental about H20, I understood that it is included as one of the 20 or so specifies considered in the GERG 2008 equations?

Cheers

Andy

**Comment by ianhbell** [comment]
Yes, even without the GERG model, I also get a similar sort of behavior. In short, adding very different components (water, helium, etc.) to the mixture can dramatically alter the behavior of the mixture, even when you add tiny amounts of them.  This is a well-known issue.

```python
import matplotlib.pyplot as plt
import pandas
import numpy as np

from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
import CoolProp.CoolProp as CP

root = 'C:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, root)

def isopleth_via_REFPROP(comps, z_mole, callback=None):
    """ From https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb#Flash-Calculations """
    # Obtain the isopleth data
    # ---
    # Set up the fluids we want
    r = RP.SETFLUIDSdll('*'.join(comps))
    if r != 0: print(RP.ERRMSGdll(r)); return
    # Construct the saturation spline
    print(RP.SATSPLNdll(z_mole))
    # Now we programatically extract the nodes of the isopleth...
    Nnodes = RP.REFPROPdll("","SPLINENODES","",0,0,0,0,0,z_mole).iUCode
    data = []
    for i in range(1,Nnodes+1):
        rho_vap,T,p,rho_eq,z0,z1 = RP.REFPROPdll("","SPLINENODES","",0,0,i,0,0,z_mole).Output[0:6]
        data.append(dict(rho_vap = rho_vap,T=T,p=p,z0=z0,z1=z1))
    # Convert the data points into a pandas DataFrame
    df = pandas.DataFrame(data)

    # And plot them...
    plt.plot(df['T'],df.p,'o-')
    plt.yscale('log')
    plt.xlabel('T [K]')
    plt.ylabel('p [kPa]')
    if callback: callback()
    plt.show()

def isopleth_via_CoolProp(comps, z_mole, callback=None):
    """ Values are interpolated from splines """
    AS = CP.AbstractState('REFPROP', '&'.join(comps))
    AS.set_mole_fractions(z_mole)
    AS.build_phase_envelope("")
    PE = AS.get_phase_envelope_data()
    if callback: callback()

    # And plot them...
    plt.plot(PE.T, np.array(PE.p)/1e3, 'o-')
    plt.yscale('log')
    plt.xlabel('T [K]')
    plt.ylabel('p [kPa]')
    plt.show()

comps = ['CO2','N2','Ar','METHANE','H2','O2','CO','H2S']
z = [0.956,0.01,0.01,0.011599,0.01,0.0000001,0.002,0.0004]

# isopleth_via_REFPROP(comps, z)
# isopleth_via_CoolProp(comps, z)

def add_water(z_H2O):
    new_comps = comps + ['H2O']
    new_z = z + [z_H2O]
    return new_comps, new_z/np.sum(new_z)

for z_H2O in np.geomspace(1e-6, 1e-1, 8):
    newcomps, newz = add_water(z_H2O)
    def callback():
        plt.title(fr'$z_{{\rm water}}$: {z_H2O} mole frac.')
        r = RP.REFPROPdll('','','TC;PC',RP.MOLAR_BASE_SI, 0,0,0,0,newz)
        print(r.ierr, r.herr)
        Tc, pc = r.Output[0:2]
        plt.plot(Tc, pc/1e3, '*')
    isopleth_via_REFPROP(newcomps, newz, callback=callback)
```

**Comment by AsimmWood** [comment]
Ian,

Is there a solution to this problem? Does V10 work any better?

Cheers

Andy

**Comment by ianhbell** [comment]
My example was in REFPROP 10, unfortunately.  Mixtures need not have critical points, that is a thermodynamic reality.

**Comment by AsimmWood** [comment]
Thanks, apologies I am actually Physical Chemist originally but have spent my entire career in Corrosion Engineering so its not an area I have a huge experience in.

I would like to calculate the maximum "saturation pressure" in the event of a decompression that a CO2 pipeline could experience when it is operating in the supercritical or liquid phase region. By saturation pressure I mean in the event of a rupture the sustained pressure that could be maintained by a pipeline as it decompresses at the liquid/gas phase boundary. The pressure should drop very quickly following a rupture until this phase boundary is reached at which point it will sustain a high pressure for a long period until the full liquid inventory in the pipeline is exhausted.

As a worst case this pressure could not be higher than the critical pressure of the mixture. So you are saying that if a tiny amount of water was added my pipeline would not actually operate in a super critical phase? The design basis of the project is that operation will be super critical.

Adding water to liquid CO2 pipelines doesn't entirely make sense not least from a corrosion perspective no liquid water is tolerable and upstream processes to remove all traces of water are extensive for these reasons, its very possible that this is a default design value of moisture for a Hydrocarbon gas pipeline that has been specified on a datasheet in a copy and paste exercise.

Cheers

Andy

**Comment by ianhbell** [comment]
If I understand correctly, I think what you actually want then is the maximum pressure of the isopleth of the phase envelope, which is not the critical point (in general). Of course, another nasty challenge here is the potential for solid formation, which is not currently handled in REFPROP.  You could, with a relatively small amount of work, consider the solid EOS for CO2, and compare the chemical potential of CO2 in the mixture to the Gibbs energy of pure solid CO2 phase at the same temperature and pressure, and see whether solid CO2 is expected to be formed.

**Comment by AsimmWood** [comment]
Thanks, yes sorry, for pure CO2 (at least to my understanding) it would be the critical point which is the maximum pressure on the phase envelope which is essentially a very defined boundary line.

The impurities in a CO2 mixture seem to change the shape of the phase envelope and create a large 2-phase region, for my above mix (excluding H2O) the low temperature side of the phase envelope does appears to be equivalent or possibly higher than the critical pressure, so the critical pressure might not be worst case in that example.

However, typically these pipelines operate just above the critical pressure and temperature so a decompression is more likely to land on a phase boundary close or just below the critical point.

Thanks for your help, its a complex area!

**Comment by ianhbell** [comment]
Yes, mixtures are in many ways not at all like pure fluids.  Some intuition maps directly, but there are many things that are simply just not the same.  Another question of course is whether the mixture model we use is actually accurate for the pipeline conditions you are considering.  Probably the answer is yes, but we have very limited multicomponent data for mixtures containing water to validate our models and phase equilibria predictions.

**Comment by AsimmWood** [comment]
Ian, the operating conditions and decompression path are within the published validity range of the GERG-2008 EOS. So if I select that option in REFPROP and only select from GERG-2008 fluids am I not OK? Or is RefProp doing something more than just the GERG-2008 equations?

**Comment by EricLemmon** [comment]
Look at the comments here, that might help understand what Refprop is doing:

https://github.com/usnistgov/REFPROP-issues/issues/343

**Comment by EricLemmon** [comment]
Were the comments in #343 helpful?  Do you need further assistance?  If not, could you close this issue?
