### ISSUE TITLE
Enthalpy of Formation from REFPROP (SuperTrapp uses it as reference enthalpy)

### ISSUE THREAD

**Issue by hanchak** [usnistgov/REFPROP-issues#393]
### This question was already answered by Ian Bell through email. However, I wanted to post it here for pedagogy
 
I noticed that in SuperTrapp, the reference enthalpy is the enthalpy of formation of the substance, which is helpful when building reactions in Fluent. In REFPROP 9.1, several reference enthalpies are possible.
 
Question: how do I get calculate the enthalpies of formations solely in REFPROP?
 
Thank you, Mike 
* REFPROP 9.1
* SUPERTRAPP 3.2.1
* Windows 10

### Ian's response

In this case, the short answer is no, not natively.  You could certainly use the SETREF function to set the reference state to your desired reference enthalpy.

Best,
Ian

### follow-up for the audience

Other than NIST Webbook and supertrapp, does anyone else have a free resource for enthalpy of formation data? Or, is there a way to compute from REFPROP EoS?

**Comment by ianhbell** [comment]
I think my colleague Marcia also answered this point, but I'll put the response here for pedagogical purposes: 

You can obtain the heat of formation by selecting the menu item "options", then "properties" then select the tab "transport, Misc." and then check the box for "heat of formation".

![Image_2021-03-24_11-56-26](https://user-images.githubusercontent.com/11966765/112363767-3cf6c180-8cac-11eb-8fd8-b4ea8e359da8.png)

With that in concert with SETREF you could force the reference states to match those of SuperTRAPP.
