### ISSUE TITLE
Unable to locate equation of state paper for Ammonia in "Journal of Physical and Chemical Reference Data"

### ISSUE THREAD

**Issue by NikoBiele** [usnistgov/REFPROP-issues#396]
Hi NIST,

I really appreciate your work with REFPROP, and think it is a great program. I am using REFPROP 10 (DLL version 10.0.0.02).

Today I got curious and wanted to take a look at the referenced paper for the equation of state for Ammonia.
However I was unable to locate the referenced study. Has it not been published yet?
I have acces to the journal through my university.
I also looked in CoolProp which references the same paper, but instead it says it was published in 2020.
Again I was unable to locate the paper. I have also looked in the FAQ and couldn't find any info on this.

No search result:
![image](https://user-images.githubusercontent.com/71772461/113714767-0af05100-96e9-11eb-83a8-8ced48cf9e78.png)

REFPROP:
![ScreenshotREFPROP](https://user-images.githubusercontent.com/71772461/113714223-77b71b80-96e8-11eb-80a0-a6bb282879b7.PNG)

CoolProp:
![ScreenshotCoolProp](https://user-images.githubusercontent.com/71772461/113714290-869dce00-96e8-11eb-8e2f-c5380682591a.PNG)

Kind regards Nikolaj Maack Bielefeld, Denmark

**Comment by ianhbell** [comment]
You are correct - the paper is under way, but not yet published.

**Comment by NikoBiele** [comment]
Thank you for the quick reply, I will close the issue then.
