### ISSUE TITLE
Add mixture parameters from the work of Beckmueller

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#398]
For H2 + X

**Comment by ianhbell** [comment]
This was done in May. Paper is published now: https://aip.scitation.org/doi/abs/10.1063/5.0040533

**Comment by MpdGit** [comment]
Dear Dr. Bell,

I'm new to REFPROP and I'd like to add new mixture parameters from Beckmueller to describe the H2 + N2 system. I could not find the hmx.bnc in the supplementary material of the paper. Could you help me where I can find it?
Thanks a lot for your time and help!

Best regards

**Comment by ianhbell** [comment]
That's true, we put it together, but didn't include it.  We have an updated HMX.BNC with the model  (and all the other ones) I can send you; please email me at ian.bell@nist.gov
