### ISSUE TITLE
Bug in PH flash for water; returns temperatures far below the triple point

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#40]
See bug reported in CoolProp : https://github.com/CoolProp/CoolProp/issues/1724

This is a bug in REFPROP, not CoolProp

**Comment by EricLemmon** [comment]
Refprop 10.0 found a solution at a temperature far below that valid for water, but which met all criteria as a valid state point (due to the behavior of the equation of state outside its region of validity). Please contact us directly at Eric.Lemmon@nist.gov for an updated DLL.

**Comment by EricLemmon** [comment]
See #67 for more information.
