### ISSUE TITLE
Alternate R1234ZE(E) model in Excel Plugin

### ISSUE THREAD

**Issue by graubergera** [usnistgov/REFPROP-issues#404]
I need to use the Alt. model FE3 for helmholtz equations of state for R-1234ZE(E) in the REFPROP 10 Excel plugin and cannot determine how to do this. Any help would be greatly appreciated

**Comment by ianhbell** [comment]
Do you have to use Excel?  It's easy in Python:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
RP.SETMODdll(1,'EOS','HMX','FE2')
print(RP.SETFLUIDSdll('R1234ZEE'))
print(RP.GETMODdll(1,'EOS'))
```
yielding
```
0
GETMODdlloutput(hcode='FE2', hcite='FE2     !Helmholtz equation of state for R-1234ze(E) of McLinden et al. (2010).')
```

**Comment by ianhbell** [comment]
Docs here: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETMODdll

**Comment by graubergera** [comment]
I have a data reduction model built into Excel that I would like to avoid rebuilding elsewhere.

**Comment by ianhbell** [comment]
It's hard to get this right in Excel because calculations happen in whatever order Excel decides, rather than the order you would like.  Setting global state like this is not easy in Excel.

**Comment by dny530** [comment]
Hi there, I'm a colleague of graubergera. We're using Refprop 9.1 with excel to perform some fluid property calcs for a test facility we've collecting a bunch of data on. We want to use the Akasaka EOS for R1234ze(E) when running these calculations, but can't seem to get Excel to use a non-default EOS. The Akasaka EOS is labeled as 'FE3' in the Refprop application. 

So far, I'm going into Module 1 on the VB project window and then editing the block of code that starts with "Set up pure fluids". In your comments, you've specifically called out how to change the EOS by using the SETMOD call, but I can't seem to get it to work. This is what that block now looks like, where the changes are bolded:

'Set up pure fluids
  Else
    nc2 = 1
    If InStr(LCase(FluidName), ".fld") = 0 And InStr(LCase(FluidName), ".ppf") = 0 Then FluidName = FluidName + ".fld"
    If InStr(FluidName, "\") Then
      hfld = FluidName
    Else
      hfld = FluidsPrefix & FluidName
    End If
    '...Use call to SETMOD to change the equation of state for any of the
    '.....pure components from the default (recommended) values.
    '.....This should only be implemented by an experienced user.
    **If InStr(LCase(hfld), "R1234ze") <> 0 And nc2 = 1 Then
      hcomp = "FE3": htype = "EOS": hmix = hcomp
      Call SETMODdll(nc2, htype, hmix, hcomp, ierr, herr, 3&, 3&, 60&, 255&)
    End If**
    Call SETUPdll(nc2, hfld, hfmix, hrf, ierr, herr, 10000&, 255&, 3&, 255&)
    If ierr > 0 Then hfld = ""
  End If
  hfldOld = hfld 

It seems straight forward, but this doesn't work! Any ideas on how I could make this work? I appreciate your help. If there's a workaround, we're open to that -- such as creating a new fluid file with the Akasaka EOS?

**Comment by ianhbell** [comment]
What does "doesn't work" mean?  Screenshots maybe?  

One point: you have the wrong fluid name.  It should be R1234ZEE (note the last E)

Recommend to:
1) check ierr (always!!)
2) call ``GETMODdll`` after ``SETUPdll`` to make sure your change took.

I agree, a separate FLD file might be the move.  Save ``R1234ZEE.FLD`` somewhere else and flip the default and Akasaka EOS.  Recommend to not put it in the ``FLUIDS`` directory, instead to pass absolute path to the file.

Also, recommend to upgrade to REFPROP 10, some of this stuff works better with v10.

**Comment by EricLemmon** [comment]
I just set this up for you.  Download the attached file, remove the ".txt" extension and then all should work, hopefully!

(see further below for file)

**Comment by EricLemmon** [comment]
P.S.  This is the 9.1 version of the fluid file, but it will also work in Version 10.

**Comment by graubergera** [comment]
This new fluid file does the trick on Versions 9.1 and 10. Thank you both for your help!

**Comment by dny530** [comment]
That worked perfectly! Thanks so much Eric and Ian. It's great that it will work in both 9.1 and 10, as I'm running 9.1 and graubergera is running in 10.

**Comment by ianhbell** [comment]
Make sure you rename to R1234ZEE...  (otherwise you could run into trouble with R1234ZEZ down the road).

**Comment by EricLemmon** [comment]
That's an extremely important point that I forgot to do.  I deleted the file above, renamed it, and attached it here.  Please update the file you downloaded early today with this one.

[R1234ZEE_with_FE3model.FLD.txt](https://github.com/usnistgov/REFPROP-issues/files/6360672/R1234ZEE_with_FE3model.FLD.txt)
