### ISSUE TITLE
Saturated liquid properties for Carbon Dioxide (CO2) near critical temperature

### ISSUE THREAD

**Issue by HarrisonSkye** [usnistgov/REFPROP-issues#408]
### Description

Unable to compute saturated liquid properties of Carbon Dioxide (CO2) at temperature=303.899 K.  

### Steps to Reproduce

1. Call REFPROP from Matlab (or REFRPOP GUI) for Carbon Dioxide with Q = 0, T  = 303.899 K

**Expected behavior:** [What you expect to happen]

I expected REFPROP to compute the thermal conductivity at this condition.

**Actual behavior:** [What actually happens]

Get error: "[SATT error 124] Iteration for saturation state did not converge for T = 303.899 K."  I get the same error in MATLAB and the REFRPOP GUI.

### Versions

**REFPROP Version:**10.0
**Operating System and Version:** Windows 10
**Access Method:** MATLAB (via Python), and the REFPROP GUI

### Additional Information

1. REFPROP (in Matlab and REFPROP GUI) successfully calculate the saturated liquid properties at 303.900 K and 303.898 K, but not 303.899 K.  

2. I tried activating the SATSPLN function by giving the RP.REFPROPdll an "iFlag" value of 1, but I still get the same error.  I couldn't figure out how to activate SATSPLN in the REFPROP GUI.  I tried the SATSPLN after reading about the known difficulty of calculating saturation properties in the critical region, per https://pages.nist.gov/REFPROP-docs/#calculation-of-the-critical-point-and-saturation-states-in-the-critical-region

![RP error](https://user-images.githubusercontent.com/61206232/120019836-eb71f800-bfb6-11eb-9580-0c58afe4ef77.jpg)

![RP_ML error](https://user-images.githubusercontent.com/61206232/120020100-46a3ea80-bfb7-11eb-82bf-d8a027726fd6.png)

**Comment by ianhbell** [comment]
When you get close to the critical point (304.13 K in this case), all kinds of things become more challenging, especially for CO2 and water with the non-analytic terms.  How precise does the value need to be?  If not too, too precise, you could use the derivative drho/dT along saturation to patch in the critical region where you have failures.  But I would have thought you are far away enough to not have problems with this.

**Comment by HarrisonSkye** [comment]
Calculation stability is much more important here than precision.  I'd easily settle for 2 % error (probably more if I spent more time figuring out how important the error is here) if it meant the calculation was successful. This error was encountered as the program is iterating to find equilibrium state for a whole refrigeration system, so it is likely that this particular thermodynamic state won't even be in the final value.

In the end, I'm trying to get the following properties at this thermodynamic state: conductivity, Prandtl number, viscosity, density liquid, density vapor, specific heat, surface tension, heat of vaporization.

Can you elaborate what you mean by "use the derivative drho/dT along saturation to patch in the critical region"?  I don't see drho/dT as a property output for the REFPROP DLL.  Are you suggesting I calculate this derivative myself outside of REFPROP? My inputs to "refprop.m" are quality and temperature.  I would have guessed to calculate the value of the property at some safe saturation temperature (say 303.50 K), then take the derivative with respect to saturation temperature and project out to my actual saturation temperature.  E.g. for liquid viscosity at saturation temperature "T" I would use: mu = mu(Q=0,T=303.50) + (mu(Q=0,T = 303.51)-mu(Q=0,T=303.50))/(303.51-303.50)*(T-303.50).  Is that what you mean?

**Comment by ianhbell** [comment]
Well, the quick-and-dirty solution is to use a temperature where the calculation succeeds (say 303.8 K), and linearly interpolate the saturated liquid and vapor densities between that point and the critical density. Not perfect, but works ok. Then for the given temperature and density, you can evaluate properties without a phase equilibrium calculation by specifying the phase to be liquid or vapor and providing temperature and density.

CoolProp uses splines in the critical region, which largely solve this problem. Explained around Eqs. 18-20 from here: dx.doi.org/10.1021/ie4033999

**Comment by HarrisonSkye** [comment]
Thanks for the response and paper link!  I'm able to calculate density, but I'm still having trouble computing transport properties because MATLAB gives me an error when calling REFPROP: "[REFPROP error 810] One or more of the input properties is not thermophysically defined for two-phase states and cannot be
calculated."  I also get an "undefined" error in the REFPROP GUI when calculating transport properties using the temperature-density values from my cubic spline. You suggested to "specify the phase to be liquid or vapor and provide temperature and density".....but I can't specify the phase using the "refpropm.m" function call in MATLAB.  Do you have suggestions for what to do next?

As feedback on the saturated liquid density calculation, I tried the linear interpolation, and also a cubic spline constrained per Eqs. 18-21 of the I&EC journal paper you suggested.  I also put EES properties just for fun.  The linear interpolation gave about 3 % error in saturated liquid density at 303.899 K. The largest error was 6 %, for 304.02 K.  The cubic spline was nearly identical to REFPROP and EES.  I used T_end=Tcrit-0.3 = 304.128-0.3 = 303.828 K as my "safe" temperature, where REFPROP calculations were stable.  Importantly, the cubic interpolation was stable and reliable for calculating the density.

![image](https://user-images.githubusercontent.com/61206232/120549602-d08df200-c3c1-11eb-81e3-fb3555d29678.png)

![image](https://user-images.githubusercontent.com/61206232/120549945-3b3f2d80-c3c2-11eb-935a-4a1fc0c418d9.png)


![image](https://user-images.githubusercontent.com/61206232/120547454-26ad6600-c3bf-11eb-8cc2-d5764c8d9614.png)

**Comment by ianhbell** [comment]
One part of the answer is to upgrade to the Python interface in MATLAB instead of refpropm.  There you can specify the phase (among many other new capabilities).

I think the cubic spline approach is a solid one. If you want to really overkill this problem, I could build you a superancillary equation (https://link.springer.com/article/10.1007/s10765-021-02824-x), though one challenge is that the EOS for CO2 is non-analytic at the critical point, and I haven't fought with that particular bedeviling feature yet when building superancillary curves. I think it should still be ok, but I might need a bit of reworking.

**Comment by HarrisonSkye** [comment]
To clarify, I believe the "refpropm.m" file I'm using _does_ use the Python interface;  it is a "new" refpropm.m that Nate Kamphius wrote for me to make my old MATLAB code (written for REFPROP 9) work with REFPROP 10.

If I specify the saturated liquid density (calculated for T=303.899 K using the previously mentioned cubic spline) and quality=0, Matlab happily returns the viscosity, etc.  This worked, where my previous attempt to specify temperature and density failed [Error 810] since the values corresponded to a 2-phase regime and REFPROP couldn't calculate the corresponding properties.

To summarize, the root issue here is that REFPROP doesn't converge for CO2 saturated liquid at T=303.899 K.  This occurs regardless of using the REFPROP GUI or the MATLAB call to the Python REFPROP wrapper.  Enabling the SATSPLN function does not improve convergence. REFPROP does converge for saturated liquid at T=303.898 K and 303.900 K, and for much of the region between 303.900 K and 304.1282 (critical temperature). My successful workaround options to compute saturated liquid properties at 303.899 K are: (1) average the saturated liquid properties at 303.898 K and 303.900 K, or (2) construct a cubic spline for rho-T near-critical region per my earlier comments, use the spline to compute the saturated liquid density, then get the properties by calling REFPROP (via Matlab-Python interface) with input of density and quality=0.  Option 1 is simpler to implement in code, so I will use it unless I find many other saturated liquid temperatures where REFPROP can't converge.

Your superancillary equations sound really neat...but I don't think it's worth your time since I've got acceptable workarounds.

![image](https://user-images.githubusercontent.com/61206232/120657476-856fef80-c452-11eb-91e6-8e150411bbf3.png)

**Comment by ianhbell** [comment]
I think the cubic spline is your best bet. You'll need to ask Nathan to modify his wrapper to allow for specification of the phase. If you do that, I think you should be in business.

**Comment by HarrisonSkye** [comment]
Ok, thanks for the feedback about the cubic spline.

Nathan's wrapper already allows for specification of phase, since I can specify density "D" and quality "Q" and get a result (the Matlab wrapper sends "DQ" input to the Python wrapper in that case).  Is that what you mean?  Or are you referring to some other method to specify phase?

**Comment by ianhbell** [comment]
Not exactly; I mean you want to have TD inputs (from the spline) and then use those as inputs and require that no phase determination is carried out so REFPROP thinks the inputs are homogenous, even if they are metastable (in 0 < Q < 1) .  See https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll , look for ``**L``

**Comment by HarrisonSkye** [comment]
Ok that makes sense.  I was able to do that by specifying "DL" rather than "D" as the 2nd input.

>>viscosity=refpropm('V','T',303.898,'DL',543.584,'CO2')

![image](https://user-images.githubusercontent.com/61206232/120681919-e3f49800-c469-11eb-98ed-5a70cff4a893.png)

**Comment by ianhbell** [comment]
I'm guessing the wrapper concatenates the property keys, so that makes sense why that would work.

**Comment by HarrisonSkye** [comment]
Ok, thanks for all the help Ian!  I will close the thread.

**Comment by EricLemmon** [comment]
I looked into the root cause of this problem and found that the equation of state for CO2 has a little wiggle in the liquid phase for temperatures near the critical point.  This "little" wiggle turns out to be a big thing in the search for the liquid spinodal.  The picture below shows the behavior for 303.899 K, 303.900K, and 303.901 K.  At densities near the liquid spinodal, there should be only one point with zero slope, and the curvature should be positive everywhere.  For CO2, there are two locations with zero slope and a small region with negative curvature.  At 303.899 K, the routine failed because the iterative solver was stuck searching for the root at densities near the upper location with zero slope.  I added a line that checked for this when the number of iterations became excessive.  The check dropped the density by 2.5%, which put it in the region where it could quickly converge to the correct root.  This will probably help with similar problems in other fluids.

If you would like the fix, please let send both Ian and me a private email:  Ian.Bell@nist.gov and Eric.Lemmon@nist.gov


![image](https://user-images.githubusercontent.com/42392984/120940029-46eb6680-c6d8-11eb-82a9-b4630bad95d6.png)

**Comment by HarrisonSkye** [comment]
Eric - thanks for looking at this issue in detail!  I can see how the "wiggle" results in convergence problems.  I will send you an email for the code with the "fix".
