### ISSUE TITLE
need of new ammonia fluid file (ammoniaL.FLD)

### ISSUE THREAD

**Issue by hosseinmonsefi** [usnistgov/REFPROP-issues#409]
Hi, I'm modeling kalina cycle in MATLAB with coupling of REFPROP. The problem is the ammonia model I'm using doesn't work very well and in many points give me the dew point error. In a tutorial video I saw that there is a new model of ammonia which is ammoniaL.FLD which is written by Eric Lemmon and fixed this kind of errors. I wanna see does any of you have that fluid files to share? Thanks a lot

**Comment by ianhbell** [comment]
What version of REFPROP do you have?  In REFPROP 10.0 we have a new ammonia+water model that works with the normal ammonia fluid file.

**Comment by hosseinmonsefi** [comment]
> What version of REFPROP do you have? In REFPROP 10.0 we have a new ammonia+water model that works with the normal ammonia fluid file.

actually, I have v8. I tried v9.1 (mini) as well but it didn't work and the same error happened.

**Comment by ianhbell** [comment]
Yeah, I'd recommend first to upgrade to version 10.0

**Comment by hosseinmonsefi** [comment]
The problem is upgrading to v10 for me which I'm a student is costful.

**Comment by EricLemmon** [comment]
Can you send me a personal email?  Eric.Lemmon@nist.gov

**Comment by Serein233333** [comment]
Hi, I was wondering if you have found the AMMONIAL.FLD file? I am also a student in school, and I met the same problem as you. When using refprop9.1 to obtain the properties of ammonia-water, I always get an error message like "did not converge in two-phase iteration". If you find this file, would you be so kind to send it to me? Thank you very much

**Comment by ianhbell** [comment]
Please email me at ian.bell@nist.gov and I can send you the file
