### ISSUE TITLE
Calling PSFLSH to calculate natural gas at 9MPa, 3.15kJ/(kg·K) showed PSFLSH calculate error 248, bubble point did not converge, SATP error 148, iteration did not converge

### ISSUE THREAD

**Issue by OneNoobForAll** [usnistgov/REFPROP-issues#411]
### Description

[Calling PSFLSH to calculate natural gas at 9MPa, 3.15kJ/(kg·K) showed PSFLSH calculate error 248, bubble point did not converge, SATP error 148, iteration did not converge]

### Steps to Reproduce

1. [Set the natural gas composition that have water , helium, H2S etc ]
2. [Call PSFLSH to get other properties by setting P 9000 and S 3.15*21.35 ]
3. [the ierr show 248, the herr show PSFLSH calculate error 248, bubble point did not converge, SATP error 148, iteration did not converge]

**Expected behavior:** [calculate the properties at unstable state, iteration at spinodal curve]

**Actual behavior:** [calculate error and no other properties show]

### Versions

**REFPROP Version:** [DLL version 9.1]  
**Operating System and Version:** [Win10 x64]  
**Access Method:** [C++]  

### Additional Information
Comp | He | H2 | N2 | CO2 | H2S | CH4 | C2H6
Mole Fraction | 0.012 | 0.028 | 0.52 | 8.64 | 15.16 | 75.52 | 0.12

**Comment by ianhbell** [comment]
Have you tried to enable the saturation splines with SATSPLN?

You should consider to upgrade to REFPROP 10.0 as well.

**Comment by OneNoobForAll** [comment]
> Have you tried to enable the saturation splines with SATSPLN?
> 
> You should consider to upgrade to REFPROP 10.0 as well.

Firstly，Thanks For Your Reply！

But I won't have REFPROP 10.0. So, Can you give more prompts？How to use the SATSPLN to get the state properties？Mainly the temperature and the pressure. And how to slove the same problems？

Waitting For Your Answer.

**Comment by NoobLuBenwei** [comment]
> Have you tried to enable the saturation splines with SATSPLN?
> 
> You should consider to upgrade to REFPROP 10.0 as well.

Firstly，Thanks For Your Reply！

But I won't have REFPROP 10.0. So, Can you give more prompts？How to use the SATSPLN to get the state properties？Mainly the temperature and the pressure. And how to slove the same problems？

Waitting For Your Answer.

**Comment by ianhbell** [comment]
Please see https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SATSPLNdll

Please show your C++ code that generates this error

**Comment by EricLemmon** [comment]
On my machine I'm using the alpha version of Refprop 10.1 and this point converges just fine.  Perhaps we could update your DLLs to the alpha version as well and let you try that.  By using the alpha, you will get all the current updates plus all the current bugs!  The bugs are generally minimal, and we rely on people like you who test the new code to help find these and report them.  If you would like to do this, please send me a personal email:  Eric.Lemmon@nist.gov

As for 9.1, fixing a non-converging point like this is not something that we can do because we have a very limited number of people working on the program and we have to devote our time to the current version.  You could also look at it this way, we really did fix this problem in 9.1, and called the fix 10.0!

**Comment by OneNoobForAll** [comment]
```C++
//set the path
string path = @"c:\Program Files (x86)\RefProp\fluids";
int size = path.Length;
path += new String(' ', 255 - size);
SETPATHdll(path, size);

//set the comp
int numComp=9;
static string hfld = "METHANE.FLD" +
            "|ETHANE.FLD" +
            "|PROPANE.FLD" +
            "|H2S.FLD" +
            "|WATER.FLD" +
            "|NITROGEN.FLD" +
            "|CO2.FLD" +
            "|HYDROGEN.FLD" +
            "|HELIUM.FLD";
static double x[20]={
    68.0664,
    00.1080,
    00.0000,
    13.6637,
    09.8700,
    00.4686,
    07.7872,
    00.0252,
    00.0108 
};

static string hfmix = "hmx.bnc" + new String(' ', 248);
static string hrf = "DEF";
hfld += new String(' ', 10000 - (hfld.Length));
string herr = new String(' ', 255);
int hfldLen = hfld.Length, hfmixLen = hfmix.Length, hrfLen = hrf.Length, herrLen = herr.Length;
int ierr = 0;
SETUPdll(numComp, hfld, hfmix, hrf, ierr, herr, hfldLen, hfmixLen, hrfLen, herrLen);

//properties known
double P=9000;//kPa
double S=3.15;//kJ/(kg·K)
PSFLSHdll(P, S, x, T0, D0, Dl0, Dv0, xl, xv, Q0, E0, H0, Cv0, Cp0, w0, ierr, herr, herrLen);

//other func

```
the code roughly like this. the code is  no problems.

My problem is that searching the properties at REFPROP 9.1  by using the 'isoproperity Tables' can get the properties, but using 'special state point' can not get. the 'special state point' may using PSFLSH or others. But, what is the 'isoproperity Tables' using  or how to slove it by other method?

@ianhbell you mean that calling SATSPLN to make the iteration more faster? OR calling other func to get the properties?

**Comment by ianhbell** [comment]
Yes, I mean that after calling ``SETUPdll`` you should call ``SATSPLNdll``.

For examples, it is best if they are complete and copy-pastable.

Some interesting decisions in your c++ code.  Why are you making all variables static? And what is this String method?
