### ISSUE TITLE
Output values when using Flag 002 and 202 using ABFLSH function

### ISSUE THREAD

**Issue by SWiell** [usnistgov/REFPROP-issues#415]
Im using the abflsh function to calculate the enthalpy of a steam. Im having T, P and the molefractions of the composition as inlet parameters. I would like the enthalpy as outlet parameter. All my parameters are on mass-bases from IPSEpro and would like to use the Flag 202 or 002 in abflsh to avoid convering all inputs from mass-basis to mole-bases before running the function but using these flags only gives me a value of 0 of the outlet enthalpy, undepended on what pressure, temperature or composition I have as inputs. I know there is some bug when using mass-basis?

Im using REFPROP version 10.0.0.97 in Microsoft Visual Studio, C++. 

Sofia

**Comment by ianhbell** [comment]
If you use C++ I would strongly recommend to call REFPROP via CoolProp: http://www.coolprop.org/ .  It's interface is well suited to this sort of mixing and matching.

**Comment by SWiell** [comment]
Okey, thanks, will look into that. But Im still wondering if ABFLSH usually works with these Flags or if the bug in the program regarding mass units I have read about in other issues might be the explanation to my problem.

**Comment by EricLemmon** [comment]
Can you send Ian and me an email and we'll update you with the current patch so that you can see if it is working.
Ian.Bell@nist.gov and Eric.Lemmon@nist.gov
