### ISSUE TITLE
incorrect quality value in PHFLSH without error

### ISSUE THREAD

**Issue by siwolga** [usnistgov/REFPROP-issues#419]
### Description

When calculating the parameters of mixture 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<body link="#0563C1" vlink="#954F72">

№ | Compound | Input molar fraction
-- | -- | --
1 | Methane | 0.3468
2 | Ethane | 0.1623
3 | Propane | 0.2671
4 | Isobutane | 0.0399
5 | Butane | 0.1289
6 | Isopentane | 0.0133
7 | Pentane | 0.0126
8 | Hexane | 0.0043
9 | Water | 0.0045
10 | Nitrogen | 0.0092
11 | Carbon dioxide | 0.0111

</body>
</html>

by pressure (6136632 Pa) and enthalpy (271615 J/kg), the value of quality -998 is returned in REFPROP 10 using the old function PHFLSH, but error 0 is returned. Everything works correctly in REFPROP 9. When checking in Excel, the correct error is also returned, but the new function is used in the Excel add-in.

**Expected behavior:** ierr > 0

**Actual behavior:** ierr = 0

### Versions

**REFPROP Version:** [REFPROP 10.0]  
**Operating System and Version:** [Win10]  
**Access Method:** [C#]  

### Additional Information

![image_2021_06_23T13_10_29_825Z](https://user-images.githubusercontent.com/86594760/123605484-8f440300-d804-11eb-94d1-653c28845ae6.png)
Using names:
_PHFLSH(ref parameters.Pressure, ref parameters.Enthalpy, molar_fraction, 
                                        ref parameters.Temperature, ref parameters.Density, ref parameters.DensityLiquid, ref parameters.DensityVapor, molar_fractionL, molar_fractionV,
                                        ref parameters.Quality, ref parameters.InternalEnergy, ref parameters.Entropy,
                                        ref parameters.CV, ref parameters.CP, ref parameters.SoundSpeed, ref parameters.Error, herr, herr.Capacity);

**Comment by ianhbell** [comment]
What result do you get for quality in refprop 9?  Do the densities differ between REFPROP 9 and REFPROP 10?

**Comment by siwolga** [comment]
It looks like everything is correct, it's just that in version 9 this state was not calculated, but now it is! Thank you!

REFPROP 911
![refprop911-2](https://user-images.githubusercontent.com/86594760/123788091-4499b800-d8e4-11eb-8498-22160e2e0242.png)

REFPROP 10
![refprop10-2](https://user-images.githubusercontent.com/86594760/123788099-4794a880-d8e4-11eb-8da8-acf0f940aa94.png)
