### ISSUE TITLE
Use of SATSPLN 

### ISSUE THREAD

**Issue by JosvantWestende** [usnistgov/REFPROP-issues#424]
I have two questions related to the use of SATSPLN in Python (also related to issue  #383)

1 : Do you need to call SATSPLN with z specified on mole-base? (if z is on mass-base, how to convert it most efficiently?)
2 : If you set the flag after iMass to 1, do you enforce SATSPLN to be called again? (if so, is it allowed to have z on mass-base?)
e.g. Hgsat = RP.REFPROPdll('', 'PQ', 'H', RP.MASS_BASE_SI, iMass, 1, P, 1, z).Output[0]

**Comment by ianhbell** [comment]
1. Yes, compositions to ``SATSPLNdll`` are molar: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SATSPLNdll
2. ``iMass=1`` doesn't call ``SATSPLNdll`` internally, but ``iFlag=1`` does

P.S. It is recommended to always use mole fractions in ``REFPROPdll``

**Comment by JosvantWestende** [comment]
Thanks Ian.

**Comment by henningjp** [comment]
Well, if calling SATSPLN through SATSPLNdll directly, it's mole fraction.

If calling SATSPLN through REFPROPdll (as indicated in your second question with iFlag = 1), then iMass "Specifies if the input composition is mole or mass based."  (iMass = 0 for mole fraction; iMass =1 for mass fraction).

At least that's what the documentation says and how I've been using it.

**Comment by henningjp** [comment]
Hmmm.  Maybe not!  See this issue: **iMass ignored in REFPROPdll** #311

**Comment by ianhbell** [comment]
@henningjp is in theory, correct.  But there are bugs with mass fractions, but only under some conditions.  So I always recommend to use mole fractions in the high-level interface, for which i have not had any issues.
