### ISSUE TITLE
High-Level API Web Docs Missing

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-issues#425]
### Description

The High-Level API doc pages are no longer available at https://refprop-docs.readthedocs.io/en/latest/DLL/index.html .  Only the Legacy API is showing.

### Steps to Reproduce

1. Just browse the on-line latest web docs at: https://refprop-docs.readthedocs.io/en/latest/index.html

### Versions

**REFPROP Version:** _latest_  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

![DLL Help Docs](https://user-images.githubusercontent.com/17114032/124272665-0df2b600-db0d-11eb-8011-14368b3086c3.png)

**Comment by ianhbell** [comment]
Thanks for the report.  I have no idea what has happened. I'll look into it!

**Comment by ianhbell** [comment]
Fixed, you might need to refresh the page to refresh your local cache
