### ISSUE TITLE
Installing REFPROP on another computer/laptop with my licence

### ISSUE THREAD

**Issue by Kandadaisrinivasan** [usnistgov/REFPROP-issues#431]

**Comment by ianhbell** [comment]
What is the question?  Licenses are per user, so if you have a new machine, there is nothing you need to do aside from installing REFPROP on your new machine.

**Comment by Kandadaisrinivasan** [comment]
The question is
I had installed on one machine.
I need to install on another machine due to work from home situation. How do I do it? My downloaded set up file is on the other machine.

**Comment by ianhbell** [comment]
You can email me (ian.bell@nist.gov) and I'll send instructions

**Comment by EricLemmon** [comment]
Do you have access to your other machine?  If not, send an email to data@nist.gov and they can provide you with another copy of the installer.

Just for information, the following helps explain how the licensing works:  https://github.com/usnistgov/REFPROP-issues/issues/227
