### ISSUE TITLE
DSAT should yield harder error for negative density

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#433]
For nitrogen, a saturation density to DSAT that is negative returns an error, but only an ``ierr`` of 2, which is in the soft error category but should be > 100 for a hard error.  Also, the error message in ``herr`` is not formed like other error codes.  Example of normal error message:

```[SATT error 121] Temperature input is greater than the critical or maxcondentherm temperature: T = -100.0000 K, Tc = 126.192 K.```

```python
import os
import sys
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)

print("SYSTEM", sys.platform)
print("VERSION", RP.RPVersion())

if __name__ == "__main__":
    fluid_str = "NITROGEN"
    density =  -999
    rt = RP.REFPROPdll(fluid_str, "DSAT", "T", RP.MOLAR_BASE_SI, 0, 0, density, 0, [1])

    print("ierr", rt.ierr)
    print("herr", rt.herr)
    print("T", rt.Output[0])
    print("Q, COMPUTED", rt.q)
```
yields
```
SYSTEM linux
VERSION 10.0.0.95d
ierr 2
herr Density below zero: D = -0.999000 mol/L;
T 126.192
Q, COMPUTED 1.0
```

**Comment by EricLemmon** [comment]
Good point!  I've changed the code to use error 143, which is already designated for D<0, with this error message:

[SATD error 143] Input value equal to or less than zero.

I'll upload the new code shortly.

**Comment by EricLemmon** [comment]
I just updated the error message to include more information:

[SATD error 143] Input value equal to or less than zero: D = -42.8722 mol/l.

Several other places in the code that used error 143 have also been updated to include the bad input value.

**Comment by ianhbell** [comment]
Works now:
```python
import os
import sys
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(r'c:\Program Files (x86)\REFPROP')

print("SYSTEM", sys.platform)
print("VERSION", RP.RPVersion())

if __name__ == "__main__":
    fluid_str = "NITROGEN"
    density =  -999
    rt = RP.REFPROPdll(fluid_str, "DSAT", "T", RP.MOLAR_BASE_SI, 0, 0, density, 0, [1])

    print("ierr", rt.ierr)
    print("herr", rt.herr)
    print("T", rt.Output[0])
    print("Q, COMPUTED", rt.q)
```
yields
```
SYSTEM win32
VERSION 10.0.1.3
ierr 143
herr [SATD error 143] Input value equal to or less than zero: D = -0.999000 mol/l.
T -9999990.0
Q, COMPUTED 999.0
```
