### ISSUE TITLE
Phase boundaries for pures allows invalid densities

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#434]
If the limits of the EOS are being checked, quite a few densities in the phase boundary table in the GUI are calculated, although they should be errors.  

For nitrogen, the triple point density is approximately 867 kg/m^3, and any densities above that should be errors, but densities up to 1034 kg/m^3 are not errors, and are returned as liquid in equilibrium with itself.  Beyond that value, erroneous values are returned:

![image](https://user-images.githubusercontent.com/11966765/127677201-f937e370-1f6e-4ca3-9950-6d8c4cd67f3a.png)

**Comment by EricLemmon** [comment]
The comments from #432 apply to this issue as well.

In the GUI, I changed the output for the "state" property to "melting" to give a better description of the input state.

**Comment by ianhbell** [comment]
What does the above table look like with the fix?

**Comment by EricLemmon** [comment]
The last line is italicized because P>Pmax but less than Pmax*2.

![image](https://user-images.githubusercontent.com/42392984/127777875-b674679e-e9d9-4a78-8d3f-ea0ac7166abb.png)

**Comment by ianhbell** [comment]
Excellent, nice work
