### ISSUE TITLE
Incorrect values returned for composition derivatives from RDXHMX

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#436]
When one component has a composition of zero, the values are silently incorrect.  In this case, we should expect the values to be very similar for a mole fraction of zero, and something extremely close to zero.

```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print('version:', RP.RPVersion())

r = RP.SETFLUIDSdll("NITROGEN*ETHANE")
print(r)

# Calculate values of composition derivatives
for e in [0, 1e-10]:
    print(RP.RDXHMXdll(1,1,0,[e, 1-e]))
```
yields
```
version: 10.0.0.02
0
RDXHMXdlloutput(Tred=300.0, Dred=0.0, ierr=0, herr='')
RDXHMXdlloutput(Tred=434.6139303500674, Dred=0.23536417026761067, ierr=0, herr='')
```

**Comment by EricLemmon** [comment]
I'm not sure I'd call this one a bug, but more of a feature.   The code simply checked if the composition was zero and didn't calculate anything if so (by design).  I just deactivated those lines and all is working for the pure fluids now as well.

Are there any special considerations when working with a ternary or higher order mixtures that we need to be concerned about?

I'll upload the changes tomorrow.

**Comment by ianhbell** [comment]
The composition derivatives in the infinite dilution limit of the reducing functions is still well-defined when one component goes to zero composition. So the case of the binary mixture of A+B with the composition of A going to zero is not the same thing as pure component B.  For reducing T and reducing density, they are identical in value because the zero compositions drop out. But not so for derivatives.

I agree that this needs to be clarified, and you need to be able to specify that you want the infinite dilution limit rather than the pure.  For multicomponent mixtures, I am not sure what is the right approach.

**Comment by ianhbell** [comment]
Looks good now.

```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print('version:', RP.RPVersion())
RP.SETPATHdll(r'c:\Program Files (x86)\REFPROP')

r = RP.SETFLUIDSdll("NITROGEN*ETHANE")
print(r)

# Calculate values of composition derivatives
for e in [0, 1e-10]:
    print(RP.RDXHMXdll(1,1,0,[e, 1-e]))
```
yields
```
version: 10.0.1.3
0
RDXHMXdlloutput(Tred=434.6139303696291, Dred=0.23536417027129689, ierr=0, herr='')
RDXHMXdlloutput(Tred=434.6139303500674, Dred=0.23536417026761067, ierr=0, herr='')
```
