### ISSUE TITLE
CSAT always gives liquid solution

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#437]
CSAT can be defined as 

![image](https://user-images.githubusercontent.com/11966765/129406666-ab26073e-fcaa-4cda-93b5-564f72c033b0.png)

where prime indicates the phase (liquid or vapor) and thus it should be defined for each phase differently.  ``REFPROPdll`` always returns the liquid CSAT, which is fairly reasonable, although if the vapor phase is specified, you should get the vapor solution.

Example:

```python
"""Script to demonstrate issue with calculating saturated heat capacity for a saturated point.

Issue reported on:
    SYSTEM: linux
    REFPROP: 10.0.0.95d
"""

import os
import sys
from math import isclose
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)

print("SYSTEM", sys.platform)
print("REFPROP", RP.REFPROPdll("", "", "DLL#", 0, 0, 0, 0, 0, [1.0]).hUnits)
print("")

# inputs
fluid = "NITROGEN"
temperature = 100
i_units = RP.GETENUMdll(1, "SI").iEnum

# set fluid
err_code = RP.SETFLUIDSdll(fluid)
if err_code >= 100:
    raise ValueError("Error setting fluid")

# compute saturation data
r_liq = RP.REFPROPdll("", "TQ", "CSAT", i_units, 0, 0, temperature, 0, [1])
csat_liq = r_liq.Output[0]

r_vap = RP.REFPROPdll("", "TQ", "CSAT", i_units, 0, 0, temperature, 1, [1])
csat_vap = r_vap.Output[0]

# validate per desktop results, v10.0.0.02
print("CSAT, LIQ", csat_liq)  # desktop = 2.2454
print("CSAT, VAP", csat_vap)  # desktop = -1.6059

# With the routines in CoolProp, to check
import CoolProp.CoolProp as CP 

AS = CP.AbstractState('HEOS', 'NITROGEN')
AS.update(CP.QT_INPUTS, 0, temperature)
print("[CoolProp] CSAT, LIQ", AS.first_saturation_deriv(CP.iSmass, CP.iT)*AS.T()/1000)

AS = CP.AbstractState('HEOS', 'NITROGEN')
AS.update(CP.QT_INPUTS, 1, temperature)
print("[CoolProp] CSAT, VAP", AS.first_saturation_deriv(CP.iSmass, CP.iT)*AS.T()/1000)

assert isclose(csat_liq, 2.2454, abs_tol=1e-3)
assert isclose(csat_vap, -1.6059, abs_tol=1e-3)
```
yields on my computer
```
SYSTEM win32
REFPROP 10.0.0.02

CSAT, LIQ 2.2454382498653795
CSAT, VAP 2.2454382498653795
[CoolProp] CSAT, LIQ 2.2454382498513827
[CoolProp] CSAT, VAP -1.6059204508930747
Traceback (most recent call last):
  File "C:\Users\ihb\Desktop\issue_saturated_heat_capacity.py", line 54, in <module>
    assert isclose(csat_vap, -1.6059, abs_tol=1e-3)
AssertionError
```

**Comment by ianhbell** [comment]
And if q is greater than 0 and less than 1, the error message could be more informative.  q=0 and q=1 are still *technically* two-phase states.

**Comment by EricLemmon** [comment]
This has been fixed now.  The error message was changed slightly to read:

[REFPROP warning -810] One or more of the output properties is/are not thermophysically defined for non-saturated two-phase states and cannot be calculated.

**Comment by ianhbell** [comment]
What value is returned for CSAT for saturated vapor now?

**Comment by EricLemmon** [comment]
With this code:

      call SETFLUIDS ('NITROGEN',ierr)
      call GETENUM (1, "SI", i_si, ierr, herr)
      Cliq = REFPROPF ('TQ','Csat',i_si,0,100d0,0d0,z,q,ierr,herr)
      Cvap = REFPROPF ('TQ','Csat',i_si,0,100d0,1d0,z,q,ierr,herr)

I get:

		Cliq	2.24543824986537	REAL(8) 
		Cvap	-1.60592045087904	REAL(8)

**Comment by ianhbell** [comment]
Excellent, thanks for the confirmation.  This issue can be closed.

**Comment by ianhbell** [comment]
It seems the code to fix this issue was never pushed.  At version 10.0.1.8, the same initial error is present.

**Comment by EricLemmon** [comment]
You are correct, sorry about that!  It's up there now.

**Comment by ianhbell** [comment]
At 10.0.1.10, it works:
```
SYSTEM win32
REFPROP 10.0.1.10

CSAT, LIQ 2.245438249865374
CSAT, VAP -1.6059204508790752
[CoolProp] CSAT, LIQ 2.2454382498513827
[CoolProp] CSAT, VAP -1.6059204508930747
```
