### ISSUE TITLE
Metastable conditions for IAPWS-Water properties

### ISSUE THREAD

**Issue by hlucian** [usnistgov/REFPROP-issues#438]
I am trying to export data from Refrop for the Metastable region for water (IAPWS-Formulation).
As given in your documentation I can enforce this by using the "<,>" symbols.

**E.g. if i provide the folling temperature and pressure input (notice the < symbol)**
Temperature: 450  K
Pressure:        1<   MPa
 
**The resulting enthalpy is:**
-> Enthalpy 0.276 881 115 × 10^4 kJ / kg
 
Which is in agreement to the validation data provided through IAPWS-97 Formulation.
 
However, when I try to compute the temperature using the enthalpy and pressure as
 
Enthalpy:   0.27688 x 10^4    kJ / kg
Pressure:   1<                         MPa
 
**The temperature is 453.3 K** and the inserted Enthalpy value automatically switches to 0.2777 kJ / kg,
which I guess is the equilibrium saturation property.
 
Is there a way to force the program to use the metastable formulations also when using pressure and
enthalpy?

The reason I ask is because our numerical algorithm / CFD code solvers for pressure and enthalpy,
hence these are the quantities I would use in a look-up table for updating temperature and density.

### Versions

**REFPROP Version:** [9.1]  
**Operating System and Version:** [Windows]  
**Access Method:** [Directly from the refprop GUI)]

**Comment by ianhbell** [comment]
I cannot reproduce this value or error.  In REFPROP 10.0.0.02 GUI I get:

![image](https://user-images.githubusercontent.com/11966765/129743647-271899ab-9540-4a41-b8ee-42d5332b94c9.png)

And in Python, I get:
```python
import ctREFPROP.ctREFPROP as c, os
RP = c.REFPROPFunctionLibrary(os.environ['RPPREFIX'])
r1 = RP.REFPROPdll('WATER', 'TP<', 'H,R', RP.MASS_BASE_SI, 0, 0, 450, 1e6, [1.0])
r2 = RP.REFPROPdll('WATER', 'HP<', 'T', RP.MASS_BASE_SI, 0, 0, r1.Output[0], 1e6, [1.0])
print(r2)
```
yielding
```
REFPROPdlloutput(
z=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
Output=array('d', [449.99999995616355, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), 
hUnits='K', 
iUCode=1, 
x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
q=998.0, 
ierr=0, 
herr='')
```

**Comment by hlucian** [comment]
Thank you so much for your quick answer.

So it seams to be an issue with the older version. Will have to ask if we can install the 
new refprop. 

One question, can you give me an example of a matlab code for the metastable conditions?
The code below works fine, but I do not know how to insert the '<' conditions.

```matlab
Material = 'Water';             %The material for which the tables are to be computed

h = refpropm('H','T',450,'p',1e6,Material)
```


9.1 returns the following:

![grafik](https://user-images.githubusercontent.com/47562558/129844227-4ff5b716-34bc-473a-b302-f4bc13686abd.png)

**Comment by ianhbell** [comment]
refpropm is deprecated.  You'll need to use the Python interface to MATLAB: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB which will give you all the functionality you need.

**Comment by hlucian** [comment]
Ok, thank you so much. I will try this way then.
