### ISSUE TITLE
How do I remove user-defined .MIX files?

### ISSUE THREAD

**Issue by marciahuber** [usnistgov/REFPROP-issues#442]
I have created user-defined mixtures and saved them. I would like to clean up and remove some of these. However, they do not appear to be in the location C:\Program Files (x86)\REFPROP\MIXTURES, rather they appear to be in some sort of virtual directory. How do I get rid of these files?

**Comment by ianhbell** [comment]
This link indicates the path where you should be looking: https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel .  In my case it's: ``C:\Users\XXX\AppData\Local\VirtualStore\Program Files (x86)\REFPROP\MIXTURES``
