### ISSUE TITLE
Solving 2-phase N2 + H2O mixture

### ISSUE THREAD

**Issue by Jonshagen** [usnistgov/REFPROP-issues#445]
### Description
I am trying to solve two phase states for a N2 H2O mixture, it seems to work with temperature and pressure as input but pressure and enthalpy or pressure and entropy returns PHFL2 error 226

### Steps to Reproduce
Call abflshdll using p = 6.3183kPa, H = -4068.02kJ/mol (h0=0 at t0 = 373.16, p0 = 100)

Simple test through Refprop GUI:
Components: Water/Nitrogen 85/15 [kg/kg]
Ref state default.
Specific state point:
Input T=308K, P = 0.0063MPa => h = 1985.5kJ/kg Ok!
Input P = 0.0063MPa, h = 1985.5kJ/kg => PHFLSH error 223 Bubble point did not converge
Note that it my code I use ABFLSHdll and my error is instead "[PSFL2 error 226] 2-phase iteration did not converge. But I am guessing that it is related and the GUI is a fast way to test.

I am using a C++ code:
```
SETUPdll(i, hf, hfmix, hrf, ierr, herr, refpropcharlength*ncmax, refpropcharlength, lengthofreference, errormessagelength); 
SETREFdll(hrf, ixflag, x, h0, s0, t0, p0, ierr, herr, lengthofreference, errormessagelength);
SATSPLNdll(x, ierr, herr, refpropcharlength*ncmax);
ABFLSHdll(ab, a, b, x, kq, t, p, d, dl, dv, xliq, xvap, q, e, h, s, cv, cp, w, ierr, herr, ab_length, errormessagelength);

hfmix = "hmx.bnc"
hrf = "OTH"
h0 = 0, s0 = 0, t0 = 373.16, p0 = 100
hf= "nitrogen.fld\|water.fld" 
x[0]= 0.8958
x[1]=0.1042
ab = "PH"
a = 6.3183
b = -4068.02kJ/mol
```

**Expected behavior:** Solving the state in the 2-phase region from pressure and enthalpy or pressure and entropy

**Actual behavior:** 
"[PSFL2 error 226] 2-phase iteration did not converge. 

### Versions

**REFPROP Version:** 10.0.0.97
**Operating System and Version:** win 7
**Access Method:** C++ wrapper)]  

### Additional Information

![image](https://user-images.githubusercontent.com/75474281/130082210-fc153131-a537-47b9-9389-baaaaddca6f5.png)

**Comment by Jonshagen** [comment]
Hi,

Have you looked at this, do you see the same error on your side? Is there any solution?

Best regards.
Klas

**Comment by ianhbell** [comment]
Please try the same calculation in molar units, and make sure to enable the saturation splines.

**Comment by Jonshagen** [comment]
Hi Ian,

Thanks for advise. We use the iFlag = 200  according to the example in refprop manual ''All inputs are on a mole basis, but quality is sent on a mass basis.''
We call the SATSPLNdll after setupdll and setrefdll:
	SETUPdll(i, hf, hfmix, hrf, ierr, herr, refpropcharlength*ncmax, refpropcharlength, lengthofreference, errormessagelength);
	SETREFdll(hrf, ixflag, x, h0, s0, t0, p0, ierr, herr, lengthofreference, errormessagelength);
	SATSPLNdll(x, ierr, herr, refpropcharlength*ncmax);

**Comment by ianhbell** [comment]
Did you try the call to ABFLSH with molar quantities and mole fractions? There are some bugs with ABFLSH with mass quantities, but molar should always be ok. Of course, that won't solve flash routine failures.

**Comment by ianhbell** [comment]
This works fine on my side, but your inputs don't appear to be two-phase.

```python
import ctREFPROP.ctREFPROP as c, os
RP = c.REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print(RP.RPVersion())

z = [0.8958,1-0.8958]
r1 = RP.REFPROPdll('NITROGEN;WATER', 'TP', 'H', RP.MASS_BASE_SI, 0, 0, 308, 0.0063e6, z)
print(r1.Output[0:2], r1.hUnits)
r2 = RP.REFPROPdll('NITROGEN;WATER', 'PH', 'T', RP.MASS_BASE_SI, 0, 0, 0.0063e6, r1.Output[0], z)
print(r2)
```
yielding
```
10.0.0.02
array('d', [476075.5817988017, -9999990.0]) J/kg
REFPROPdlloutput(
z=array('d', [0.8958, 0.10419999999999996, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
Output=array('d', [307.9999999999999, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), 
hUnits='K', 
iUCode=1, 
x=array('d', [0.8958, 0.10419999999999996, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
y=array('d', [0.8958, 0.10419999999999996, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
q=998.0, 
ierr=0, 
herr='')
```

**Comment by Jonshagen** [comment]
Hi Ian!
Here is what happens for me. I call first with pt that converges, but the it seems to be in 2-pahse for me. Can you check "q" after your first call? I have put all my abflsh input in watch in the print screens:
![image](https://user-images.githubusercontent.com/75474281/135436454-76f28294-23c1-4c51-86b6-c9b561f76f3b.png)
Then I call with ph and it does not converge:
![image](https://user-images.githubusercontent.com/75474281/135436699-a52d308a-149c-4d53-8483-b20e4c7ea510.png)

**Comment by ianhbell** [comment]
Have you padded all the strings and mole fractions to the appropriate lengths? My guess from looking at your code is no, and your code is reading out of bounds, which is undefined behavior.  Can you please provide a copy-pastable runnable example and I can test on my side?

**Comment by Jonshagen** [comment]
Hi Ian,

Here is our function that calls abflsh. 

void load(int on)
{
	std::string path = "C:/Program Files (x86)/REFPROP";
	//	std::string DLL_name = "REFPRP64.dll";
	std::string DLL_name = "REFPROP.dll";
	// Call a function in another file (and load the DLL, and then unload it) another_file(path, DLL_name);

	// Load the shared library
	std::string err;

	if (on == 1)
	{
		bool loaded_REFPROP = load_REFPROP(err, path, DLL_name);
	}


	SETPATHdll(const_cast<char*>(path.c_str()), 400);
	if (on == 0)
	{
		bool unloaded_REFPROP = unload_REFPROP(err);
	}
}

vector<vector<double>> f_abflsh(char* ab, double a, double b, double x[], int i, char* hf)
{
	#define refpropcharlength 255
	#define lengthofreference 3
	#define errormessagelength 255
	#define ncmax 20 // note: ncmax is the max number of components
	
	double xliq[ncmax], xvap[ncmax], xliqkg[ncmax], xvapkg[ncmax];
	double t, p, dl, dv, wvap, wliq, xvkh, xlkg, qkgt, wm, qkg;
	double d = 0.0, q = 0.0, e = 0.0, h = 0.0, s = 0.0, cv = 0.0, cp = 0.0, w = 0.0, c = 0, fld_ID = 0, fld_index, dummy = 0, PhaseInput = 1;
	int ierr = 0, ixflag = 2, ab_length = 2, fluids, j, tot_flds = 9;
	char hf[refpropcharlength*ncmax], hrf[4] = "OTH", herr[255] = "Ok", herr1[255] = "Ok", herr2[255] = "Ok", herr3[255] = "Ok", hfmix[255] = "hmx.bnc", href[3][4] = { "NBP", "OT0", "OTH" }, ac[3] = "NN";
	
	//REFERENCE STATE
	double h0 = 0, s0 = 0, t0 = 373.16, p0 = 100;
	int kq = 200;

	load(1);

	SETUPdll(i, hf, hfmix, hrf, ierr, herr, refpropcharlength*ncmax, refpropcharlength, lengthofreference, errormessagelength); //Legacy API setup function that will be removed in the future, might need to be replaced with High-level API setup function
	SETREFdll(hrf, ixflag, x, h0, s0, t0, p0, ierr, herr, lengthofreference, errormessagelength);
	SATSPLNdll(x, ierr, herr, refpropcharlength*ncmax);


	ABFLSHdll(ab, a, b, x, kq, t, p, d, dl, dv, xliq, xvap, q, e, h, s, cv, cp, w, ierr, herr, ab_length, errormessagelength); 
	
	//result vector
	int n = 20;
	vector<double> results(n, 0);
	results[0] =  t - 273.15;
	results[1] =  p / 100;
	results[2] =  d;
	results[3] =  dl;
	results[4] =  dv;
	results[5] =  0; 
	results[6] =  0; 
	results[7] =  q;
	results[8] =  e;
	results[9] =  h; 
	results[10] = s; 
	results[11] = cv;
	results[12] = cp;
	results[13] = w;
	results[14] = 1 / (d); 
	results[15] = 1 / (dl);
	results[16] = 1 / (dv);
	results[17] = 0;
	results[18] = 0;
	results[19] = 0; 

	//unit result matrix
	int coloumns = 3;
	int rows = 20;
	vector< vector<double> > matrix_results(coloumns, vector<double>(rows, 0)); //builds matrix 20 rows, 3 coloumns with 0s
	double sum = 0;
	int k = 0;
	for (int i = 0; i < rows; i++) {
		matrix_results[0][k] = results[i]; //column 0
		matrix_results[1][k] = xliqkg[i];  //column 1
		matrix_results[2][k] = xvapkg[i];  //column 2
		sum += matrix_results[0][k];
		k++;
	}

	load(0);
	return matrix_results;
}

**Comment by ianhbell** [comment]
This is still not a runnable example...  I need something I can copy-paste into a file on my computer and compile and run and get the same error as you.

**Comment by Jonshagen** [comment]
Hi Ian,

I am trying to set up project that produces an .exe for this purpose but I am getting an compiler error that ´t´ is an undeclared identifier on row 759 of REFPROP_lib.h.

Here is my code, as said unfortunately I cannot compile it. The problem I have is that ph as input does not seem to work in, or perhaps close to, the two-phase region coming from the gas side.
```c++
#include <windows.h>
#include <stdio.h>
#include "stdafx.h"

#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION

#include <vector>
#include <iostream>	// write 
#include <fstream>	// write 
#include <chrono>	
#include <ctime>	
#include <string>

using namespace std; //OK as no other namespaces are used

#define refpropcharlength 255
#define lengthofreference 3
#define errormessagelength 255
#define ncmax 20 // note: ncmax is the max number of components
#define tot_flds 9

void load(int on)
{
	std::string path = "C:/Program Files (x86)/REFPROP";
	// std::string DLL_name = "REFPRP64.dll";
	std::string DLL_name = "REFPROP.dll";
	// Call a function in another file (and load the DLL, and then unload it) another_file(path, DLL_name);

	// Load the shared library
	std::string err;

	if (on == 1)
	{
		bool loaded_REFPROP = load_REFPROP(err, path, DLL_name);
	}


	SETPATHdll(const_cast<char*>(path.c_str()), 400);
	if (on == 0)
	{
		bool unloaded_REFPROP = unload_REFPROP(err);
	}
}

//#############################################################################################################
//#############################################################################################################
//  f_abflsh, general function for abflsh with two inputs, a and b
//#############################################################################################################
//#############################################################################################################

vector<vector<double>> f_abflsh(char* ab, double a, double b, string outlet, double x[], int i, char* hf, double wm)
{
	int kq = 200;
	double xliq[ncmax], xvap[ncmax], xliqkg[ncmax], xvapkg[ncmax];
	double t, p, dl, dv, wvap, wliq, xvkh, xlkg, qkgt, qkg, d, q, e, h, s, cv, cp, w, c;
	int ierr = 0, ixflag = 2, ab_length = 2, fluids, j;
	char hrf[4] = "OTH", herr[255] = "Ok", herr1[255] = "Ok", herr2[255] = "Ok", herr3[255] = "Ok", hfmix[255] = "hmx.bnc", href[3][4] = { "NBP", "OT0", "OTH" }, ac[3] = "NN";
	//REFERENCE STATE
	double h0 = 0, s0 = 0, t0 = 373.16, p0 = 100;
	load(1);

	SETUPdll(i, hf, hfmix, hrf, ierr, herr, refpropcharlength*ncmax, refpropcharlength, lengthofreference, errormessagelength); //Legacy API setup function that will be removed in the future, might need to be replaced with High-level API setup function
	SETREFdll(hrf, ixflag, x, h0, s0, t0, p0, ierr, herr, lengthofreference, errormessagelength);
	SATSPLNdll(x, ierr, herr, refpropcharlength*ncmax);


	ABFLSHdll(ab, a, b, x, kq, t, p, d, dl, dv, xliq, xvap, q, e, h, s, cv, cp, w, ierr, herr, ab_length, errormessagelength);

	// unit conversion of q, xliq and xvap from mole to mass basis (REFPROP to IPSE units) 
	if (outlet.compare("Q") == 0 || outlet.compare("XVAP") == 0 || outlet.compare("XLIQ") == 0) {
		QMASSdll(q, xliq, xvap, qkg, xliqkg, xvapkg, wliq, wvap, ierr, herr, errormessagelength);
		q = qkg;
	}

	//unit result vector
	int n = 20;
	vector<double> results(n, 0);
	results[0] = t - 273.15;
	results[1] = p / 100;
	results[2] = d * wm;
	results[3] = dl * wm;
	results[4] = dv * wm;
	results[5] = 0;
	results[6] = 0;
	results[7] = q;
	results[8] = e / wm;
	results[9] = h / wm;
	results[10] = s / wm;
	results[11] = cv / wm;
	results[12] = cp / wm;
	results[13] = w;
	results[14] = 1 / (d * wm); //v [m3/kg]
	results[15] = 1 / (dl * wm); //vliq
	results[16] = 1 / (dv * wm); //vvap
	results[17] = 0;
	results[18] = 0;
	results[19] = 0; //this value needs to be a zero

	//unit result matrix
	int coloumns = 3;
	int rows = 20;
	vector< vector<double> > matrix_results(coloumns, vector<double>(rows, 0)); //builds matrix 20 rows, 3 coloumns with 0s
	double sum = 0;
	int k = 0;
	for (int i = 0; i < rows; i++) {
		matrix_results[0][k] = results[i]; //column 0
		matrix_results[1][k] = xliqkg[i];  //column 1
		matrix_results[2][k] = xvapkg[i];  //column 2
		sum += matrix_results[0][k];
		k++;
	}

	load(0);
	return matrix_results;
}
int main()
{
	double P, T, H;
	cin >> P;
	cin >> T;
	double a = P, b = T;
	char ab[3] = "PT";
	string outlet = "H";
	int index = 9; // for enthalpy
	double x[2];
	x[0] = 0.15;
	x[1] = 0.85;
	int i = 2;
	double wm = 1;
	char hf[refpropcharlength*ncmax] = "nitrogen.fld|water.fld";

	vector<vector<double>> results = f_abflsh(ab, a, b, outlet, x, i, hf, wm);
	
	H = results[0][index];
	
	cout << H;

	b = H;
	char ab2[3] = "PH";
	outlet = "T";
	index = 0; // for Temperature
	results = f_abflsh(ab2, a, b, outlet, x, i, hf, wm);
	T = results[0][index]; // 0 for temperature
	
	cout << T;
	cin >> H; //To keep window open
}
```

**Comment by ianhbell** [comment]
I added triple-backticks and removed redundant code so your code would format nicer in github.  For testing, always start simple: no reference state setting, etc.

**Comment by ianhbell** [comment]
Code compiles on my side.

Some issues I can see:
* load should ONLY happen right at the beginning of your code
* make sure your fluid names have the right case (this matters on non-windows platforms)
* always check your error codes (you never check your error codes)
* SETPATHdll uses a buffer that is too small (needs to be at least 255 characters)

**Comment by Jonshagen** [comment]
Thank you very much for the quick response!
In my dll code I always return the error message, I just cut it out from this code. But you are right,  it would have been nice to return it here as well.
The buffer to the setpathdll means that I should create a string of 255 and then assign it? I copied the the setpathdll part from the main.cpp example.
What temperature is returned if you enter P = 0.0063MPa and T=308K?

**Comment by ianhbell** [comment]
The code works fine, and the inputs are single-phase (I output the Q in your calls).  I get
```
REFPROP version: 10.0002
6.3
308
Q: 998
H: -2061.28
Q: 1.00115
T: 308
```
from
```C++
#include <windows.h>
#include <stdio.h>

#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION

#include <vector>
#include <iostream>	// write 
#include <fstream>	// write 
#include <chrono>	
#include <ctime>	
#include <string>

using namespace std; //OK as no other namespaces are used

#define refpropcharlength 255
#define lengthofreference 3
#define errormessagelength 255
#define ncmax 20 // note: ncmax is the max number of components
#define tot_flds 9

void load(int on)
{
	std::string path = "C:/Program Files (x86)/REFPROP";
	std::string DLL_name = "REFPRP64.dll";
	//std::string DLL_name = "REFPROP.dll";
	// Call a function in another file (and load the DLL, and then unload it) another_file(path, DLL_name);

	// Load the shared library
	std::string err;

	if (on == 1)
	{
		bool loaded_REFPROP = load_REFPROP(err, path, DLL_name);
		SETPATHdll(const_cast<char*>(path.c_str()), 400);
	}
	if (on == 0)
	{
		bool unloaded_REFPROP = unload_REFPROP(err);
	}
}

//#############################################################################################################
//#############################################################################################################
//  f_abflsh, general function for abflsh with two inputs, a and b
//#############################################################################################################
//#############################################################################################################

vector<vector<double>> f_abflsh(char* ab, double a, double b, string outlet, double x[], int i, char* hf, double wm)
{
	int kq = 200;
	double xliq[ncmax], xvap[ncmax], xliqkg[ncmax], xvapkg[ncmax];
	double t, p, dl, dv, wvap, wliq, xvkh, xlkg, qkgt, qkg, d, q, e, h, s, cv, cp, w, c;
	int ierr = 0, ixflag = 2, ab_length = 2, fluids, j;
	char hrf[4] = "OTH", herr[255] = "Ok", herr1[255] = "Ok", herr2[255] = "Ok", herr3[255] = "Ok", hfmix[255] = "hmx.bnc", href[3][4] = { "NBP", "OT0", "OTH" }, ac[3] = "NN";
	//REFERENCE STATE
	double h0 = 0, s0 = 0, t0 = 373.16, p0 = 100;
	
	SETUPdll(i, hf, hfmix, hrf, ierr, herr, refpropcharlength * ncmax, refpropcharlength, lengthofreference, errormessagelength); //Legacy API setup function that will be removed in the future, might need to be replaced with High-level API setup function
	SETREFdll(hrf, ixflag, x, h0, s0, t0, p0, ierr, herr, lengthofreference, errormessagelength);
	SATSPLNdll(x, ierr, herr, refpropcharlength * ncmax);

	ABFLSHdll(ab, a, b, x, kq, t, p, d, dl, dv, xliq, xvap, q, e, h, s, cv, cp, w, ierr, herr, ab_length, errormessagelength);
	std::cout << "Q: " << q << std::endl;

	// unit conversion of q, xliq and xvap from mole to mass basis (REFPROP to IPSE units) 
	if (outlet.compare("Q") == 0 || outlet.compare("XVAP") == 0 || outlet.compare("XLIQ") == 0) {
		QMASSdll(q, xliq, xvap, qkg, xliqkg, xvapkg, wliq, wvap, ierr, herr, errormessagelength);
		q = qkg;
	}

	//unit result vector
	int n = 20;
	vector<double> results(n, 0);
	results[0] = t - 273.15;
	results[1] = p / 100;
	results[2] = d * wm;
	results[3] = dl * wm;
	results[4] = dv * wm;
	results[5] = 0;
	results[6] = 0;
	results[7] = q;
	results[8] = e / wm;
	results[9] = h / wm;
	results[10] = s / wm;
	results[11] = cv / wm;
	results[12] = cp / wm;
	results[13] = w;
	results[14] = 1 / (d * wm); //v [m3/kg]
	results[15] = 1 / (dl * wm); //vliq
	results[16] = 1 / (dv * wm); //vvap
	results[17] = 0;
	results[18] = 0;
	results[19] = 0; //this value needs to be a zero

	//unit result matrix
	int coloumns = 3;
	int rows = 20;
	vector< vector<double> > matrix_results(coloumns, vector<double>(rows, 0)); //builds matrix 20 rows, 3 coloumns with 0s
	double sum = 0;
	int k = 0;
	for (int i = 0; i < rows; i++) {
		matrix_results[0][k] = results[i]; //column 0
		matrix_results[1][k] = xliqkg[i];  //column 1
		matrix_results[2][k] = xvapkg[i];  //column 2
		sum += matrix_results[0][k];
		k++;
	}
	return matrix_results;
}
int main()
{
	load(1);
	char rpv[255]; RPVersion(rpv, 255); std::string ver(rpv); auto ispace = ver.find(" "); if (ispace > 0) { ver = ver.substr(0, ispace); }
	std::cout << "REFPROP version: " << ver << std::endl;
	double P, T, H;
	cin >> P;
	cin >> T;
	double a = P, b = T;
	char ab[3] = "PT";
	string outlet = "H";
	int index = 9; // for enthalpy
	double x[2];
	x[0] = 0.15;
	x[1] = 0.85;
	int i = 2;
	double wm = 1;
	char hf[refpropcharlength * ncmax] = "nitrogen.fld|water.fld";

	vector<vector<double>> results = f_abflsh(ab, a, b, outlet, x, i, hf, wm);

	H = results[0][index];

	cout << "H: " << H << std::endl;

	b = H;
	char ab2[3] = "PH";
	outlet = "T";
	index = 0; // for Temperature
	results = f_abflsh(ab2, a, b, outlet, x, i, hf, wm);
	T = results[0][index]; // 0 for temperature

	cout << "T: " << T+273.15;
	cin >> H; //To keep window open
}
```

**Comment by Jonshagen** [comment]
Hi Ian,
Thanks for your help!
I found that I specified the composition in kg/kg and that explains why we get a dry condition. It should be
	x[0] = 0.102;
	x[1] = 0.898;

Can you please try that?
Klas

**Comment by ianhbell** [comment]
Yup, with that composition I now get: 
REFPROP version: 10.0002
6.3
308
Q: 0.894595
H: -6648.86
Q: 999
T: 306.982

**Comment by ianhbell** [comment]
Unfortunately I think you might need to write your own iteration loop to solve the PH flash.

**Comment by Jonshagen** [comment]
Ok, I will iterate T to match the other states via PT. 

Thanks,
Klas
