### ISSUE TITLE
Adding RIEM to REFPROP GUI

### ISSUE THREAD

**Issue by ruppeiner** [usnistgov/REFPROP-issues#450]

**Comment by ruppeiner** [comment]
Dear REFPROP team,

I have a question that maybe you can help me with.

In the path

REFPROP DLL documentation->High-Level API->Function Listing

there is the function RIEM, which is the thermodynamic curvature.

I would like to add RIEM to REFPROP as a menu item in some appropriate place, so that I can evaluate it, tabulate it, and graph it. How would I do this?

I thank you in advance for your help.

—George

George Ruppeiner
Professor of Physics and Astronomy
New College of Florida

**Comment by ianhbell** [comment]
Can you use a programming language like Python? Or Excel? If so, it is available through the REFPROPdll function.

**Comment by EricLemmon** [comment]
There's an option in Refprop that few people have ever tried, but which brings a wealth of new options to the GUI, at least to those of us who fit equations of state.  This is under the Options/Preferences menu and is labeled "Show options used for analyzing equations of state".  Unfortunately when I finished putting the GUI together for version 10, I made the RIEM available only when this EOS option had been activated, and I should have put it in the regular property menus.  That was an oversite that I later corrected in the GUI.

When you enable the EOS option, a new tab will appear in the Options/Properties menu called "EOS".  Under that you will find the RIEM.  Additionally, when you pull down the Plot menu, you will find a slew of new options, one of which is a predefined item to plot the RIEM vs. temperature.  Other strange things will happen with the EOS option enabled, such as the ability to see what the equation of state is doing inside the two phase.  So be warned that plots will behave differently when you enable the "Show 2-Phase" option in the plotting setup menu.

**Comment by ianhbell** [comment]
Good information!

Question was about getting it in tables though, which is not possible, correct? Even with this flag enabled?

**Comment by EricLemmon** [comment]
I've pasted below a screenshot of the Options/Properties menu when the ...analyzing EOS... option has been enabled.

![image](https://user-images.githubusercontent.com/42392984/131695014-1a5b7d67-6502-4e31-804c-fc9cc273a112.png)

Most of the "properties" in this menu are for testing purposes only, but there are a few good ones that we should have included in the other tabs so that they would be available to everyone.

Once the RIEM item has been selected, it can then be added to any table as shown below.

![image](https://user-images.githubusercontent.com/42392984/131695662-2a1b49aa-5034-42d8-92ce-dcb9bfaba3f6.png)

**Comment by ruppeiner** [comment]
Eric and Ian,

Thanks for your valuable thoughts on my question, particularly Eric’s tutorial on how to implement RIEM on REFPROP version 10. This tutorial answered my question, and I can now calculate RIEM completely. To start, I plan to look at liquid Helium 4 and see if I can find negative RIEM, signaling possibly the boson interaction expected in the superfluid.

By the way, the calculation of thermodynamic curvature can be done reliably in binary fluids, using the formula worked out recently for the binary van der Waals fluid. Results are really nice, and extend the basic patterns found in the pure fluid. They also add some new ones. If you would like, we could maybe program this binary fluid formula for curvature into REFPROP, and use it to calculate thermodynamic curvature for real binary fluids.

Again, thanks for your help, and I look forward to calculating RIEM in the pure fluid with version 10 of REFPROP.

**Comment by ianhbell** [comment]
@ruppeiner Glad we were able to help.

Of course, one must be very cautious to infer deep meaning from our thermodynamic models which are at their core just empirical models.  But I am very interested to hear more about your mixture results, particularly if it could be an aid to mixture model development. Is the formula different than for the pure fluid?

You can drop me an email at ian.bell@nist.gov for further discussion if you like.
