### ISSUE TITLE
The problem with density units

### ISSUE THREAD

**Issue by idkakorin** [usnistgov/REFPROP-issues#451]
### Description

The incorrect result for liquid/gas density when the user chooses the following units:
mass/mole g; mol
volume cm^3

### Steps to Reproduce

1. Choose units for mass/mole -  g; mol
2. Choose units for volume - cm^3
3. Choose substance - helium
4. Calculate->Saturation Points(at Equilibrium)
5. Enter the value 4.5 K for temperature

**Expected behavior:** 
The liquid density (g/cm^3): 0.118490
The Capor Density (g/cm^3): 0.022255

**Actual behavior:** 
The liquid density (g/cm^3): 118490
The Capor Density (g/cm^3): 22255

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** Windows 10 Home Edition
**Access Method:** Through official GUI

### Additional Information

When we choose for mass/mole kg; mol
                            for volume m^3
we get the correct values for density:
118.48 kg/m^3 - liquid
22.255 kg/m^3 - vapour.

**Comment by ianhbell** [comment]
Cannot reproduce with REFPROP 10.0.0.02:
![image](https://user-images.githubusercontent.com/11966765/132369962-4e2e7038-ce17-48bc-8341-2023fa549844.png)

**Comment by idkakorin** [comment]
That is my case:
![image](https://user-images.githubusercontent.com/12768579/132383342-1c2fb15d-7ecd-4f45-9a9c-49bccec2050b.png)

1. There is ? instead of the index 3.
2. The density values are not the same as in your case, but they should be that.

May this issue be related to regional settings?

**Comment by ianhbell** [comment]
Yes, I too wonder if somehow this is particular to your computer and its settings.

**Comment by idkakorin** [comment]
What test should I do to check this suggestion?  I am ready to help to find this problem.

I check it on another computer - the situation is the same.

**Comment by ianhbell** [comment]
I have no idea.  Can you use REFPROP from Python/MATLAB/Excel?

**Comment by idkakorin** [comment]
Yes, I can use REFPROP from Python.

**Comment by ianhbell** [comment]
I'm curious to see what value you get from:
```python
import CoolProp.CoolProp as CP
# fld = 'Helium'
fld = 'REFPROP::Helium'
print(CP.PropsSI('Dmass','T',4.5,'Q',0,fld), 'kg/m^3')
print(CP.PropsSI('Dmass','T',4.5,'Q',1,fld), 'kg/m^3')
print(CP.PropsSI('Dmass','T',4.5,'Q',0,fld)*1e3/1e6, 'g/cm^3')
print(CP.PropsSI('Dmass','T',4.5,'Q',1,fld)*1e3/1e6, 'g/cm^3')
```
I get:
```
118.49222494460066 kg/m^3
22.25523963370984 kg/m^3
0.11849222494460065 g/cm^3
0.02225523963370984 g/cm^3
```

**Comment by idkakorin** [comment]
I get the same output:

```
118.49222494460066 kg/m^3
22.25523963370984 kg/m^3
0.11849222494460065 g/cm^3
0.02225523963370984 g/cm^3
```

**Comment by ianhbell** [comment]
That's good.  Problem is only in the GUI then.

**Comment by ianhbell** [comment]
My guess is your computer is skipping the . in numbers like 0.118490 according to your regional settings.

**Comment by idkakorin** [comment]
Could you, please, provide your regional settings for these numbers? I will set the same and test again.

**Comment by ianhbell** [comment]
I have no idea what regional settings impact that.  Maybe @EricLemmon has some idea?

**Comment by EricLemmon** [comment]
Where are you located?  20 years ago when I was developing the GUI I had to put in code to make things work on Asian computers, but then later I found a way to make it work automatically.  Since then I have not received any comments that things were not working, so this really surprises me.

In your Options/Preferences menu there is an option to not use special symbols, but I think that will only fix the ? symbol.  There's also an option to switch the use of commas and periods in numbers.  Give those a try and let's see what happens.

**Comment by idkakorin** [comment]
By the way,  **option to not use special symbols** resolve the problem.
![image](https://user-images.githubusercontent.com/12768579/132749432-d0e3bda9-6e21-430b-8abe-13be0d98abd4.png)

**Comment by ianhbell** [comment]
Super weird...

**Comment by EricLemmon** [comment]
Indeed, but glad it is semi-resolved.
