### ISSUE TITLE
Wrong density values in English units. 

### ISSUE THREAD

**Issue by odrakhnia** [usnistgov/REFPROP-issues#455]
### Description

I needed to export properties at saturation temperature for a couple of refrigerants in "EN" units. All the results were fine except the densities. 

### Steps to Reproduce
1. Selected the fluid R513a.
2. Selected English units in Options. 
3. Calculate -> Saturation Tables @ Liquid and vapor at same compositions, Variable Temperature
4. Temperature range 0 to 200°F, with 1°F step.
4. Selected "SI" units in Options.
5. Repeat step 3.
6. Temperature range 255.45 to 366K, with 0.55K step. 

**Expected results:**
***Results for EN units***
Temperature,   °F | Liquid Density,   lbm/ft3 | Vapor Density,   lbm/ft3
-- | -- | --
0 | 79.76283429 | 0.568361467
1 | 79.65788922 | 0.580586486
2 | 79.55271916 | 0.593017655
3 | 79.4473218 | 0.605657548

***Results for SI units***
Temperature,   K | Liquid Density,   kg/m3 | Vapor Density,   kg/m3
-- | -- | --
255.37 | 1277.67804 | 9.10427735
255.93 | 1275.996981 | 9.300103367
256.48 | 1274.312318 | 9.499231592
257.04 | 1272.624014 | 9.701703255

**Actual results:**
![Screenshot 2021-09-24 161121](https://user-images.githubusercontent.com/91351754/134749876-ec1e298b-05f5-4137-9154-222c019a2f87.png)

### Versions

**REFPROP Version:** 10.0  
**Operating System and Version:** Windows 10
**Access Method:** REFPROP and Excel wrapper  

### Additional Information
The same problem is observed for other fluids (R134a, R245fa, R152a, etc.).
I have double-checked with the other available sources, and the ratio between the results I have obtained was much higher than supposed to be. Something is wrong with the unit conversion, the results I have received are lbm/m^3, not lbm/ft^3.
I have checked the results using Density function, from REFPROP wrapper for EXCEL, with TVAP and TLIQ inputs, and for both SI and EN units. The results from excel were correct. Could you please suggest how to fix this issue?

***Results from Excel***
![Screenshot 2021-09-24 162816](https://user-images.githubusercontent.com/91351754/134750109-ea2524ab-72e6-418e-996d-5bf0af014d00.png)

**Comment by ianhbell** [comment]
The only problem is present in the GUI, right? From the shared library directly I get:

```python
import ctREFPROP.ctREFPROP as c, os
RP = c.REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print(RP.RPVersion())
r1 = RP.REFPROPdll('R513A', 'QT', 'DLIQ;DVAP', RP.ENGLISH, 0, 0, 0, 0, [1.0])
print(r1.Output[0:2])
```
yielding
```
10.0.0.02
array('d', [79.76283428662252, 0.5713477078248257])
```
which agrees, right?

**Comment by odrakhnia** [comment]
Correct, the problem is present only in GUI

**Comment by EricLemmon** [comment]
Can you send Ian an email and he will send you a link to an updated GUI that should fix this.
Ian.Bell@nist.gov

**Comment by odrakhnia** [comment]
Thank you for the advice. 
I have contacted Ian Bell and tried a couple of GUI which he shared. Unfortunately, the results were the same. 
After that, I have installed REFPROP on a new PC, and GUI returned the right results. Looks like the problem is with the OS.

**Comment by EricLemmon** [comment]
Glad to know, sometimes we will never understand why such things happen.  I can imagine how difficult it must be for software developers to write code that works all across the world with so many languages and formats.
