### ISSUE TITLE
h,log-p Diagram

### ISSUE THREAD

**Issue by HenryRudolph** [usnistgov/REFPROP-issues#457]
Gentleman !
I have finished the graphic program for the h,-log p Diagram for **R134a**
Now final I must draw the lines for the **Entropy**.
For the different diagram curces I use for sample the following functions:
+++++++++++++++++Sample only+++++++++++++++++
    Call REFPROP(" ", "Tvap", "p,hvap", 0, TKM, 0#, z, Output, hUnits)
    y = Output(1) * 10
    X = Output(2) - 100
   '------------------------------
    Picture1.PSet (xxc(X), yyc(y))
   '------------------------------   
++++++++++++++++++++++++++++++++++++++++
Now I want to draw the Entropy lines for the values
Entropy               1.70       first       (kJ/kg K)
                           1.75
                               *
                               *
                          2.30       last
For the points „X“ and „Y“ now I can enter in the REFPROP function
for **hIn**  the first Entropy  = 1.70 
and the coresponding different values for the **pressure**
and as result I want to get the **Entropy  hvap**
Can show me please now the **REFPROP function** call, how it must look ?

hIn = Entropy
hIn = pressure
hOut= Entropy  as result !!!

Call REFPROP(" ", "Tvap",-----------
Or
Call REFPROP(" ", "TP",-----------

For  my h,log-p Diagramm which is based on x,y-values I always need
pressure value for „y“ and a enthalpy value for „x“
Now final I need the Entropy lines,
I already have finished the program for
the Saturation -line, temperature- lines and  volume –lines.
Thank you and  greetings from Austria
Henry
rudolphkh@a1.net

**Comment by ianhbell** [comment]
I don't 100% understand your question, but I think you are asking how to plot an isentrope in a p-h diagram?  If so, one approach would be to make ``hIn="PS"`` and ``hOut="H"``, which would give you the x coordinate. Then you go through the set of pressures, calling one at a time to build the curve.

**Comment by HenryRudolph** [comment]
Hi Ian Bell,
thank you for help, but please I need more detail help since I do not find a result.
I want to draw the **entropy lines** in my diagram
I have now the following code:
++++++++++++++++++++++++++++++++++++++++++
'-----**[iu and iMassI have direct set in REFPROP**
    'iU = 3
    'iMass = 1
     -------------------------------------------------------
     Call REFPROP(" ", " ", "DLL#", 0, 0, 0, z, Output, hUnits)
    ---------------------------------------------------------
  Now I want to calculate for the different entropy from 1.70 to 2.40 **Step 0.10** 
  for  each entropy with the pressure from 0.1 to 4.0 (MPa) in small steps to get the y coordinate
 and then I can draw the line
 Please show me how my function calls now must be set:   
 Whhat is my value for a and b ??
   --------------------------------------?-?
    Call REFPROP(RefrREFP, "PS", "H", 0, a, b, z, Output, hUnits)
  ------------------------------------------
Do I also need another Call ?
For one entropy value line  such as 1.70 I think I need many x (H) values and y (P)values 
**Please I kindly ask to show me as full line how the call must be and what are the values for a  and b**
I have so many positive function call in my program but I have a blackout now how to
calculate the entropy lines.
Thank you and greetings from Austria
Henry

**Comment by ianhbell** [comment]
a and b

**Comment by ianhbell** [comment]
are the values of p, and s, respectively.

**Comment by ianhbell** [comment]
Where are you getting this function REFPROP() from?

**Comment by ianhbell** [comment]
Please see https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html

**Comment by HenryRudolph** [comment]
I send a file with all my basic REFPROP Call.
I purchased for some years the REFPROP Software and received a CD -Rom 
I also send a filefor my first result of the R134a Drawing with my REFPROP files, but mow I need
the Call for the Entropy.
For a and b you told me this is p and s

------------------------------------------------------------
Call REFPROP(RefrREFP, "PS", "H", 0, p, s, z, Output, hUnits)
------------------------------------------------------------
x=Output(1)   in (kJ/kg)

p I do enter in (MPa)       ????
s I do enter in (kJ/kg.K)    ????

Is this  now OK ?
[REFPROP_Function.pdf](https://github.com/usnistgov/REFPROP-issues/files/7295533/REFPROP_Function.pdf)
[R134b_02.pdf](https://github.com/usnistgov/REFPROP-issues/files/7295535/R134b_02.pdf)

**Comment by ianhbell** [comment]
The units depends on your choice of unit system. Please see the documentation I linked.  You hard-coded the value of iU = 3, which should be instead obtained from ``GETENUMdll``.

**Comment by HenryRudolph** [comment]
Thanks for the answer, I can not find the documentation, please send it to my mail >rudolphkh@a1.net<

**Comment by ianhbell** [comment]
Please see https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html

**Comment by rudolphkh** [comment]
Hi Eric,
**Call REFPROP(RefrREFP, "PS", "H", 0, p, s, z, Output, hUnits)**
Thank you, I work with this function very well.
Henry

**Comment by EricLemmon** [comment]
You are welcome!

**Comment by HenryRudolph** [comment]
Hi ianhbell,
Hi EricLemmon
I come back to my program for R-407C.
As I told you already, I found a print mistake in the ASHRAE Fundamentals for R407C  Page 30.28.
The diagramwas calculated with Version 7.0
I shows the Entropy at -20 oC with 1.80
When I calulate this value as follows:
TKM = -20
Call REFPROP(" ", "TQ", "S", iU, iMass, 0, TKM, 1, z, Output, hUnits, q, ierr, herr)
Entropy = Output(1)
The Result for Entropy = 1.90
For other points always the result will be instead of 1.90 as result = 2.00 aso.
All other diagram points are valid to my calculation and my drawing look same as ASHRAE drawing.
Greeitngs from Austria
Henry

**Comment by ianhbell** [comment]
Do you use pseudo-pure R407C or the predefined mixture? Did you change the reference state?

**Comment by HenryRudolph** [comment]
I Use predefined mixture. Please help me once again, how is the reference state to change ?

**Comment by ianhbell** [comment]
The reference state setting routine is this one: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETREFdll . See also the code at the top of the VBA provided with the add-in.

**Comment by HenryRudolph** [comment]
In my Visual Basic-6 program to calculate all my REFPROP Valaues and my logPH-Diagramm I use the following:
++++++++++++++++++++++++++++++++++++++++++
 Public Declare Sub REFPROPdll Lib "REFPROP.DLL" (ByVal hFld As String, ByVal hIn As String, ByVal hOut As String,      iUnitNumb As Long, iMass As Long, iFlag As Long, a As Double, b As Double, zm As Double, Output As Double, _
 ByVal hUnits As String, iUnits As Long, X As Double, y As Double, x3 As Double, _
 q As Double, ierr As Long, ByVal herr As String, ln1 As Long, ln2 As Long, ln3 As Long,  ln4 As Long, ln5 As Long)
+++++++++++++++++++++++++++++++++++++++++
Do I need now also similar for some of this DLL files:
+++++++++++++++++++++++++++++++++++++++++
Function Documentation:
subroutine ABFL1dll(a, b, z, kph, ab, Dmin, Dmax, T, P, D, ierr, herr, ab_length, herr_length)
a.s.o.
Please which of them must I use now and how does  the "Public Declare" programming must look for sample 
"subroutine ABFL1dll(a,.........)

**Comment by ianhbell** [comment]
The piece you are missing is this one from the Excel addin:

```vba
        'Use the following line to calculate enthalpies and entropies with a reference state based on the currently defined mixture (and thus calculations will be the same as those produced from the graphical interface for mixtures).
        'See the file manual.txt in your REFPROP\Fortran directory for further information on the use of the SETREF subroutine.
           i = 2 'Set to 1 or 2 (see the SETREF routine in the file SETUP.FOR) or the information on the "Welcome" sheet.
           hFld = "": hIn = "Flags": hOut = "SETREF": Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, i, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
```
