### ISSUE TITLE
h,log-p Diagram for refrigerant R134a

### ISSUE THREAD

**Issue by HenryRudolph** [usnistgov/REFPROP-issues#458]
Gentleman,
adding my question I show attached my result h,log-p Diagram which I have programed with SOLVAY refrigeration functions.
Now I have started to change the program with REFPROP functions.
I build this program also for teaching refrigration technicians.
I hope you like my work.
Greetings from Austria
Henry (Karl-Heinz Rudolph)
[R134a_02.pdf](https://github.com/usnistgov/REFPROP-issues/files/7291994/R134a_02.pdf)

**Comment by EricLemmon** [comment]
Thanks for the plot!  Reminds me of the old days when we used to produce plots for ASHRAE.  I know how difficult it is to make them look good.

**Comment by HenryRudolph** [comment]
Thanks for the nice words. My plots I will program also o show differnt refrigeration cycle to use for teaching refrigeration engineers and refrigeration technician. Greeting from Austria also to Ian Bell who helps me also.
