### ISSUE TITLE
GUI tips:  Adding a fluid to a predefined mixture.

### ISSUE THREAD

**Issue by EricLemmon** [usnistgov/REFPROP-issues#461]
Refprop comes with a slate of predefined mixtures, mostly for refrigerants, to help you quickly select components and their compositions without having to create the mixture manually.  For example, choosing "Air (dry)" in the Substance/Predefined Mixtures menu is the same thing as selecting nitrogen, oxygen, and argon in the Substance/Define New Mixture menu and then entering 0.7812, 0.2096, and 0.0092 for their mole fractions.  The calculations of properties will be identical in both situations.  But what if you want CO2 as part of the mixture, how can you use the shortcut provided by the Predefined Mixtures menu as a starting point?

After selecting "Air (dry)" in the Predefined Mixtures menu, go to Substance/Specify Composition and press the "Add fluid" button.  This will take you to the same menu that you get when you ask for a pure fluid.  Select "Carbon dioxide" and press OK.  The composition screen will reappear with CO2 added, at which point you can enter a value for CO2 and choose the "Normalize compositions to one" option, or you can enter new compositions for everything.  If you already have the compositions entered elsewhere such as Excel, a txt file, and so on, simply copy them while in that program and then use the Paste button to place them into the composition fields.  The GUI recognizes compositions entered by rows or columns in Excel, as lines in a txt file, or as a single line with tab stops between each value.

(Here's a great GUI tip within this GUI tip issue:  If you enter the letter "c" in any of the composition fields, it will calculate the composition of that fluid based on the other compositions so that the sum of all compositions is equal to one!)

(And other tip: In Github, you can receive an email every time an issue is posted to watch what is going on.  Many of the items that are posted will not be of interest to you, but there are a few gems mixed in with all the boring ones.  While viewing an issue in Github, at the top of the webpage on the right is a Watch or Unwatch button with a pull down arrow.  Use the arrow to select the Notification menu and then select "All activity".)

(And one more!  I mark all of the issues with the label "documentation" when I discuss items of interest.  You can search for this label to find these issues and to learn more about Refprop.)

Back to predefined mixtures...

Once you have entered the new mixture, save your mixture!  Under the Substance/Specify Composition menu is a Store button.  First change the name of your new mixture at the top of this menu to a unique identifier that will be used next time you enter the Predefined Mixtures menu (you will need to restart the Refprop GUI to reread the *.MIX files in the Refprop\Mixtures directory before it will appear).  Then press Store and give it a new file name.  This will write out the MIX file.  This is the same procedure that we used to create all of the predefined MIX files in the first place.  In the Refprop\Mixtures directory is a readme.txt file that describes the contents of the MIX files.  

Two other ways are available to store your new mixture.  Under the Options/Save Current Options menu you can save the mixture as a prf file that can later be loaded with the Options/Retrieve Options menu.  If you save it as Defaults.prf, then your new mixture will be loaded each time you restart the GUI.  Second, if you save everything (tables, plots, settings, etc.) under the File/Save menu, you can then retrieve the entire section later with the File/Open menu.

If you have questions, please open a new issue to submit these and we'll respond there.

**Comment by ianhbell** [comment]
How to do this yourself is also described here: https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=2411728801845017631
