### ISSUE TITLE
Specialty Fluids Not in REFPROP 10

### ISSUE THREAD

**Issue by ldequay99** [usnistgov/REFPROP-issues#466]
When working with REFPROP 9.1, I was able to acquire and use fluid and mixture files for hydrogen peroxide, isopropanol, RP-1, and RP-2.  These fluids were not part of the standard REFPROP package at that time, but NIST was able to provide these separately to me.  Can I do the same with REFPROP 10?  If so, do I need and can I acquire the latest versions of these files?

**Comment by ianhbell** [comment]
The fluid files from 9.1 *should* still work in REFPROP 10.  If not, that is a bug and please report it.

**Comment by ldequay99** [comment]
I forgot to retain a copy of the fluid file for isopropanol when acquiring a replacement PC yesterday.  Can someone send me this file?  Thanks.

**Comment by EricLemmon** [comment]
Can you send me a personal email and I'll get these to you:  eric.lemmon@nist.gov

**Comment by ldequay99** [comment]
My e-mail is:   Larry.deQuay-1@nasa.gov

**Comment by ldequay99** [comment]
Thank you, Eric and Ian!
