### ISSUE TITLE
Wrong pressure units in error message

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#467]
I put in a negative pressure to REFPROPdll of -0.1 MPa but the error message says it is -100.0 MPa.  I think the error message should be -100.0 kPa?

```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)
print('REFPROP: ', RP.RPVersion())
r = RP.REFPROPdll('CO2','TP','D',RP.MASS_BASE_SI,0,0,400,-0.1e6,[1.0])
print(r.ierr, r.herr)
```
yields
```
REFPROP:  10.0.1.14
143 [TPFLSH error 143] Input value equal to or less than zero: P = -100.000 MPa.
```

**Comment by EricLemmon** [comment]
Fixed.  It now returns a value of -0.1 MPa in the error message.

**Comment by ianhbell** [comment]
Fine now.  But still odd that the pressure unit is MPa since all other internal pressures are in kPa.  Just a comment, can be left.

**Comment by EricLemmon** [comment]
All pressure units are converted to MPa before reporting them in the error messages.  You just happened to find the one that got missed!  (Thanks!)
