### ISSUE TITLE
How to increase Tmax for a hydrogen-methane mixture

### ISSUE THREAD

**Issue by alastmurray** [usnistgov/REFPROP-issues#470]
Hi,

I am currently trying to predict the enthalpy of a high-temperature stream of methane and hydrogen (>1200K). This is not currently supported under the default EOS so I was just wondering if you have a recommendation for how to adjust the Excel macro to calculate and enthalpy at higher temperatures and increase the Tmax? This is the error I currently get:

#[TPFLSH error 1] One or more inputs are out of range; Temperature above 1.5x(upper limit): T = 1000.00 K, Tmax = 625.683 K.

Any input would be greatly appreciated, thanks in advance.

Best,

Alastair Murray

**Comment by EricLemmon** [comment]
Hi Alastair,

You inspired me to write some details about extrapolating equations of state.  They can be  found at #471 and #472.

The hydrogen equation of state will extrapolate safely to 1200 K, at least for thermodynamic properties.  If you are interested in transport properties as well, we will need to look into their formulations to determine if they can also be extended.

Eric

**Comment by alastmurray** [comment]
Hi Eric,

Thanks for the help on this. I've been able to get the enthalpy to run under an assumed density, but when I try to calculate density to use for enthalpy (based on T and P) I get the following message: 

#[TPFLSH error 1] One or more inputs are out of range; Temperature above 1.5x(upper limit): T = 1160.00 K, Tmax = 625.683 K.

This should be within the EOS bounds for a hydrogen-methane mixture to my understanding based on your updates, but please let me know if I've misinterpreted or if you have any advice. Again I really appreciate all of your help.

Thanks,

Alastair

**Comment by EricLemmon** [comment]
Can you send me the file you modified so that I can check it here?  eric.lemmon@nist.gov

**Comment by alastmurray** [comment]
Definitely, I've just passed that along
