### ISSUE TITLE
"SI" should maybe not be allowed?

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#474]
Evidently "SI" is a valid unit system, and maps to "MASS SI", but this isn't documented.  I think it should be an error, or at least a warning, and the Excel notebook should remove reference to "SI"

**Comment by EricLemmon** [comment]
The unit label "SI" was actually the second unit I added to the brand new Excel spreadsheet so many years ago ("molar SI" was the first), and is probably the most common unit label in all Refprop workbooks out there.  Making that an error would break them all.  And even making it a warning would be confusing to many.  I think it's best to leave as is.  The differences between molar and mass densities or molar and mass enthalpies is so large that it shouldn't cause much, if any, confusion.  We just need to add it to the documents.

**Comment by ianhbell** [comment]
It would be better to push people to migrate to "molar si" or "mass si" by updating the demos at least; "SI" is not a thing in the enumerated unit systems. Hard-coded magic is best avoided.

**Comment by EricLemmon** [comment]
We definitely can do that, I'll make the changes in the Excel file (and elsewhere).
