### ISSUE TITLE
Using ABFLSH with T and p as input to yield q

### ISSUE THREAD

**Issue by SWiell** [usnistgov/REFPROP-issues#477]
Hi, 

I am using ABFLSH to yield q by using t and p as inputs in the two phase region. I have done the same simulation for pure water and the result is constantly q = 998 (Superheated vapor, but quality not defined (usually T > Tc)), which is not true as I am sure I am in the two phase region. I am aware that finding q based on t in the two phase region has infinite number of solutions and therefore it is somewhat missleading that this answer is given and no error messages. 

It works fine using h and p as inputs to yield a correct q so I have solved the problem that way, but I wanted to share what I came across. 

Im using Refprop version: 10.0.0.97.

**Comment by ianhbell** [comment]
Please provide a runnable example.  Otherwise I have no idea what you did. I have some guesses...

**Comment by HenryRudolph** [comment]
I will made an install.exe from my program called "Refr_diagram,exe". I use for my Visual basic- 6 programs "InstallShield.Express"
but I need now about 1 week to send the file.

**Comment by EricLemmon** [comment]
I think Ian wants a bit of code to test things, not an executable.  You should not put up your installer on this website, that does not help debug the problem.

**Comment by ianhbell** [comment]
@SWiell in particular I need to know what fluids and composition, what values of T and p and if you changed any of the defaults for reference states and so on.

**Comment by HenryRudolph** [comment]
Is it helpfull when I send only a copy of my Visual basic-6 Source Code as *zip file which shows all the functions I use for
my Diagramm and also for calculation of property tables like in the ASHRAE Handbook ?
I only still work with Visual basic-6 and not with Visual basic-Net Code.

**Comment by ianhbell** [comment]
@HenryRudolph please keep your correspondence regarding your issue in your issue: #475

**Comment by SWiell** [comment]
Im using pure water, p = 1 bar and T = 99.606°C. I have my reference state at: h0 = 0 J/mol, s0 = 0 J/molK, t0 = 373.16 K, p0 = 100 kPa. This gives med q = 998 and h = -15.12 J/mol. Using this h as input together with p = 1 bar gives q = 1 which it true.

I might be able to provide you with a runable example but it is outside my knowledge how to do that at the moment unfortunately and will take me some time. 

Thanks for support!

**Comment by ianhbell** [comment]
Ah, right. I proposed: https://github.com/usnistgov/REFPROP-issues/issues/82 . CoolProp does what I proposed and I think it is the right solution for pure fluids.

For your use case, you should set the phase to ensure you get the liquid or vapor solution.
