### ISSUE TITLE
Should first check existence of model

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#479]
### Description

When a melting curve output is requested, the first check should be whether the model is available.  If not, no calculation should take place. At 0 K, a flash calculation is tried.

### Steps to Reproduce

```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)
print('REFPROP: ', RP.RPVersion())

for T in [0.0, 100.0]:
    r = RP.REFPROPdll("ACETONE", "TMELT","P", RP.MOLAR_BASE_SI, 0, 0, T, 101325, [1.0])
    print(r.Output[0], r.ierr, r.herr)
```
yielding
```
REFPROP:  10.0.1.17
-9999990.0 203 [TPRHO error 203] Vapor iteration has not converged for T = 0 K and P = 0 MPa.
-9999990.0 501 [MELTK error 501] Equation not available.
```

**Expected behavior:** at T=0 K, error code is 501, no value is returned

**Actual behavior:** at T=0 K, error code is not 501

Test added here: https://github.com/usnistgov/REFPROP-tests/commit/eae748b6ceafefcc3cf766c008aa236edaa3a586

**Comment by EricLemmon** [comment]
This is fixed now.

**Comment by ianhbell** [comment]
Yup, works now.
