### ISSUE TITLE
Density Function using Air

### ISSUE THREAD

**Issue by hdschwei** [usnistgov/REFPROP-issues#481]
Several years ago I put together some VBA code using a lot of code examples from the Excel file that came with REFPROP 7.
Over the years I’ve upgraded the refprop.dll file and the files in the Fluids and Mixtures folders for this application. Everything worked well.
I’m presently using version 9.1.1.11 of the dll file and its associated files in the Fluids and Mixtures folders. The other code in the app is still the original code based on code from the REFPROP 7 Excel file.
I recently needed to find the density of Air but I get the following error message: “Density = "[SATT error 121] Temperature input to saturation routine is great...“
My inputs to the function are 77 ⁰F and 187 psia. 

Any idea what I need to do to correct this issue?
REFPROP.EXE does return a good value for Density with these inputs.

`

**Comment by ianhbell** [comment]
What is the complete error message?

**Comment by hdschwei** [comment]
The error message is truncated to what I posted.
Is there a way to show the complete message in VBA?

**Comment by ianhbell** [comment]
Are you using pseudo-pure air or predefined mixture?

**Comment by ianhbell** [comment]
Well, in the debugger you should be able to see the complete 255 character string.

**Comment by hdschwei** [comment]
Predefined mixture, “Air.mix”

**Comment by ianhbell** [comment]
Did you enable saturation splines?

**Comment by ianhbell** [comment]
There is a reason we ask issue reporters to fill out the issue template, saves us a lot of time asking questions.

**Comment by hdschwei** [comment]
No, not familiar with the term.
Is this something specifically required for air, never done this for refrigerant mixtures.

**Comment by ianhbell** [comment]
Well, if you are using air, I would recommend the pseudo-pure air anyhow. Saves you a lot of headaches.

For saturation splines: https://github.com/usnistgov/REFPROP-wrappers/issues/106

**Comment by hdschwei** [comment]
Thanks, I’ll use the pseudo-pure file and check into SATSPLN.
