### ISSUE TITLE
How REFPROP is calculating speed of sound for mixtures?

### ISSUE THREAD

**Issue by masoud-babaei** [usnistgov/REFPROP-issues#482]
How REFPROP is calculating w (speed of sound) for mixtures? is it based on Newton–Laplace equation? If so does REFPROP calculate Ks (isentropic bulk modulus) from two-phase flash for mixtures?

**Comment by ianhbell** [comment]
I tidied up your question.

The speed of sound is obtained from the equation of state.  In particular, in terms of derivatives of the Helmholtz energy with respect to reciprocal temperature and density.  This is explained in the GERG-2004 monograph: https://www.gerg.eu/wp-content/uploads/2019/10/TM15.pdf ; in particular see Table 7.1

**Comment by nist-aharvey** [comment]
The original post seems to also be asking about 2-phase systems.  The thermodynamic speed of sound (which is based on the Newton-LaPlace equation so it is related to the isentropic compressibility) is only defined for homogeneous, single-phase systems (which can be a pure fluid or a mixture).  If you ask REFPROP for the sound speed in a 2-phase condition, it will tell you that the quantity is "Undefined."

**Comment by ianhbell** [comment]
And a conceptual explanation for _why_ it is undefined is that if you have two phase in equilibrium, there are two different speeds of sounds you can talk about: that of the vapor phase and that of the liquid phase.

**Comment by masoud-babaei** [comment]
Thank you for the clarifications.

**Comment by nist-aharvey** [comment]
A further part of the explanation is that, while sound is transmitted in 2-phase systems, the speed of sound cannot be obtained only from thermodynamics.  The effective sound speed in a two-phase system also depends on the physical arrangement of the phases in the system -- for example whether one phase is dispersed as small droplets or bubbles in a continuous phase, or in a flowing system if you have annular flow or slug flow, etc.
Such calculations involve fluid mechanics -- all REFPROP can do is give you the thermodynamic sound speed within the vapor and liquid phases and then it is up to the user to use appropriate tools of fluid mechanics and knowledge of the specific engineering situation to combine these into an appropriate effective sound speed for a two-phase system.

**Comment by masoud-babaei** [comment]
Yes, that is, I think, the patchy vs. uniform distribution of phases.
