### ISSUE TITLE
Questions about Mixing Parameters of CO2+HFC-161 by REFPROP 10.0

### ISSUE THREAD

**Issue by RayleighSun** [usnistgov/REFPROP-issues#483]
Hello, 

I recently encountered a problem when using REFPROP 10.0 for calculating thermodynamic properties of **CO2 + HFC-161 binary mixture**:

A warning was given in the GUI of REFPROP 10.0 that mixture data have not been fitted for this binary mixture and the mixing parameters have been estimated. There is also such a reminder on the next interface, **but here give the parameters of gammaT (1.0126) and gammaV (1.0229)**. 

I am confused that where do these two parameters come from? Are these parameters selected from some other mixture (then what is it)?

This problem has troubled me for a long time, and I hope to get your help.

**Comment by EricLemmon** [comment]
Take a look at this one, hopefully it will help:

https://github.com/usnistgov/REFPROP-issues/issues/248

**Comment by RayleighSun** [comment]
Thanks a lot, Mr. Lemmon!
