### ISSUE TITLE
Fluid files for NO, NO2 and maybe C2H6S...

### ISSUE THREAD

**Issue by sinavskis** [usnistgov/REFPROP-issues#484]
Hello,

Is there possibility to get xxx.FLD for nitrogen monoxide (NO) and nitrogen dioxide (NO2)?

And maybe dimethyl sulfide (C2H6S) also available?

Thanks in advance.

**Comment by ianhbell** [comment]
Currently no, we do not have fluid files for any of these fluids.  But you could model (at least the last one because it is non-reactive) with Peng-Robinson

**Comment by EricLemmon** [comment]
We are working on equations for NTO (N2O4 + NO2) as well an equation for NO, but it will still be a while before they are ready and we have nothing preliminary that we could give to you.  Can you send me a personal email:  eric.lemmon@nist.gov
