### ISSUE TITLE
I get two different answers for speed of sound between MATLAB and Jupyter wrapper (please see the comment section)

### ISSUE THREAD

**Issue by masoud-babaei** [usnistgov/REFPROP-issues#485]

**Comment by masoud-babaei** [comment]
In MATLAB:

refpropm('A','T',298,'P',101.325,'CO2', 'Methane',[0.4, 0.6])

ans =

  **386.6521**

In Jupyter:

units = RP.GETENUMdll(0,'DEFAULT').iEnum
out = RP.REFPROPdll("Carbon Dioxide * Methane","TP","W",units,0,0,298,101.325,[0.4, 0.6])
assert(p.ierr == 0)
W = out.Output[0]
W

**343.11656496876856**

**Comment by ianhbell** [comment]
Compositions.  One is on a molar basis (``REFPROPdll``), and in ``refpropm``, on a mass basis.  

``refpropm`` is deprecated, you should move to Python interface in MATLAB.

**Comment by masoud-babaei** [comment]
Thanks, all resolved.

**Comment by EricLemmon** [comment]
I've moved your issue to the wrappers website.
