### ISSUE TITLE
question: how to tell if binary interaction parameters are in use?

### ISSUE THREAD

**Issue by walterhw1950** [usnistgov/REFPROP-issues#49]
1) Is there a way to tell, using the Excel wrapper function, whether or not binary interaction parameters BIPs are available for a particular pair of components?  

2) If BIPs are available, are they always used in mixtures?  

3) Is there a way to disable/enable use of BIPs so the results can be compared?

**Comment by ianhbell** [comment]
In short, the answers to all your questions are yes, except you can't easily answer your questions from Excel.  From an environment like Python, no problem.  But the Excel wrapper was explicitly designed for lowest-common-denominator kind of work -- give a state point, get a value.


You need to call other functions in the DLL to get access to the information you desire.  But it is all there if you can use another environment for which we have already developed a robust wrapper (e.g., Python).

**Comment by walterhw1950** [comment]
I'd like to write separate VB functions that accesses the DLLs to query/set BIP usage.  I'm thinking of something like

Function queryBIP(arguments...) as boolean 'returns TRUE if BIPs are in use
    call REFPROP() to ensure environment is set up correctly
    queryBIP = directDLLaccess(arguments) to retrieve result
End Function
and
Function setBIP(BIPs as boolean, arguments...) as boolean 'returns TRUE if BIPs are in use
    call dllAccess() to set/reset use of BIPs
    call REFPROP() to ensure environment is set up correctly
    setBIP = directDLLaccess() to retrieve result
End Function 

Is this approach good enough?  
What am I overlooking?  
What DLLs and function calls should I be looking at?

**Comment by ianhbell** [comment]
You should be looking at the GETKTVdll function to obtain the interaction parameters, and checking the ierr code when you call SETUPdll to know whether parameters were available for the mixture you set up or not.

________________________________

**Comment by walterhw1950** [comment]
Just in case anyone else is interested, it is possible to test for the use of binary interaction parameters using the VB wrapper supplied with REFPROP10.0.  Paste "=REFPROP("FIJMIX","R114;R125|.5,.5",,,1,2)" into a cell and the returned value of 1.0 is the first binary mixture parameter for the pair R114 and R125.  

Error messages are sometimes returned, for example:
#[SETUP error 117] Mixture data have not been fitted for one or more binary pairs in the specified mixture; the mixture is outside the range of the model and calculations will not be made.
and
#[SETUP error 117] Estimation of mixing parameters is not possible for most mixtures containing water, helium, hydrogen, neon, carbon monoxide, fluorine, methanol, or ethanol.

I don't know enough to know if an error message is always returned if binary parameters are not used, so I replaced the line
``` VB
REFPROP = Output(1)   'Load the requested property into the function value.
```
after the last call to REFPROP() with
``` VB
  If ("fijmix" = OutputCode) And (Not (ierr > 0 And Abs(ierr) < 10000)) Then
      Dim outTemp As String, ii As Integer
    outTemp = Left(hUnits, 3)
    For ii = 1 To 6
      outTemp = outTemp & "," & Output(ii)
    Next ii
    REFPROP = outTemp
  Else
    REFPROP = Output(1)   'Load the requested property into the function value.
  End If
```
By using a lower case output code argument, the returned value is a string listing the mixing rule and its 6 binary parameters.  
"=REFPROP("fijmix","R114;R125|.5,.5",,,1,2)" returns the string "XR0;1;0.964040930867582;1;1.00975193106147;0;0" indicating the XR0 mixture model is used.
