### ISSUE TITLE
Small bug in Define Mixture window

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#490]
This is in REFPROP 10.0, running the Windows GUI.

1) Start program, select Define New Mixture
2) Add component Nitrogen
3) Realize that the next thing you want to Add (Novec 649) is not in the Common Fluids list, so select All Fluids.
4) It gives a warning that selecting a new Fluid Set will delete the fluids you have already added.  It would be desirable if it would keep the components you have already added, but that's not the bug (maybe that's a Feature Request).
5) Hit OK on the warning.
6) It deletes Nitrogen, but it puts me back with the "Common Fluids" list.
The expected behavior would be that, after the warning, it would put me in the list I had selected.

**Comment by EricLemmon** [comment]
I believe this is fixed now, I'll send you a link to the new exe.

**Comment by nist-aharvey** [comment]
I just tried the new .exe and the bug is still there.

**Comment by EricLemmon** [comment]
Bug is fixed now.
