### ISSUE TITLE
Cell addresses for FLUID NAME(S) and Component Fractions

### ISSUE THREAD

**Issue by DavidStaz** [usnistgov/REFPROP-issues#491]
DavidStaz; new member to GitHub

###
Not an "issue" per se, except that I can't accomplish what I'd like:
• Attempting to make an Excel (Excel 2016, on Windows 10 Pro) tool that calculates properties of cryo fluids with variable, user-defined inputs.
Ideally, REFPROP (v10.0) properties formulae would accept cell addresses for several components (say 4 - 6), and the mass/mole fractions for each, including '0' for when a component on the list isn't used for a particular calculation.
• I have tried various syntax, as per the examples in the REFPROP "help" tabs, but have been unsuccessful.  If, for example, I attempt to point to cell E37 for the text value of a REFPROP name of a component, the tool tells me that it can't find component file E37.FLD in the REFPROP library.

FOR EXAMPLE:
=REFPROP("H","E121;E122;E123|0.8;0.15;0.05","TP","SI",300,2.8)
YIELDS:
#[SETUP error 101] Error in opening file for component 1: filename = E121.FLD in the path C:\Program Files (x86)\REFPROP

**Comment by ianhbell** [comment]
Do you know about the FluidString10 function? Used for precisely this case.

**Comment by ianhbell** [comment]
See cell E12 on Mixtures page

**Comment by DavidStaz** [comment]
Didn't know of it; new to REFPROP, and getting myself injured clanging around as much as I've been.
What you've referred to looks like the very thing.
A thousand thanks!!

**Comment by ianhbell** [comment]
Please make sure you read over the entire Excel spreadsheet, it has lots of useful information.

**Comment by DavidStaz** [comment]
Yes; guilty as implied.
RTFM!  (Though info doesn't 'stick' well until it's needed.)
