### ISSUE TITLE
GUI tables: mark cell that were input

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#492]
When using "Calculate, specified state points" tables, it would sometimes be convenient to see which cells were inputs, and which ones were outputs/calculated. In the screenshot, I used yellow background to mark the cells that were prescribed, all others normal/white cells are thus calculated form the two yellow cells.
Just an idea, very low priority, maybe you do not even like it at all.

![RefProp_Water](https://user-images.githubusercontent.com/314571/146367261-ae3d4c74-a751-4531-805f-98f8505b05c6.png)

**Comment by ianhbell** [comment]
Good idea! But probably won't get implemented as we are rolling out a new web interface (you'll be on the email list) and our focus is there.

**Comment by EricLemmon** [comment]
You can imagine that this request has come up many times before!  When I wrote the GUI then it was one of those things I wanted too, but there was no way to set the color or other properties in a single cell to be different from the others.  With a lot of crazy programing I probably could have found a way, but it would have been a serious cludge with some possibilities of errors if the superimposed cell did not line up correctly.  So I abandoned the idea and moved on.  Even such things as simply bolding the contents in a single cell are not available.  Pity.
