### ISSUE TITLE
REFPRP64.DLL cannot run if FLUIDS and MIXTURE is not in C:\Program Files (x86)\REFPROP

### ISSUE THREAD

**Issue by tripheo0412** [usnistgov/REFPROP-issues#494]
### Description

Hi, we have a desktop app written in VB and using `REFPRP64.DLL` to calculate. 
It works fine on PC when you can copy `FLUIDS` and `MIXTURE` folder to `C:\Program Files (x86)\REFPROP`. But on cloud environment (to be specific Azure App service). We cannot do this because we don't have permission.
Is there any way to dynamically link `REFPRP64.DLL` with `FLUIDS` and `MIXTURE`?

Thank you!
### Steps to Reproduce

1. Install Refprop through the provided installer into any folder different than `C:\Program Files (x86)\REFPROP`
2. Call function in REFPRP64.DLL, get the wrong result
3. Copy `FLUIDS` and `MIXTURE` folder to `C:\Program Files (x86)\REFPROP`
4. Call function in `REFPRP64.DLL` again, get the correct result.

**Expected behavior:** `REFPRP64.DLL` can run if `FLUIDS` and `MIXTURE` are in same directory.

**Actual behavior:**  If `FLUIDS` and `MIXTURE` folder are not in `C:\Program Files (x86)\REFPROP`. `REFPRP64.DLL` does not run correctly.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** VB app through REFPRP64.DLL  

### Additional Information

We host our VB app in Azure app service, windows environment.

**Comment by EricLemmon** [comment]
Can you send an email to Ian.Bell@nist.gov?  He'll forward it to my personal account so that we can take this offline.

**Comment by tripheo0412** [comment]
@EricLemmon email sent, thank you for the fast response!

**Comment by tripheo0412** [comment]
Found out that you can dynamically set Refprop dependencies location by adjust the value of `RPprefix` env variable
