### ISSUE TITLE
Installation by administrator guidelines

### ISSUE THREAD

**Issue by BrunoLaloy** [usnistgov/REFPROP-issues#498]
Dear Sir, Madam,
 
My laptop was recently re-imaged by IT Service Desk, and Refprop v10 was installed on Windows 365 environment, but the program stores the mixtures in another folder than the one from Programs x86.
 
Unfortunately, the collaboration with other tools is then broken.
 
In the meantime, I don’t succeed to get Excel collaborating with Refprop v10.
 
Would you have some guidelines for a proper installation since my IT Service Desk does not succeed solving these issues ?
 
Thanking you in advance,
 
Best regards

**Comment by EricLemmon** [comment]
Take a look through the issues here that discuss the RPprefix environment variable, hopefully that does the trick.

https://github.com/usnistgov/REFPROP-docs/blob/nist-pages/index.md#resolving-problems-linking-with-excel
https://github.com/usnistgov/REFPROP-wrappers/issues?q=rpprefix

Even better would be to uninstall and then reinstall in your Users directory or the root of your C drive.  Then Windows will not try making ghost directories that really mess things up.
