### ISSUE TITLE
Error in density calculation close to critical point for R410A.MIX for DLL calls but not GUI

### ISSUE THREAD

**Issue by crlaugh** [usnistgov/REFPROP-issues#499]
When calculating the density in the two-phase region near the critical point for R410A.MIX, I find that the output has step-like discontinuities in the middle of the two-phase region when using DLL calls, but not when using the GUI.  

For example, I have used the following Julia code that employs the ctypes REFPROP interface to calculate the density along a line of constant pressure; slight modifications may be needed to run this on a given platform (e.g., the GETENUMdll line).

```
RP = REFPROPEOS()  # This line sets up the ctypes interfaces to the REFPROP DLL. 
DEFAULT = GETENUMdll(RP, 0,"DEFAULT")["iEnum"]
PVal = 4580
hBub = REFPROPdll(RP, "R410A.MIX", "PQ", "H", DEFAULT, 0, 0, PVal, 0, [])["Output"][1]
hDew = REFPROPdll(RP, "R410A.MIX", "PQ", "H", DEFAULT, 0, 0, PVal, 1, [])["Output"][1]
hVec = hBub-200:5:hDew+200
dVec = zeros(size(hVec))
xVec = (hVec.-hBub)./(hDew - hBub)

for (ih, hVal) in enumerate(hVec)
    dVec[ih] = REFPROPdll(RP, "R410A.MIX", "PH", "D", DEFAULT, 0, 0, PVal, hVal, [])["Output"][1]
end

plot(xVec, dVec)
```

The resulting plot is as follows: 
![image](https://user-images.githubusercontent.com/9616147/149028547-1c3690db-6d82-4c10-99f6-5bbdd0ba446f.png)

However, when I use the GUI to manually calculate the density at the same values of P and h, I do not see the discontinuities in the density - the curve appears to be smooth.  

I therefore have two questions:

1. How does the GUI calculate the density, as opposed to the high-level interface? 
2. Is there some way to make the high-level interface (or, ideally, the low-level interface) produce the density calculations without these artifacts?  

I am using REFPROP version 10.0.0.97 on a Win10 machine.

**Comment by ianhbell** [comment]
Yes: call ``SATSPLNdll`` which will build the saturation spline for this mixture composition. In ``REFPROPdll``, that is the ``iFlag`` argument

**Comment by crlaugh** [comment]
Beautiful - works like a charm.  Many thanks for the quick response.
