### ISSUE TITLE
Callable ENERGYdll() missing in the DLLs

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-issues#5]
The thermodynamic properties as a function of T, rho, and x are provided in ENTHAL(T, rho, x, h), ENERGY(T, rho, x, h), ENTRO(T, rho, x, h), etc.   Each of these has a companion callable routine in the DLLs through PASS_FTN.for.  Like:

ENTHALdll()
ENTROdll()
CVCPdll()

However, there is no DLL function call for ENERGYdll().  There are ways around this, but publishing this function to the DLLs would be very convenient.

An equivalent set of routines SPEED(T,rho,x,w) and SPEEDdll() would also be very convenient.  SPEED() can easily be written as a simple modification to CVCP(), and then published in PASS_FTN.for.

This would make these functions callable from the DLLs without the user having to rebuild them (I suspect most of your users are not up for that anyway).

We have REFPROP 9.1.1, but haven't gotten REFPROP 10 yet.  If these functions are there, please disregard.

Thanks!

**Comment by ianhbell** [comment]
Overall the current thinking for REFPROP is to avoid adding functions to the DLL unless absolutely necessary, and this problem can be solved by calling the THERMdll function, so I don't see a pressing need to add the SPEEDdll function to the dll. Anyway, the REFPROP function covers this output, and is the recommended interface for version 10.

**Comment by henningjp** [comment]
It's an issue of execution speed.  If the calling code only needs one of the thermodynamic properties, say many thousands of times over a range of temperatures and pressures, it doesn't make sense to call THERMdll, which calculates and returns all eight thermodynamic values (P, H, U, S, Cv, Cp, W, hjt), when all that is needed is one.  An 8:1 speedup is significant.

**Comment by ianhbell** [comment]
Actually, you should probably profile this - the derivatives of Helmholtz energy are cached, so there should be essentially no computationally penalty I would think

**Comment by henningjp** [comment]
OK, I'll check.
