### ISSUE TITLE
Excel and REFPROP V10a

### ISSUE THREAD

**Issue by mdsrjw** [usnistgov/REFPROP-issues#50]
I have recently installed REFPROP V10a (clean install) and attempted to integrate it with Excel in Office 2010.  I discoveredthat the call for excel based functions has completely changed from previous versions of REFPROP.  Here is what I am seeing:

REFPROP(OutputCode,FluidName,InpCode,Units,Prop1,Prop2,Props3)

This is as opposed to the previous methodology, taking “density” as an example:

=Density("argon","TP","E",100,250)

I am assuming that this is by design and not some indication of a problem with the program installation and integration with Excel?

**Comment by ianhbell** [comment]
Correct, this is to be expected! Did you see the huge warning box in the sample Excel spreadsheet 😊?  There is also a macro in the Excel sheet that can upgrade your sheet to use the new interface.

________________________________

**Comment by mdsrjw** [comment]
I'm sorry, but I did not open the Excel spreadsheet since there was no
reason I could think of to assume that anything had changed with the
interface with Excel.  It does however mean that the previous work we've
done in integrating Refprop with Excel now requires a full reboot.  I just
wanted to be sure that I didn't just miss a switch or something.  Thank you
for your reply.

**Comment by jeffkshaw** [comment]
they wrote a script that converts most of these for you, it prompted me
when i ran in the install on how to invoke it.

**Comment by EricLemmon** [comment]
Does this give you the information that you need?  If so, could you close this issue?  If not, let us know and we'll help out!

**Comment by mdsrjw** [comment]
Closed.  Thank you all for your help.
