### ISSUE TITLE
Calculation of dP/dT along saturation line (result of DPTSATKdll) for mixtures - REFPROP10

### ISSUE THREAD

**Issue by trabucs** [usnistgov/REFPROP-issues#500]
Hello, 
I am facing an issue with REFPROP10 dlls regarding the calculation of dP/dT along saturation line for mixtures (not dP/dT at the saturation line for the single phase state, but the change in saturated vapor pressure as the saturation temperature changes!). 
I am using the REFPROP1dll instead of the DPTSATKdll, since I am updating all the interfaces to the new high level API, coding in C++.
For pure fluids I get a value, while for mixtures (e.g. R410A) I get the value -9999990 (=not calculated value). If I call the subroutine DPTSATKdll I get a value.

### Steps to Reproduce

1. Set the mixture fluid:
``` c++
SETMIXTUREdll(hf, z, ierr, hMixNme_length);
ERRMSGdll(ierr, herr, errormessagelength);
```
where hf is "R410A.MIX". 

2. Call the REFPROP1dll subroutine to retrive the desired value:
``` c++
REFPROP1dll("TQ", "DPDTSAT", iUnits, iMass, t, b, z, dpt, qq, ierr, herr, hIn_lenght, hOut_lenght, herr_lenght);
```
where t is the temperature value and b is the phase (0 = liquid, 1 = vapor).

**Expected behavior:** I should get a value, like with 9.1 dlls version:
``` c++
Initialize the library for R410A.MIX t:273.150000 K p:200.000000 kPa
REFPROP VERSION: v9.1
 - molar weight 72.585414 kg/kmol
 - density vap 6.636001 kg/m3
 - density real 6.636001 [kg/m3]
 - density liq part 6.636001 [kg/m3]
 - density vap part 6.636001 [kg/m3]
 - quality: superheated vapor, quality not defined
 - enthalpy 438.569540 [kJ/kg]
 - entropy 2.085055 [kJ/kgK]
 - heat capacity 0.823605 [kJ/kgK]
 - dPdT 21.183964 [kPa/K]
 - Viscosity 12.228819 [uPa*s]
```
N.B: I get the same value (21.1839 .....) both with vapour and liquid phase set in DPTSATKdll.

**Actual behavior:** I get the "no calculation" value:
``` c++
Initialize the library for R410A.MIX t:273.150000 K p:200.000000 kPa
REFPROP VERSION: v10
 - molar weight 72.585414 kg/kmol
 - density vap 6.636001 kg/m3
 - density real 6.636001 [kg/m3]
 - density liq part 6.636001 [kg/m3]
 - density vap part 6.636001 [kg/m3]
 - quality: superheated vapor, quality not defined
 - enthalpy 438.569540 [kJ/kg]
 - entropy 2.085055 [kJ/kgK]
 - heat capacity 0.823605 [kJ/kgK]
 - dPdT -9999990.000000 [kPa/K]
 - Viscosity 12.228819 [uPa*s]
```

### Versions

**REFPROP Version:** [REFPROP 10]  
**Operating System and Version:** [OS Windows 10]  
**Access Method:** [C++ code]  

### Additional Information

Is this related to a calculation bug or to other reasons? I tried to evaluate the derivative numerically in Excel (with a variation of +-0.01K on temperature), and for instance I get the same value of DPDTSAT for CO2:
![image](https://user-images.githubusercontent.com/97669416/149316095-d60b2364-b610-4ecd-bc3d-db8c317e44cd.png)
With R410A I get:
![image](https://user-images.githubusercontent.com/97669416/149316549-e0ab7e47-3c7d-48f9-b1f8-5f4c967c5c42.png)

I also did the test with REFPROP.EXE and I get no values as well:
![image](https://user-images.githubusercontent.com/97669416/149316886-7c377df0-26a0-487f-a19a-6109e206a7f7.png)

Thanks for your help!

**Comment by ianhbell** [comment]
Important point to note: ``DPTSATKdll`` returns the pressure derivative along saturation for the i-th component, not for the mixture.  There are ways to get the analytic derivative along the saturation curve at constant composition, but they are not implemented in REFPROP currently.

**Comment by KoldMen** [comment]
Generate a phase envelope by varying the density from say 0.1 to 30 kmol/m3. Try to fit a polynomial locally in the region where you want dp/dT to determine dp/drho and dT/drho. Calculate dp/dT. See if this works for you.

**Comment by trabucs** [comment]
> Important point to note: `DPTSATKdll` returns the pressure derivative along saturation for the i-th component, not for the mixture. There are ways to get the analytic derivative along the saturation curve at constant composition, but they are not implemented in REFPROP currently.

Thanks Ian for the note. In the REFPROP9.1 version of the code we were (wrongly) considering dP/dT of i-th component as dP/dT of the whole mixture. 

> Generate a phase envelope by varying the density from say 0.1 to 30 kmol/m3. Try to fit a polynomial locally in the region where you want dp/dT to determine dp/drho and dT/drho. Calculate dp/dT. See if this works for you.

@KoldMen, in v10 code I implemented a manual calculation as described above, which for our needs is quick and dirty. 

Thanks for the support, we can close the issue.
