### ISSUE TITLE
Mixture Calculations with hydrogen

### ISSUE THREAD

**Issue by sgstamatin** [usnistgov/REFPROP-issues#502]

**Comment by ianhbell** [comment]
What is the question?

**Comment by sgstamatin** [comment]
I tried setting up a mixture of 96% hydrogen and 4% ammonia to calculate thermodynamic properties at various temperatures and pressures.  I got a message that the system did not handle mixtures with hydrogen.  This was in version 9.1 of REFPROP.  Does version 10 hadle hydrogen mixtures.

**Comment by ianhbell** [comment]
No, REFPROP 10 does not have, nor allow, mixtures of ammonia + hydrogen.  That is a challenging mixture to model.
