### ISSUE TITLE
[TPFLSH error 213]

### ISSUE THREAD

**Issue by emanueleviglianti** [usnistgov/REFPROP-issues#503]
Hi,
I've a problem with the calculation of different properties of a gas mixture using the REFPROP 9.1 in Excel.

The mixture is the following, in % mole:

methane | 0.7273
ethane | 0.1016
propane | 0.0391
butane | 0.0111
isobutan | 0.0068
pentane | 0.0032
ipentane | 0.0041
hexane | 0.0030
nitrogen | 0.0050
co2 | 0.0950
heptane | 0.0023
octane | 0.0013
nonane | 0.0003

I need to calculate its density (given temperature and pressure) at 80 bar and 15°C. When I type the command, the following error appears:
"#[TPFLSH ERROR 213] liquid density iteration did not converge".

If I perform the same calculation at 52°C (same pressure) it works.

**Comment by ianhbell** [comment]
Please see: https://github.com/usnistgov/REFPROP-wrappers/issues/106

**Comment by emanueleviglianti** [comment]
Problem solved. Thank you!
