### ISSUE TITLE
Different TP envelopes using REPROP GUI and DLL (via CoolProp) 

### ISSUE THREAD

**Issue by andr1976** [usnistgov/REFPROP-issues#504]
### Description

Strange TP phase envelope for oxyfuel CO2 rich gas mixture using the GUI of REFPROP 10
TP envelope smooth using REFPROP 10 via CoolProp

I have tried both using GERG, no_GERG and PR in REFPROP but get the same strange behaviour.

### Steps to Reproduce
Composition: 
```
mix1_comp = "Carbon dioxide&Water&Nitrogen&Oxygen&Argon&Carbon monoxide&Methane&Hydrogen sulfide"
mix1_x = [0.926295,1500e-6,0.02,0.03,0.02,1500e-6,500e-6,100e-6]
```

### Versions

**REFPROP Version:** 10
**Operating System and Version:** win 10 x64
**Access Method:** GUI and via CoolProp wrapper

### Additional Information
Envelope using REFPROP
![image](https://user-images.githubusercontent.com/58475535/151833408-c2667e2e-f73a-4582-8360-f877d3193197.png)
Envelope via CoolProp wrapper
![Figure_1](https://user-images.githubusercontent.com/58475535/151833830-ec13433f-4666-4d36-bcff-295cb3d8fae4.png)

If possible, please post examples and/or screenshots of the issue.
REFPROP file:
[oxyfuel.zip](https://github.com/usnistgov/REFPROP-issues/files/7972449/oxyfuel.zip)

**Comment by ianhbell** [comment]
Strange.  The curves look quite different.  Can you please post your python script?

**Comment by andr1976** [comment]
```
from CoolProp.CoolProp import AbstractState
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt
import numpy as np 
import sys


CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, "C:\\Users\\ANRA\\AppData\\REFPROP\\")
mix1_comp = "Carbon dioxide&Water&Nitrogen&Oxygen&Argon&Carbon monoxide&Methane&Hydrogen sulfide"#&SO2"
mix1_x = [0.926295,1500e-6,0.02,0.03,0.02,1500e-6,500e-6,100e-6]#,100e-6]
mix1_x = [i/sum(mix1_x) for i in mix1_x]

OXY = AbstractState('REFPROP',mix1_comp)
OXY.set_mole_fractions(mix1_x)
CP.set_config_double(CP.PHASE_ENVELOPE_STARTING_PRESSURE_PA,1e5)
OXY.build_phase_envelope("dummy")
PE_OXY = OXY.get_phase_envelope_data()
PELabel = 'Oxyfuel::REFPROP'
plt.plot(PE_OXY.T, PE_OXY.p, '-', label=PELabel)
plt.ylim((0,100e5))
plt.legend(loc='best')
plt.show()
```

**Comment by andr1976** [comment]
These CO2 rich streams are really a pain it seems - I have tried to reproduce the mixtures in Stefan Herrigs thesis, and boy do the phase envelopes look different  when I both try CoolProp (both HEOS and REFPROP backend) and REFPROP compared to his and also between CoolProp / REFPROP.

**Comment by ianhbell** [comment]
Indeed.  But: we should be able to reproduce Stefan's models in both REFPROP and CoolProp.  The same pure fluid models are being used in both places, and the only differences should be the mixture model. How about checking binaries rather than multi-component mixtures? That can help to track down what is going on.  

Mixtures are always complicated in ways large and small.

**Comment by andr1976** [comment]
That's indeed an option - but I just acquired a REFPROP license in the hope that such detailed checking was no longer necessary :-) I realized that the GERG implementation in one of our commercial tools was flawed - but first after checking binary pairs and properties. The EOS-CG back end in the same tool is really a little shaky. Further Aspen Properties apparently also has a Refprop backend, but that jumps most of the dew line, which is maybe the most interesting from a compression / transport point of view. So my faith in the BIG commercial tools is quite low and I have put my faith in REFPROP.

**Comment by ianhbell** [comment]
For pure fluids, yes, I would put high confidence in REFPROP. For mixtures, that's harder, and there are definitely places we could improve, but doing so generally without causing other problems is non-trivial.

**Comment by andr1976** [comment]
I agree, let me check a few things and then revert. I have a pretty good suspect......water

**Comment by andr1976** [comment]
With a dry composition the envelope now looks more sane (calculated in REFPROP GUI, get same result via CoolProp both with CoolProp and REFPROP backend)
![image](https://user-images.githubusercontent.com/58475535/151926913-a9009795-0a18-4ac0-b368-941742c3b73a.png)

**Comment by andr1976** [comment]
Sorry, reopening this. I think there is an issue with the flash in REFPROP GUI still. But it is a little hard to tell I think this one might be right (wet) from CoolProp with REFPROP backend. 
https://user-images.githubusercontent.com/58475535/151833830-ec13433f-4666-4d36-bcff-295cb3d8fae4.png
The tricky part is that condensation at the dew line is likely a water rich phase, which might give issues since only a VLE flash is used. Not sure though

**Comment by andr1976** [comment]
A small update for "wet" conditions (1500 ppm water) 
Compared to Sterrigs data for Oxyfuel combustion data CoolProp gives excellent match both via DWSIM via a multiphase flash algorithm and directly via the python wrapper  (although resolution is a little sparse). GERG via DWSIM is also looking sane (Peng Robinson included for comparison). REFPROP is totally off with different results when using GUI and the CoolProp wrapper. 
 
![image](https://user-images.githubusercontent.com/58475535/151975481-3e978716-8224-40b0-8b47-edd810f10a99.png)

It seems the REFPROP envelope is a combination of the water wet and the dry gas envelope

**Comment by ianhbell** [comment]
The pure fluids will all be the same.  Can you please investigate which mixture models are the same or different? Unfortunately there are 8*7/2=28 pairs to check.

I don't like your figure too much :/  Where does the Sterrig data come from?

**Comment by andr1976** [comment]
The Sterrig data is read from a graph in his thesis, calculated using his expanded EOS-CG model

**Comment by andr1976** [comment]
CO2-N2
REFPROP: 
![image](https://user-images.githubusercontent.com/58475535/151999369-8f8f291a-60d8-4d27-b20d-42c126f3c415.png)


<html>
<body>


Ref. | Name1 | Name2 | function | F | xizeta | betaTbetaV | gammaTgammaV
-- | -- | -- | -- | -- | -- | -- | --

[35] | CarbonDioxide | Nitrogen | Nitrogen-CarbonDioxide | 1 |   | 9.9414e-01 1.0227e+00 | 1.1077e+00 1.0476e+00



</body>
</html>

I will keep looking, still have 20+ to go :-)

**Comment by ianhbell** [comment]
Well, I think automation is the way to go, with this in CoolProp

``
AS.get_binary_interaction_double(i,j,'betaT') for instance
``

which works for REFPROP and HEOS backends (watch out for ordering of binary pairs with REFPROP backend though)

**Comment by andr1976** [comment]
CO2-Argon 

![image](https://user-images.githubusercontent.com/58475535/152000703-dd408362-04ed-4d6c-8fe8-e72705dc5bfb.png)

<html>
<body>


Ref. | Name1 | Name2 | function | F | xizeta | betaT betaV | gammaT gammaV
-- | -- | -- | -- | -- | -- | -- | --
[35] | CarbonDioxide | Argon | Argon-CarbonDioxide | 1 |   | 1.0271e+00 1.0014e+00 | 9.6878e-01 1.0297e+00


</body>
</html>

**Comment by ianhbell** [comment]
Hmm not the same.

**Comment by ianhbell** [comment]
I would recommend to generate the CoolProp mix file from the conversion script.  Otherwise getting the models to match is going to be somewhat painful.

**Comment by andr1976** [comment]
No exactly, I skipped the ones which were identical. Still not through yet.

**Comment by andr1976** [comment]
Sorry about the formatting, these are the ones differing between CoolProp and REFPROP, 

Binary Comp 1 Comp 2 Par (CoolProp) Par (REFPROP)
gammaT: CO2 Oxygen 1.031986 inf
gammaT: CO2 Argon 0.968781 1.0396748
gammaT: CO2 CO 1.068392 inf
gammaT: Water Argon 0.921 inf
gammaT: Nitrogen Argon 0.989311 inf
gammaT: Nitrogen CO 0.9941 inf
gammaT: Oxygen Argon 0.988822 inf

Binary Comp 1 Comp 2 Par (CoolProp) Par (REFPROP)
gammaV: CO2 Oxygen 1.08446 inf
gammaV: CO2 Argon 1.02971 1.013833
gammaV: CO2 CO 1.245499 inf
gammaV: Water Argon 1.050952 inf
gammaV: Nitrogen Argon 1.001549 inf
gammaV: Nitrogen CO 1.001317 inf
gammaV: Oxygen Argon 1.001341 inf

Binary Comp 1 Comp 2 Par (CoolProp) Par (REFPROP)
betaV: CO2 Nitrogen 1.022709642 0.977794634
betaV: CO2 Argon 1.001378 0.996248228795
betaV: CO2 CO 1.030855 inf
betaV: CO2 Methane 1.0004821603665812 0.999518072
betaV: Water Nitrogen 1.079628 0.926245
betaV: Water Oxygen 0.972576 1.028197
betaV: Water Argon 0.940398 inf
betaV: Water CO 1.063348 0.940426
betaV: Water Methane 0.9873781778851817 1.012783169
betaV: Nitrogen Argon 1.006697 inf
betaV: Nitrogen Methane 1.0012802599698434 0.998721377
betaV: Oxygen Argon 1.006502 inf
betaV: Argon Methane 0.9665288554063061 1.034630259
betaV: CO Methane 1.002666318348409 0.997340772

Binary Comp 1 Comp 2 Par (CoolProp) Par (REFPROP)
betaT: CO2 Nitrogen 0.994140013 1.005894529
betaT: CO2 Argon 1.027147 1.0012966792
betaT: CO2 CO 0.993245 inf
betaT: CO2 Methane 0.9778760530172712 1.02262449
betaT: Water Nitrogen 0.954149 1.048054
betaT: Water Oxygen 0.798046 1.25306
betaT: Water Argon 0.679104 inf
betaT: Water CO 1.045927 0.95609
betaT: Water Methane 0.9404383588017851 1.063333913
betaT: Nitrogen Argon 0.999442 inf
betaT: Nitrogen CO 1.002409 inf
betaT: Nitrogen Methane 1.0019047913321368 0.99809883
betaT: Oxygen Argon 0.9990390000000001 inf
betaT: Argon Methane 1.0091282909549284 0.990954281
betaT: CO Methane 1.012748752715853 0.987411732

**Comment by ianhbell** [comment]
If the order of the pair is swapped, the beta should be the reciprocals of each other: beta_{ij}=1/beta_{ji}. The gamma are more indicative of different models being used.  Why the inf for REFPROP?

**Comment by andr1976** [comment]
I don't know, I am not the expert here :-)  ok so it seems CO2 Argon at least differs. It seems most of the differences in betas might be the order being swapped. But calling 
COOLPROP.get_binary_interaction_double(i,j,'betaT')  / REFPROP.get_binary_interaction_double(i,j,'betaT')
I would guess that the same order was used, but not necessarily the case?

**Comment by andr1976** [comment]
The inf is output from the get_binary_interaction_double
```
from CoolProp.CoolProp import AbstractState
import CoolProp.CoolProp as CP

CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, "C:\\Users\\ANRA\\AppData\\REFPROP\\")

# Oxyfuel
mix1_comp = "Carbon dioxide&Water&Nitrogen&Oxygen&Argon&Carbon monoxide&Methane&Hydrogen sulfide"#&SO2"
mix1_heos = "CO2&Water&Nitrogen&Oxygen&Argon&CO&Methane&H2S"#&SO2"
mix1_x = [0.926295,1500e-6,0.02,0.03,0.02,1500e-6,500e-6,100e-6]#,100e-6]
mix1h_x = [0.926295,1500e-6,0.02,0.03,0.02,1500e-6,500e-6,100e-6]#,100e-6]

COOLPROP = AbstractState('HEOS',mix1_heos)
REFPROP =  AbstractState('REFPROP',mix1_comp)

names = mix1_heos.split("&")
print("Binary", "Comp 1", "Comp 2", "Par (CoolProp)", "Par (REFPROP)")
for i in range(len(mix1_x)):
    for j in range(i,len(mix1_x)):
        CP_kij = COOLPROP.get_binary_interaction_double(i,j,'betaT')
        RP_kij = REFPROP.get_binary_interaction_double(i,j,'betaT')
        if CP_kij != RP_kij and CP_kij !=1 and CP_kij !=0:
            print("betaT:", names[i], names[j], CP_kij, RP_kij)
```

**Comment by ianhbell** [comment]
Right, not necessarily.  It's sort of a bug in REFPROP (or a feature if you prefer)

**Comment by andr1976** [comment]
Small update, Tried to calc the dew points (quite naive just the PQ spec increasing P) with REFPROP  (via CoolProp) - looks better, somehow its the phase envelope / phase boundary calc which is causing the problem apparently 

![image](https://user-images.githubusercontent.com/58475535/152022979-a5e2a417-0a5d-4756-97bf-f0631a8a52ad.png)
Btw: Caption is wrong Blue is CoolProp wet with HEOS::CoolProp backend and Orange is Wet CoolProp with REFPROP backend - both phase envelopes. Dew points are AS.update(PQ_INPUTS,P,1), AS having REFPROP backend.

**Comment by KoldMen** [comment]
Water condenses at close to room temperature. Hence water containing mixtures can have two dew point temperatures at a given pressure, one for water and another regular dew point. Refprop does not look for two dew point temperatures (or two dew lines). 

As the "Cautions" tab in Refprop tells you, Refprop does not consider multi-phase equilibria. Without the capability to produce three-phase envelope and two different dew lines, the complete phase envelope of water containing HC mixtures can never be calculated satisfactorily. The problem is not so much with the mixture model, but with the phase equilibrium calculation methods currently used. 

To understand more about phase envelopes for water containing mixtures, see the article of Michael Michelsen:
https://onepetro.org/SPEATCE/proceedings/02ATCE/All-02ATCE/SPE-77770-MS/136138

**Comment by andr1976** [comment]
@KoldMen thanks, I  know this is hard and tricky. The funny thing is that I can reproduce the dew curve by Sterrig on one hand with DWSIM/Coolprop (and closely by GERG) which gives a much lower cricondentherm than REFPROP (via CoolProp). I am starting to agree with myself that REFPROP is the better one (via CoolProp, not via REFPROP GUI) and that the dew curves by Sterrig are wrong and somehow leaves out the top of the (CO2 rich) envelope near the critical point of CO2.  My head is starting to implode. What do you think @ianhbell ? If not for other reasons, I will advice a very hard spec on moisture, if not for other reasons, then just to make my own life easier with respect to VLE :-)

**Comment by ianhbell** [comment]
I think the discussion from nist-aharvey in this thread is germane: https://github.com/usnistgov/REFPROP-issues/issues/300#issuecomment-638409429

**Comment by KoldMen** [comment]
@andr1976 Water in natural gas was extensively studied at https://ttk.kit.edu in the 90s and 2000s. They may have the right program for your mixture.

**Comment by andr1976** [comment]
Closing this one, leaving the original note that phase envelopes obtained via REFPROP GUI and via CoolProp wrapper are vastly different.
