### ISSUE TITLE
Refrigerant R-471A

### ISSUE THREAD

**Issue by andy43168** [usnistgov/REFPROP-issues#506]
Honeywell has been promoting their R-471A refrigerant: R-1234ze(E)/227ea/1336mzz(E) (78.7/4.3/17.0)
Any plans to make an R1336mzze.fld file available?

Andy Schoen
HVACR Advisors LLC

**Comment by ianhbell** [comment]
We have a FLD file for R1336mzz(E), I just need to check it is ready for sharing.

**Comment by andy43168** [comment]
Hi Ian, are you ready to share the R1336mzze.fld file?

**Comment by ianhbell** [comment]
Sorry for the delay, yes, please email me: ian.bell@nist.gov
