### ISSUE TITLE
Calculation not converged for R227EA mixture with ETHANOL

### ISSUE THREAD

**Issue by hossainchizari** [usnistgov/REFPROP-issues#507]
I am working on the mixtures of R227EA and ETHANOL with different mole-fractions of ETHANOL from 0 to 1.

### Prerequisites

Using Matlab 2021 direct call of the REFPROP 10.0 with python (using ctREFPROP). The model fraction varies from 0 to 1 for ETHANOL in the mixture with R227EA.

### Description

I am looking at calculating the pressure for a range of saturation temperatures, hence,
* hIN  = 'TQ' 
* hOut = 'P'
* a = range[250, 300] Kelvin
* b = 0.0

I used the REFPROPdll function.

### Results

Up to mole fraction 0.5 for ETHANOL in the mixture, the calculation is done without any errors. However, for mole-fraction 0.6 onwards I got this error,

[SATT error 124] - Iteration for saturation state did not converge for T = ...

The output 'q' value has also become 999 which is for supercritical conditions and this is a little weird since the temperature and pressure are far below the critical.

### Questions

1. Am I doing something wrong? If yes, please advise me. If not, then is it possible to overcome this issue?
2. If I cannot fix this then until what mole-fraction of ETHANOL I can trust the data from REFPROP?

**Comment by ianhbell** [comment]
I am not sure how you were able to do any calculations with this mixture.  You should have gotten a fatal error message 117 because there is no mixture model for this binary pair.  I couldn't find any literature data for this mixture to check against.

**Comment by hossainchizari** [comment]
Would you please tell me whether it is possible in REFPROP to do other mixtures containing ETHANOL such as R134A or R152A or R1234ZEE?

**Comment by ianhbell** [comment]
It is allowed to do ethanol + {R134a,R152a}, but I would be skeptical of these models.  We would have to compare against the experimental data, but it is very limited.  

Literature reference for R152a/Ethanol
I.H. Bell and E.W. Lemmon, JCED, 2016.
DOI:10.1021/acs.jced.6b00257
MAPD: 1.94% from 13 bubble-point pressures

Literature reference for R134a/Ethanol
I.H. Bell and E.W. Lemmon, JCED, 2016.
DOI:10.1021/acs.jced.6b00257
MAPD: 1.85% from 15 bubble-point pressures

**Comment by hossainchizari** [comment]
Thank you very much for the clarification.
