### ISSUE TITLE
Speed of the REFPROPdll and possible solutions

### ISSUE THREAD

**Issue by hossainchizari** [usnistgov/REFPROP-issues#510]
Using REFPROP 10 DLL connection with MATLAB by python 'ctREFPROP'.

Based on the DLL documentation I used REFPROPdll function and it is working fine. The only thing is the fact that it is very slow. In the documentation, this issue is mentioned and then it is suggested that I can use REFPROPdll without passing the fluid names and molar composition. I tried this method, however, the speed is still pretty much low.

Kindly let me know your suggestions.

**Comment by ianhbell** [comment]
You could switch to C++ or Python or more suitable low-level language.  But what are you doing? If mixtures, "it is very slow" is to be expected. Can you please provide more context, and some timing results?

**Comment by hossainchizari** [comment]
Yes, indeed switching to C++ is one good option. About the situation, I am facing right now, I do not do any mixtures now, this is a test I only did for a single component to verify the code.
I am using the direct call and the wrapper for MATLAB and the wrapper seems to be around 15-20 times faster than the direct call. Not sure what would be the reason.

**Comment by ianhbell** [comment]
What do you mean by direct call? Please provide example code demonstrating.

**Comment by hossainchizari** [comment]
Thank you for the quick response, I meant using the following method rather than the wrapper,

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('c:\program files (x86)\REFPROP');
r = RP.REFPROPdll(.......);

So the above method is very much slower than the wrapper (around 15 times)

**Comment by ianhbell** [comment]
Provide your complete code; it is important to see how you did your timing. I can believe it is slower, but I am surprised it is that much slower and I think you have made unnecessary calls to Python things without realizing.

**Comment by hossainchizari** [comment]
Sure, I cannot put all the code, however, I can tell how the structure is, hopefully, it will be clear.

------------------------------------------------------------------------------------------------------------------------------
Start the main loop (100 times) with many functions engaged

Start local loop (10 times)

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('c:\program files (x86)\REFPROP');
iUnits = RP.GETENUMdll(......).iEnum;
iMass = int8(0);
iFlag = int8(0);
r = RP.REFPROPdll(.......);
r = RP.REFPROPdll(.......);

End local loop

End of the main loop

------------------------------------------------------------------------------------------------------------------------------

Please let me know your thoughts.
Thank you!

**Comment by ianhbell** [comment]
Impossible to say without a comprehensive example.

**Comment by hossainchizari** [comment]
Sure, I will code up an example and will post it here, thank you!

**Comment by hossainchizari** [comment]
Here is a sample code, apologies if this is not the best way to present what I am doing,

``` matlab
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
fprintf("refprop version: ");
fprintf("%s", RP.RPVersion());
iUnits = RP.GETENUMdll(int8(0),'MASS BASE SI').iEnum;
iMass = int8(0);
iFlag = int8(0);
z = {1.0};

% 'R134A' 'R227EA' 'R152A' 'R1234zeE'
refregerant_name = 'R227EA';
hFld = sprintf('%s', refregerant_name);
nT = 100001;
Temperature = zeros(nT);
Pressure = zeros(nT);

Q = 0.0;
r = RP.REFPROPdll(hFld, 'PQ', 'T', iUnits, iMass, iFlag, 101325, Q, z);
o = double(r.Output);
fprintf("\nT-%s: %.2e\n", hFld, o(1));
Tmin = o(1);
Tmax = 273.15 + 30.0;

tic

for t = 1:nT

T = Tmin + (Tmax - Tmin) * (t - 1) / (nT - 1);

% Using dll
r = RP.REFPROPdll(hFld, 'TQ', 'P', iUnits, iMass, iFlag, T, Q, z);
o = double(r.Output);

% Using the wrapper
% o(1) = refpropm('P', 'T', T, 'Q', Q, hFld);

Temperature(t) = T;
Pressure(t) = o(1);

end

timeElapsed = toc;
```
-------------------------------------------------------------------------------------------------------------------------

Duration of the main loop:

For nT = 100001 
t_{dll} = 26.5882 seconds
t_{wrapper} = 7.1101 seconds

I also test nT = 10001
t_{dll} = 2.6963 seconds
t_{wrapper} = 0.7702 seconds

It is not as bad as my original code but it is still very much different. Is this difference expected? Or I shall do something differently?

Thank you!

**Comment by ianhbell** [comment]
Try to convert ``z`` to python data structure so it doesn't have to get converted at each call. Same with input strings.

**Comment by hossainchizari** [comment]
Thanks, would you please elaborate more in a short example? Or any documents/links that I can read from? Thank you!

**Comment by ianhbell** [comment]
I think you would want something like ``py.numpy.array({1.0})`` and ``py.str('TP')``. But I don't use MATLAB. Check out the MATLAB interfacing with Python docs

**Comment by hossainchizari** [comment]
Thanks a million!

I tried to use the python formats for the function such as 'py.str'. However, the timing becomes worse. Any suggestions?

**Comment by hossainchizari** [comment]
Just one thought, I realized that the MATLAB function 'double' that has been used to convert the PYTHON array to MATLAB double is actually taking half of the calculation time. I am not sure why but at least I know the reason. If you have any suggestions on converting the PYTHON array to MATLAB double then please let me know. Thank you!

**Comment by ianhbell** [comment]
You could not convert with double, but then index into the array to extract what you want.  No guarantee that would be faster though, you'd need to test.
