### ISSUE TITLE
REFPROP DLL Expired

### ISSUE THREAD

**Issue by AD84194** [usnistgov/REFPROP-issues#511]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

I received a message upon opening REFPROP stating the DLL I am using has expired.  It says to "Please return to the Refprop website and download the latest installer"

### Steps to Reproduce

1.  Open REFPROP version 10

**Expected behavior:** [What you expect to happen]

Refprop opens normally.

**Actual behavior:** [What actually happens]

Error message comes up as stated above.

### Versions

**REFPROP Version:**  10.0.0.97
**Operating System and Version:** Microsoft Windows 10 Enterprise
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Please email me for download link: ian.bell@nist.gov
