### ISSUE TITLE
Thermal stability

### ISSUE THREAD

**Issue by vve-Venzik** [usnistgov/REFPROP-issues#512]
Hello all,
I am currently dealing with fluid selection for high temperature heat pumps. In this context, I would also like to take a closer look at the thermal stability of low GWP refrigerants (natural refrigerants and HFOs or HCFOs). Is there a possibility to get information on thermal stability of fluids at Refprop?

Many greetings and thanks!

**Comment by ianhbell** [comment]
Nope, that is outside the scope of REFPROP.
