### ISSUE TITLE
How to model gas solubility in a brine mixture at P/T in Refprop

### ISSUE THREAD

**Issue by EcoVaporRS** [usnistgov/REFPROP-issues#513]
Is it possible to model gas solubility of a known gas mixture either by solvent or by TDS?

I'm not really sure where to start on this one, but essentially, I'm hoping to be able to define a custom liquid (based on salts dissolved in water therein) and then essentially estimate the partial pressure of the gas stream (contains some CO2 and some H2S). The end result is that I'd like to know the approximate liquid content of CO2 and H2S given a fluid at P/T. As a note, it's anticipated that the brine will have a very high TDS (>20%), which will likely change things. I can add as much detail as you wish, but trying to understand if this is even possible within REFPROP.

**Comment by ianhbell** [comment]
What is TDS?

REFPROP does not handle brines currently.  There are other groups that I can point you to that are working on phase equilibria with brines.

**Comment by EcoVaporRS** [comment]
TDS is total dissolved solids, and is designed as a catchall when dealing with complex brines (example: oilfield brines). If you can point me to another group, I'm happy to talk to whomever you recommend.

**Comment by ianhbell** [comment]
Can you please email me (ian.bell@nist.gov) and I can give you some contacts
