### ISSUE TITLE
How to load ASHRAE34blends *.MIX files to  Refprop10 ?

### ISSUE THREAD

**Issue by cnsvert** [usnistgov/REFPROP-issues#514]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

How do I correctly install the *.Mix files included in ASHRAE34blends folder ?   Do I just copy them into the REFPROP/MIXTUREs folder and restart REFPROP?    I have not tried this because I do not have Admin credentials
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP version you are using]  10.0
**Operating System and Version:** [OS you are running REFPROP on]  Windows 10
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  Standalone

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Yes, that is right.  But it is best if your REFPROP is not installed in a place that needs admin rights, because if you put files in there, the files will actually be residing in a ghost directory, which is very confusing to debug.
