### ISSUE TITLE
Nonconvergent output for R454C at high pressures

### ISSUE THREAD

**Issue by crlaugh** [usnistgov/REFPROP-issues#515]
Density computations using PHFLSH() for R454C (a low-GWP high-glide blend) relatively close to the critical point have some strange behavior that I would like to understand; in particular, when REFPROP mixture computations for density don't converge, can you confirm that REFPROP always returns the density on the bubble line?

In studying the density, I can sweep the specific enthalpy through the two-phase region at a pressure of 4080 kPa using increments in the thermodynamic quality x of 0.001 (where x = (hVal - hBub(P))/(hDew(P) - hBub(P)) and get the following result: 

![temp1](https://user-images.githubusercontent.com/9616147/157104513-d8e66084-a54e-4bce-b014-9948c9af9fdc.png)

Although the pressure under study is appreciably less than the critical pressure of 4318 kPa, the challenges of the mixture computations are such that I am not surprised that there are some areas in the two-phase region where the computations don't converge.  PHFLSH does indeed raise some errors at specific points, which are also highlighted in the above plot with circles - each circle represents a point at which ierr is not equal to 0.  

However, if I remove all of the points for which ierr != 0, leaving only points with ierr=0 remaining, REFPROP still produces some clearly erroneous results, as can be seen in the following plot: 

![temp2](https://user-images.githubusercontent.com/9616147/157104922-7e21eca4-a0f3-4a58-a546-15935fe3fe65.png)

These points are a little bit more troublesome, as it is hard to tell from the numerical REFPROP output that the points are inherently bad, unlike the points for which ierr != 0.  

In looking at these points, it appears that the erroneous density is always equal to the density on the bubble line at the given pressure.  If this is always true, then I can use this fact to distinguish these undesirable points from good REFPROP output for thermodynamic qualities far away from the bubble line.  

I would therefore like to confirm on the basis of the underlying iterative algorithms that REFPROP will always return the bubble density (or other property, like entropy, analogously) when the mixture computations don't converge.  Can you provide a guarantee (at least from the perspective of design intent) that I should be able to expect this behavior?  

I am using REFPROP 10.0.0.98 on Win10 through the ctREFPROP interface in Python.

**Comment by ianhbell** [comment]
What is the critical pressure for this mixture? Did you turn on saturation splines?

**Comment by crlaugh** [comment]
After your insightful comments in my previous related issue (https://github.com/usnistgov/REFPROP-issues/issues/501), I did indeed turn on the saturation splines.  The critical pressure is 4318 kPa.

**Comment by ianhbell** [comment]
Example runnable code is helpful...

**Comment by crlaugh** [comment]
The code that I'm running is in Julia, which gets complicated with PyCall - let me work up an example in Python that should be easier to run and get back to you.

**Comment by crlaugh** [comment]
Here's some Python code that reproduces the above plots.  

Can I always expect that the value of the density calculation output for which the mixture calculations do not converge but no error is raised to be nearly equal to the density on the bubble line?  

```
import os
import numpy as np
import matplotlib.pyplot as plt
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])

resMix = RP.SETMIXdll("R454C.MIX", "HMX.BNC", "DEF")
resREF = RP.SETREFdll("DEF", 2, resMix[2], 0, 0, 0, 0) 
zVal = resMix.z

msg = RP.SATSPLNdll(zVal)

PVal = 4080.0

resBub = RP.SATPdll(PVal, zVal, 1)
resBub2 = RP.THERM2dll(resBub.T, resBub.Dl, zVal)
hBub = resBub2.h

resDew = RP.SATPdll(PVal, zVal, 2)
resDew2 = RP.THERM2dll(resDew.T, resDew.Dv, zVal)
hDew = resDew2.h

xVec = np.arange(-0.5, 1.5, 0.001)
hVec = np.zeros_like(xVec)
dVec = np.zeros_like(xVec)
errVec = np.zeros_like(xVec)
errVec[:] = np.NaN 

for (ix, xVal) in enumerate(xVec):
    hVal = hBub + xVal*(hDew-hBub)

    res = RP.PHFLSHdll(PVal, hVal, zVal)

    if res.ierr != 0: 
        errVec[ix] = res.D

    hVec[ix] = hVal
    dVec[ix] = res.D

plt.plot(1e-3*hVec, dVec)
plt.title("All data")

bad_ndx = np.where(~np.isnan(errVec))
good_ndx = np.where(~np.in1d(np.arange(len(xVec)), bad_ndx))[0]

plt.plot(1e-3*hVec, dVec,
         1e-3*hVec[bad_ndx], dVec[bad_ndx], 'o')
plt.title("All data with ierr!=0 points marked with little circles")

plt.plot(1e-3*hVec[good_ndx], dVec[good_ndx])
plt.title("Data without points for which ierr!=0")
```

**Comment by ianhbell** [comment]
Why not interpolate within the phase envelope values in this case? I have an example here: https://nbviewer.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb#Phase-Boundary-for-Mixtures

**Comment by crlaugh** [comment]
Thanks for the suggestion - I can run the nbviewer code provided at the link.  Can you provide a bit more insight how I would use this to calculate the densities via interpolation?  An example would be really helpful.  

Here's my current code (slightly adapted from yours):
```
import pandas as pd

msg = RP.SETMIXTUREdll('R454C')
zVal = msg.z

msg = RP.SATSPLNdll(zVal)

# Now we programatically extract the nodes of the isopleth...
Nnodes = RP.REFPROPdll("","SPLINENODES","",0,0,0,0,0,zVal).iUCode

data = []
for i in range(1,Nnodes+1):
    rho_vap,T,p,rho_eq,z0,z1 = RP.REFPROPdll("","SPLINENODES","",0,0,i,0,0,zVal).Output[0:6]
    data.append(dict(rho_vap = rho_vap,T=T,p=p,z0=z0,z1=z1))

df = pd.DataFrame(data)
# And plot them...
plt.plot(df['T'],df.p,'o-')
```

**Comment by ianhbell** [comment]
My idea was that you would at least know where the phase boundary in P,h coordinates is. And you could in your code decide inside/outside of the VLE bubble.

**Comment by crlaugh** [comment]
Ah.  I already have code to calculate the phase boundary in P,h coordinates by using my own splines, so that isn't an issue.  I'm trying to calculate properties inside the two-phase region, and have been stymied by the calculations of problematic points inside this region, as there are many points which produce erroneous output from REFPROP but for which REFPROP returns ierr = 0.  Do you have any suggested strategies for avoiding the calculation of these erroneous points?

**Comment by ianhbell** [comment]
I don't have any better ideas to offer, sadly. It's tricky because the pressure isn't constant as you boil, so you can't do the tricks you can with pure fluids.

**Comment by crlaugh** [comment]
Do you expect that the mixture iterations for a given property (density) will always return the value of the given property on the bubble line in such a case?  I am interested to know if that is the default output of these algorithms.

**Comment by ianhbell** [comment]
No, I shouldn't think so. I think it is a "feature" of the algorithm

**Comment by crlaugh** [comment]
I appreciate this info.  Thanks!
