### ISSUE TITLE
Mixture Propylene Glycol (C3H802) and Water

### ISSUE THREAD

**Issue by hlucian** [usnistgov/REFPROP-issues#517]
For the numerical analysis of a gas-liquid separator in zero gravity
i need the properties of a mixture of propylene glycol (C3H802)
with water. The mass fractions are 0.4 for C3H802 and 0.6 for water.
I was however unable to find propylene glycol in the fluids. 
Does anybody have an idea on how I could get the properties
of this mixture?

**Comment by ianhbell** [comment]
We have a fluid file for PG.  Please email me for it: ian.bell@nist.gov

**Comment by nist-aharvey** [comment]
I don't think there has been any optimization of the PG-water mixture within REFPROP, and mixtures with water are often difficult to model accurately.
So you should verify any results against experimental data for this mixture before trusting them for anything important.

**Comment by hlucian** [comment]
Hi Ian, Hi Mister Harvey

Thank you so much for the quick help. As I already replied to Ian, even after integrating the PG-file to refprop, it does not allow me to compute any values with a molar fraction higher than 5%. I switched to CoolProp, where it is possible to compute the viscosity value up to 60% and compared against measurement values found in an article of Ibrahim S. Kattab from 2017 called:

"Density, viscosity, surface tension, and molar volume of propylene glycol + water mixture from 293 to 323 K and correlations by the Jouyban-Acree model"

I did a graphical comparison and the measurement data agrees really well compared to the values extracted from CoolProp (CP in the legend).

![Selection_086](https://user-images.githubusercontent.com/47562558/157887545-fe1b7253-f81b-429b-add7-a907d6d5aee5.png)

As always, i am left speechless on how fast you usually reply and I would like to express my gratitude

Kindly
Lucian

**Comment by nist-aharvey** [comment]
That looks like a good result -- while for mixture liquid viscosity I would expect predictions to at least be reasonable, quantitative agreement can be challenging when the viscosities of the two pure components differ by a lot.  Liquid density should also be OK if that enters into your calculations.
If you care about vapor-liquid equilibrium, that is more likely to be significantly erroneous without optimization of a mixture model.

I looked in a database here and found some additional sources of viscosity data in case you want to check it some more (it seems to be a popular mixture to measure):
Kapadi, U. R.; Hundiwale, D. G.; Patil, N. B.; Lande, M. K.; Patil, P. R.
Studies of viscosity and excess molar volume of binary mixtures of propane-1,2 diol with water at various temperatures
Fluid Phase Equilib., 2001, 192, 63-70
George, J.; Sastry, N. V.
Densities, Dynamic Viscosities, Speeds of Sound, and Relative Permittivities for Water + Alkanediols (Propane-1,2- and -1,3-diol and Butane-1,2-, -1,3-, -1,4-, and -2,3-Diol) at Different Temperatures
J. Chem. Eng. Data, 2003, 48, 1529-1539
Sun, T.; Teja, A. S.
Density, Viscosity and Thermal Conductivity of Aqueous Solutions of Propylene Glycol, Dipropylene Glycol, and Tripropylene Glycol between 290 K and 460 K
J. Chem. Eng. Data, 2004, 49, 1311-1317
Miksik, Frantisek; Skolil, Jan; Kotlik, Josef; Caslavsky, Josef; Miyazaki, Takahiko; Kacirkova, Marie; Puckova, Helena
Viscosities, Densities, and Refractive Indices of Aqueous Propane-1,3-diol
J. Chem. Eng. Data, 2018, 63, 4350-4367

**Comment by ianhbell** [comment]
I would also recommend to check out the book from Melinder upon which the correlations (valid in the liquid phase only!) are based for PG+water that are cited in the docs: http://www.coolprop.org/zbibliography.html#melinder2010
