### ISSUE TITLE
Gao EOS for Ammonia has wrong number of coefs/term

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#518]
In the implementation of the Gao EOS, the incorrect number of coefs/terms is used for the new terms.  it should be 12, but is entered as 0:

```
405.56       11363.4      13.696       !Tc [K], pc [kPa], rhoc [mol/L]
405.56                    13.696       !Reducing parameters [K, mol/L]
8.3144598                              !Gas constant [J/mol-K]
   8  4  10 12   2 0    0 0  0 0  0 0  !# terms and # coefs/term for normal terms, Gaussian terms, and Gao terms <<<< 2 0 should be 2 12
  0.006132232     1.0     4.  0.       !a(i),t(i),d(i),l(i)
  1.7395866       0.382   1.  0.
 -2.2261792       1.0     1.  0.
 -0.30127553      1.0     2.  0.
  0.08967023      0.677   3.  0.
 -0.076387037     2.915   3.  2.
 -0.84063963      3.51    2.  2.
 -0.27026327      1.063   3.  1.
  6.212578        0.655   1.  2. 2.   -0.42776   -1.708    1.036   -0.0726    0. 0. 0.
 -5.7844357       1.3     1.  2. 2.   -0.6424    -1.4865   1.2777  -0.1274    0. 0. 0.
  2.4817542       3.1     1.  2. 2.   -0.8175    -2.0915   1.083    0.7527    0. 0. 0.
 -2.3739168       1.4395  2.  2. 2.   -0.7995    -2.43     1.2906   0.57      0. 0. 0.
  0.01493697      1.623   2.  2. 2.   -0.91      -0.488    0.928    2.2       0. 0. 0.
 -3.7749264       0.643   1.  2. 2.   -0.3574    -1.1      0.934   -0.243     0. 0. 0.
  0.0006254348    1.13    3.  2. 2.   -1.21      -0.85     0.919    2.96      0. 0. 0.
 -0.000017359     4.5     3.  2. 2.   -4.14      -1.14     1.852    3.02      0. 0. 0.
 -0.13462033      1.0     1.  2. 2.  -22.56    -945.64     1.05897  0.9574    0. 0. 0.
  0.07749072839   4.0     1.  2. 2.  -22.68    -993.85     1.05277  0.9576    0. 0. 0.
 -1.6909858       4.3315  1.  2. 2.   -2.8452     0.3696   1.108    0.4478    1.244 0. 1.
  0.93739074      4.015   1.  2. 2.   -2.8342     0.2962   1.313    0.44689  0.6826 0. 1.
                                           eta          beta      gamma    epsilon
                                         EXP[eta*(delta-epsilon)^2+beta*(tau-gamma)^2]
```

**Comment by ianhbell** [comment]
@EricLemmon can you please confirm and then close this issue?

**Comment by EricLemmon** [comment]
The second number that was once used to specify the number of parameters for each term (each line) doesn't really have any use, so we disabled the need for that with the Gao terms.  Those terms always need 12 parameters, just like the Gaussian terms above it (and in fact they are stored in the same arrays).  By not requiring the second number, it frees up all the other zeros on that line for use with new types of terms that will come later.

**Comment by ianhbell** [comment]
So the description needs to be fixed

**Comment by EricLemmon** [comment]
"# terms and # coefs/term for normal terms" technically could be read as just for the normal terms, then a comma, and then who knows what for the other ones.  English is wonderfully vague! But, OK, we should remove the vagueness to clarify it for anyone reading the line.  It now reads:

First digit: # of normal terms, third digit: # of Gaussian terms, fifth digit: # of Gao terms.  Second and fourth digits are no longer used but kept to be compatible with previous versions of Refprop. 

File has been pushed up.

**Comment by ianhbell** [comment]
And the same for all other fluid files

**Comment by EricLemmon** [comment]
Yep, one of these days...  It's easy to do, but you know what's going on right now.

**Comment by ianhbell** [comment]
Yup, just a placeholder reminder.
