### ISSUE TITLE
Unable to Get z as Output from SETMIXTUREdll()

### ISSUE THREAD

**Issue by jpkauffman** [usnistgov/REFPROP-issues#52]
I am not able to get the resulting composition object z as an output from the SETMIXTUREdll(hMixNme, z) ctREFPROP function. I attempted to initialize a list and pass it as an argument to SETMIXTUREdll, expecting that the list would be updated byReference within the SETMIXTUREdll method, but I have been unable to determine the correct syntax to allow this to work.

As an alternative, I modified the SETMIXTUREdll() method to the form below in order to allow the mixture composition to be returned as an output from the SETMIXTUREdll() method. 

Please review and comment on the suitability of this modified method and let me know if there is a simple syntax that allows me to pass z by reference to the original SETMIXTUREdll(hMixNme, z) method.

`    def SETMIXTUREdll_JPK(self,hMixNme,maxNumberOfComponents = 20):
        """
        ierr = SETMIXTUREdll(hMixNme,z)
        """
        hMixNme = ct.create_string_buffer(hMixNme.encode('utf-8'),10000)
        zList = [0 for x in range(maxNumberOfComponents)]
        z = (len(zList)*ct.c_double)(*zList)
        ierr = ct.c_long()

        if self._SETMIXTUREdll is None: raise ValueError("The function SETMIXTUREdll could not be loaded from the shared library.") 
        self._SETMIXTUREdll(hMixNme,z,ct.byref(ierr),10000)

        return ierr.value, z
`

**Comment by ibell** [comment]
``SETMIXTUREdll`` is a write-only function, and the inputs are immutable, as you can see if you check out the REFPROP code: 
``` fortran
      subroutine SETMIXTUREdll (hMixNme,z,ierr)
      include 'CONSTS.INC'
      character, intent(in) :: hMixNme*10000
      double precision, intent(in) :: z(ncmax)
      integer, intent(out) :: ierr
      character*10000 hMixNme2
cDEC$ ATTRIBUTES DLLEXPORT,Decorate,Alias:"SETMIXTUREdll"::SETMIXTUREdll
cDEC$ ATTRIBUTES STDCALL, REFERENCE::SETMIXTUREdll
c     dll_export SETMIXTUREdll
      i=INDEX(hMixNme,CHAR(0))-1
      if (i.lt.0) i=LEN(hMixNme)
      hMixNme2=hMixNme(:i)
      call SETMIXTURE (hMixNme2,z,ierr)
      end
```

Two options to get the compositions for a predefined mixture:
1) Call the legacy function ``SETMIXdll``
2) Call ``REFPROPdll`` with the mixture file and extract the compositions See the docs(https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ALLPROPSdll): "To retrieve the property of a single component, use, for example, hOut=’XMOLE(2),XMOLE(3)’." or "XLIQ: Return the mass or molar liquid compositions (depending on the value of iMass) for 2-phase states."

**Comment by EricLemmon** [comment]
In reviewing past issues, this one caught my attention as a possible problem.  After talking with Ian Bell, we have decided that the intent of the z array should have been "out" instead of "in".  Thus the 4th line in this  routine should be:

      double precision, intent(out) :: z(ncmax)

If you wish to obtain an updated DLL, let us know (eric.lemmon@nist.gov).
