### ISSUE TITLE
any plans to release an updated HMX.BNC file for v10?

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#520]
### Description

The mixing parameter file HMX.BNC for version 10 was released/dated around mid-2018. NIST has published a paper summarizing available property data sets for refrigerant blends as recently as mid-2021 (https://pubs.acs.org/doi/10.1021/acs.jced.1c00192). Are there any plans to develop and release an updated HMX.BNC file based on NIST review of data sets and making recommendations for mixture parameters?

If not, should users contact NIST staff to request recommendations on specific binary pairs and then manually revise the file contents?

### Versions

**REFPROP Version:** [10.0]

**Comment by ianhbell** [comment]
Yes, we intend to make an updated HMX.BNC available with version 10.1, it will include a few refrigerant mixtures where we have new data.

**Comment by HightopRaven** [comment]
thanks!

**Comment by ianhbell** [comment]
You are welcome to reach out to us regarding particular binaries
