### ISSUE TITLE
REFPROP Code Signing

### ISSUE THREAD

**Issue by miketheitguy** [usnistgov/REFPROP-issues#522]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Description

Various DLLs, such as the Excel Add-In files, are not digitally signed. For example, REFPRP64.DLL. Is there any way the software could be digitally signed moving forward?
### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10

**Comment by miketheitguy** [comment]
This also includes macros.

**Comment by ianhbell** [comment]
You're right - we sign the installer, but we could in principle also sign the shared libraries.  This is the first notice we've had of this as an issue, so clearly not too many people are having this problem, but it is one we could remedy.  The add-in is trickier.  Is there a way to automate signing the add-in?

**Comment by miketheitguy** [comment]
I'll research and dig in. A user of mine (I'm in IT) said the add-in that was loaded was the DLL I mentioned above, I don't know very much about refprop otherwise :) I'll chat with the user on Monday and learn a little more.

**Comment by ianhbell** [comment]
add-in != DLL

Both can in principle be signed, but I need to know what is required.

**Comment by miketheitguy** [comment]
Hey! I just dug into this tonight and found out how to do this. The 32-bit version of signtool that comes with the Windows 10/11 SDK supports both XLA and XLAM formats.

I was able to both sign and timestamp the add-in.

The 64-bit sign tool does not work. :/ lame.

**Comment by miketheitguy** [comment]
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\signtool.exe" sign /sha1 sha-hash-of-x509-cert /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 c:\files\REFPROP.xla

**Comment by ianhbell** [comment]
And in your call, the ``sha-hash-of-x509`` is a flag, not the sha, am I correct?

**Comment by miketheitguy** [comment]
The /sha1 d482758365827defabccd command is a reference to the thumbprint of the code signing cert in the user store. There's a flag to use the machine store also, I forget what it is off the top of my head.

**Comment by ianhbell** [comment]
Can you give me a tiny powershell script for signing? I can't quite make out what comes from where

**Comment by miketheitguy** [comment]
Sure! Will be a little later today or tomorrow. Thanks so much for working with me!

**Comment by ianhbell** [comment]
No problem. Thanks for your help, sadly I'm not an expert at this

**Comment by ianhbell** [comment]
Any update? Another user asked for a similar thing quite recently.

**Comment by ianhbell** [comment]
I have been trying this for the last hour, all the permutations I can think of, and I keep getting something like:

```
SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: REFPROP.XLA
```

I tried something like:
```
.\signtool sign /f .\renewal\authenticodeCertificate.pfx /p super_clever_password /tr http://timestamp.digicert.com /td sha256 /fd sha256 /a "REFPROP.XLA"
```

**Comment by ianhbell** [comment]
In the end the only way I was able to get the signing to work on the excel files was to add the cert to my personal store and then do the signing manually.

**Comment by ianhbell** [comment]
Gonna close for now, please re-open if you have a solution for us.
