### ISSUE TITLE
OCX errors with other accounts 

### ISSUE THREAD

**Issue by IT-CEA-GRAMAT** [usnistgov/REFPROP-issues#526]
Hello,

I encounter OCX errors at launch of REFPROP.

The use case is  :
- Installation of Refprop by an IT admin (for security purposes, users are not administrators of their computers and cannot install any program). REFPROP works with his account
- Launch of Refprop  with my user account : Runtime Error 339 : mshflxgd.ocx or one of its dependencies are missing of corrupted
- The IT admin also attempted to "run as admin" REFPROP : an error about COMDLG32.ocx appear...
- Another IT admin attempted to launch refprop with his own account : COMDLG32.ocx missing or corrupted.

Registrering these files as described here https://pages.nist.gov/REFPROP-docs/ didn't work...

Any idea ?

**Comment by ianhbell** [comment]
I'm afraid I don't have any other ideas, aside from to call the shared library directly and not use the GUI. Not a great answer, but it should be more reliable.
