### ISSUE TITLE
#State is single phase, quality not calculated

### ISSUE THREAD

**Issue by MMeza1301** [usnistgov/REFPROP-issues#528]
Hi, 
I used to write [=Quality("water","ph","C",(8.35),(3,130.73))], and the result was [#Superheated steam (or the correspondent state)], but now the 10th version with [=REFPROP("Qmass","water","ph","C",(8.35),(3,130.73)] only gives [#State is single phase, quality not calculated]
How could I obtain the state? 

Thanks

**Comment by ianhbell** [comment]
Try the "PHASE" output. See the docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html

**Comment by MMeza1301** [comment]
Thanks, Ian, it worked perfectly
