### ISSUE TITLE
carbon dioxide and water mixture calculation

### ISSUE THREAD

**Issue by prettyEric** [usnistgov/REFPROP-issues#529]
Hi,
I used to write [refpropm('H','T',295,'P',8.5,'water','co2',[0.144 0.856])] in MATLAB, but the result was [2-phase iteration did not converge]. However, [refpropm('H','T',294,'P',8.5,'water','co2',[0.144 0.856])] could be calculated. What was the reason and how could I obtain the former state? (The version is REFPROP V10)

**Comment by ianhbell** [comment]
You need to switch to the Python interface, as it will give you more capabilities for specifying the phase.  See: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

**Comment by prettyEric** [comment]
Thanks, Ian. But the iteration in REFPROP interface did not converge, either. So I wonder whether this problem would emerge in Python.
![co2-water](https://user-images.githubusercontent.com/101103538/168809581-4c7bbe45-5ba4-4def-a4ba-3ee85f63e6bb.png)

**Comment by ianhbell** [comment]
Well, you need to do some combination of 

1. specifying the phase

2. enabling the saturation splines

which you can do in Python, but not the legacy interface.

**Comment by ianhbell** [comment]
Here's working code with the CoolProp interface to REFPROP:
```python
# With CoolProp interface to REFPROP
 
import CoolProp.CoolProp as CP
AS = CP.AbstractState('REFPROP','CO2&Water')
AS.set_mass_fractions([0.856, 0.144])
# Check saturation temp at this pressure
AS.update(CP.PQ_INPUTS, 8.5e3, 1)
print(AS.T())

AS.specify_phase(CP.iphase_gas)
AS.update(CP.PT_INPUTS, 8.5e3, 295)

```

**Comment by prettyEric** [comment]
Thanks Ian.
