### ISSUE TITLE
Add note to FAQ about how to use wine + REFPROP for *nix

### ISSUE THREAD

**Issue by ibell** [usnistgov/REFPROP-issues#53]
To force 32-bit mode on 64-bit OS:
https://askubuntu.com/questions/136714/how-to-force-wine-into-acting-like-32-bit-windows-on-64-bit-ubuntu

then 
```
wine NIST2310.exe
```
to install.

**Comment by ianhbell** [comment]
Closed by https://github.com/usnistgov/REFPROP-docs/commit/1d81bba8c7bfbb901e6926f0eee11238fa6decf3
