### ISSUE TITLE
RERPROP 10.0 R514A Missing

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-issues#531]
Hi Ian,

I am using the python code to generate MIX files by: 
https://github.com/usnistgov/REFPROP-issues/issues/358#issuecomment-872394368

It can't create R514A because of lack of R1130E. 

So I should use REFPROP 9.1? Or would you please share R514A MIX files?

Thanks a lot for your support. 

Frank

Could not load these fluids: R12|R31
<class 'ValueError'>
Could not load these fluids: R31|R114
<class 'ValueError'>
Could not load these fluids: R1336MZZZ|R1130E
<class 'ValueError'>
Could not load these fluids: R1234ZEE|R227EA|R1336MZZE
<class 'ValueError'>
Could not load these fluids: R1132A|R32|R1234YF
<class 'ValueError'>

**Comment by ianhbell** [comment]
Good point.  No fluid file for R1130E exists (for REFPROP 10 or 9.1).  Ergo, no mix file for R514A
