### ISSUE TITLE
Failed to call R515b mix file generated by python 

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-issues#532]
Hi Ian,

I generated the R515B.MIX by using the your python code by 
https://github.com/usnistgov/REFPROP-issues/issues/358#issuecomment-872394368

And I put it in the installation folder called *****\REFPROP\REFPROP\MIXTURES
When I tried to call in python wrapper, I got a error with -99999990. Is there any more setting before using new mix file?

Thanks. 

Frank

import  numpy as np
import os
import  numpy as np
import csv
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

T_crit = RP.REFPROPdll("R515B", "CRIT","T", RP.MOLAR_BASE_SI, 0, 1, 0, 0, [0]).Output[0]
print(T_crit)

**Comment by ianhbell** [comment]
I think it is because the file is *actually* in a ghost directory.  What happens if you provide the absolute path to the file? Also try ``"R515B.MIX"``.

**Comment by fuxinniu** [comment]
Thank you Ian

It is file path issue. Figure it out.

**Comment by ianhbell** [comment]
Can you say how you fixed it for future readers?
