### ISSUE TITLE
Mixture of CO2, Methane and Nitrogen: error calculating temp from enthalpy and hump in results

### ISSUE THREAD

**Issue by StefanBennoit** [usnistgov/REFPROP-issues#533]
Hello Sir or Madam, in the attached example fortan code (RefproTestCall.txt is a .for source code) using Refprop dll with version 10.0098 I found 2 problems.

1. With the given pressure and temperature I calculate the enthalpy with no problem.  Using this enthalpy to calculate back the temperature results in an error. (see Printout.txt).

2. Using the given pressure I calculate the enthalpy within a loop. There is a hump in the result values. (see Printout.txt)
        step  temperature                   enthalpy(p, t)
          29   293.066649169922        13880.2747193272     
          30   293.066809082031        13880.9394717376     
          31   293.066968994141        17254.0442857537  <<<------   
          32   293.067128906250        17254.0536303082  <<<------     
          33   293.067288818359        17254.0629748557  <<<------
          34   293.067448730469        17254.0723193963  <<<------
          35   293.067608642578        17254.0816639300  <<<------
          36   293.067768554688        13880.6284889380     
          37   293.067928466797        13880.6587749722     

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
4. [Second Step]
5. [and so on...]

**Expected behavior:** [What you expect to happen]
```
      ncomp = 3
      hFiles = 'CO2.FLD|METHANE.FLD|NITROGEN.FLD'
      hFmix  = 'HMX.bnc'
      hrf    = 'DEF'
      CALL SETUPdll(ncomp,hFiles, hFmix, hrf,ierr,herr)
      CALL SETNCdll(ncomp)
      z(1) = 0.77412369140474746
      z(2) = 0.21236335822914112
      z(3) = 0.013512950366111305

      P = 9901.8640902344705
C
C     ############
C     PROBLEM #1/2
C     ############
C     First step: start with pressure and temperature to get the enthalpy
      T = 20 + 273.15
      CALL TPFLSHdll(T,P,z,D,Dl,Dv,x,y,q,e,h,s,Cv,Cp,w,
     &            ierr, herr)
C     Second step: with pressure and the calculated enthalpy we should get
C     our temperature back.
      CALL PHFLSHdll (P,h,z,T,D,Dl,Dv,x,y,q,e,s,Cv,Cp,w,ierr,herr)
```
**Actual behavior:** [What actually happens]
It result in an error:
[PHFLSH error 3] One or more inputs are out of range; Temperature below triple-
 point or minimum temperature: T = 71.4336 K, Tmin = 120.948 K; Density above up
 per limit: D = 40.2323 mol/L, Dmax = 38.0147 mol/L.
Remind: the temperature it is all starting with is 20 DegC.

### Versions
[RefPropTestCall.txt](https://github.com/usnistgov/REFPROP-issues/files/9001860/RefPropTestCall.txt)

**REFPROP Version:** [REFPROP 10.0098]  
**Operating System and Version:** [Windows 10 Enterprise (Build 19042.1766) [64Bit]]  
**Access Method:** [normally C++, here example FORTRAN program build with Intel® Fortran Compiler – toolkit version: 2022.1.0, extension version 22.0.0065.16, ]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.
[PrintOut.txt](https://github.com/usnistgov/REFPROP-issues/files/9001789/PrintOut.txt)

Thanks in advance for the support.
Best regards
Stefan

**Comment by ianhbell** [comment]
Try to turn on the saturation splines with SATSPLN

**Comment by StefanBennoit** [comment]
Hello Ian, thanks for the immediate answer. I will read about SATSPLN and give it a try. Will post here about the result.
Best regards
Stefan

**Comment by StefanBennoit** [comment]
Hello Ian, I called SATSPLNdll after specifying my composition and it worked, the unexpected behaviors are gone. How can I recognize when to call it before using TPFLSHdll or PHFLSHdll or other functions or should I add this call on every changed composition?
Best regards
Stefan

**Comment by ianhbell** [comment]
It's hard to say.  Generally you should always turn it on, but check that the results you are getting are sensible.

**Comment by StefanBennoit** [comment]
Thank you again for your very quick and immediately helping answer.
Best regards
Stefan.
