### ISSUE TITLE
2-phase iteration did not converge.

### ISSUE THREAD

**Issue by prettyEric** [usnistgov/REFPROP-issues#535]
Hello, I have met a strange issue.
I would like to calculate enthalpy of a mixture using pressure and entropy in MATLAB, but it failed.
I used codes as bellow:
[iUnits=RP.GETENUMdll(int8(0),'MASS BASE SI').iEnum;]
[r=RP.REFPROPdll('water;co2','PS','H',iUnits,int8(1),int8(0),9100,6.755e3,{0.784,0.216});], and it showed "[PSFL2 error 226] 2-phase iteration did not converge." in the [r.herr].
However, if you changed '6.755e3' to '6.76e3' or '6.75e3', which are all 2-phase, they can be calculated well. So how can I deal with that?

**Comment by ianhbell** [comment]
Have you tried with and without the saturation splines? Sometimes that makes a difference.

**Comment by prettyEric** [comment]
Not yet. How to write the code?

**Comment by ianhbell** [comment]
You set iFlag to 1 in your call, try 0 (default flags)

**Comment by prettyEric** [comment]
In my call, iFlag had been set to 0, and whether 0 or 1, it didn't work.

**Comment by ianhbell** [comment]
Hmm, yes, there are issues with iterative routines sometimes, it is very tricky to do these calculations. Have you tried the ABFL2 function: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/ABFL2dll

**Comment by prettyEric** [comment]
Not yet, and how to use ABFL2? It seems that there is no fluid information input in ABFL2.
 Can I use the function in High-Level API :https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/

**Comment by ianhbell** [comment]
You need to first set the fluid with SETFLUIDSdll or SETMIXdll, then call the ABFL2 function. Note which arguments are inputs or outputs.

**Comment by prettyEric** [comment]
I was not familiar with SETMIXdll and ABFL2, and it always reported errors when I called. Can you please write the codes?

**Comment by ianhbell** [comment]
Please read the docs, give it a try, show your code and report the errors.

**Comment by prettyEric** [comment]
I called SETMIXdll first, but I did not know how to give the parameter 'hFmix'. It is described as 'File containing mixture coefficients' in the docs, what is that?

**Comment by ianhbell** [comment]
Default would be ``"HMX.BNC"``

**Comment by prettyEric** [comment]
I tried with [RP=py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP'); RP.SETMIXdll('water&co2','HMX.BNC','DEF')], it showed 'Error in opening mixture file: water&co2'.

**Comment by ianhbell** [comment]
``&`` is not a valid delimiter, try ``;`` .  Also, you should always use the case of the fluid names consistent with the FLD file name (so all uppercase in this case)

**Comment by prettyEric** [comment]
The code [RP.SETMIXdll('WATER;CO2','HMX.BNC','DEF')] also did not work.

**Comment by ianhbell** [comment]
I think you misunderstand. ``SETFLUIDSdll`` is to specify the components, ``SETMIXdll`` is to load a predefined mixture from a ``.MIX`` file

**Comment by prettyEric** [comment]
Thanks, it works well. Now I am going to try ABFL2dll, but how can I get the input parameters 'Tbub, Tdew, Pbub, Pdew, Dlbub, Dvdew'?

**Comment by ianhbell** [comment]
Those are only needed if ksat is 1, otherwise set them to whatever value you like

**Comment by prettyEric** [comment]
I tried with [RP.ABFL2dll(9,6.755e3,{0.784,0.216},int8(2),int8(0),'PS',0,0,0,0,0,0,0,0)], it reported that [No method 'ABFL2dll' with matching signature found for class 'py.ctREFPROP.ctREFPROP.REFPROPInstance'.]. Maybe the function is not available in the class.

**Comment by ianhbell** [comment]
Can you please post your complete runnable test code?

**Comment by prettyEric** [comment]
[RP=py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
RP.ABFL2dll(9,6.755e3,{0.784,0.216},int8(2),int8(0),'PS',0,0,0,0,0,0,0,0)]

**Comment by ianhbell** [comment]
That's not complete, missing setup of mixture

**Comment by prettyEric** [comment]
[RP=py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
RP.SETFLUIDSdll('water;co2');
RP.ABFL2dll(9,6.755e3,{0.784,0.216},int8(2),int8(0),'PS',0,0,0,0,0,0,0,0)]

**Comment by ianhbell** [comment]
I ran your example in Python:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(r'C:\Program Files (x86)\REFPROP');\
RP.SETFLUIDSdll('water;co2')
print(RP.ABFL2dll(9,6.755e3,[0.784,0.216],0,0,'PS'))
```
yielding
```
ABFL2dlloutput(Tbub=156.8479844487202, Tdew=312.3229345633781, Pbub=0.0, Pdew=0.0, Dlbub=57.15977290546818, Dvdew=0.0034726183158053704, 
ybub=array('d', [0.9757019429763398, 0.02429805702366017, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
xdew=array('d', [0.9999817603445199, 1.82396554800901e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
T=310.76818506223157, P=0.0, Dl=0.0, Dv=0.0, 
x=array('d', [0.784, 0.216, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
y=array('d', [0.784, 0.216, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), 
q=998.0, ierr=226, herr='[PSFL2 error 226] 2-phase iteration did not converge.')
```
which unfortunately is the same bad answer you got.

The docs and the code appear to be out of sync.  The docs are wrong, because this is the function that is exposed from FORTRAN:
```fortran
      subroutine ABFL2dll (a,b,z,kq,ksat,ab,
     &                     Tbub,Tdew,Pbub,Pdew,Dlbub,Dvdew,ybub,xdew,
     &                     T,P,Dl,Dv,x,y,q,ierr,herr)
      include 'CONSTS.INC'
      double precision, intent(in) :: a, b, z(ncmax)
      integer, intent(in) :: kq, ksat
      character, intent(in) :: ab*2
      double precision, intent(out) :: Tbub,Tdew,Pbub,Pdew,Dlbub,
     &                                 Dvdew,ybub(ncmax),xdew(ncmax),T,
     &                                 P,Dl,Dv,x(ncmax),y(ncmax),q
      integer, intent(out) :: ierr
      character*255, intent(out) :: herr
cDEC$ ATTRIBUTES DLLEXPORT, Decorate, Alias: "ABFL2dll"::ABFL2dll
cDEC$ ATTRIBUTES STDCALL, REFERENCE::ABFL2dll
c     dll_export ABFL2dll
      call ABFL2 (ab,a,b,z,kq,ksat,
     &            Tbub,Tdew,Pbub,Pdew,Dlbub,Dvdew,ybub,xdew,
     &            T,P,Dl,Dv,x,y,q,ierr,herr)
      herr(255:255)=CHAR(0)
      end
```

**Comment by prettyEric** [comment]
Is there a solution?

**Comment by ianhbell** [comment]
You could try the beta, you can email me (ian.bell@nist.gov) for access

**Comment by prettyEric** [comment]
Already sent.

**Comment by prettyEric** [comment]
I have replaced with the beta. Should I still try ABFL2dll, or REFPROPdll?

**Comment by prettyEric** [comment]
I tried with REFPROPdll, it still failed.

**Comment by ianhbell** [comment]
Sorry, I don't have any better ideas, mixture iterative calculations are difficult. You could do the iteration yourself manually if you have a good guess for temperature and density with the ``fsolve`` function in MATLAB

**Comment by prettyEric** [comment]
Ok, fine. I will do the iteration manually. Thanks for your kind answers.
