### ISSUE TITLE
Can't be liquid

### ISSUE THREAD

**Issue by Ranzengar** [usnistgov/REFPROP-issues#536]
hi,
we are implementing the RefProp 10 library in a c# application via a custom wrapper, as the wrapper listed on the repo uses deprecated functions.
We are trying to perform a calculation via the REFPROPDLL function by entering as input a mixture consisting of 97% CH4 and 3% CO2, but at the conditions of 313.15K and 15.4 bar g the result calculates a q = 0 (liquid), but this cannot be.
We then tried changing the percentages of the composition to 97.1% CH4 and 2.9 CO2, and so the results are correct.
Is there perhaps a bug of some kind?

Code:
``` C#
            string hIn = "TP";          //type of inputs
            double a = T;               //first input [K]
            double b = p * 100000;      //second input [Pa]

            double[] prop_z = z;    //Array of molar fractions
            long iFlag = 0;  //determines some specific input and output behaviours
            string herr = new string(' ', 255);
            long hEnum_length = 255;
            long herr_length = 255;

            long iEnum = 0;
            string hEnum = "MASS BASE SI";
            string hOut = "DLIQ;DVAP;HVAP;SVAP;CPVAP;CVVAP;CP/CVVAP;MVAP;ZVAP;QMASS;QMOLE";

            long iMass = 0;          //input and output compositions on mole basis
            long ierr = 0;

            IRefProp64.GETENUMdll(ref iFlag, ref hEnum, ref iEnum, ref ierr, ref herr, ref hEnum_length, ref herr_length);

            iFlag = 0;
            double[] output = new double[200];
            string hUnits = new string(' ', 255);
            long iUnits = iEnum;
            long iUCode = 0;
            double[] x3 = new double[20];
            long hInLength = 255;
            long hOutLength = 255;
            long hUnitsLength = 255;

            long hfldLength = 10000;

             IRefProp64.REFPROPdll(ref hfldMsSs, ref hIn, ref hOut, ref iUnits, ref iMass, ref iFlag,
                        ref a, ref b, prop_z, output, ref hUnits, ref iUCode, x, y, x3, ref q, ref ierr,
                        ref herr, ref hfldLength, ref hInLength, ref hOutLength, ref hUnitsLength, ref herr_length);
```

Thanks
Alket

**Comment by ianhbell** [comment]
Recommend to call the SATSPLNdll function to generate the saturation spline.  Helps in many, but not all, cases.

**Comment by Ranzengar** [comment]
Thank you, i confirm that in this case it helped.

I'm doing some more calculations and, in particular, with a mixture of 67% methane, 30% nitrogen and 3% water at the conditions of 313.15K and 5049900 Pa I would expect water condensation but I'm not getting any, is this normal?
The value of q results 999

**Comment by ianhbell** [comment]
First stop is to look at the isopleth of the phase boundary and see where your point is relative to the phase boundary. Mixtures with water have weird thermodynamics that is hard to model and especially hard to write algorithms for.

**Comment by bigoper** [comment]
Hi @Ranzengar 

Will you be able to share your implementation of `GETENUMdll` and `REFPROPdll`?
It'll be highly appreciated.

Thank you!
