### ISSUE TITLE
Wrong phase detection

### ISSUE THREAD

**Issue by likona1993** [usnistgov/REFPROP-issues#538]
### Description

Good Afternoon! I'm doing some calculations in EXCEL using REFPROP 10 for the following mixture: 77,95 % Methane, 13% Ethane, 5% Propane, 4% 
hydrogen sulfide, 0,02 % Water and 0,03 % Helium. For 265,15 K and pressure 4 MPa it shows that the mixture is a Superheated gas, 
although the point is above a dew point line, so it should be a liquid. Which result should be trusted?

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 64bit
**Access Method:** Excel

**Comment by ianhbell** [comment]
This is a challenging mixture you have put together.  Recommend to plot the isopleth of the phase envelope to see what it looks like.  Make sure you turn on saturation splines.

**Comment by berryjx** [comment]
If it is above the dew point it is a superheated gas.

**Comment by ianhbell** [comment]
Correct, but you need to plot the isopleth to see what REFPROP *thinks* the isopleth looks like.
