### ISSUE TITLE
Run-time error '339'

### ISSUE THREAD

**Issue by Tasquith** [usnistgov/REFPROP-issues#539]
### Versions

**REFPROP Version:** [10]  
**Operating System and Version:** [win 64] processing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![image](https://user-images.githubusercontent.com/112190047/186940736-e1aed26b-0faf-4442-833f-527c16f91380.png)
 runtime error 339
"component 'mshflxgd.ocx' or one of its dependencies not correctly registered: a file is missing or invalid

**Comment by ianhbell** [comment]
Please see https://pages.nist.gov/REFPROP-docs/#installation-problems
