### ISSUE TITLE
R507A.PPF bug in REFPROP 10

### ISSUE THREAD

**Issue by ChenYuChih** [usnistgov/REFPROP-issues#54]
### Description

When using "R507A.PPF" for getting saturation liquid temperature from pressure, there's a wide error range between 2.39 MPa to 3.1 MPa and cannot return any value. This problem exists not only on GUI application but also direct dll(32 bit) function calls.

**Expected behavior:** 

Return the correct value.

**Actual behavior:** 

Return error.

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 7 and 10
**Access Method:** Excel VBA

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
This is a confirmed and very unfortunate bug.  Eric has communicated an updated fluid file and additional tests will be added for the pseudo-pure fluids.

**Comment by EricLemmon** [comment]
The R507A.ppf pseudo-pure fluid file is missing the last term in the equation.  This has now been fixed, and the updated fluid file can be found here:

https://pages.nist.gov/REFPROP-docs/#errors-in-version-10
