### ISSUE TITLE
Phase boundaries can depend on component order

### ISSUE THREAD

**Issue by ahawryluk** [usnistgov/REFPROP-issues#544]
### Description

For some mixtures, the phase boundary depends on the order of the components. This may be related to #537, but I'm submitting a separate issue in case they are not related.

### Steps to reproduce

``` python
import os
import numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print('Refprop version', RP.RPVersion())


def check_max_T(components, mole_fracs):
    RP.SETUPdll(len(components), '|'.join(components), 'HMX.BNC', 'DEF')
    RP.SATSPLNdll(mole_fracs)
    return RP.MAXTdll(mole_fracs)


components = np.array([
    'METHANE.FLD', 'ETHANE.FLD', 'PROPANE.FLD', 'ISOBUTANE.FLD', 'BUTANE.FLD',
    'CO2.FLD', 'NITROGEN.FLD', 'ISOPENTANE.FLD', 'PENTANE.FLD', 'HEXANE.FLD',
    'HEPTANE.FLD', 'HYDROGEN.FLD', 'OCTANE.FLD', 'HELIUM.FLD', 'NONANE.FLD',
    'DECANE.FLD', 'H2S.FLD'])
mole_fracs = np.array([
    0.9033, 0.0672, 0.0163, 0.0038, 0.0034, 0.0019, 0.0012, 0.0011, 0.0007,
    0.0006, 0.0003, 0.0001, 0.0001, 0.,     0.,     0.,     0.])
print(check_max_T(components, mole_fracs))
print(check_max_T(components[::-1], mole_fracs[::-1]))

```

**Expected behavior:**

We were expecting to see the same phase boundary (cricondentherm), independent of the component order.

**Actual behavior:**

```
Refprop version 10.0
MAXTdlloutput(Tm=274.3598343576143, Pm=4335.914866076322, Dm=2.190303935501533, ierr=0, herr='')
MAXTdlloutput(Tm=270.64599077638997, Pm=3677.9666432586805, Dm=1.8482019073418126, ierr=0, herr='')
```

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** Python ctypes

**Comment by ianhbell** [comment]
What precise version do you have? Want to try the beta that fixes (I think) this problem, but introduces a few others.

**Comment by ianhbell** [comment]
If so, email me at ian.bell@nist.gov

**Comment by ahawryluk** [comment]
I'm not sure how to check the precise version, but most of the files inside C:\Program Files (x86)\REFPROP are dated 2018-06-04 if that's any help. I'll email you about the beta. Thanks for the reply!

**Comment by ahawryluk** [comment]
I've confirmed that this bug is fixed in the beta version. For my test script above it prints

```
Refprop version 10.0.0.98
MAXTdlloutput(Tm=274.3595173159961, Pm=4335.892113409694, Dm=2.19029375179402, ierr=0, herr='')
MAXTdlloutput(Tm=274.3595173159956, Pm=4335.892113408338, Dm=2.1902937517931713, ierr=0, herr='')
```
