### ISSUE TITLE
Applicability on REFPROP on cryo service on mixed refrigerant 

### ISSUE THREAD

**Issue by marcotognotti** [usnistgov/REFPROP-issues#545]
We are using the REFPROP Equation of State embedded with the Aspen properties in Hysys 12.0 (using the NIST database version 10.16 xml files dated 2018) for a process simulation of a mixed refrigerant loop in a natural gas liquefaction plant.
The mixed refrigerant mixture contains the following five components:

Nitrogen
Methane
Ethylene
Propane
Isopentane

When we expand this mixture from 550 psig and -260°F down to 55 psig, the Refprop EOS shows very high nitrogen and methane flash, in comparison with the results from the Hysys Peng Robinson EOS.
The amount of vapor generated because of pressure reduction is 1.5 times higher than the PR.
We’d like to understand if the NIST Refprop property package is reliable when used with this mixture, how the binary interaction between the components are handled, and if the high nitrogen flash when reducing the pressure at this cryo condition is realistic or not.

Thank you.

**Comment by ianhbell** [comment]
Peng-Robinson, often, but not always, does a pretty good job with phase equilibria. But of course, the selected values for the k_ij parameters will play a big role in the phase equilibria results.

Overall I would *think* that a model with these components should be well-modeled by the REFPROP model because the experimental data used to develop the models should cover these pairs well, and thus the mixture model should be reliable (there is no hydrogen, or water, or helium, for instance).  But the only way to know for sure is to compare against experimental data.

**Comment by marcotognotti** [comment]
The problem is that PR and Refprop are providing very different results for this specific case and experimental data for these cryo conditions are difficult to be obtained.

**Comment by ianhbell** [comment]
Understood. But I don't think we can answer this question conclusively.

**Comment by marcotognotti** [comment]
Ok, thank you for your response

**Comment by nist-aharvey** [comment]
If 2 or 3 of the components are dominant with the others at low levels like 1%, you could potentially find experimental data to compare against by looking at just the main heavy/light binaries.  So for example if there is not very much isopentane or ethylene, you could see how well Refprop and PR did with the methane/propane and nitrogen/propane binaries, preferably at conditions similar to your calculation.  Those binaries would have a good amount of vapor-liquid equilibrium data.  
If you do well with the dominant 2 or 3 components, small amounts of others should not make much difference in terms of which model is better.

**Comment by marcotognotti** [comment]
Does NIST have some experimental data to share about flash of liquid nitrogen from medium pressure to low pressure?
Or even flash of a liquid nitrogen-methane mixture?
Thank you.

**Comment by ianhbell** [comment]
You can see what is in the literature as of approximately 2016 at https://trc.nist.gov/thermolit/main/home.html#property/syssel:2:form:form:form/props:-1:-1:-1
