### ISSUE TITLE
Ideal Gas Entropy Discrepancy?

### ISSUE THREAD

**Issue by jonathanpmcdonald** [usnistgov/REFPROP-issues#546]
### Description

Ideal gas entropy (S0) output by REFPROP (either GUI or Excel interface) along an isobar is not consistent with it basic definition from TdS relation where, along an isobar, deltaS0 = Integral(Cp0(T)/T) dT.  The discrepancy is small 4th or 5th significant figure, but REFPROP typically reproduces most basic thermodynamic relations to 12+ significant figures.  Other common sources for ideal gas quantities (Thermodynamic Properties of Individual Substances, NIST-JANAF Thermochemical Tables) obey the basic dS relation.

### Steps to Reproduce

1. Easiest to observe this for atoms such as Helium or Argon where Cp0 is constant, such that the integral result for deltaS0 is simply Cp0*ln(T).  Though the same qualitative behavior is observed for nitrogen and parahydrogen - I haven't tried others.
2. Of course, be certain to additively shift results to share a common reference point since only changes in entropy matter.
3. Observe that resulting S0 curve deviates from that output by REFPROP on either side of the chosen reference point.  The error grows to be in the 4th or 5th significant figure over an interval of a few 100 Kelvin.

**Expected behavior:** For ideal gas properties along an isobar, the relation dS0 = Cp0*dT should apply when integrated between any two temperature points.

**Actual behavior:** Small deviations as described above are observed.

### Versions

**REFPROP Version:** DLL Version 10.0 
**Operating System and Version:** Windows 10 Enterprise 10.0.19044 
**Access Method:** Both GUI and Excel calls 

### Additional Information

Please forgive me if the real issue is that I took thermodynamics 35 years ago.

**Comment by ianhbell** [comment]
Most popular FAQ: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

**Comment by jonathanpmcdonald** [comment]
> Most popular FAQ: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

Thanks.  The issue is with curve shape and not reference state.  As noted in the original posting on how to recreate the issue, one must shift the reference state to that used by REFPROP prior to observing the difference.  Otherwise, values at all temperatures will likely be different due to dissimilar reference states.

**Comment by ianhbell** [comment]
Then you are talking about the gas constant probably: https://github.com/usnistgov/REFPROP-issues/issues/239

**Comment by jonathanpmcdonald** [comment]
That would result in a constant offset, but we are ensuring that we use the same value used by REFPROP by asking for it in an Excel call for "R".  Confirmation that we got the correct value comes, though not mentioned above, in the fact that for Helium Cp0 is exactly 2.5 times R.

**Comment by ianhbell** [comment]
Then I'm stumped. My guess is that you are accumulating small errors in density as you do calculations of rho(T,p) and that is why you therefore see small errors in the calculation of s0 ultimately. 

Can you put together a runnable example in something like MATLAB or Python? Or at least provide some numbers so I can confirm on my side?

**Comment by jonathanpmcdonald** [comment]
I will try to attach a spreadsheet with the calculations for Helium and Argon.

Working with Ideal Gas quantities along an isobar, density should never come into play when calculating S0, since the term dealing with changes in Rho*T becomes ln(1) = 0.
[REFPROP S0 Does not Appear to Agree with Value from Integration of Cp0 over T.xlsx](https://github.com/usnistgov/REFPROP-issues/files/9759918/REFPROP.S0.Does.not.Appear.to.Agree.with.Value.from.Integration.of.Cp0.over.T.xlsx)

**Comment by jonathanpmcdonald** [comment]
That sheet contains a tab with limited comparisons of helium from REFPROP 10 and the NIST-JANAF tables, one with helium ever 1 K, and one for Argon every 1 K - note that I just used the helium page for Argon so valid results aren't found until somewhere around row 80.

**Comment by jonathanpmcdonald** [comment]
One great thing about REFPROP 10's Excel AddIn is that it seems to just work as sheet are passed around, unlike many of the past versions.  Hopefully, that one works for you.

**Comment by EricLemmon** [comment]
Did you try this at 0 MPa or at 1 atm?  If at 1 atm, then the entropy is not the ideal gas, but there will be a small correction for the real gas and that might be what you are seeing.  

Actually, that was a dumb question because entropy at 0 MPa is infinite, so you had to enter a pressure in order to make those calculations.  In the GUI is an option to show the ideal gas entropy.  You will find it under the Options/Properties window on the "Special" tab.  The calculated values should be within the precision of the methods you are using.

**Comment by jonathanpmcdonald** [comment]
Eric.  I made calls to the Ideal Gas Properties directly in both GUI and Excel.  Cp0 and H0 are independent of pressure but S0 depends on pressure so I specified 1 bar when making the calls.  That 1 bar was held constant to ensure the pressure term should be zero.

**Comment by ianhbell** [comment]
In the EOS, when you specify pressure, the density is calculated, and _that_ density is used in the ideal-gas Helmholtz energy contribution. I suspect that is causing your troubles.

**Comment by jonathanpmcdonald** [comment]
I can kind of recreate the S0 numbers output by REFPROP if I integrate 1/(T+A) instead of 1/T, where A is some very small number.

**Comment by EricLemmon** [comment]
Inputs to the Refprop routines are temperature and density, not pressure.  The pressure you are using is the real-gas pressure, but the code expects that you send it the ideal gas pressure based on temperature and density.  You would thus need to calculate the density you send to the THERM0 subroutines as D=P/T/R.  

Hopefully this helps some:  https://github.com/usnistgov/REFPROP-issues/issues/102

**Comment by jonathanpmcdonald** [comment]
Eric.  Thanks.  I suspect that might very well be what is tripping me up here.  When I request ideal gas entropy via specification of P and T, I was not expecting P to be treated as a real gas value.  I will try to work around this by request ideal gas density from P and T first, and then feeding T and ideal gas density to an ideal gas entropy call.

BTW - 102 did not come up when I searched the REFPROP area here on Github for the string "ideal gas entropy".  computers?!?!

**Comment by EricLemmon** [comment]
Odd.  I'll type it in here as text with a few spaces to fool it so that a link is not formed:

https:// github.com /usnistgov /REFPROP-issues /issues /102

Ian probably knows how to format that properly, but I'm still learning with his help!

**Comment by ianhbell** [comment]
@EricLemmon the URL is fine, @jonathanpmcdonald just didn't find the information when searching the issues

**Comment by jonathanpmcdonald** [comment]
Ian and Eric.  That did the trick.  I calculated a D0 as P/T/(call to retrieve "R" at P and T) and fed this D0 and T into the call for S0.  The result so obtained is in exact agreement with the result expected from the integral relationship.

Any chance that this can be made more transparent by treating input pressure as ideal gas in nature when passed to a call for an ideal gas property?  I realize there might be a user that requests ideal gas properties and needs P to correspond to the real-gas PVT surface, but I am betting most users are like me and thinking ... "but, I am interested in an ideal gas here".

Big thanks to you both.  Always a pleasure dealing with you guys.  Makes me wish I ran across issues more than once every decade.

**Comment by ianhbell** [comment]
No, don't think we can make this more transparent as this is just how the EOS works. Everything is in terms of temperature and density. We could definitely document better, but this won't change in REFPROP's interface.

**Comment by jonathanpmcdonald** [comment]
Ian,

What I am getting at isn't actually EoS related, but it would add a decision to the calculation flow that is seldom relevant so likely not worth slowing things down slightly for 99.99999% of calls.

If the code processes the requested function first, then on recognizing a request for an ideal gas property, it would calculate ideal gas density instead of using the EoS to find density.\
