### ISSUE TITLE
Missing term for air in ideal-gas

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#547]
In the EOS for air from JPCRD there are 10 terms:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/11966765/195889239-324cfd64-7fe6-4541-8ea2-e21fb411fcfb.png">

whereas in the FLD file, the last term is not present:
```
#AUX   !---Auxiliary function for PH0
PH0    !Ideal gas Helmholtz form for air of Lemmon et al. (2000).
?
?```````````````````````````````````````````````````````````````````````````````
?Lemmon, E.W., Jacobsen, R.T, Penoncello, S.G., and Friend, D.G.
?
!```````````````````````````````````````````````````````````````````````````````
0.                 !
10000.             !
0.                 !
0.                 !
1 6  2 0 0  0 0 0  !Nterms:  ai*log(tau**ti); ai*tau**ti; ai*log(1-exp(bi*tau)); cosh; sinh
 2.490888          1.0                 !ai, ti for [ai*log(tau**ti)] terms
-3.4666226577      0.0                 !aj, ti for [ai*tau**ti] terms
 3.3037934171      1.0
-0.0001588607     -1.0
-0.0000210275     -2.0
 0.0000000606     -3.0
-0.0001953634      1.5
 0.7913095100     -25.3636474676       !aj, ti for [ai*log(1-exp(ti*tau)] terms
 0.2122367700     -16.9074094180
```

Where did it go? Is there some reason it was not included?

**Comment by EricLemmon** [comment]
If I remember right, this term accounted for the electronic contribution in oxygen at very high temperatures and had nearly no impact in the range where the oxygen equation is valid (up to 2000 K).  But more importantly is that oxygen decomposes before the electronic contribution kicks in and the term becomes meaningless.

Depending on how one sets up the code for calculating properties, this term adds an additional 2.5% to 5% to the total time required to make calculations for the pure fluid.  It's not much but it's also not insignificant when fitting an equation of state or running process simulations.

**Comment by ianhbell** [comment]
Interesting, could this be documented somewhere?

**Comment by EricLemmon** [comment]
Oxygen is being (slowly) refit, that would be the best place when the new document is written.  But here is also a great place!
