### ISSUE TITLE
Wrong temperature outputs for a given pressure and density (for certain compositions)

### ISSUE THREAD

**Issue by JoelvdLee** [usnistgov/REFPROP-issues#548]
Currently I am computing the temperature of a 11-component mixture based on pressure and density using the Matlab extension of RefProp. In some cases RefProp is unable to return a proper temperature. I found the NIST SUPERTRAPP is in general unable to perform calculations based on pressure and density, from which I derive that there is a problem in computing properties based on these state variables. RefProp is, however, able to return proper results for most conditions, so I wonder if there is a bypass/fix for this issue? My application requires a robust EOS, something that works in all cases.

species: C12', 'HYDROGEN', 'methane', 'ETHYLENE', 'ethane', 'PROPYLEN', 'propane', '1BUTENE', 'butane', 'toluene', 'octane'
composition = [0.92372, 2.843e-05, 0.0017067, 0.0049654, 0.0048561, 0.0053972, 0.0045441, 0.0020565, 0.0011228, 0, 0.051603]

**INCONSISTEN RETURNS** 
when I first compute the density for a given temperature, lets say 792 K at 30 bar

refpropm('D','T',**792**,'P',3000,'C12','HYDROGEN','methane','ETHYLENE','ethane','PROPYLEN', 'propane','1BUTENE','butane','toluene','octane',compostion) returns **88.52 kg/m3**

but the other way around returns an incorrect value.
refpropm('T','D',**88.52**,'P',3000,'C12','HYDROGEN','methane','ETHYLENE','ethane','PROPYLEN', 'propane','1BUTENE','butane','toluene','octane',compostion) returns **624.15 K**

**CORRECT OUTPUT FOR DIFFERENT COMPOSITION**
if the composition changes slightly, then function works property, it is only for this specific composition that I encounter problems. In the case the composition is changed the previous operation provides correct outputs.
new_composition = [0.93197, 2.5356e-05, 0.0015221, 0.0044285, 0.004331, 0.0048136, 0.0040528, 0.0018341, 0.0010014, 0, 0.046024]

refpropm('D','T',**792**,'P',3000,'C12','HYDROGEN','methane','ETHYLENE','ethane','PROPYLEN', 'propane','1BUTENE','butane','toluene','octane',**new_composition**) returns **90.45 kg/m3**

refpropm('T','D',**90.45**,'P',3000,'C12','HYDROGEN','methane','ETHYLENE','ethane','PROPYLEN', 'propane','1BUTENE','butane','toluene','octane',**new_composition**) returns **791.98 K**

**UNEXPLAINED JUMP OF TEMPERATURE** 
when considering the first composition, the temperature calculation does strange things.
if density comes above 82 kg/m3, the temperature drops 200 K. This is not the case for new_composition.

refpropm('T','D',**81**,'P',3000,'C12','HYDROGEN','methane','ETHYLENE','ethane','PROPYLEN', 'propane','1BUTENE','butane','toluene','octane',composition) results in **823.7K**

refpropm('T','D',**82**,'P',3000,'C12','HYDROGEN','methane','ETHYLENE','ethane','PROPYLEN', 'propane','1BUTENE','butane','toluene','octane',composition) results in **628.4 K**

It would be very helpful to receive insight about any limitations RefProp has when computating properties based on state variables pressure and density and why wrong outputs are observed for certain compositions. I think it might be related to limitations of certain individual species, in which case I could eliminate them from the calculation.

**Comment by EricLemmon** [comment]
Do a search for "SATSPLN" at both REFPROP github websites and you'll find information to help.  In particular, look for ones with the label "Documentation".  If that doesn't help, let us know.

https://github.com/usnistgov/REFPROP-issues/issues
https://github.com/usnistgov/REFPROP-wrappers/issues

**Comment by JoelvdLee** [comment]
Hi Eric, thank you for helping me in the right direction. I have been searching through different cases in both links using the provided keywords, but was not able to fix the issue myself. If I am not mistaken, the problem relates to critical conditions of the mixture and therefore I should activate the SATSPLN subroutine.
I found that the SATSPLN code line in rp_proto.m is already uncommented. I think I also have to uncomment a line in the refprop.m file itself related to the SATSPLN subroutine, but I am not sure.  
Joel

**Comment by EricLemmon** [comment]
The refprop.m file has been deprecated and we are no longer supporting it, instead you should switch over to the python interface described here:

https://github.com/usnistgov/REFPROP-wrappers
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by JoelvdLee** [comment]
I noticed that 1BUTENE is not available in the actual REFPROP software. When I eliminate this specie is seems to work correctly. Could it be that the issue relate to this component specifically? (since it is also not supported in the REFPROP.EXE file)

Related to you reply, thank you for the answer, I will check the python interface. But do I understand correctly that in the python interface the issue does not occur? Or do you mean that only in the python interface you can provide further help?

thanks

**Comment by ianhbell** [comment]
The Python routines call the same functions in the shared library, so no, the interfaces will yield the same answers, but you can easily call the SATSPLNdll function in the Python interface, plus a lot of other new capabilities not present in the refpropm interface.
