### ISSUE TITLE
Question: Does Refprop Include Support For TTSE or Bicubic Interpolation?

### ISSUE THREAD

**Issue by kauffmanjp** [usnistgov/REFPROP-issues#549]
In order to improve the performance of thermodynamic systems analysis and optimization, I would like to be able to use computationally efficient fluid property calculation routines. Refprop is a fantastic tool, but is built to favor high precision HEOS models and mixture models, at the cost of computational speed. And, given that many promising low GWP fluids in the ongoing HVAC&R transition are mixtures, the high precision HEOS/mixture models may not be computationally efficient enough for those who wish to model and optimize systems.

As a result, I have considered migrating some projects to CoolProp, in order to leverage its' ability to use [TTSE or Bicubic methods](http://www.coolprop.org/coolprop/Tabular.html#) with tabular data generated from detailed models (via the Refprop interface).

But it prompted the question:
- Does the Refprop.dll currently include any built-in methods to support these fast interpolation methods? 
- If not, are there plans to support TTSE or Bicubic methods in the future?

Thanks for your consideration.

**Comment by ianhbell** [comment]
Sadly, I think the answers to both questions are no. Seeing as how CoolProp implements those methods, I just point people there. The methods in CoolProp have some definite weaknesses, but they are at least very fast when they work. I am working on a more generic root finding treatment in REFPROP that will avoid some of the pain points, and should make REFPROP a LOT(!) faster.  Maybe not to the point that tabular methods are not needed, but getting there.

**Comment by kauffmanjp** [comment]
Ian, thanks for the rapid response and your efforts on the root finding in REFPROP (and prior efforts for tabular methods in CoolProp).
