### ISSUE TITLE
Handles being created and never freed when REFPROP 32 bit DLL returns an error

### ISSUE THREAD

**Issue by ScottALang** [usnistgov/REFPROP-issues#553]
We are having an issue with handles being created by the REFPROP DLL in our main application - because we call the DLL potentially millions of times during a simulation, this can become a serious problem. In fact, it can completely exhaust the allowable number of handles causing the application to crash.

![image](https://user-images.githubusercontent.com/111408926/198381007-7ba611f6-3bd3-4f73-9be6-fb1022b02b92.png)

We have tracked this down to the generation of error messages by REFPROP calls. 

For example, calling TPRHOdll() will generate 2 handles that are not freed if it returns a non-zero ierr & an herr string, as would be the case calling it for Water with T=200 and P=100. The same thing happens with other calculation routines, and also with non-calculation routines like  SETFLUIDSdll().

Here is some simple C# test code I put together to demonstrate.

``` c#
using System.Runtime.InteropServices;

[DllImport(@"C:\Program Files (x86)\REFPROP\REFPROP.DLL")]
static extern void TPRHOdll(
        ref double T,
        ref double p,
        [MarshalAs(UnmanagedType.LPArray, SizeParamIndex = 0)] double[] z,
        ref int kph,
        ref int kguess,
        ref double D,
        ref int ierr,
        [MarshalAs(UnmanagedType.VBByRefStr)] ref string herr,
        ref long herr_length);

int count = 0;
while (true) {
    count++;
    double T = 300;
    double P = 100;
    double[] z = new double[20];
    z[0] = 1;
    int kph = 1;
    int kguess = 0;
    double D = 0;
    int ierr = 0;
    string herr = "".PadLeft(255);
    long herr_length = herr.LongCount();
    TPRHOdll(ref T, ref P, z, ref kph, ref kguess, ref D, ref ierr, ref herr, ref herr_length);
    Console.WriteLine(count.ToString() + ": TPRHOdll errorFlag " + ierr.ToString());
}
```

I would note that I am **intentionally** not calling any setup routines here. I **expect** the call to TPRHO to fail. (The same problem can generated with a correct setup, but with fluid properties in valid range (no handles made) or out of valid range (handles created) ).

When I run the above code pointing to the 32 bit REFPROP.dll installed with the REFPROP 10 installer (DLL version 10.0, dated 6/4/2018), handles get created every loop.

**However** - if I instead change the code to point to the 64 bit REFPRP64.dll also installed with REFPROP 10, this issue does not exist. The _only_ change I make to the code is replacing the name of the DLL (and of course changing the platform target).

In both cases, the call fails with errors (as expected), but only the 32 bit DLL is generating handles. Unfortunately, we need to use the 32 bit DLL for our shipping applications.

We would really appreciate help in diagnosing this issue!

**Comment by ianhbell** [comment]
It is compiler specific. Please see https://github.com/usnistgov/REFPROP-issues/issues/299

**Comment by ianhbell** [comment]
In fact it is a bug in the version of Intel compiler used to build the DLL. I think the new compiler does not have this problem.

**Comment by ScottALang** [comment]
Thanks Ian.
Are there new versions of REFPROP.DLL that you have compiled that we are able to use (either in a new REFPROP installer or otherwise)? Or is the only option at the moment a DLL we compile ourselves?

**Comment by ianhbell** [comment]
Yes, I believe the 10.0.0.02 version should not have this bug, and the beta also. Please email me (ian.bell@nist.gov) for the link.

**Comment by ScottALang** [comment]
This does appear to have solved the issue! Thank you again.

**Comment by ianhbell** [comment]
Which version solved your problem? (for future readers)

**Comment by ScottALang** [comment]
I only tried the 10.0.0.02 version which solved the issue. Neither my test code above or our full application is generating handles with that version.

**Comment by ianhbell** [comment]
Thanks!
