### ISSUE TITLE
can't use RP.RPVersion()

### ISSUE THREAD

**Issue by xiaohanzhuwei** [usnistgov/REFPROP-issues#555]
I did everything the tutorial said in [https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB](url).
`>> pyversion

       version: '3.7'
    executable: 'D:\Anaconda3\python.exe'
       library: 'D:\Anaconda3\python37.dll'
          home: 'D:\Anaconda3'
      isloaded: 0

>> [v,e] = pyversion; system(['"', e, '" -m pip install --user -U ctREFPROP'])
Requirement already satisfied: ctREFPROP in d:\anaconda3 (0.10.2) 

ans =

     0

>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

RP = 

  Python REFPROPInstance with properties:

     MOLAR_ENGLISH: [1×1 py.int]
               MKS: [1×1 py.int]
     MOLAR_BASE_SI: [1×1 py.int]
               CGS: [1×1 py.int]
           ENGLISH: [1×1 py.int]
         SI_WITH_C: [1×1 py.int]
             MIXED: [1×1 py.int]
           MASS_SI: [1×1 py.int]
           MEUNITS: [1×1 py.int]
           DEFAULT: [1×1 py.int]
      MASS_BASE_SI: [1×1 py.int]
    managed_handle: [1×1 py.NoneType]
               dll: [1×1 py.ctypes.WinDLL]
           MOLE_SI: [1×1 py.int]

    <ctREFPROP.ctREFPROP.REFPROPInstance object at 0x0000016835732E10>`
It seemed everything was alright but when I tried to use  'RP.RPVersion()' or other functions, some error occurred as below. 
`>> RP.RPVersion()

Error using py.ctREFPROP.ctREFPROP.REFPROPInstance/RPVersion
Unable to return the number of named arguments if not in an active function.`

**Comment by ianhbell** [comment]
Sounds like a MATLAB bug. Haven't heard any reports like this before.

**Comment by xiaohanzhuwei** [comment]
Is there any way I can try to solve the problem? Maybe reinstall MATLAB?

**Comment by ianhbell** [comment]
No I think you need to contact Mathworks support. Possibly a reinstall would solve it, but that wouldn't be my first choice.
