### ISSUE TITLE
Different 410A Enthalpy Results

### ISSUE THREAD

**Issue by Psychrometric-James** [usnistgov/REFPROP-issues#556]
### Description

I’m trying to convert from the Refprop 9 legacy API functions (TPFLSHdll and TQFLSHdll) for calculating Enthalpy of vapor and Enthalpy of Saturated Liquid to the new High-Level API; however, I’m getting two different results from REFPROPdll and the Refprop.XLS excel spreadsheet.

### Steps to Reproduce
Use these inputs in Refprop.XLS:
Input Codes: TP
Units: English
Temperature: 80°F
Pressure: 300.000003

Use these inputs for REFPROPdll in python:
```SH_r = RP.REFPROPdll(Refrig,"PT","H",ENGLISH, 0, 0, SH_Ppsia, SH_TF, [1.0])```
where:
```
Refrig = 410A.MIX
SH_TF = 80
SH_Ppsia = 300
```

**Expected behavior:** [What you expect to happen]
**Refprop.XLS results:**
Input Codes: TP
Units: English
Temperature: 80°F
Pressure: 300.000003
**Enthalpy(H) result: 104.3256582**

**Actual behavior:** [What actually happens]
**Ignition Python REFPROPdll results:**
What I’m sending to the REFPROPdll API:
```SH_r = RP.REFPROPdll(Refrig,"PT","H",ENGLISH, 0, 0, SH_Ppsia, SH_TF, [1.0])```
where:
```
Refrig = 410A.MIX
SH_TF = 80
SH_Ppsia = 300
```
**Python returned Enthalpy result: 104.82490694965124**

### Versions

**REFPROP Version:** [REFPROP version 10]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [ Python]  

### Additional Information
Am I sending the correct REFPROPdll inputs? I also replicated the problem using Ian Bells VB.NET example which gave me an even worse Enthalpy than expected

Thanks in advance!

**Comment by ianhbell** [comment]
The default reference states differ between Excel and the DLL for historical reasons. Thus set the reference state in one to match the other. The models themselves should be fine.

**Comment by Psychrometric-James** [comment]
What is the default reference state for Excel? DEF, NBP, IIR, ASH, OTH, OT0, or NA?

Does that mean I'll need to pass all these inputs into REFPROPdll:
REFPROPdll(hFld, hIn, **hOut**, iUnits, iMass, iFlag, a, b, z, Output, hUnits, iUCode, x, y, x3, q, ierr, herr, hFld_length, hIn_length, hOut_length, hUnits_length, herr_length)

or can I just add hOut?

This is my python script in my Ignition SCADA software:
```
print('Version:', RP.RPVersion())
SH_TF = float(sys.argv[1]) #80
SH_Ppsia = float(sys.argv[2]) #300
m = RP.SETMIXTUREdll('R410A')

print('Enthalpy(H):',RP.REFPROPdll('','TP&','H',RP.ENGLISH,0,0,SH_TF,SH_Ppsia,m.z).Output[0])
```
Result:
```
Version: 10.0
Enthalpy(H): 104.84786075950775
```

Thanks again Ian

**Comment by ianhbell** [comment]
Look in the VBA code, it explains how the Excel reference state works. For mixtures, reference states are much more complicated than for pure fluids.

**Comment by Psychrometric-James** [comment]
Are you refering to this section:
```
 'Use the following line to calculate enthalpies and entropies with a reference state based on the currently defined mixture (and thus calculations will be the same as those produced from the graphical interface for mixtures).
        'See the file manual.txt in your REFPROP\Fortran directory for further information on the use of the SETREF subroutine.
           i = 2 'Set to 1 or 2 (see the SETREF routine in the file SETUP.FOR) or the information on the "Welcome" sheet.
           hFld = "": hIn = "Flags": hOut = "SETREF": Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, i, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
```
My Fortran folder doesn't contain a manual.txt

**Comment by Psychrometric-James** [comment]
I appreciate a good puzzle but that was a long route just to say: 
```
print(RP.SETREFdll('IIR',2,r.z,0,0,0,0))
```

Thanks Ian

**Comment by ianhbell** [comment]
That's only one possible answer, which is why I was being cagey. More docs here: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETREFdll

**Comment by Psychrometric-James** [comment]
Hey Ian,
Where would I input the Q input for bubble point and dew point in my above statement?
```print('Enthalpy(H):',RP.REFPROPdll('','TP&','H',RP.ENGLISH,0,0,SH_TF,SH_Ppsia,m.z).Output[0])```

I attempted your R454C.MIX example but having no luck.

Thanks for your help, sir.

**Comment by ianhbell** [comment]
Something like this:
```python
print('Enthalpy(H):',RP.REFPROPdll('','PQ','H',RP.ENGLISH,0,0,SH_Ppsia,Q,m.z).Output[0])
```

Please see the docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html
