### ISSUE TITLE
Discrepancy between python and app

### ISSUE THREAD

**Issue by JoelSGul** [usnistgov/REFPROP-issues#558]
``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

os.environ['RPPREFIX'] = r'C:\Program Files (x86)\REFPROP\\'


RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MASS_BASE_SI = RP.GETENUMdll(0, "MASS BASE SI").iEnum

# inputs
fluid = 'R134a'
zmol = [1.0]
Tlow = 20 # *C
icomp = 1
RP.SETREFdll("NBP", icomp, zmol, -1, -1, -1, -1)
RP.SATSPLNdll(zmol)


base = RP.REFPROPdll(fluid, 'TQMOLE', 'D;E;S', MASS_BASE_SI, 0, 0, Tlow+273.15, 0, zmol)
print(base.Output[1]/1000, 'kJ/kg')
```

### Description

I am trying to calculate the efficiency of a cycle however I obtain very different answers between copy/pasting from the app versus calculating from within python. Here is one of the many points where the figures deviate.
I have tried switching between mass/mol based units, setting reference state, using SATSPLN however nothing seems to help. I am out of ideas. How can I get the python calculation to match the app?

**Expected behavior:** 
Expected enthalpy: 61.657 kJ/kg

**Actual behavior:** 
Python enthalpy: 61.19083026979883 kJ/kg 
Furthermore this enthalpy is impossible to input in the app at the specified temperature.

### Versions

**REFPROP Version:** '10.0'
**Operating System and Version:** Windows 11
**Access Method:** Python 3.9

### Additional Information

![image](https://user-images.githubusercontent.com/118264174/202135169-479fee33-a856-4ecd-b5d2-8c03105b6f60.png)

**Comment by ianhbell** [comment]
Make sure you set the same reference states, the defaults are not the same in the GUI and Python.  In Python, you need the SETREFdll function: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETREFdll

**Comment by JoelSGul** [comment]
I am quite certain I set the same reference state between the GUI and Python.
Setting the reference state to a different standard like IIR does not fix the issue.

``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

os.environ['RPPREFIX'] = r'C:\Program Files (x86)\REFPROP\\'


RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MASS_BASE_SI = RP.GETENUMdll(0, "MASS BASE SI").iEnum 

# inputs
fluid = 'R134a'

zmol = [1.0]
Tlow = 20+273.15 # *C
icomp = 1
RP.SETREFdll("IIR", icomp, zmol, -1, -1, -1, -1)
RP.SATSPLNdll(zmol)


base = RP.REFPROPdll(fluid,'TQMOLE','D;E;S',MASS_BASE_SI,0,0,Tlow,0,zmol)
print(base.Output[1]/1000,'kJ/kg')

```

**Expected behavior:** 
Expected enthalpy: 227.47 kJ/kg

**Actual behavior:** 
Python enthalpy: 227.0011342354281 kJ/kg

![image](https://user-images.githubusercontent.com/118264174/202402651-4be9cc6a-4d6e-4edf-acca-af7ccdd8650d.png)

**Comment by ianhbell** [comment]
For one, you re printing the internal energy from Python.  Do you get the same density?

**Comment by ianhbell** [comment]
Confirmed, that was the problem.

```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MASS_BASE_SI = RP.GETENUMdll(0, "MASS BASE SI").iEnum 

# inputs
fluid = 'R134a'

zmol = [1.0]
Tlow = 20+273.15 # *C
icomp = 1
RP.SETREFdll("IIR", icomp, zmol, -1, -1, -1, -1)
RP.SATSPLNdll(zmol)


base = RP.REFPROPdll(fluid,'TQMOLE','D;E;H;S',MASS_BASE_SI,0,0,Tlow,0,zmol)
print('u:', base.Output[1]/1000,'kJ/kg')
print('h:', base.Output[2]/1000,'kJ/kg')


```
yields
```
u: 227.00113423542805 kJ/kg
h: 227.4677061397501 kJ/kg
```
