### ISSUE TITLE
Calculating superheated Parahydrogen

### ISSUE THREAD

**Issue by bin-cui** [usnistgov/REFPROP-issues#559]
Hello,

I need to calculate the enthalpy of Parahydrogen after it's flash evaporation. The subcooled liquid Hydrogen (A) will go to a superheated state (B) due to rapid depressurization, where it's in a metastable condition. There it will not stay a long time, before it will strive for equilibrium to Point (C). Due to different pressure levels, the Point C can go lower than the Triple-point.
 
![image](https://user-images.githubusercontent.com/118458584/202485312-9d3f2884-6753-49d7-b282-3bcabf987f19.png)

Regarding the [Thread](https://github.com/usnistgov/REFPROP-issues/issues/244), it is still possible to determine the Point B in REFPROP, even when it's below the triple-point due to an FLD-File (SBL).  
I also get an enthalpy from the calculation of B and C. But what I do not understand is, which routines will be used to calculate these properties. Will the FLSH-routine be called while calculating Point B and can it be considered as stable or metastable condition?

Point B: T=20 K, P=0.001 MPa
Point C: T=11.291 K, P=0.00098820 MPa

**Comment by ianhbell** [comment]
I don't see physically why your hydrogen is following that path, but that is a different question. To answer your question, you can get a more clear idea of it by using the TPRHOdll function which is internally what REPROP uses.  A phase determination routine is generally needed, but if you have a sublimation curve, REFPROP will do the TP flash call for you, and keep you from ending up in the solid phase.

**Comment by bin-cui** [comment]
Ok but in the

**Comment by bin-cui** [comment]
Ok, but in the TPRHOdll or TP flash-function. Will it automatically take care of the boundaries of the metastable liquid phase e.g. in this picture? Are these functions limited to the unstable region or may it happen, that even points in the unstable region can be calculated through these functions?

![image](https://user-images.githubusercontent.com/118458584/202503578-9285e5dd-8e66-44c4-b0b6-b684158fb3be.png)

**Comment by ianhbell** [comment]
No, TPRHO does not consider the phase boundaries, and assumes the state is homogeneous (liquid, gas, supercritical, but not two-phase).  Metastable solutions are possible.  Also unstable solutions are possible, so you need to check whether the solution is feasible.
