### ISSUE TITLE
R1336mzz(E) isomer as a fluid

### ISSUE THREAD

**Issue by NickPooleRSL** [usnistgov/REFPROP-issues#560]
### Description

For R1336mzz the Z isomer is present in Refprop 10 but not the E isomer. Can this be added?

### Steps to Reproduce

1. Click Substance -> Define new mixture
2. Select All fluids 
3. Look for the R1336mzz isomers in the Available fluids list

Whereas R1336mzz(Z) is present R1336mzz(E) is not.

### Versions

REFPROP 10.0.0.98
Windows 11 Pro, Version: 22H2, OS build: 22621.819

**Comment by ianhbell** [comment]
You're in luck! Please email me (ian.bell@nist.gov) and I can send you the fluid file
