### ISSUE TITLE
Triple Point Temperature Issue

### ISSUE THREAD

**Issue by jafari-ali** [usnistgov/REFPROP-issues#562]
Hi Everyone,
I use Excel and VB.net wrappers and found an issue to call triple point temperature.
=refprop("T","R14","TRIP","SI with C",273.15,0.1,0)
=refprop("T","R114","TRIP","SI with C",273.15,0.1,0)

Thanks 
Ali

**Comment by ianhbell** [comment]
What error do you get?

**Comment by jafari-ali** [comment]
I get #[TQFLSH error 3] one more input are out of the range.

![image](https://user-images.githubusercontent.com/65745497/204948540-a19b6468-007c-4948-af24-921cb019af80.png)

**Comment by ianhbell** [comment]
For these fluids, the experimental data did not extend down to the triple point temperature, so when the EOS was developed a higher minimum temperature was specified.
