### ISSUE TITLE
Refprp64.dll - Setup() speed degradation

### ISSUE THREAD

**Issue by MoVenkat** [usnistgov/REFPROP-issues#563]
### Prerequisites
Visual Studio 2019/VC++ and REFPRP64.DLL

Points for clarification:

1. I am assuming that the call to SETUPdll() is required every time the fluid mixture changes.  Is that correct? 
2. Should I not be using this call as this seems to be part of the "legacy" api ?  As you can tell, I am revisiting the Refprop functionality after a while.
3. Assuming I can use the legacy API, I am noticing that SETUPdll() seems to be taking a lot longer to execute in the x64 version of REFPROP i.e. when using Refprp64.dll (a little over twice the time).

Could you please explain if I am correct in my observations? Any related thoughts or suggestions to improve performance when the program logic requires multiple calls for different mixtures? Does the "high level api" solve this issue?

Also, is there a UNICODE equivalent dll for Refprp64.dll ?  Converting from UNICODE to ANSI (wchar to char) for various calls (particularly "SETUPdll(...)" is an overhead.

Thank you.

**Comment by ianhbell** [comment]
You might want to use the manager in this case: https://github.com/usnistgov/REFPROP-manager

1. Yes
2. It is fine to still use SETUPdll, although the new functions SETFLUIDSdll and SETMIXTUREdll are more convenient
3. Not sure why, but I can't think of anything else to recommend.

REFPROP does not use unicode anywhere, recommend that any calling code does not either.

**Comment by MoVenkat** [comment]
Thank you Ian.  I think you have answered all my questions.  I will take a fresh look at the x64 code to see why it's taking more time.

Thanks again.
