### ISSUE TITLE
Refprp64 - SetupDll call speed degradation (continued...)

### ISSUE THREAD

**Issue by MoVenkat** [usnistgov/REFPROP-issues#564]
[RefpropSetupTestVC++.zip](https://github.com/usnistgov/REFPROP-issues/files/10131484/RefpropSetupTestVC%2B%2B.zip)
[Uses Visual Studio 2022]
After your response regarding the speed issue with the x64 version of refprop i.e. refprp64.dll, I thought it would be good to send you a VC++ sample that compares the speeds for the calls to the SetupDll in both the 32 bit and 64 bit versions.  It's a common codebase for both obviously.  Unzip the files in a folder called "C:\temp\refprop".  You should then have the following folders (it's a #defined path in the dialog header file):

C:\temp\refprop\fuilds,
C:\temp\refprop\mixtures

The refprop.dll and refprp64.dll should be in the folder C:\temp\refprop\

Run the executables from:
C:\Temp\Refprop\MFCRefpropTester\release\MFCRefpropTester.exe
and
C:\Temp\Refprop\MFCRefpropTester\x64\release\MFCRefpropTester.exe

It's a simple dialog that comes up.  Click OK to start the loop.  Then wait till the dialog disappears.  The loop calls SetupDll repeatedly for different fluids. You can trace the calls from the function CMFCRefpropTesterDlg::OnOK()" in the file MFCRefpropTesterDlg.cpp.  The code simply loads the appropriate DLL, gets the function addresses for 2 functions and executes them both in a loop.  That's it.

What is surprising is the speed difference.  On my machine the 32 bit executable (using refprop.dll) takes 16 seconds to run while the same executable compiled to 64 bit (using refprp64.dll) takes 38 seconds to run.

Would be good to know why there is such a huge speed penalty.

Would appreciate any insights.  Thank you so much as always.

**Comment by ianhbell** [comment]
As I mentioned before, you should use REFPROP-manager for this use case.

**Comment by MoVenkat** [comment]
Ian: Yes. I was intending to test the same code with Refprop-Manager and now I have.  It does make a huge difference to the speed!!  Thank you for the tip.

**Comment by ianhbell** [comment]
Good to hear!
