### ISSUE TITLE
Version 9.1.1.1 or 10?

### ISSUE THREAD

**Issue by EdPaBo** [usnistgov/REFPROP-issues#565]
Hello,

I'm trying to use Refprop from Matlab(R2022b) via Python (3.10) but there's a point which is not clear to me.
I refer to [this page](https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB)  to setup the wrapper for Refprop 10.

Everyting works fine up to the RP.RPVersion() command, there I get:

```
>>RP.RPVersion()

      ans = 
      Python str with no properties.
      9.1111
```

Now, if I chek the DLL version when I open Repfrop I get version 10

![image](https://user-images.githubusercontent.com/119731042/205435287-da5a581e-6deb-4fb2-98f6-bb0da1d52f9f.png)

While if I check the refrop.exe file version I find File version 9.1.0.0 and version 9.01

![image](https://user-images.githubusercontent.com/119731042/205435381-3f30f06e-a232-400b-bfee-eb451769e277.png)

Do I have to install the upgrade that I can find on [Refprop homepage](https://www.nist.gov/srd/refprop) or do I already have the right version?

I suspect that the former is the right answer but I was told by data@nist.gov that the important version number was the DLL version number although I didn't specify exactly what I wanted to do but just if there was any kind of update available.

**Comment by ianhbell** [comment]
You have two versions of REFPROP installed on your machine evidently. Make sure the RPPREFIX environment variable points to the installation of REFPROP 10.0
