### ISSUE TITLE
Calculation with refrigerant R 455A

### ISSUE THREAD

**Issue by AlwinMeppen** [usnistgov/REFPROP-issues#566]
We are using the refprop dll version 10a from 2018.
 
When we make a calculation for R 455A there are differences in results to some other programs (e.g. BITZER or TEGA, see attachment).

They are using version 10.0.
I add some lines from the source code
 
"" Visual Studio
Case "R 455A" REM  ** R 455A *******************************************************
                KM_NEU(Index).Gleit = 1
                KM_NEU(Index).NC = 3
                KM_NEU(Index).Rxxx_files = "fluids\CO2.fld|fluids\R1234YF.FLD|fluids\R32.FLD|"
                KM_NEU(Index).Rxxx_mix = "fluids\hmx.bnc"
                Mol_Anteil(1) = 0.035 : Mol_Anteil(2) = 0.757
                Mol_Anteil(3) = 0.208 : Mol_Anteil(4) = 0
""

Kind regards
Alwin Otten

[4FE-35; R455A; t0 -12; tc 42.pdf](https://github.com/usnistgov/REFPROP-issues/files/10284408/4FE-35.R455A.t0.-12.tc.42.pdf)
[Auslegungsdaten Gatenbröker.pdf](https://github.com/usnistgov/REFPROP-issues/files/10284409/Auslegungsdaten.Gatenbroker.pdf)
[Dampftafel.pdf](https://github.com/usnistgov/REFPROP-issues/files/10284410/Dampftafel.pdf)
[R_455A_pT_DE.pdf](https://github.com/usnistgov/REFPROP-issues/files/10284411/R_455A_pT_DE.pdf)

**Comment by ianhbell** [comment]
Are you sure they are using the same exact mixture models? Also, are the reference states all the same?

**Comment by AlwinMeppen** [comment]
Dear Ian,
I don't know exactly.
The calculation of the BITZER compressor is done with the aserep.dll. The calculation of the refrigerant table from TEGA should have been done with version 10.0, probably of the refprop dll.

**Comment by ianhbell** [comment]
We'll you'll have to dig into the docs for each library.  REFPROP 10 is the standard. And if there are differences, they should update.  Also, I have just published an updated model for R-32/1234yf, which is going to be implemented in REFPROP, and then in the other libraries too.  So that will change the numbers, but the new model is more accurate.
