### ISSUE TITLE
Quality Calculation

### ISSUE THREAD

**Issue by excipioroy** [usnistgov/REFPROP-issues#569]
I am sure its a simple problem.  The Ammonia quality goes from "Super Cooled" to "Super Heated" with a 0 and 1 appearing at the saturation point, but never gives the partial quality.  For example at 204.2 K and .890 MPa I have a reference that shows a quality of 65%, yet REFPROP shows  fully liquid state?
[Ammonia Quality.txt](https://github.com/usnistgov/REFPROP-issues/files/10369638/Ammonia.Quality.txt)

**Comment by ianhbell** [comment]
You cannot specify the quality of a two-phase point for a pure fluid at constant temperature and pressure. You go "into the page" in a p-v-T surface as you make the transition from liquid to vapor, as the density changes. Along that process, the temperature and pressure do not change.

**Comment by nist-aharvey** [comment]
Another way of saying this is that, as a pure component vaporizes at a fixed temperature, the pressure stays constant.  So if your pressure/temperature point is on the vapor-pressure curve, the quality will vary depending on the overall density.  You could see this for example by doing a series of calculations specifying temperature and density with the density changing across the series.  As you go across the 2-phase region in this path, you will see the pressure staying constant while the quality changes.

Also, unless you made a typo, your reference is doing something wrong.  At 204.2 K, the vapor pressure of ammonia is about 0.012 MPa.  So 0.890 MPa will not be anywhere close to a 2-phase state.

**Comment by excipioroy** [comment]
Thanks
You are correct it was a typo.  294.2 K not 204.2 K.
