### ISSUE TITLE
Gasoline and other fuels

### ISSUE THREAD

**Issue by EricLemmon** [usnistgov/REFPROP-issues#57]
From an outside source:

I am not sure if the REFPROP or SRD 4 databases would be more useful for gasoline and diesel blends. I need to know density, absolute viscosity, and bulk modulus, at barest minimum, as a function of the temperature and pressure. Both of these libraries seem to carry that information, but I am not sure which carries the best library of fluids to meet my needs. Ideally whichever database is most appropriate would have a ‘standard’ gasoline that we could take as our reference as our customers generally do not define their desired compositions well.

**Comment by EricLemmon** [comment]
Both Refprop and SRD4 have the capabilities to model gasoline to some extent, depending on whether you want high accuracy equations of state (Refprop, but with only a limited number of equations for fuels) or far less accurate equations (SRD4) that has a much larger variety of fluids.  Refprop has 147 fluids available, shown at www.nist.gov/srd/refprop, and gasoline could be modeled with the normal hydrocarbons octane, heptane, nonane, isooctane (not quite “normal”), etc., and some of the other available fluids such as benzene, cyclohexane, cyclopentane, methylcyclohexane, and perhaps toluene and the xylenes, and of course ethanol.  We also have a few other very preliminary equations of state that could be used if you have some specific fluids you would like to have.  We do not have a “standard” gasoline mixture file as there really is no such thing, but would be glad to make one if you have some sort of analysis of the components in the mixture.  You can make a *.mix file yourself by pressing the "Store" button after entering the composition. SRD4 will most likely not give you anything better even though it has more fluids in it due to the lower accuracy.

**Comment by sthakris** [comment]
Hello, i wanted to calculate the Gasoline mixture properties mixed with varying water content. The composition would be
n-heptane/iso-octane/toulene/ethanol/water. Is it possible to calculate these mixture with REFPROP 10. I tried with REFPROP 9.1 it gives me error as attached here
![error_msg](https://user-images.githubusercontent.com/65964243/82916013-c4cb4c80-9f71-11ea-8d72-e7806b5534d8.JPG)
