### ISSUE TITLE
Presence of water in the mixture - calculations issue

### ISSUE THREAD

**Issue by RefProp** [usnistgov/REFPROP-issues#570]
I am running the analysis with roughly 85 mol% of CO2, ~15% methane and 0.014 mol% of water.
The aim is to determine phase boundary as well as the critical pressure and temperature using GERG 2008 EoS. I am using ver. 10 of the software; unfortunately, I cannot run the calculations ok with the presence of water, everything is fine if water is removed.

**Comment by ianhbell** [comment]
What are "the calculations"? You are trying to plot the isopleth of the phase envelope and the matching critical point?

**Comment by RefProp** [comment]
Hi Ian,

Yes, I am trying to get a phase envelope within Pressure-Temperature diagram and determine the critical pressure.


Kind Regards,


Yuri

**Comment by ianhbell** [comment]
Please make sure to respond in the web interface otherwise your email response appears in the issue

**Comment by RefProp** [comment]
I am trying to get a phase envelope within Pressure-Temperature diagram and determine the critical pressure.

**Comment by ianhbell** [comment]
In Python? Or the desktop application?

**Comment by RefProp** [comment]
This is a desktop application

**Comment by ianhbell** [comment]
I plotted with the CoolProp around REFPROP, looks fine:

import os
os.environ['RPPREFIX'] = os.getenv('HOME') + '/REFPROP10'

import matplotlib.pyplot as plt 

import CoolProp.CoolProp as CP 
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, os.getenv('RPPREFIX'))
print(CP.get_global_param_string('REFPROP_version'))
AS = CP.AbstractState('REFPROP','CO2&Methane&Water')
xCO2 = 0.85
xH2O = 0.00014
xC1 = 1-xCO2-xH2O
AS.set_mole_fractions([xCO2,xC1,xH2O])
AS.build_phase_envelope("")
PE = AS.get_phase_envelope_data()
plt.plot(PE.T, PE.p)
plt.yscale('log')
plt.gca().set(xlabel='$T$ / K', ylabel='$p$ / Pa')
plt.show()

yielding

<img width="625" alt="image" src="https://user-images.githubusercontent.com/11966765/211826220-3a55e112-da43-4919-836d-c0c6da0e3aa7.png">

**Comment by ianhbell** [comment]
What is the precise composition that doesn't work? It is very sensitive.
