### ISSUE TITLE
The Refprop code in Excel (when the value of Temperature and Enthalpy are known but cannot define Pressure)

### ISSUE THREAD

**Issue by sokleng123** [usnistgov/REFPROP-issues#571]
Dear sirs and Madame

I have a problem with Refprop code when using in Excel. When I knew the value of the Temperature and Enthalpy, I want to define the Pressure from these 2 parameters but cannot find in Excel (The value is wrong). If use in Refprop with the same value it can define the pressure. For the code in Excel that I use is: =Pressure("R421A","TH","SI with C",20,300). The value of the pressure from Excel is difference from Refprop software. Any wrong with the VBA code or what. Thanks in advance for your kindness and help.
![1](https://user-images.githubusercontent.com/122616523/212330265-b3ec5d21-025b-4b9f-81be-8900e5d0202c.PNG)

![2](https://user-images.githubusercontent.com/122616523/212330271-85d2ad02-5138-4b3c-a5fe-0a1c454a48b6.PNG)

**Comment by ianhbell** [comment]
T,H inputs are double-valued for many sets of T,H, so you need to specify which root you want.

**Comment by ianhbell** [comment]
Which you do with a suffix of > or < on one of the inputs.  Make sure you check the densities as well

**Comment by sokleng123** [comment]
> 

I checked with the other parameter such as to define Density, entropy that knew TH but the value not correct. Example: =Density("R421A","TH","SI with C",20,300). I still cannot find what wrong with this. If knew the value of Temp. and Entropy, I can Define Pressure like (=Pressure("R421A","TS","SI with C",20,..
)

**Comment by ianhbell** [comment]
See my comment above - you need to force the solution you want. See https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll and look for ``TH>``

**Comment by sokleng123** [comment]
> Which you do with a suffix of > or < on one of the inputs. Make sure you check the densities as well

Thank you sir for your help
now I can solve that problem by using =Pressure("R421A","TH<","SI with C",20,300)

**Comment by ianhbell** [comment]
Good to hear! Please throughly read the docs in the future
