### ISSUE TITLE
Neural networks for faster property evaluations

### ISSUE THREAD

**Issue by mihail-gti** [usnistgov/REFPROP-issues#572]
I am not sure this is the right place to ask this question. So, if not please ignore it. 

I was wondering if anyone has tried using neural networks to speed up REFPROP lookups. The idea being that you would use regular REFPROP calls to generate data to train the neural network. And then use the neural networks during simulations to improve CPU performance. The only paper I found online is this one: 

https://docs.lib.purdue.edu/iracc/2048/

But I thought maybe people here might have some thoughts why it would or wouldn't work.

**Comment by ianhbell** [comment]
There are a lot of other methods out there for estimation. Two more are here: http://www.coolprop.org/coolprop/Tabular.html#tabular-interpolation

Another good one is SBTL: http://www.iapws.org/relguide/SBTL.html

But a general NN could be a good idea.  I wonder how well it would handle interpolation and how fast it would be to evaluate.  Definitely worth looking into.

If you did a self-contained implementation in C++ with an open-source license I would be interested to possibly implement in the new version of REFPROP.

**Comment by mihail-gti** [comment]
Thanks for the response. I will update you on any progress.
