### ISSUE TITLE
Critical point by REFPROP 9 

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-issues#574]
Hi Ian

I am trying to use RP9 to get PHTDS value at critical point. And I got this error. Would you suggest to which function should be used to calculate all properties?

Thanks for your help. 

RP = REFPROPFunctionLibrary('*******\\REFPROP9\\REFPROP.DLL')
RP.SETPATHdll('****\\REFPROP9')
mix = 'R513A_DP.mix'
sm = RP.SETMIXdll(mix, 'HMX.BNC', 'DEF')
r = RP.REFPROPdll(mix ,"CRIT","P;H;T;D;S",0, 0, 0, 0, 0,sm.z).Output[0:5]

The function REFPROPdll could not be loaded from the shared library.

**Comment by ianhbell** [comment]
See your other issue. Read the docs for the legacy interface, then see what questions remain
