### ISSUE TITLE
Function between RP 9 vs 10

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-issues#575]
Hi Ian,

All the works were done in RP10 before. Now I need to roll back RP 9 to do some calculation. I got lots of crash and error. Would you point out which function I should use such like these two calls?  Could you share an example? Thanks a lot. 

Frank

   General = RP.REFPROPdll(RefName, "PH","T;V;S;CP;CV;TCX;VIS;W", RP.MOLAR_BASE_SI, 0, 0, p, h, [0]).Output[0:8]
   Der = RP.REFPROPdll(RefName, "PH","DDDT;DDDP;DHDT_P;DHDP_T", RP.MOLAR_BASE_SI, 0, 0, p, h, [0]).Output[0:4]

**Comment by ianhbell** [comment]
See https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html

THERMdll and TRNSPdll for the first one, read the docs for the others, some from DHD1dll
