### ISSUE TITLE
meaning or definition of input code Q for Excel REFPROP function

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#576]
### Description
The Excel wrapper documentation found in REFPROP.XLS does not clearly state whether two-phase quality is mass basis or mole basis when the input code includes only "Q", such as when the input code is "PQ", "TQ", "DQ", etc., and no indication whether the choice of unit system determines which basis to use for "Q". In contrast the output property codes allow the distinction between "Qmass" or "Qmole".

For example, if the input code is TQ or PQ and the units code is "SIwithC" or "MASS BASE SI", a user may assume that the Q value should be mass based due to choice of a unit system that is mass based. However the Excel REFPROP function behavior demonstrates that the input is always assumed to be mole based quality.

If this non-intuitive behavior is intended functionality then please document it to assist users. If this is not the intended functionality, then please add it to the list of issues to resolve. My apologies in advance, if I am missing some obvious point about how refrigerant blends behave then please point me in the right direction.

### Steps to Reproduce

1. See example in attached Excel file (additional information below). 
2. Issue is limited to refrigerant blends and not present for single component refrigerants.

**Expected behavior:** Expected that input Q was intended to use mass basis when the units of measure were mass basis, and molar basis when the units of measure were molar basis.

**Actual behavior:** Input Q uses mole basis even when the units of measure were mass basis.

### Versions

**REFPROP Version:** 10.0  
**REFPROP.XLS Version:** 10.0.0.02 (downloaded from Gitub, file commit date was 2020-06-23)
**REFPROP.XLA Version:** 10.0.0.02 (downloaded from Gitub, file commit date was 2020-06-23)
**Operating System and Version:** Win10  
**Access Method:** Excel wrapper  

### Additional Information

[input code examples.xlsx](https://github.com/usnistgov/REFPROP-issues/files/10504308/input.code.examples.xlsx)

REFPROP GUI output corresponding to the Excel example, for R407C at T=35°C and D=130kg/m³:
#### Mass basis
![image](https://user-images.githubusercontent.com/39253715/214735778-9b102a37-4836-48f4-9ae4-b41e07b2e778.png)

#### Molar basis
![image](https://user-images.githubusercontent.com/39253715/214735813-ad5b9f47-74c4-4911-81d1-c07d529665e9.png)

![image](https://user-images.githubusercontent.com/39253715/214736274-3b1092b6-b3e7-416d-97de-ecdb62494aa7.png)

**Comment by ianhbell** [comment]
@EricLemmon This one is for you.

@HightopRaven This is what [the docs ](https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll) have to say: When q is >0 and <1, then the quality uses a molar basis when iMass=0, and a mass basis when iMass=1.

**Comment by HightopRaven** [comment]
@ianhbell thanks, I had not looked into the details under the hood, but use of iMass as a switch makes sense within the various REFPROP function routines; [the docs](https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll) also state *The value of iUnits has no effect on the value of q (as either an input or output).*

@EricLemmon  Reviewing the VBA code within the Excel add-in (REFPROP.XLA) I see a statement to always set iMass=0 (no other logic to possibly set iMass=1 when appropriate for the requested unit system); the REFPROP GUI gives the user an option to choose mass or molar basis for properties (and also a separate basis choice for compositions when defining a mixture) but the Excel wrapper does not explicitly provide that option (other than manually editing the VBA code); for the majority of Excel REFPROP wrapper users (that I would characterize as *'casual'* users rarely looking at the VBA code), I'll suggest that the iMass flag should be set according to the unit system, to have the same basis (mass or molar), something like this inserted after the block that checks if units need to be reset, and within the checks for missing inputs; my suggestion hard codes the iUnits numerical values, so not best practice but conveys the proposed behavior

```
'Check for missing inputs and transfer inputs to other variables that can be changed when needed.
  iUnitNumb = iUnitSave
' iMass = 0   'propose to remove this statement, replace with Select Case below or a more elegant solution not relying on hard coded numerical values
  Select Case iUnitNumb
    Case 0, 1, 6, 20: iMass = 0
    Case 2, 3, 5, 7, 8, 9, 10, 21: iMass = 1
    Case 11: iMass = 0 'for user defined units, set to 1 for mass basis and 0 for mole basis
    Case Else: iMass = 0
  End Select
  hIn = "": hFld = "": a = 0: b = 0: c = 0: hOut2 = Strings.Trim(hOut)
[...]
```

**Comment by ianhbell** [comment]
There are two things that are different:
1. Whether you want properties to be on a molar basis (kJ/kg versus kJ/mol)
2. Whether compositions should be on a molar or mass basis

This is why in CoolProp (in the low-level interface at least) the distinction is explicit, and I recommend the CoolProp API for REFPROP for this reason.

**Comment by EricLemmon** [comment]
This is one of those cases where you are, to my poor memory, the first to ask this question.  Making a change at this point in time to deal with this opens up all sorts of new possible errors that we'd like to avoid.  My suggestion would be the same as Ian's in his comments directly above, or in the use of your own embedded VBA code that you gave further up.  Those truly interested in this will be able to follow the same procedure.
