### ISSUE TITLE
GWPMIX Excel REFPROP function

### ISSUE THREAD

**Issue by SYR-Rick** [usnistgov/REFPROP-issues#577]
I understand a new function was added to return the GWP for mixtures.

I tried to use the function =refprop("GWPMIX",A2) where the value of cell A2 is R457A and get the error: 

```
#[GETENUM error 811] Input string not recognized: GWPMIX
```
I have downloaded the most recent versions for the refprop excel wrappers (REFPROP.XLA, REFPROP.XLS, etc) but this has not helped.  Is there another file that I need to update?   If so, where do I find it?

**Comment by ianhbell** [comment]
Where were you led to this understanding? 

There is no record of this in the docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html  and I have myself always manually done a mole-fraction-weighted average of the pure fluid GWP, as in for instance: https://www.sciencedirect.com/science/article/pii/S0140700719302361

**Comment by ianhbell** [comment]
Please respond in the web interface

**Comment by SYR-Rick** [comment]
Determination of the GWP-value (Global Warming Potential) of refrigerant fluids with RefProp V. 10.0
#280

EricLemmon commented on Jul 12, 2020

"The string GWPMIX has been added and will return the GWP of the mixture. If one of the GWP's for the pure fluids is not known (i.e., set to -1 in the fluid file), an error code will be returned. A comment has been added in the section that describes the codes that the string GWP is for pure fluids only, and that the array returned from the REFPROP routine will contain all of the values for each pure fluid."

**Comment by ianhbell** [comment]
Ah, you need the beta release for that. Please email me (ian.bell@nist.gov) and specify your operating system and how you use REFPROP so I know what to send you.

**Comment by SYR-Rick** [comment]
I moved my old REFPROP.DLL and REFPROP64.DLL files to another folder, downloaded the links you provided (my system renamed them: Unconfirmed 226415.crdownload, but I renamed them back to their original names) and put them in the REFPROP folder.   Unfortunately, I am getting the same result as before (but at least everything else seems to still work!)

=REFPROP("GWP","R457A.MIX") returns 675  (the GWP for the first constituent - R32)
=REFPROP("GWPMIX,"R457A.MIX") returns: #[GETENUM error 811] Input string not recognized: GWPMIX

**Comment by ianhbell** [comment]
What version of REFPROP is reported?

**Comment by SYR-Rick** [comment]
Oh my.  I went to the REFPROP folder and tried to open the REFPROP.XLA and REFPROP.XLS files to see what version they reported and got this message:  
![Picture1](https://user-images.githubusercontent.com/123974752/215552623-7500dc86-8b10-4dbc-a0bd-ff1a99073b6a.png)
Both files opened, but they look nothing like REFPROP - seem to be some kind of script from GitHub page??

**Comment by ianhbell** [comment]
My guess is you didn't get to the raw version of the XLA or XLS files before you tried to download them.

**Comment by SYR-Rick** [comment]
OK, I will try again.  My old versions still open - show Version 10.0 for both .XLA and DLL

**Comment by ianhbell** [comment]
Sounds like maybe you have multiple copies of REFPROP installed too.

**Comment by SYR-Rick** [comment]
I am only aware that I installed REFPROP once, however I did move the REFPROP.XLS and REFPROP.XLA files to a sub-folder before copying the new ones in.    I downloaded the files from GetHub again - things look better:  
![Picture2](https://user-images.githubusercontent.com/123974752/215560515-8e92698f-153a-407d-95da-56be1876eea5.png)

**Comment by ianhbell** [comment]
If you successfully downloaded the files for the beta, it should give a DLL version number of 10.0.0.98, so I recommend you try again with the DLL download

**Comment by SYR-Rick** [comment]
OK, here are my current files.   I will try to download the Beta files again.
![Picture3](https://user-images.githubusercontent.com/123974752/215562220-96d7d0e0-99d7-4e78-9ad5-5baa0688f2e1.png)

**Comment by ianhbell** [comment]
What version does the GUI report?

**Comment by SYR-Rick** [comment]
![Picture5](https://user-images.githubusercontent.com/123974752/215564199-0785d62a-9d7c-4178-90fa-cabbcc0f690e.png)

When I down load the DLL files, my system renames them....
![Picture4](https://user-images.githubusercontent.com/123974752/215564323-205d869d-2248-4672-8df4-2b0da10e6d30.png)
I need to save them in a different location, give them their original names, and put them into the REFPROP folder.

**Comment by ianhbell** [comment]
Ok, so the GUI is picking up the new DLL. That's good. Can you try again with the Excel interface?  Are you sure sure you don't have another REFPROP installed on your machine? In particular, another installation that set the RPPREFIX environment variable to some other location?

**Comment by SYR-Rick** [comment]
I installed the beta DLL files again.   Still getting same results.   Perhaps the issue is my REFPROP.XLAM add-in file is not updated.   Do I need to delete / reinstall the add-in?

**Comment by ianhbell** [comment]
I really think you have two copies of REFPROP installed; I don't think it is necessary to re-install anything. The Excel add-in will find the one indicated by the RPPREFIX environment variable.

**Comment by SYR-Rick** [comment]
Do I need to use the uninstaller, or just delete all refprop related files and folders outside of where they should be?

**Comment by ianhbell** [comment]
Don't touch any of the things, just check and/or fix the RPPREFIX environment variable to point to the folder where your REFPROP is installed. The Oracle docs explain it as well as I could: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html

**Comment by SYR-Rick** [comment]
Sorry, I got a bit lost after following your link - took me a while to find my way back :-)   

It seems that the RPPrefix is pointed to the correct file loacation where I think REFPROP is installed:

![Picture6](https://user-images.githubusercontent.com/123974752/215572449-bc9d683e-6940-4a08-8040-8086e6f6e681.png)

**Comment by SYR-Rick** [comment]
but my REFPROP.XLAM seems to be buried deep elsewhere....
![Picture7](https://user-images.githubusercontent.com/123974752/215573947-10e40805-6666-4460-841f-e93dde43d485.png)

**Comment by SYR-Rick** [comment]
Dr. Bell,   I feel so bad about taking so much of your time.  Your assistance is greatly appreciated.   I believe you are correct and there is some issue with my excel / add-in.   I'll continue to try to debug in the AM.   (well, it is 2:40 in the AM here - but after I get some rest and can think more clearly).      Best Regards!

**Comment by ianhbell** [comment]
No problem, that's very much in my my job description. I hope @EricLemmon can resolve your problem and you will post the solution here for future readers

**Comment by SYR-Rick** [comment]
I suspect I might need updated Excel wrappers (REFPROP.XLS) that contain the code necessary to use the GWPMIX function.  I have downloaded the most recent ones I could find (February 2019), but I believe the GWPMIX function was introduced since then.   My version does not mention the GWPMIX function.

**Comment by SYR-Rick** [comment]
I have been able to resolve an associated issue with not being able to generate a new REFPROP.XLAM file. (My installation of Excel would not allow the REFPROP.XLS file to be saved as REFPROP.XLAM).   I found that I could store it as REFPROP.XLSM first, and then I could store it as REFPROP.XLAM - after which I was prompted to update the add-in location.

**Comment by SYR-Rick** [comment]
I have discovered that although the REFPROP.XLS file reflects DLL version 10.0 the REFPROP.XLSM shows the beta DLL 10.0.0.98
I tried to use the GWPMIX function inside of the REFPROP.XLSM workbook and still get the same result.
![Picture8](https://user-images.githubusercontent.com/123974752/215714714-6da85284-679d-462c-a97b-3861f74b242a.png)

I believe I have successfully updated the REFPROP.XLAM in the add-in location.   (Could not figure out how to get the add-in to point to the REFPROP file, but this seems to work OK.)

**Comment by SYR-Rick** [comment]
Here are the dates shown for the REFPROP.XLS and REFPROP.XLAM files and their locations....
![Picture9](https://user-images.githubusercontent.com/123974752/215715642-b8350540-6cba-4e56-a569-95d2d822bcd9.png)

Any other ideas?

**Comment by ianhbell** [comment]
Apparently 10.0.0.98 is not new enough, but our internal version is:

```python
import os
os.environ['RPPREFIX'] = os.getenv('HOME')+'/REFPROP10beta'

import os 
root = os.getenv('RPPREFIX')
import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
print(RP.RPVersion())

print(RP.REFPROPdll('R410A.MIX','','GWPMIX',RP.MOLAR_BASE_SI,0,0,0,0,[]).Output[0])
```
yields
```
10.0.1.20
2087.5000000000005
```

**Comment by SYR-Rick** [comment]
I am not savvy enough to understand the code ;-(    

Is it possible for you to send me another download link for the 10.0.1.20  DLL files?

**Comment by ianhbell** [comment]
I have to loop back with our team and figure out whether this version is ready for public consumption.  For now, recommend you manually calculate the GWP of mixture based on the mass fractions of the components.  

Also: I previously noticed some of the GWP need to be added and/or updated

**Comment by SYR-Rick** [comment]
Yes, I can set up a routine to manually calculate the GWP.   (I should have let go of the GWPMIX function and done this a long time ago - I thought the updated DLL would have been the easier path.)  If I am only the second person to inquire about this in the past 2-3 years, we can assume it must not be very important to users and your efforts should be placed elsewhere.    It is OK to close this issue out.   (This is my first time using GitHub, am I supposed to close it or are you?)    

Thanks again for your help.   I do sincerely appreciate it and the great work you are doing!

**Comment by ianhbell** [comment]
It is fine for you to close it, or I can too. Personal preference.
