### ISSUE TITLE
No example for 'Delphi call REFPROP DLL'

### ISSUE THREAD

**Issue by IMDAV2023** [usnistgov/REFPROP-issues#580]
It's regretful that no appropriate wrapper code is available to Delphi. or could you please suggest which wrapper code can be referenced for delphi?

**Comment by ianhbell** [comment]
Best I can recommend is http://www.coolprop.org/coolprop/wrappers/DelphiLazarus/index.html#delphi (which offers the facility to call REFPROP via CoolProp in Delphi)

But you are also welcome to provide wrappers to the community.
