### ISSUE TITLE
Set Mixing Parameters not working in Excel

### ISSUE THREAD

**Issue by smoe38** [usnistgov/REFPROP-issues#581]
Hello,
I am using Refprop v10 to calculate the phase boundary of a given composition. In my example it is just Oxygen/Carbon dioxide. I want to compare different mixing rules: Default XR0 with given parameters by Gernert/Span, XR0 with other fij, and Peng-Robinson.

So for testing I just created an Excel sheet with the command in a cell: =REFPROP("P", composition, "TSAT", ...)
This works fine and I get the value I want with the Default settings for mixing rule and parameters.

Via VBA I  set to Peng-Robinson with command: Call FLAGSdll("PR", 2, kFlag, ierr, herr, 255&, 255&)
This also works fine and I get the value calculated with PR-Rule in my excel cell (it differs from the default settings).

So, the thing that doesn't work is to set my own parameters for fij with mixing rule XR0. I use Call SETKTVdll and it works fine within VBA with e.g. Call SATTdll, but it won't change the value in my excel cell. Is there any chance to set the programme behaviour like the FLAGSdll with Peng-Robinson does to calculate the values with an Excel sheet for changed parameters in the HMX file?

I hope I described the problem well enough.

**REFPROP Version:** REFPROP v10.0
**Operating System and Version:** Windows 10 64-bit
**Access Method:** Excel/VBA

**Comment by ianhbell** [comment]
If you want to fit parameters, cannot recommend to do so with Excel. You want to use a programming environment that is deterministic in its calls to the DLL, which is not the case in Excel.

**Comment by smoe38** [comment]
Yes I know, but it is a programme running with Excel and this will not be changed soon. So if it works for setting to Peng-Robinson, is there no similar command for setting new fij parameters as programme behaviour? I tried many command from the DLL docs without success. Could it be possible to SETKTV in the .xla-file?

**Comment by ianhbell** [comment]
First, I would write a test-program in Python, Fortran, or C++ to ensure that you know how to make the calls. And then only then test the calls with Excel. I recommend Python's interface because it protects you against most of the most common errors with string buffer overwrites.

**Comment by smoe38** [comment]
It works in Python as well. I use the SETKTV call in my python script. Just the problem I described in the first place, setting program behaviour for Excel commands in a cell. By the way, thank you Ian for trying to help.

**Comment by smoe38** [comment]
I found a first solution to my problem. I copied the HMX.BNC file and adjusted the parameters.. So now if I want to calculate my Excel sheet with my parameters I use the "new" HMX.BNC file in Call SETUPdll.

**Comment by ianhbell** [comment]
Yes, this is the dangerous solution, because it is easy to forget to replace the old one. But it should work.  I agree, I recall I tried to fit kij with PR and couldn't get it to work. Depending on what you are doing, you could also do the same thing with teqp: https://teqp.readthedocs.io/en/latest/models/cubics.html#Adjusting-k_ij
