### ISSUE TITLE
Calling SATPdll and TQFLSHdll from Excel VBA

### ISSUE THREAD

**Issue by BarendMeiring** [usnistgov/REFPROP-issues#582]
Hi, hope you are well.

I would like to call SATPdll and TQFLSHdll directly from Excel and I'm guessing that one should use VBA to do so. I want to know if you have an example of how to call these?

I know that an Excel document is shipped with REFPROP with VBA code where you can call the REFPROPdll and I want to modify it to call SATPdll and TQFLSHdll only.

I'm struggling to find any documentation or examples of this.

What I want to achieve:
I want to calculate the saturation temperature for water from a pressure input using SATPdll and calculate density and entahlpy from the saturation temperature and quality using TQFLSHdll.

REFPROP Version: 10.0 
Operating System and Version: Windows 11 
Access Method: Excel VBA

**Comment by ianhbell** [comment]
Please follow the pattern used to call the REFPROPdll function in the VBA code to call these other functions. However, we do not recommend to do this, rather if you care about speed, you should be using a different programming environment.

**Comment by BarendMeiring** [comment]
Hi Ian, thanks for your reply.

I tried calling SATPdll and TQFLSHdll in the same manner as for the REFPROPdll but Excel crashes everytime I do so. I managed to call REFPROP1dll, ABFLSHdll, ABFL1dll, SATTdll, and PQFLSHdll without Excel crashing.

Please see the attached text file for the Excel VBA code. Excel crashes when I uncomment either SATPdll or TQFLSHdll.

[Excel VBA REFPROP dll.txt](https://github.com/usnistgov/REFPROP-issues/files/10825447/Excel.VBA.REFPROP.dll.txt)

**Comment by ianhbell** [comment]
Are you getting ``ierr = 0`` for each call? If not, you should not trust any following results.

**Comment by ianhbell** [comment]
I can't see any obvious problems in your script.

**Comment by BarendMeiring** [comment]
Hi Ian,

I managed to get Excel to call the SATPdll and TQFLSHdll functions without crashing. Excel crashed when I saved the workbook as an macro-enabled workbook (.xlsm), but this was solved by saving the workbook as 97-2003 workbook (.xls).

Thank you for your assistance.

**Comment by ianhbell** [comment]
Hmm.. That is weird. I guess we can close this issue for now.
