### ISSUE TITLE
Using RefProp 9.1 with Python 3.9

### ISSUE THREAD

**Issue by myronmenezes** [usnistgov/REFPROP-issues#584]
Hi,

I have RefProp 9.1 installed on my system. I want to use the software along with Python to calculate the states of a mixture at a given state.

However all the examples found online are for RefProp 10 (except for one example with legacy API using RefProp 9.1 on the jupyter notebook example) 

Assuming there aren't any examples online, can anyone guide me to how I can find states of a user defined mixture using RefProp 9.1 using the Python wrapper?

Thanks!

**Comment by ianhbell** [comment]
The REFPROP 9.1 version is no longer actively supported, and for that reason we have not put together examples for it. Please upgrade to version 10.0.

**Comment by myronmenezes** [comment]
Thanks!
