### ISSUE TITLE
Unable to load CO2 properly

### ISSUE THREAD

**Issue by darkdragon12345** [usnistgov/REFPROP-issues#588]
I am using Reprop 9.1.
like the title says，these are the code and pictures
![屏幕截图 2023-03-17 214708](https://user-images.githubusercontent.com/127290873/225923267-87c1480c-2f1c-417c-84d2-9f35e6a42518.png)
![屏幕截图 2023-03-17 215315](https://user-images.githubusercontent.com/127290873/225924719-755177f8-f283-430c-a01a-cb503304674b.png)
please let me know the reason. i just want to call the REFPROP in my project and use CO2 properties. thank you for answering my question

**Comment by ianhbell** [comment]
Sounds like your installation directory is not right. Where is your REFPROP installed?

**Comment by darkdragon12345** [comment]
you mean that i should install REFPROP in my project? i installed it in the other place, but i copied the files in my project, and linked refprp64.lib.

**Comment by ianhbell** [comment]
Are you trying to use REFPROP through the DLL or to call the Fortran files directly? 

A note is that the folder of FLUIDS should be located in the working directory where the executable is launched from.

**Comment by darkdragon12345** [comment]
now i don't have my computer along with me, i'll try tomorrow. thank you for answering my question so late.

**Comment by darkdragon12345** [comment]
i want to add REFPROP in my project, both adding dll and calling fortran files are ok. and what's your means of the working directory where the executable is launched from? it's the files named x64?

**Comment by darkdragon12345** [comment]
my question has been solved, i just reinstalled REFPROP in my project files then the function could be normally used.
