### ISSUE TITLE
Dipole moments for all alkanes seem incorrect

### ISSUE THREAD

**Issue by ibell** [usnistgov/REFPROP-issues#59]
A couple of folks are implementing dipole moments in CoolProp (https://github.com/CoolProp/CoolProp/pull/1701 ), and a number of discrepancies have been identified.  The clearest one is the alkanes, they are all 0.07 Debye?  Is that really correct? Thanks to @henningjp and @wandadars .

**Comment by EricLemmon** [comment]
Here are several sources that agree with the lower values in Refprop:

http://hbcponline.com/faces/documents/06_34/06_34_0001.xhtml
http://www.stenutz.eu/chem/solv6.php?name=nonane
http://butane.chem.uiuc.edu/pshapley/Enlist/Labs/LiquidSol/LiquidSol.html

**Comment by ibell** [comment]
Indeed, I may have spoken too soon. The sources I am finding are also in
the 0.07 Debye range

**Comment by nist-aharvey** [comment]
You can see how we got the dipole moments for the normal alkanes up to C10 in Section 2.3 of this paper:
https://link.springer.com/article/10.1007/s10765-005-2351-5
Beyond C5, the number is a guess and I am not aware of any reliable experimental (or theoretical) data.
It is an additional complication that the average dipole moment for these flexible molecules (C4 and above) will have a small temperature dependence.

**Comment by EricLemmon** [comment]
Can this be closed now?

**Comment by henningjp** [comment]
Yes.  We figured it out.  One of our references was erroneously reporting acentric factor values as dipole moments.  We’re findining references with the REFPROP values now.
