### ISSUE TITLE
linking to MS Excel 365

### ISSUE THREAD

**Issue by KyoungSRo** [usnistgov/REFPROP-issues#592]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Please fill out the question template

**Comment by KyoungSRo** [comment]
Hi, Ian

I am trying to link my REFPRO V.10 to W10 Excel.  I just found that I need administrator privilege to save the REFPRO.xlam to C:\Program (x86)\REFPRO not in my user folder.  I am waiting for our IT person to do this.  BTW, do you have any manual/instruction how to use REFPRO in Excel? 

Thanks,

Kyoung

**Comment by ianhbell** [comment]
The Excel files provided with REFPROP provide quite extensive documentation, please check them out

**Comment by KyoungSRo** [comment]
OK  Thanks

**Comment by KyoungSRo** [comment]
Hi, Ian

I have REFPROP v.10 on my old w10 notebook.
I recently upgraded to a new notebook with w11 and try to install the REFPROP (nist10e_32.exe), but cannot install the app.
Does this app not work on w11?
Or should I buy other version of REFPROP?

Please advice.

Thanks,

Kyoung S Ro, Ph.D.
Research Environ. Engineer
USDA-ARS
Coastal Plains Soil, Water & Plants Research Center
2611 West Lucas Street
Florence, SC 29501
***@***.******@***.***>
https://www.ars.usda.gov/kyoung.ro
‪<https://scholar.google.com/citations?user=YGB9AhQDoFIC>Kyoung S Ro - ‪Google Scholar








This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by ianhbell** [comment]
In what way does the install fail?

**Comment by KyoungSRo** [comment]
It appeared that it was installing the app in the beginning , but at the end, it says there was a problem.

If you want actual screen shot, I have to ask our IT to install it again and give you the screen shot tomorrow  as I do not have authority to install app on my gov. computer.

Kyoung S Ro
USDA-ARS

**Comment by KyoungSRo** [comment]
Hi, Ian

Our IT person gave me the screen shot (see below).

It appears that I need 64-bit Windows compatible version.
However, my old computer was also 64bit W10.
Only difference between the two computer is that my new one runs on W11.

The installation file that I have
Nist1-e_32.exe  (8/1/2006)

Thanks,


***@***.***

Kyoung S Ro
USDA-ARS

**Comment by ianhbell** [comment]
Please email me the screenshot at ian.bell@nist.gov
