### ISSUE TITLE
Using Refprop with Matlab

### ISSUE THREAD

**Issue by Albert-Gil** [usnistgov/REFPROP-issues#593]
Hi,

I just installed Refprop v10.0. I need to use it with Matlab, so I have followed all the tutorials available.
When I try to get any value using refpropm.m, it just doesn't work. I have tried so many times doing different things that I got different error messages.
I have placed the .dll and .m files in the directory, I have tried placing also the files in my Matlab's working folder, and I have uninstalled and re installed Reprop twice. I haven't got any single result.

For example, if I write this in the command line:
`refpropm('P','T',373.15,'Q',0,'water')`

The error that I'm getting in Matlab is the following:

`Error using loadlibrary
Too many input arguments.
Error in ==>@()rp_proto64(BasePath) at 211
There was an error running C:\Program Files (x86)\REFPROP\refpropm.m.
Run @()rp_proto64(BasePath) from the command line to reproduce the error and fix it.

Error in refpropm (line 227)
    [notfound,warnings]=loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

Error in TankModel_Refprop (line 79)
ptank(i)=refpropm('P','T',ttank(i),'D',h2dens(i),'hydrogen');

Caused by:
    Error using rp_proto64
    Too many input arguments.`

### Versions

REFPROP Version: v10.0
Operating System and Version: Windows 10 64bit
Access Method: Matlab R2022b

Any help will be much appreciated. Thanks.

**Comment by ianhbell** [comment]
refpropm is no longer supported for reasons like you see here. Migrate to the python interface for MATLAB: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB
