### ISSUE TITLE
Version 10 XLA not solving, version 9.1 XLA OK

### ISSUE THREAD

**Issue by NikF1** [usnistgov/REFPROP-issues#595]
When using the v10 "REFPROP" function in Excel, I get an error. However, the v9 Excel add-in gives a result that appears plausible (compared to available data and other equations of state).

```=REFPROP("P","Hydrogen;Nitrogen;Ammonia|.7;.26;.04","TVAP","C",-5)```

gives "#[TQFLSH error 121] Temperature input is greater than the critical or maxcondentherm temperature: T = 268.150 K, Tc = 72.2338 K."

whereas

```=Pressure("Hydrogen;0.7;Nitrogen;0.26;Ammonia;0.04","TVAP","C",-5)```

gives 15.41660513 MPa.

**Comment by ianhbell** [comment]
Did you turn on the saturation splines in both cases?

**Comment by NikF1** [comment]
Yep, they're on in both cases: "iFlag = 1" is uncommented in v10, and "Call SATSPLNdll(x(1), ierr, herr, 255)" is uncommented in v9.

**Comment by ianhbell** [comment]
Well, we have updated the models for all the binary pairs in this mixture since REFPROP 10, but this is a flash calculation failure, so updated models might not make the difference. I ran with REFPROP 10, and I am curious how you got any values at all. I got this result:

```python
import os
os.environ['RPPREFIX'] = os.getenv('HOME')+'/REFPROP10'

root = os.getenv('RPPREFIX')
import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

i = RP.SETFLUIDSdll('HYDROGEN;NITROGEN;AMMONIA')
print(i)
if i != 0:
    print(RP.ERRMSGdll(i))
    quit()
z = [0.7, 0.26, 0.04]
r = RP.REFPROPdll('','TQ','P',RP.MOLAR_BASE_SI,0,1,273.15-5,1,z)
print('h,s:', r.Output[0:2])
```
yielding
```
117
[SETUP error 117] Estimation of mixing parameters is not possible for most mixtures containing water, helium, hydrogen, neon, carbon monoxide, fluorine, methanol, or ethanol.
```

**Comment by NikF1** [comment]
I don't know what to tell you; that's what I get from the Excel functions. The big difference that I perceive is that the v9.1 XLA does not call the REFPROPdll subroutine (as it didn't exist then), but v10 one does – as does your Python code above. I haven't dug into the Fortran source, but my guess is that the call via the REFPROPdll subroutine is not exactly equivalent to the SATTdll call that the v9.1 XLA uses; not sure if it's a matter of REFPROPdll doing some "pre-processing" before even trying the flash, or something else...

**Comment by NikF1** [comment]
Probably worth stating as well that this is with the 10.0098 DLL.

**Comment by ianhbell** [comment]
Are you using the REFPROP 10.0 models? If so, I maintain that you should not have been able to get values from Excel. Try it in the GUI.

**Comment by NikF1** [comment]
I hear you, but 

```=RefpropDLLVersionNumber()```

gives me 10.0098.

The GUI gives me this:


![REFPROP GUI](https://github.com/usnistgov/REFPROP-issues/assets/111129716/2ff07d1e-afbf-4805-8eeb-0cd15fcbf361)

![image](https://github.com/usnistgov/REFPROP-issues/assets/111129716/62a1f755-cd9e-443d-983d-86a7806dad52)

**Comment by ianhbell** [comment]
Did you get a warning or error when you selected this mixture in the GUI? You should have I should think.

**Comment by NikF1** [comment]
I've received literally no warnings or errors at any point in this process, whether in Excel or the GUI.

**Comment by ianhbell** [comment]
That's a bug then. Unless you have updated your HMX.BNC. What do you see for mixing parameters (Substance -> View Mixing Parameters)?

**Comment by NikF1** [comment]
Ah-ha! I am indeed using an updated HMX.BNC that I got from Eric, as I needed the new H2/CO2 model. (I can attach the HMX.BNC I am using for your reference, if it's permitted to post it publicly.)

When I switch back to the default v10 one, I do indeed get "#[SETUP error 117] Estimation of mixing parameters is not possible for most mixtures containing water, ammonia, helium, hydrogen, neon, carbon monoxide, fluorine, methanol, or ethanol."

Nevertheless, it's still odd that the REFPROPdll call and the TSATdll call give a different output, no? I would have thought that the call via REFPROPdll would "route" the calculation internally to get the same result.

**Comment by ianhbell** [comment]
Ok, that makes sense. Please don't post the HMX.BNC.

Yes, it *should* be the case that all route to the same method. But that is not the case.

**Comment by NikF1** [comment]
If it should, but isn't, is it then a bug...?

**Comment by ianhbell** [comment]
I would say not, just an inconsistency in my opinion.
