### ISSUE TITLE
Plotting Phase Diagram

### ISSUE THREAD

**Issue by Ranzengar** [usnistgov/REFPROP-issues#596]
Hi, i'm trying to retrieve the phase diagram by calling the DLL. I'm trying to understand from the official REFPROP documentation how this can be achieved, but i'm not finding how to retrieve the points of the plot.

In some other Issues, for example " Use of SATSPLNdll #383" an example on how to retrieve this data is provided but it seems that a python or something is used as a wrapper for the DLL and the REFPROPDLL method seems even different from the one in the documentation (order and number of inputs is different). In this example the "SPLINENODES" name is provided to the REFPROPDLL but is not stated anywhere in the official documentation, how can i retrieve that following the official documentation?

After that, how can i retrieve the specific points to plot the diagram?

Steps to Reproduce
n/a

Versions
REFPROP Version: REFPROP 10.0.0.02
Operating System and Version: 64-bit Windows 10
Access Method: Building my own wrappers in C# to call the DLL API functions.

Thanks in advance!

**Comment by ianhbell** [comment]
There is the ``SPLNVALdll`` function in the DLL, which will return interpolated values from the saturation spline. Or, you can use the method I showed, to yield the points that were actually stored internally, and from which the spline curves are based.

**Comment by Ranzengar** [comment]
I tried prividing "SPLINENODES" as a string to the hOut variable in REFPROPDLL function but it returns "[GETENUM error 811] Input string not recognized: SPLINENODES", probably i'm not figuring out something obvious

**Comment by ianhbell** [comment]
Did you try the exact code as in the Python example? Did you run the python example?

**Comment by Ranzengar** [comment]
Nope, as i stated in the opening post, i have a custom c# wrapper

**Comment by ianhbell** [comment]
Start off with a one-to-one test of the python example in C# I'd say

**Comment by Ranzengar** [comment]
I mean, in the python wrapper the arguments for the REFPROPDLL are not even matching the ones of the documentation, i'm worried that something more under the hood is happening there (9 in python, 23 in documentation), (or maybe in python you can omit some values if needed, i don't know the language).

It is correct to pass "SPLINENODES" to hOut parameter or it is intended on something else?

**Comment by ianhbell** [comment]
I don't follow. Did you run this in C#: 

<img width="1222" alt="image" src="https://github.com/usnistgov/REFPROP-issues/assets/11966765/76396233-c82c-4315-95d4-bde34f4927be">

**Comment by Ranzengar** [comment]
![image](https://github.com/usnistgov/REFPROP-issues/assets/53427451/1f118c81-9334-4f8d-9ecd-b6daf8feca2d)
I tried running it providing to hOut parameter the value "SPLINENODES" but it says "[GETENUM error 811] Input string not recognized: SPLINENODES".

My doubts are:
1) Where does this "SPLINENODES" comes from? It doesn't exists on the official documentation.
2) Because python implementation has lesser arguments on the REFPROPDLL function, is correct to provide "SPLINENODES" to hOut parameter?

**Comment by ianhbell** [comment]
The arguments to the ``REFPROPdll`` function in python are the inputs, the remainder are the outputs, collected in a class.

It is correct that the SPLINENODES is not well-documented. It is an expert-user functionality. What exact version of REFPROP do you have?

**Comment by Ranzengar** [comment]
I have 10.0

**Comment by ianhbell** [comment]
Can you try to patch to 10.0.0.02? Email me (ian.bell@nist.gov) for the link. That's what I used to run the Python examples

**Comment by Ranzengar** [comment]
Is it a stable version? Because we are implementing the library in production environment and we don't want to risk introducing other problems

**Comment by ianhbell** [comment]
Yes, 10.0.0.02 just fixes a few very minor bugs. But I don't think it will fix this problem. I suspect the issue with not finding SPLINENODES is on your side.

**Comment by Ranzengar** [comment]
Hi @ianhbell, i was able to retrieve the data following the python example.
I only have one problem, it seems that if i try to apply the same to a single substance, for example Nitrogen 100%, the number of nodes returned is 0.

Is there some known issue about it? It's not possible to retrieve the plot of a single substance?

**Comment by ianhbell** [comment]
I seem to recall that REFPORP does not build phase envelopes for pure fluids. You could fudge it by adding another component with a tiny, tiny mole fraction. But I would instead recommend to just do the conventional VLE calculations.
