### ISSUE TITLE
Fail to produce viscosity, thermal conductivity and so on

### ISSUE THREAD

**Issue by ZidanFang** [usnistgov/REFPROP-issues#597]
Hi there, 
I've been calculating several physical quantities(isobaric heat capacity, viscosity, thermal conductivity, etc.) when crossing the critical point. The results throw an Error Flag to me in several cases: '[TRNPRP error 561] Pure fluid correlation produced an erroneous value for either viscosity or thermal conductivity.'  

### Description

An example producing erroneous result is shown as follows:
``` python
FldType = "METHANE; O2"
hIn = "TP"   
hOut = "VIS"
iUnits = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum 
iMass = 0 
iFlag = 1  
T = 182.21    #K
p = 5950487   #Pa
muCalResult = RP.REFPROPdll(FldType, hIn, hOut, iUnits, iMass, iFlag, T, p,[0.6, 0.4])
print("the value of mu is", muCalResult.Output[0])
print("the error flag is", muCalResult.ierr)    #Error Flag 561
```

I wonder if there is something wrong in my settings.

Thanks in advance for your kind assistance!

### Versions

**REFPROP Version:** 10.0 
**Operating System and Version:** Win 10 
**Access Method:** Python 3.8.13, using REFPROPdll

**Comment by ianhbell** [comment]
Both thermal conductivity and viscosity are divergent _at_ the critical point for pure fluids. In some models, this divergence is explicit, in others not explicit. But... for mixtures, there is some disagreement whether these quantities are divergent or not.
