### ISSUE TITLE
Path problem in Excel add-in.

### ISSUE THREAD

**Issue by mcapobianchi** [usnistgov/REFPROP-issues#6]
I am trying to install REFPROP as an add-in on Excel.  However, when I call a function such as =DENSITY(“argon”,”TP”,”SI”,300,10), I receive the following error message:

#[SETUP error 101] error in opening file for component #  1; filename = (C:\Program Files (x86)\miniREFPROP\fluids\argon.fld                             ).

It is apparently looking for “miniREFPROP” in the path, but no such subdirectory exists.  Instead, the subdirectory created at installation is simpy “REFPROP”.  How do I correct this?

**Comment by ianhbell** [comment]
Almost certainly this is a manifestation of miniREFPROP being on your PATH environment variable, or RPPREFIX being set to the miniREFPROP directory.  Please google how to modify the PATH variable, and replace the instance of miniREFPROP with REFPROP in your PATH environment variable.  That should make REFPROP much happier.

No chance you did have miniREFPROP installed before?

**Comment by mcapobianchi** [comment]
Thanks, Ian; I will give that a try.  Insofar as miniREFPROP is concerned, I never owned a copy and, for that matter, I was unaware of its existence until today.  Is it possible that what I have installed is actually miniREFPROP?  How would I confirm?  Thanks so much…Max

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by ianhbell** [comment]
How did you get it?  If you bought it, it’s REFPROP, if not, its miniREFPROP.  As I am sure you can understand, we primarily support REFPROP, for miniREFPROP you are on your own and you will have to use google to find your answers…  If you buy REFPROP, we can provide support.

**Comment by mcapobianchi** [comment]
This is a purchased copy that is owned by a local company, RadMax Technologies, for whom I consult.  I am the one who recommended its purchase for my work; they had no prior copies of any kind.  I was thus wondering, since the path is set for miniREFPROP, if it is possible that I received the wrong version.

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by ianhbell** [comment]
So that suggests that your PATH is incorrect somehow (maybe at one point you installed miniREFPROP?).  When you start up the REFPROP GUI, what does the splash screen say, and how many fluids are available?

**Comment by mcapobianchi** [comment]
The splash screen says “REFPROP, NIST Standard Reference Database 23, Version 9.1, DLL Version 9.1”.  miniREFPROP was never installed to my knowledge, although I had multiple exchanges with Eric Lemmon regarding a problem with a FORTRAN program linking to REFPROP’s DLL.  He sent me revised versions of the subroutines, but I was ultimately only able to install REFPROP as a static library.  That has since all been purged, and what I have on the machine now should be only the original version.  But I wonder if something has been inadvertently changed.

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by ianhbell** [comment]
Yup, sounds to me like there were some traces of miniREFPROP left.  Recommend to edit your PATH environment variable and remove the offending miniREFPROP entry.

**Comment by mcapobianchi** [comment]
OK, I will let you know as soon as I am done.  Thanks so much.

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by mcapobianchi** [comment]
It works now; thanks so much!

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by ianhbell** [comment]
Great! Please go ahead and close the issue!

**Comment by mcapobianchi** [comment]
I think I closed it correctly, but please let me know if it is still open.  Thanks so much.

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by ianhbell** [comment]
It's still open, you need to click the "close and comment" button in the web interface

**Comment by mcapobianchi** [comment]
OK, it should be closed now.

Massimo “MAX” Capobianchi, Ph.D., P.E.
Professor and Chair
Department of Mechanical Engineering

PHONE (509) 313-3541
www.gonzaga.edu<http://www.gonzaga.edu/>
[Gonzaga University Logo]<http://www.gonzaga.edu/>

**Comment by ianhbell** [comment]
Yup, you got it!
