### ISSUE TITLE
Issues predicting 2-phase behaviour for wet combustion gas mixtures

### ISSUE THREAD

**Issue by acr2699** [usnistgov/REFPROP-issues#601]
**REFPROP Version:** REFPROP 10.0
**Operating System:** Windows 10
**Access Method:** GUI

Hello,

I’m looking for some assistance with an ongoing issue when using REFPROP to validate the behaviour of combustion gas systems containing water.

I am using REFPROP to validate results obtained from a process simulator which uses the PSRK equation of state. The systems in question have the following gas compositions (by mole):

Case 1 (High CO2 concentration gas): 
Argon – 3.2%
CO2 – 80.62%
Nitrogen – 2.26% 
Oxygen – 0.47%
Water – 13.45%

Case 2 (Low CO2 concentration gas):
Argon – 0.903%
CO2 – 20%
Nitrogen – 58.87% 
Oxygen – 14.11%
Water – 6.11%

The temperature range considered is -40 to 200 degrees C and a pressure of 0 barg.

The issue arises with the low CO2 concentration flue gas as the 2-phase behaviour of the system as predicted by REFPROP does not agree with that predicted by the PSRK EOS in the process simulator. I’ve attached two screenshots of graphs generated to show divergence in the T-H plots of both systems. The PSRK data looks intuitively correct as any liquid water in the system at lower temperatures is vaporised and the system is in the gaseous phase which is shown by the upwards curve in enthalpy at mid-range temperatures followed by a linear region to the system boundary. The ‘Quality’ and ‘Phase’ properties on REFPROP also indicated that there is no prediction of liquid water which is unexpected.

<img width="473" alt="80% Flue Gas" src="https://github.com/usnistgov/REFPROP-issues/assets/137483200/f0df8475-1b6c-4985-ac9d-16934a6f9ab8">
<img width="275" alt="20% Flue Gas" src="https://github.com/usnistgov/REFPROP-issues/assets/137483200/975c9ffb-3596-4a74-bf09-e9118cb2ebda">

 
From what I’ve been able to gather on various Github threads, other users have had similar issues and I’m not sure if there is yet a solution for it? Please let me know if there’s anything I can try to resolve this issue, any thoughts you may have, or if there’s anything else I can provide to help find a solution.

Best Regards

**Comment by ianhbell** [comment]
A couple of things: 
* REFPROP does not implement the PSRK EOS, your only options are the multi-fluid model and the PR model. What model did you use?
* What precisely have you plotted in those figures? I don't understand the differences between the two figures.
* What atmospheric pressure do you consider? You should always present absolute pressure, even if you have gage pressure measurements

**Comment by acr2699** [comment]
Hi Ian,

Thanks for your reply!

We have used the multi-fluid model and will be using the results obtained from this as a comparison with the PSRK EOS to confirm that we can indeed use the PSRK EOS to simulate our systems. We are essentially undertaking a thermodynamic validation exercise as part of our work.

With regards to the two figures, they plot the change in enthalpy of each system across the temperature range I provided in the original post. Since REFPROP and the process simulator we are using have different reference states we could not use the enthalpy values provided by REFPROP directly. We assumed that -40 degC was the reference state and subsequently found each relative enthalpy value from here. It is these 'dH' values which are plotted on the figures I provided.

We considered all systems at atmospheric pressure.

Anything else please let me know.

Thanks!

**Comment by ianhbell** [comment]
What change in enthalpy? Please define it more precisely (mathematically).

Please label the figures, it is not clear which is which.

What atmospheric pressure? It matters if you are in New York or Colorado.

**Comment by acr2699** [comment]
<img width="590" alt="Screenshot 2023-06-23 135946" src="https://github.com/usnistgov/REFPROP-issues/assets/137483200/95244340-a9d2-49fb-a1eb-1eb154ff967b">

From the above screenshot it is assumed that H_ref = 15858 kj/kmol. (H at -40 degC)
Thus the enthalpy difference between the defined reference state and subsequent temperatures can be: 
dH (-40 to T) = H(T) - Href.
This is repeated for each temperature giving a data set of dH values for each temperature. This is what is shown on the figures. I've attached an excel sheet with the data which should hopefully show this more clearly.

The pressure considered for each system is 101.325 kPa

[Enthalpy Graphs.xlsx](https://github.com/usnistgov/REFPROP-issues/files/11848744/Enthalpy.Graphs.xlsx)

Thanks

**Comment by ianhbell** [comment]
Ok, the problem seems to be the use of saturation splines. Usually they help, but in this case they hinder. Here is my test code:
```python
import os
os.environ['RPPREFIX'] = os.getenv('HOME')+'/REFPROP10'

root = os.getenv('RPPREFIX')
import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
import matplotlib.pyplot as plt

import numpy as np
i = RP.SETFLUIDSdll('ARGON;CO2;NITROGEN;OXYGEN;WATER')
T_C = np.linspace(-40, 200)
T_K = T_C + 273.15

p = 101325

z1 = [0.032, 0.8062, 0.0226, 0.0047, 0.1345]
z2 = np.array([0.00903, 0.2, 0.5887, 0.1411, 0.0611])
z2 = z2/z2.sum()

fig, (ax1, ax2) = plt.subplots(2,1, figsize=(10,6))

for splines, ax in zip([False, True],(ax1,ax2)):
    for z in [z1, z2]:
        h = []
        for T_K_ in T_K:
            r = RP.REFPROPdll('','TP','H',RP.MOLAR_BASE_SI,0,splines,T_K_, p,z)
            # print(r)
            h.append(r.Output[0])
        ax.plot(T_C, h, label=z[1])
    ax.legend()
    ax.set_title(f'splines: {splines}')
    ax.set(xlabel='$T$ / C', ylabel='$h$ / J/mol')
plt.show()
```
yielding: 
![Figure_1](https://github.com/usnistgov/REFPROP-issues/assets/11966765/0b20e1e1-0588-49c3-ad7b-c17527745fa5)

**Comment by ianhbell** [comment]
Also, your second composition doesn't sum to 1

**Comment by acr2699** [comment]
Thanks for noticing the composition discrepancy, I had made a normalisation error after changing the CO2 fraction to 20%.

With regards to your above code, I am accessing REFPROP via the GUI and have deselected 'Initialise saturation boundaries for mixtures' in preferences (screenshot below) and this has solved the problem. I assume this has to do with saturation splines as shown in your code? 
<img width="242" alt="image" src="https://github.com/usnistgov/REFPROP-issues/assets/137483200/0ff1d574-01fe-4f97-84e2-358ef001652c">

Can I ask what these saturation splines are and why this change has allowed the correct phase behaviour to be determined?

Thanks again for your help with this!

**Comment by ianhbell** [comment]
The saturation splines are the curve along the isopleth of the phase envelope (which is sometimes erroneously called the phase envelope)

The saturation splines are used to provide a good guess value for the iteration. Often they help, sometimes like your case, they don't.  Mixtures with water are notoriously difficult for the algorithms, which is due to bad models, and the physics of water-containing mixtures.

**Comment by acr2699** [comment]
Great, thank you
