### ISSUE TITLE
how to import excel file data such as temperature and pressure to REFPROP

### ISSUE THREAD

**Issue by mejehiemi** [usnistgov/REFPROP-issues#602]
Hi
 
I recently purchased REFPROP 10. I am trying to import a large set of data from an excel spreadsheet into REFPROP to calculate various properties.
 
I have been unable to do so as the steps I found online are not consistent with what is in REFPROP.
 
An example is :
 
" Open REFPROP. ...
Go to File/Options/Trust Center/Trust Center Settings (button at bottom right).
Select "Trusted Locations" on the left. ...
Go to File/Options/Add-Ins and select "Excel Add-ins" in the Manage drop-down box at the bottom and click Go."
However, there is no File/Options etc. in the REFPROP folder. If you launch the REFPROP, you still would not find it in the drop box under file.
 
How do I resolve this?
 
I look forward to a positive response from you.

**Comment by ianhbell** [comment]
Do you mean into the REFPROP GUI? I think what you mean is you are trying to install the REFPROP add-in for Excel.

**Comment by mejehiemi** [comment]
Yes, I mean into REFPROP GUI. I have installed REFPROP add-in for excel. However, I can only calculate properties at a specific point, like one temperature and pressure at a time.

**Comment by ianhbell** [comment]
But you can also apply the same formulas to sets of columns and evaluate a table in Excel

**Comment by mejehiemi** [comment]
Could you kindly explain further how this can be achieved, because when I click on REFPROP in excel, its asks for two parameter input and with that calculates a stipulated parameter under the set conditions.

**Comment by ianhbell** [comment]
Yes, and you can do the same thing on the next row in your file. Have you read over completely the excel workbook included with your REFPROP installer?

**Comment by mejehiemi** [comment]
Yes I have. So basically, I can't import a large set of data into REFPROP GUI for lets say temperatures and pressures. and then calculate selected properties at once? That would be time saving as oppose to calculating one property at a time on excel.

**Comment by ianhbell** [comment]
Why do you want to do that rather than using Excel directly? Copy-paste is almost never the right answer and introduces lots of potential bugs.

You can do it: copy the temperature column into the REFPROP table, copy the pressure column into the REFPROP table

**Comment by mejehiemi** [comment]
Ok. Thanks alot.

I appreciate the time.
