### ISSUE TITLE
Discrepancy between Refprop App and Excel function call calculations

### ISSUE THREAD

**Issue by FredFact** [usnistgov/REFPROP-issues#603]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

I have been trying to understand why some Excel viscosity calls are giving errors with user defined mixtures. I can illustrate the problem with a specific example.

I set up a simple Excel spreadsheet for one of the mixtures: methane;ethane;propane;carbondioxide;nitrogen|.8864;.0659;.0231;.011;.0136 (mole fractions). The unit type used was ‘SI with C’. The spreadsheet used V10 function calls. It was run for a range of pressures from 7 to 10 MPa at 0.1 MPa intervals with a fixed temperature of 15 C. The output were columns of enthalpy, density, viscosity and quality. A screenshot ‘ExcelFunctions1.png’ is attached below which shows the resulting output. At some values of pressure, numerical viscosity values are output which look reasonable, but at other pressure values, an error was given for the viscosity; ‘#[REFPROP error 810] One or more of the input properties is not thermophysically defined for two-phase states and cannot be calculated’. These errors only occurred where output quality values were rather odd, being very small, around 1.e-12. Although small, these are between 0 and 1 so they are interpreted as indicating a two phase fluid, which leads to the viscosity errors. The range of pressures and the temperature chosen were well away from any phase boundary for the mixture, so I think that the quality values must be wrong.
 
For comparison, I set up exactly the same mixture in the standalone REFPROP App and used the ‘Isoproperty Tables’ calculation to cover the same range of pressures at a fixed temperature of 15 C. The output is shown in a second screenshot ‘RefpropApp1.png’. There are no odd quality values and no viscosity errors in the App output.

I have not changed the calculation methods for mixtures in either the App or the VBA wrapper code. They are at the defaults set up in the installation.

It may be worth mentioning that if I do the same spreadsheet calculations in V9.1 installation there are no errors, the viscosity values just coming out slightly higher than the V10 App values. 

### Steps to Reproduce

1.
Set up an Excel spreadsheet. Use the mixture specified above and use REFPROP V10 function calls for enthalpy, density, viscosity and quality for the range of pressures and temperature given above.
2.
Set up the same case in the REFPROP App

**Expected behavior:** [What you expect to happen]
The outputs should agree

**Actual behavior:** [What actually happens]
The Excel results have errors which are not present in the App output

### Versions

**REFPROP Version:** 
REFPROP 10  
**Operating System and Version:** [OS you are running REFPROP on] 
Windows 11 pro 
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  
Excel VBA wrapper
### Additional Information
Excel is latest Microsoft 365 version

If possible, please post examples and/or
![ExcelFunctions1](https://github.com/usnistgov/REFPROP-issues/assets/134863356/5ebe7020-546d-4578-8809-7e7f11743d8c)
![RefpropApp1](https://github.com/usnistgov/REFPROP-issues/assets/134863356/c4f3af9e-c370-4380-9015-96196ab197d5)
 screenshots of the issue.

**Comment by ianhbell** [comment]
These problems with the viscosity model calculations have been fixed in the development version. Unfortunately we do not have an ETA for when this version might be available to the public.

**Comment by FredFact** [comment]
Thanks for the information. I will wait for a future update.
