### ISSUE TITLE
Obtain -9999990 as the value of thermal conductivity of air

### ISSUE THREAD

**Issue by atit-sut** [usnistgov/REFPROP-issues#606]
I would like to use MATLAB to access REFPROP to determine the air properties by using the following commands

clear
clc
T1 = 50 + 273.15;
p1 = 101325;
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
fluid = 'air';
z = {1  0};
rho_air1 = refp(fluid,'TP',T1,p1,'D',RP,z)
mu_air1 = refp(fluid,'TP',T1,p1,'VIS',RP,z)
k_air1 = refp(fluid,'TP',T1,p1,'THC',RP,z)

and here is the content of refp

function answer = refp(fluid,input,parameter1,parameter2,output,RP,z)
MOLSI = RP.GETENUMdll(int8(0),'MASS base si').iEnum;
iMass = int8(1); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
r = RP.REFPROPdll(fluid,input,output ,MOLSI,iMass,iFlag,parameter1,parameter2 ,z);
G = double(r.Output);
answer = G(1);
end

I found that the obtained values of "rho_air1" and "mu_air1" are reasonable. However, I obtained -9999990 as a value of "k_air1". Please help me out.

### Versions

**REFPROP Version:**10.0
**Operating System and Version:** Microsoft Windows 11 Home 
**Access Method:** Python wrapper to connect between MATLAB R2022a to REFPROP.

**Comment by ianhbell** [comment]
Wrong output key for thermal conductivity if indeed that is what you want:

<img width="1146" alt="image" src="https://github.com/usnistgov/REFPROP-issues/assets/11966765/8e607fdc-32eb-4549-bc8b-13b958047dee">

You should also be checking the value of ierr and herr

**Comment by ianhbell** [comment]
See https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html

**Comment by atit-sut** [comment]
Thank you very much.
