### ISSUE TITLE
R471A on REFPROP

### ISSUE THREAD

**Issue by LidiaLLP** [usnistgov/REFPROP-issues#607]
Do you have available a patch to add R471A on REFPROP v9.1?

**Comment by ianhbell** [comment]
Nope, we only provide such a thing for REFPROP 10.0, please upgrade

**Comment by LidiaLLP** [comment]
Thanks for the quick feedback. Just making sure Does REFPROP 10.0 has R471 available?

**Comment by ianhbell** [comment]
Yes and no. Yes we have the pure fluids so you can model this mixture in REFPROP 10.0, but we don't have experimental data to fit the interaction parameters so an estimation scheme is used.

**Comment by LidiaLLP** [comment]
Thanks I appreciated
