### ISSUE TITLE
REFPROP use clarification

### ISSUE THREAD

**Issue by crlaugh** [usnistgov/REFPROP-issues#608]
I have created a bit of software that accelerates the property calls in REFPROP, particularly for low-GWP mixtures, for use in dynamic cycle simulations.  This software does not use any of REFPROP source code, but simply calls the REFPROP dll using the Python interface to calculate coefficients of interpolants which it then stores in specific datafiles.  The coefficients in these datafiles are then loaded by a second simpler set of codes that implement the interpolating functions and then compute property values, such as the bubble density or two-phase specific entropy.  As the library author, I am the only one that uses REFPROP to calculate the coefficients, but there are other engineers who load these coefficient datafiles, which are distributed separately and independently from REFPROP, and then use them in their dynamic cycle simulations.

I would like to clarify the application of the approved uses of REFPROP in this case as pertaining to copyright and license restrictions.  I have purchased a license for REFPROP (of course) and I also cite the use of REFPROP in the software that calculates the coefficients.  However, my understanding is that the engineers who then load these computed coefficients from the newly created datafiles in their cycle simulations are not restricted by the terms of use of REFPROP in any way, since they do not directly use any REFPROP output or REFPROP software.  

Is my understanding correct, or are there other concerns that I have not considered?

**Comment by ianhbell** [comment]
That is correct. If REFPROP shared libraries or source code are not being used, you are free to do what you like with data calculated by REFPROP. Make sure it is clear what precise version of REFPROP was used to generate your data

**Comment by crlaugh** [comment]
Thanks!
