### ISSUE TITLE
Entropy Calculation Issues in Compressible Flow Using REFPROP

### ISSUE THREAD

**Issue by atit-sut** [usnistgov/REFPROP-issues#614]
I am currently modeling the flow across a turbine, which comprises a nozzle and a rotor. My primary concern is the discrepancies in the entropy changes that I observed, specifically negative entropy changes. I believe this might be related to the type of enthalpy used as an input to REFPROP.

Details:

Turbine Structure: The turbine consists of a nozzle and rotor.
Flow Velocity: The maximum flow velocity exceeds 100 m/s.
Input Parameters to REFPROP: I used pressure and enthalpy to determine entropy changes.
Question:
When entering data into REFPROP, should I use "static" enthalpy or "stagnation" enthalpy (static + dynamic) to achieve accurate entropy calculations?

Technical Information:

REFPROP Version: 10.0
Operating System: Microsoft Windows 11 Home
Access Method: I used a Python wrapper to bridge MATLAB R2022a with REFPROP.
I appreciate any insights or guidance on this matter.

Thank you,
Atit

**Comment by ianhbell** [comment]
I would do the analysis yourself, staying away from the static and stagnation enthalpy. You can write the energy balance as 

$$
\dot W = \dot m((h_2+V_2^2/2)-(h_1 + V_1^2/2))
$$

remembering that V is in m/s, and enthalpy is in J/kg and $\dot m$ in kg/s. h_1 and h_2 are then the "normal" enthalpy. Then you can work out for yourself which kind of enthalpy you want.

**Comment by atit-sut** [comment]
Dear Ian Bell,

Thank you for your prompt response. I apologize if I was not clear enough in my initial post. Let me provide more specifics to convey my concerns better.

Objective: My primary goal was to determine the entropy change across various components of a turbine, namely the nozzle and the rotor.

Procedure:

I utilized REFPROP to calculate the entropy values by feeding it pressure and enthalpy data.
After obtaining the entropy values, I computed the entropy change across the components (from the inlet to the outlet).
Notably, the entropy change across the rotor appeared negative, which raised my concerns.
Primary Concern: My uncertainty revolves around the input to REFPROP. Specifically, for the enthalpy input:

Should I provide REFPROP with "static" enthalpy values?
Or, should I provide the "stagnation" enthalpy, accounting for both static and dynamic components?
The energy balance equation you provided is valuable, and I am familiar with it. However, my main concern stems from the type of enthalpy used as input to REFPROP and how it affects the computed entropy, which subsequently influences the calculated entropy change.

I appreciate your patience and any further guidance on this matter.

Warm regards,

Atit

**Comment by ianhbell** [comment]
I am not a turbomachinery person, so I am almost always operating in the domain where the kinetic energy is negligible relative to internal energy plus the product of pressure*volume (the enthalpy $h = u + pv$). So I am not immediately sure what to recommend. I think most calculations in Refprop make the same assumption as I do. All flash calculations assume negligible kinetic energy, for instance.

Can you please provide a concrete example, with numbers?
