### ISSUE TITLE
REFPROP 10 Inconsistent R134a temperature results between ABFLSH and PHFLSH

### ISSUE THREAD

**Issue by friedlettuce** [usnistgov/REFPROP-issues#619]
### Description

I’m trying to convert from the legacy API functions in Refprop 10 to the high-level API. I'm trying to replace a call to PHFLSHdll with ABFLSHdll. I expect the temperature output from both calls to match, but currently they're returning different values. I tested with refrigerant R134a.

### Steps to Reproduce

1. Call PHFLSHdll with pressure: 904.833 kPa, enthalpy: 43365.3 J/mol. Return temperature.
2. Call ABFLSHdll with pressure: 904.833 kPa, enthalpy: 43365.3 J/mol. Return the temperature.
3. Call PHFLSHdll with pressure: 0.904833 kPa, enthalpy: 43365.3 J/mol. Return temperature.
4. Call ABFLSHdll with pressure: 0.904833 kPa, enthalpy: 43365.3 J/mol. Return the temperature.

**Expected behavior:** The temperatures from 1 & 2 should match. The temperatures from 3 & 4 should match.
**Actual behavior:** The temperatures from 1 & 2 do not match. The temperatures from 3 & 4 closely match.
* Temperature 1: 315.766K
* Temperature 2: 296.541K
* Temperature 3: 296.561K
* Temperature 4: 296.541K

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 11 
**Access Method:** C++ 17 w/ REFPRP64.dll

### Additional Information

``` c++
array<char, DEFAULT_ERROR_SIZE> HERR = {};
array<double, DEFAULT_ARRAY_SIZE> x = {};
array<double, DEFAULT_ARRAY_SIZE> y = {};
array<double, DEFAULT_ARRAY_SIZE> zCompositionArray = {};

std::string abInputProperties = "PH";  // The following inputs are pressure and enthalpy units
double dischargePressure = 0.904833;
double dischargeEnthalpy = 43365.3;
double temperature = 0;
double density = 0;
double liquidDensity = 0;
double vaporDensity = 0;
double vaporQuality = 0;
double internalEnergy = 0;
double entropy = 0;
double enthalpy = 0;
double isochoricHeat = 0;
double isobaricHeat = 0;
double speed = 0;
int errorFlag = 0;
int iFlag = 010;    // (Left to right) kr,kq = default. kph/phase = 1 (liquid). iMass = All inputs/outputs molar.

SETPATHdll(path.data(), DEFAULT_PATH_SIZE);
SETFLUIDSdll(fluidFile.data(), errorFlag, DEFAULT_ERROR_SIZE);  // Loads R134a.FLD

// Refprop 9 API
PHFLSHdll(dischargePressure, dischargeEnthalpy, zCompositionArray.data(), temperature, density, liquidDensity,
        vaporDensity, x.data(), y.data(), vaporQuality, internalEnergy, entropy, isochoricHeat, isobaricHeat, speed,
        errorFlag, HERR.data(), DEFAULT_ERROR_SIZE);

// Refprop 10 High-level API
ABFLSHdll(abInputProperties.data(), dischargePressure, dischargeEnthalpy, zCompositionArray.data(), iFlag, temperature,
    dischargePressure, density, liquidDensity, vaporDensity, x.data(), y.data(), vaporQuality, internalEnergy,
    enthalpy, entropy, isochoricHeat, isobaricHeat, speed, errorFlag, HERR.data(), 
    std::strlen(abInputProperties.data()), DEFAULT_ERROR_SIZE);

return temperature;
```
Thanks!

**Comment by ianhbell** [comment]
The problem is your units I think. ``ABFLSHdll`` and ``PHFLSHdll`` expect pressure in kPa. This was my test in Python:
```python
import os 
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = os.getenv('HOME')  + '/REFPROP10'
RP = REFPROPFunctionLibrary(root)
print(RP.RPVersion())
ierr = RP.SETFLUIDSdll('R134A')
if ierr != 0:
    print(RP.ERRMSGdll(ierr))

# In base SI units to start
dischargePressure = 904.833e3 # [Pa]
dischargeEnthalpy = 43365.3 # [J/mol]

# PHFLSHdll wants kPa for pressure
print(RP.PHFLSHdll(dischargePressure/1e3, dischargeEnthalpy,[1.0]*20).T)

# ABFLSH wants pressure in kPa
r = RP.ABFLSHdll('PH',dischargePressure/1e3, dischargeEnthalpy, [1.0]*20, 000)
print(r.T)

# REFPROPdll allows a lot of units, molar base SI are most reliable
r = RP.REFPROPdll('','PH','T',RP.MOLAR_BASE_SI, 0,0,dischargePressure,dischargeEnthalpy,[1.0])
print(r.Output[0])
```
yields
```
10.0
315.76621102174875
315.76621102174875
315.76621102174875
```

**Comment by friedlettuce** [comment]
Thanks Ian, for looking into this. The calculations did work as expected.
It turned out to be a setup issue on our end, where we were using the wrong version of our application to debug the issue.
Thank you again for your help!
