### ISSUE TITLE
PT flash table

### ISSUE THREAD

**Issue by SubodhPatwardhan** [usnistgov/REFPROP-issues#624]
I am writing this email to request your support in one of the cases using REFPROP 10.0.

I am finding some anomaly when I try arriving at property set for various temperature & pressure combinations.
Hot humid air is composed with Nitrogen, Oxygen & Water. I am attaching related Refrop file snapshot below.

The Dew Point Table (created with default equations) shows that the due point at 1 bara is 46.412 °C (see Table 8 in attached file). This means that below this temperature at 1 bara, the water portion in humid air should come out as condensate (liquid Water).
However, when I take properties at give state (pressure & temperature), then even at 45 °C state is shown as “Superheated” where as it should show “Quality” between 0 and 1 (see table 7 in attached file).

I also tried to change equations to Peng-Robinson and the Table results (Table 3) are not far from Table 7.

With Peng-Robinson, I am NOT able to create “Due Point” Table.

Will you please explain why I am getting such anomaly ?
Thank you.

Kind regards,
Subodh Patwardhan
![PH flash table](https://github.com/usnistgov/REFPROP-issues/assets/56533795/419cd244-9e4e-4f6b-955e-8c8358883b18)

**Comment by ianhbell** [comment]
Recommend to plot the phase envelope in the p-T plot to get a sense for where your state points are and see if your inputs are indeed in the wrong phase.
