### ISSUE TITLE
The REFPROP DLL you are using has expired (Version number 10.0.0.98a; date: 240202). Please return to the Refprop website and download the latest installer

### ISSUE THREAD

**Issue by tbusari** [usnistgov/REFPROP-issues#628]
It seems similar to two other issues that were closed after sending an email to Ian or Eric

### Description

This is related to the Excel wrapper. I have a version the 10 DLL of Refprop and in attempting to diagnose the issue, I have followed all the steps in the link here: https://pages.nist.gov/REFPROP-docs/#errors-in-version-10
In addition it was working just previously but it suddenly stopped. I used to have version 9 but I am almost sure I have all the old files deleted or unlinked.

I do not have the installer anymore.

In addition the error occurs when I use the =@REFPROP($C17,$B$10,$C$10,$D$10,$D$13,$D$14) notation

Whether I use the old notation =Density("argon","TP","SI",325,5,8,4) or the new notation, =@REFPROP("D","argon","TP","SI",325,5,8,4) I get the "VALUE" error

![image](https://github.com/usnistgov/REFPROP-issues/assets/7028773/953b3f1e-2b6c-41f1-97b9-e446cd75c38a)

**Comment by tbusari** [comment]
Updated DLLs from https://trc.nist.gov/refprop/10-BETA/REFPROP.HTM

**Comment by ianhbell** [comment]
Please email me (ian.bell@nist.gov) for access to beta DLL with longer expiration.
