### ISSUE TITLE
Glycol-Water model accuracy for heat capacity

### ISSUE THREAD

**Issue by Olaf987** [usnistgov/REFPROP-issues#629]
Dear all:

I have a question about the general accuracy of the calculations for ethylene glycol / water mixtures. I am trying to calculate the heat capacity.

The first thing I ran into that what is sold as ethylene glycol as cooling liquid is not pure ethylene glycol. It contains quite a bit of other stuff. Of course this "other stuff" is never specified in detail. When you calculate the volume based heat capacity (cp*rho) things line up again. This is because the density manufacturers provide is the density of their mixture and not the ideal mixture.

What I am seeing is that there are still significant deviations of 10% or more for high glycol mole fractions (~0.5 and more) and temperatures below 0°C. Most of the deviations are negative: the calculated value of cp*rho calculated is less than given by the manufacturer.

To check if there is something systematic, I inverted the calculation and calculated the mole fraction from the given value of rho*cp and compared it to the mole fraction based on manufacture tables. At this time I see no systematic relation between the two.

My current question is, if this is a known feature of the refprop 10 models, or do you think am I doing something wrong. All suggestions are welcome.

As an example I have added the specification of some DOW products.
[Dow_2001b.pdf](https://github.com/usnistgov/REFPROP-issues/files/14283525/Dow_2001b.pdf)
This also demonstrates that values of rho*cp for the 2 products are a lot closer than either those for either rho or cp.

Thanks for your help.

Olaf

**Comment by nist-aharvey** [comment]
While I do not have time to convert units from the volume fractions given in the Dow material, I was able to make a spot check against some experimental data for EG-H2O mixtures.
At an EG mole fraction of .53725, there is an experimental data point at 252.62 K of 103 J/K/mol.  REFPROP yields 100.7, so that is pretty good agreement. 248 K with that composition gives 98.1 in REFPROP, experiment 100.6.
At an EG mole fraction of .73216 and temperature 258 K, experiment is 115.6 and REFPROP gives 116.4, even better agreement. Same mixture at 248 K experiment is 112.7 and REFPROP is 111.2.
Accuracy on heat capacity experimental data is likely to be in the ballpark of 1%.
Several points I tried at 5 and 25 degC showed very good agreement with experiment.  

So assuming the experiments were accurate, I am not seeing anything at the conditions I tried that would suggest a 10% error.
That leads me to think that the difference from DOW specs might be due to the "other stuff", since REFPROP seems to be reproducing pretty well the binary H2O+EG mixture.

I did not test your product of density times Cp, so it is possible that the density calculation could be off, since I suspect this mixture is fairly nonideal.
But I just tried density at mole fraction .73216 and 258 K, where experimental density is 1128 kg/m3 and REFPROP gives 1127, so REFPROP densities seem to be good.

Secondarily, I wonder how they even define a "volume fraction" at some of the conditions in their tables where pure liquid water does not exist. I hope they are not using a volume of ice? Maybe it is a volume fraction with everything mixed together at 25 degC or something.

**Comment by Olaf987** [comment]
Dear Allan,

Thank you very much for your feedback. I will try to reproduce your results.

Regarding the weight and volume fractions: DOW lists both weight and volume fractions of glycol. I assumed that the weight fractions were correct. But they may be measured against the actual liquid which may contain the "other stuff". The volume fractions may be "more correct". I will convert their glycol volume fraction to mole fraction assuming this was done at 60°F (sigh) and the rest is water and see what happens.

Olaf

**Comment by Olaf987** [comment]
Dear Allan,

I delved into the Glycol-Water mixture calculations a bit deeper.

On the plus side: I was able to replicate your results. The density values calculate by REFPROP match values from literature quite well. Even for the DOW solutions the results is not all bad. Kudos for that.

However: values for the heat capacity differ by quite a bit. I eliminate all values with warnings from REFPROP. This eliminates the most ridiculous errors but that still does not make it right. Deviations from the DOW specification sheets are still big and even for values from clean experiments, for example Ignatowicz: https://doi.org/10.1016/j.ijrefrig.2023.08.008 (supplementary data available on the website), the deviations are larger. 

![cp](https://github.com/usnistgov/REFPROP-issues/assets/42813680/b775cb44-db32-4458-8a9f-59dbcf5a248a)

The curves with pub are from Ignatowicz and rp from REFPROP. Just to get a feeling for the size of the deviations, the relative deviation in %:

![rel_dev](https://github.com/usnistgov/REFPROP-issues/assets/42813680/a902b844-e13a-48e0-b89e-ba0d8df0e008)

Obviously these deviations are larger than you would expect. Do you have any thoughts on this.

I suspect that the DOW mixtures have too much "other stuff" to make a reliable prediction. I am worried about the fact that the deviation curves have a very similar shape with the largest deviations at low temperatures.

Thanks in advance for your insight

Olaf

**Comment by nist-aharvey** [comment]
Taking a quick look at that paper you linked, I'm not sure I would trust their reported Cp values.  They used DSC (Differential Scanning Calorimetry), which is good for detecting phase transitions but only approximate for heat capacities.  The paper says something about 1% accuracy, but I think that is very optimistic for DSC for a fluid heat capacity (as evidenced by them saying they get 1.5% error compared to well-known values for pure water).

One of their references, Milnes & Zanella (1965), used adiabatic calorimetry, which should be a much more accurate technique if done properly.  They measured a single composition, 62.5 wt% EG, and got the following values in cal/g/K (for Celsius temperatures):

![image](https://github.com/usnistgov/REFPROP-issues/assets/45049145/ad8be7e4-0630-402f-b1db-91c6f6011b10)

I note that the 60 wt% values from the recent DSC paper (when converted, 1 cal = 4.184 J) are significantly higher than these values, for example at -20 degC getting .7103 compared to .6688 in the 1965 paper.
REFPROP refuses to calculate at the lowest T (but gives 0.5874 at -35 degC). Other points in order are:
.6335
.6604
.6789
.6930
.7076
.7144
.7231
.7310
So REFPROP is quite consistent (within 1-2%) with the 1965 data except at the lowest T where it looks like it disagrees significantly.

So based on the rather limited data available below 0 degC (I see the 2023 paper did not cite the data source I was citing in my previous reply, which was work from China in the 1980s), I don't know that we can say what the "right" answer is in this region to be able to judge if the REFPROP results are good or not.  It seems like 2 experimental sources agree with REFPROP pretty well, while this 2023 DSC paper and perhaps the Dow spec sheets do not.  Figuring out the right answer would at minimum take more careful digging into the various literature sources, which I don't have time for in the foreseeable future.

It is quite possible that REFPROP gets worse at low T, as perhaps evidenced by the larger deviation for the lowest-T point of the 1965 reference.  At that temperature, you are well below the freezing point of both pure components (EG freezing point seems to be about 260 K), so the EOS of each pure fluid is being extrapolated beyond the range it was fit.  I know that the water EOS gives pretty good Cp for supercooled liquid water down to maybe -30 degC; I have no idea whether any attention was paid to low-T extrapolation for the EG EOS.  I find some pure EG Cp data around 265 K where the EOS in REFPROP agrees within about 1%, but if you have to extrapolate both EOS things can get unreliable.

A relevant question would be whether any low-T mixture Cp data were used to fit the mixture model parameters for EG-H2O in REFPROP; if not, it would not be surprising if results were poor once you got considerably below the ranges of the pure-component EOS.  @ianhbell might know where the mixing parameters came from.  In general, mixtures with H2O in REFPROP are not as thoroughly fitted as mixtures involving things like natural gas and refrigerants.

**Comment by nist-aharvey** [comment]
Supplement:
There are some more recent adiabatic calorimetry data in this 2002 paper:
https://doi.org/10.1006/jcht.2002.0945
The data go down to 0 degC.
The mole fraction of 0.3033 in their Table 2 is 60 wt% and so can be compared directly to that 2023 paper.
The 2023 paper is systematically higher, for example giving 3.1346 at 0 degC compared to 2.9204 from the more reliable technique (REFPROP gives 2.989).  At 20 degC the 2023 paper gives 3.2628 while this 2002 paper gives 3.0710 (REFPROP gives 3.097).
This does not specifically help us evaluate REFPROP at subzero temperatures, but is another indication that the 2023 DSC data may not be accurate.

I do agree with the 2023 paper that heat capacities backed out from apparatus designed to measure thermal conductivity are of questionable value.

**Comment by Olaf987** [comment]
Allan:

Thank you for your elaborate answer putting things into perspective. This story starts to ring a bell. I have heard from a colleague that people in the heat measurement business are starting to question the numbers. Maybe this will lead to some better numbers in the future.

It proves again that just because numbers are published, they are not necessarily right!

Olaf
