### ISSUE TITLE
z array (composition array) definition

### ISSUE THREAD

**Issue by b3pe** [usnistgov/REFPROP-issues#630]
Can someone please point me to a reference or source for the definition of the composition (z) array for passing in a mixture to the refpropdll function?

**Comment by ianhbell** [comment]
I'm not sure I follow the question. The array passed in is either an array of mass fractions or mole fractions depending on the value of iMass argument.

**Comment by Olaf987** [comment]
b3pe:

I got confused by this last week as well so I decided to run some tests. I have REFPROP 10 and I used MATLAB which is calling the Python interface.

Assume a glycol-water mixture of weight fractions of z_mass = [0.8,0.2] which is equivalent to z_mole = [0.53725,0.46275]
If you call:
```matlab
i_mass = int8(1); % 0: molar fractions; 1: mass fractions
dummy = rp.REFPROPdll(mix_name,'TP','XMASS',i_units,i_mass,i_flag,T,p,z_mass);
```
You get nonsense. dummy.Output should return the same values as z_mass but that does not happen.

However if you call
```matlab
i_mass = int8(1); % 0: molar fractions; 1: mass fractions
dummy = rp.REFPROPdll(mix_name,'TP','XMASS',i_units,i_mass,i_flag,T,p,z_mole);
```
``dummy.Output`` returns z_mass and ``dummy.z`` also returns z_mass. This means that the z in the call is always MOLE-FRACTION

The output in z (dummy.z) depends on i_mass. When I call:
```matlab
i_mass = int8(0); % 0: molar fractions; 1: mass fractions
dummy = rp.REFPROPdll(mix_name,'TP','XMASS',i_units,i_mass,i_flag,T,p,z_mole);
```

``dummy.Output`` returns again z_mass but now dummy.z returns z_mole!

If you want to specify the concentration in mixture name, than it would have been:
"etylene glycol;water|0.8;0.2 mass" or "etylene glycol;water|0.53725,0.46275". In both cases you have to set the input z to zeros(20,0) in MATLAB or 20*[0.0] in Python.

So if you use z for input: MOLE FRACTION

Hope this helps a bit

Olaf

**Comment by b3pe** [comment]
I understand that the values are either mole or mass fractions. My question is there a specific order that the values need to be passed in. For example, z(0)=methane, z(1)=ethane, etc. In other words, how does the function know which fraction value applies to which component? Pls advise if you know.

**Comment by b3pe** [comment]
Thank you for your response.

My question is there a specific order that the values need to be passed in. For example, z(0)=methane, z(1)=ethane, etc. In other words, how does the function know which fraction value applies to which component? Pls advise if you know.

**Comment by ianhbell** [comment]
> Thank you for your response. My question is there a specific order that the values need to be passed in. For example, z(0)=methane, z(1)=ethane, etc. In other words, how does the function know which fraction value applies to which component? Pls advise if you know.

The order of component names matches the order of component fractions

**Comment by ianhbell** [comment]
> b3pe:
> 
> I got confused by this last week as well so I decided to run some tests. I have REFPROP 10 and I used MATLAB which is calling the Python interface.
> 
> Assume a glycol-water mixture of weight fractions of z_mass = [0.8,0.2] which is equivalent to z_mole = [0.53725,0.46275] If you call:
> 
> i_mass = int8(1); % 0: molar fractions; 1: mass fractions dummy = rp.REFPROPdll(mix_name,'TP','XMASS',i_units,i_mass,i_flag,T,p,z_mass);
> 
> You get nonsense. dummy.Output should return the same values as z_mass but that does not happen.
> 
> However if you call
> 
> i_mass = int8(1); % 0: molar fractions; 1: mass fractions dummy = rp.REFPROPdll(mix_name,'TP','XMASS',i_units,i_mass,i_flag,T,p,z_mole);
> 
> dummy.Output returns z_mass and dummy.z also returns z_mass. This means that the z in the call is always MOLE-FRACTION
> 
> The output in z (dummy.z) depends on i_mass. When I call:
> 
> i_mass = int8(0); % 0: molar fractions; 1: mass fractions dummy = rp.REFPROPdll(mix_name,'TP','XMASS',i_units,i_mass,i_flag,T,p,z_mole);
> 
> dummy.Output returns again z_mass but now dummy.z returns z_mole!
> 
> If you want to specify the concentration in mixture name, than it would have been: "etylene glycol;water|0.8;0.2 mass" or "etylene glycol;water|0.53725,0.46275". In both cases you have to set the input z to zeros(20,0) in MATLAB or 20*[0.0] in Python.
> 
> So if you use z for input: MOLE FRACTION
> 
> Hope this helps a bit
> 
> Olaf

I recommend to only ever use mole fractions. There are a number of bugs in REFPROP 10.0 with mass fractions, and you should therefore prefer to always use mole fractions. That is what I do and I don't run into problems.

**Comment by b3pe** [comment]
Actual never was resolved

**Comment by ianhbell** [comment]
Yes, for now the solution is use mole fractions. I know it is not the right resolution, but that's what we have to offer

**Comment by b3pe** [comment]
ok
