### ISSUE TITLE
Compute where derivatives d2T/dh2 and d2s/dh2 are equal to zero for mixtures (e.g. R454C)

### ISSUE THREAD

**Issue by crlaugh** [usnistgov/REFPROP-issues#631]
I would like to be able to compute the points where d2T/dh2 and d2s/dh2 are equal to zero at a given pressure for a given multicomponent mixture, such as R454C.  This usually occurs in the two-phase region, and the warnings in THERM and ALLPROPS indicate that the straightforward computation of derivatives using API calls in this region are not recommended.  I imagine that these points might be used in the iterative Helmholtz computations to bound iterations, but it is difficult to see where they would be in the Fortran code.  Is there any way to access such computations from the Fortran API (either high-level or low-level)?

**Comment by ianhbell** [comment]
No, but you can use the interface of CoolProp around REFPROP which supports all combinations of second partial derivatives. That's the only thing I can recommend.

**Comment by crlaugh** [comment]
Thanks for the quick response!  I'll ping you if I have trouble after I try this with Coolprop.
