### ISSUE TITLE
CO2 with trace compositions

### ISSUE THREAD

**Issue by gchoquet** [usnistgov/REFPROP-issues#632]
I have high quality shock tube data (performed by Botros et. al at NOVA Chemicals) of mostly CO2 with trace components of gases likely to be used in CCUS applications. Would this data be of value to NIST for the purposes of refining REFPROP?

**Comment by EricLemmon** [comment]
Yes, definitely!  Can you send a message to refprop@nist.gov and it will be forwarded to me.

**Comment by gchoquet** [comment]
I sent two reports today to your NIST email.

**Comment by EricLemmon** [comment]
Did you send them to Refprop@nist.gov?

**Comment by gchoquet** [comment]
No, I emailed them to your direct email address. One of them bounced as being too large.

**Comment by EricLemmon** [comment]
Can you send Marcia Huber a personal email to get in touch with me?  She's at Marcia.Huber@nist.gov
