### ISSUE TITLE
Unexpected convergence error in refrigerant+water mixture - [PHFLSH error 223]

### ISSUE THREAD

**Issue by rigojea-bh** [usnistgov/REFPROP-issues#634]
### Description

Hello NIST team,
 
I would like to share an inconsistent behavior I have observed with Refprop computations. 
On a refrigerant+water mixture, I am unable to compute an isenthalpic evolution between 1 state point describe by pressure and temperature, and the final state point at given pressure. When iterating by hand on temperature, I can find a solution, but this is inconvenient to implement in the code that calls the Refprop DLL.

### Steps to Reproduce

1. Define New Mixture
2. Add components R1234ze(E) and Water
3. Insert molar fractions 0.98188 (R1234ze) and 0.018116 (water)
4. Ok then confirm on error 117 (mixing parameters estimation), click ok again
5. Select Units: °C for temperature and bar for pressure
6. Choose Calculate option "Specified State Points"
7. Run T=15°C and P=1 bar to get H value: 405.53 as first calculation
8. Impose P = 7 bar and H = 405.53 kJ/kg to model an isenthalpic transformation

**Expected behavior:** Computation should find a solution at about 28.15°C. I can check that this solution is there if imposing P = 7 bar and T = 28.15°C, I get H =  405.53 kJ/kg

**Actual behavior:** [PHFLSH error 223] Bubble point calculation did not converge.

### Versions

**REFPROP Version:** NIST Standard Reference Database 23, DLL version number 10.0
**Operating System and Version:** Windows 10, Version 22H2 (OS Build 19045.4046)
**Access Method:** Running the Refprop desktop application  

### Additional Information

Screenshots

![image](https://github.com/usnistgov/REFPROP-issues/assets/91125167/fb1e3a6b-b7f9-4f81-8b2b-6e1d95421309)

![image](https://github.com/usnistgov/REFPROP-issues/assets/91125167/ece4d360-ee67-49c6-85aa-6839adc4e4bd)

![image](https://github.com/usnistgov/REFPROP-issues/assets/91125167/aa48b967-4e08-4a2f-8231-e3e1f680854f)

**Comment by ianhbell** [comment]
You cannot do calculations with refrigerant+water like this. You should have received an error code when you initialized this mixture, and that is the end of your journey; REFPROP does not support such a system.
