### ISSUE TITLE
Water at constant enthalpy not converging.

### ISSUE THREAD

**Issue by mclaas** [usnistgov/REFPROP-issues#635]
### Description
When calculating properties for water at a constant enthalpy, at or above 1700 kPa the tool fails to converge for real points.

### Steps to Reproduce
Using the GUI:
```
2: Water: Specified state points

      Temperature  Pressure     Density      Volume       Enthalpy     Entropy      
      (C)          (kPa)        (kg/m^3)     (m^3/kg)     (kJ/kg)      (kJ/kg-K)
                                                                       
1     16.000       5000.0       1001.2       0.00099879   71.927       0.23814      
2     17.040       500.00       998.96       0.0010010    72.000       0.25393      
3     16.000       4024.4       1000.8       0.00099924   71.000       0.23831      
4     16.000       1700.0       999.69       0.0010003    68.789       0.23869      
5     17.000       1700.0       999.52       0.0010005    72.970       0.25313      
6     16.500       1700.0       999.60       0.0010004    70.880       0.24592      
7     16.600       1700.0       999.59       0.0010004    71.298       0.24736      
8                       1700.0                                             71.298                     <--ERROR
```
However if the "Pressure" column is set to 1700 and the "Enthalpy" column is set to 71.298 the tool does not converge and no values are displayed.
     
**Expected behavior:** 
Column 7 and 8 calculate the same.

**Actual behavior:** 
Column 8 fails to calculate

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 11
**Access Method:** GUI 

### Additional Information
![Water Calc Error](https://github.com/usnistgov/REFPROP-issues/assets/38664621/53f38651-e998-417f-84e6-6f38c
[Water Calc Error.txt](https://github.com/usnistgov/REFPROP-issues/files/14886709/Water.Calc.Error.txt)
adfc11e)

If possible, please post examples and/or screenshots of the issue. (attached)

**Comment by ianhbell** [comment]
Can you email me and I can give you access to the beta? It should help with this problem I think.

**Comment by ianhbell** [comment]
sorry, email: ian.bell@nist.gov
