### ISSUE TITLE
Relative density: Reference temperature and pressure

### ISSUE THREAD

**Issue by philip-lindner** [usnistgov/REFPROP-issues#636]
### Note
This not not a description of a bug. Instead, I am missing information, that I could not find in the documentation.

### Description
I would like to use the property "RDAIR" (relative density in air) of a gas mixture. 

I assume that this is the density of the mixture at a specific reference pressure and temperature, divided by the density of air at the same reference conditions. 

My Question is now: Which reference condition (pressure and temperature) are used?

I was not able to find this information on the FAQ, in other issues on gituhb, or in the documentation.

**Comment by EricLemmon** [comment]
It depends on where you intend to use the value.  In the US natural gas industry, it is generally 60 F and 14.73 psia.  For the same industry in Europe, it is 15 C and 0.101325 MPa.  Scientific applications often use 25 C and 0.101325 MPa.

**Comment by philip-lindner** [comment]
Thank you for the quick reply! The different conventions are indeed the background of my question. In principle, the value of "RDAIR", calculated at 15 C can be different from the value of "RDAIR" at 25 C, right? Although  in reality, I would expect the differences to be very small.
Can you tell me which values are used by the REFPROP code? Is there an option to change the pressure/temperature values?

**Comment by EricLemmon** [comment]
After looking at the code, I realized that the values given are the ideal gas relative densities with a reference state equal to the same value of temperature as your input value.  In the calculation, the temperature and pressure cancel out and you are left with only the ratio of the densities, which for an ideal gas would be the ratio of the molar masses!  Thus, the relative density is simply the molar mass of your fluid divided by 28.9625 g/mol.

**Comment by philip-lindner** [comment]
Thank you for this important information! In this case, I will calculate the real-gas relative density manually.
