### ISSUE TITLE
R1234ze(E)

### ISSUE THREAD

**Issue by Laur75** [usnistgov/REFPROP-issues#637]
Hello,
I just update from 9.1 version to 10.

I notice that 134ze(E) does not appear in the "Pure Fluid (single compounds)" list. Is this normal since it should appear in the FAQs consulted.

**Comment by Laur75** [comment]
Sorry, I wanted to write R1234ze(E)

**Comment by ianhbell** [comment]
If you turn on all fluids I believe it appears

**Comment by ianhbell** [comment]
Yes with all fluids it appears, but not with common fluids. I think this is a bug,

**Comment by Laur75** [comment]
Thank you,

Yes I found it.

Regards

De : Ian Bell ***@***.***>
Envoyé : vendredi 26 avril 2024 14:37
À : usnistgov/REFPROP-issues ***@***.***>
Cc : Laurent CAVACO ***@***.***>; Author ***@***.***>
Objet : Re: [usnistgov/REFPROP-issues] R1234ze(E) (Issue #637)


Yes with all fluids it appears, but not with common fluids. I think this is a bug,

**Comment by Laur75** [comment]
Thank you
Yes it's work.

**Comment by Laur75** [comment]
yes it works
Thank you
