### ISSUE TITLE
Subroutine RPVersion is not giving correct REFPROP working version in 10.0

### ISSUE THREAD

**Issue by msuresh20** [usnistgov/REFPROP-issues#64]
Hello NIST team,

We are calling RPVersion() subroutine to fetch the current working version of refprop.dll.

This subroutine is working properly in earlier versions 9.1, 9.4.4  - not working in 10.0 version.

Can you please look into this issue.

Regards,
Suresh.

**Comment by EricLemmon** [comment]
This bug has already been fixed, if you would like an update, please contact us (eric.lemmon@nist.gov)

**Comment by msuresh20** [comment]
Received the updated dll and tested. After using the latest dll, i was able to get the correct working version of REFPROP.
Thank you.
