### ISSUE TITLE
Excel calculation of propylene-hydrogen mixture in two phase area

### ISSUE THREAD

**Issue by StefanNovo** [usnistgov/REFPROP-issues#640]
Hello, I am having an issue when calculating a propylene-hydrogen mixture in the two-phase area using the Excel wrapper.

Inputs
Molar composition
Propylene: 0.975
Hydrogen: 0.025
T: 333.15 K
p: 2.9 MPa

Outputs
Density based on T, p: 181.62 kg/m3
Enthalpy based on T, p: 426.1 kJ/kg
Density based on H, p: 359.17 kg/m3

The density output based on T,p is consistent with other outputs. However, I am interested in calculating properties based on H,p as inputs.

With a propylene-ethylene mixture (composition 0.9, 0.1; also in two-phase area) the issue does not exist.

Versions:
REFPROP 10
Windows 10
Excel wrapper
I have activated iFlag option in the REFPROP.XLA file, it did not make a difference.

Thanks for your help! I can provide the Excel file if required.

**Comment by ianhbell** [comment]
The thermodynamic model for propylene+hydrogen should not be trusted. It is based on an estimation scheme. Furthermore, the thermodynamics for such asymmetric mixtures are wildly different than propylene+ethylene.
