### ISSUE TITLE
The solution to add a new working fluid in REFPROP?

### ISSUE THREAD

**Issue by yplakaka** [usnistgov/REFPROP-issues#641]
Hi, is there a way to add new fluids and add relevant thermodynamic data in REFPROP?

**Comment by ianhbell** [comment]
Can you please say a bit more about what kinds of fluids you want to add? The answer is probably no since REFPROP implements the most accurate multiparameter EOS models, and REFPROP already includes almost all of them that have been published so far.

**Comment by yplakaka** [comment]
Haha, Just curious. For now there is no additional fluids I want to add. Thank you///(^v^)\\\
