### ISSUE TITLE
Concentration at equilibrium state of Ammonia water

### ISSUE THREAD

**Issue by JulianRodriguez10** [usnistgov/REFPROP-issues#642]
I need to calculate the concentration of the liquid and gas phase for a mixture of ammonia - water in a state of saturation (The mixture is in equilibrium). The starting data are the pressure and temperature of the mixture.

I'm looking to do this by making the call from Python.

REFPROP Version: Version 10
Operating System and Version: Windows 11
Access Method: Python

**Comment by ianhbell** [comment]
Please read the documentation: https://refprop-docs.readthedocs.io/ . Python info here : https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

**Comment by JulianRodriguez10** [comment]
Hi ianhbell, I have considered that the most appropriate thing is to use the SATTPdll subroutine, however I have not been able to implement it because it requires more variables in addition to pressure and temperature.

**Comment by ianhbell** [comment]
Please read the documentation on the ABFLSH and REFPROP functions.

**Comment by JulianRodriguez10** [comment]
I have been reading the documentation, however I cannot find the right way to address my problem.

**Comment by ianhbell** [comment]
You want TP as your inputs to the REFPROPdll function.

**Comment by JulianRodriguez10** [comment]
Hi, I understand how to use the REFPROPdl function, however, it requires the composition of the mixture to be able to perform the respective calculations.

r = RP.REFPROPdll(Fluid,'TP','D,H,S',RP.MASS_BASE_SI, 1,0,300, 2000e3,[0.85, 0.15])
print(r.Output[0:3])

I need to calculate for a state of equilibrium, the mass fraction of ammonia in the liquid phase, as a function of temperature and pressure, as shown in the image. From what I understand so far, I could not perform this calculation using the REFPROPdll function

![Imagen1](https://github.com/usnistgov/REFPROP-issues/assets/165821331/a949f33d-140c-43c6-a332-ef9dd945ef2d)

**Comment by ianhbell** [comment]
REFPROP does not have such functionality, you need to specify the bulk composition and the vapor quality and either temperature or pressure, or you need to iterate yourself to find the right composition (what I would recommend).

**Comment by JulianRodriguez10** [comment]
OK, thanks a lot.

What I will do then is:

Starting from a pressure Po and To

1. Specify an initial concentration x
2. Define the desired pressure P=Po
3. Define a quality Q=0
4. Determine the temperature T=Ti
5. Iterate until the value of Ti=To is reached

Would this be a correct procedure?

**Comment by ianhbell** [comment]
Yes that sounds about right, but I would use a nonlinear solving routine in your programming environment to do this rootfinding problem for you.  Also, you will need to specify the Q value upfront (Q=1 for saturated vapor, Q=0 for saturated liquid).
