### ISSUE TITLE
R-514A Calculations

### ISSUE THREAD

**Issue by R-744** [usnistgov/REFPROP-issues#664]
I need to do R-514A calculations but can't find this refrigerant or R-1130E to make it in mixtures. Can you confirm it is impossible to evaluate R-514A in Refprops or a method of doing so please .
I'm using Refprop version 10 working in windows 10 using it in excel 365

**Comment by ianhbell** [comment]
There is an ECS model in:

Teraishi, R., Kayukawa, Y., Akasaka, R., Saito, K. Universal parameters of the extended
corresponding states (ECS) model for hydrofluoroolefin refrigerants.
Int. J. Refrigeration  131:33-40 (2021).

**Comment by ianhbell** [comment]
But that is all that we have given the experimental data currently available.

**Comment by ianhbell** [comment]
You can email me (ian.bell@nist.gov) for an implementation of that model that can be used in REFPROP.
