### ISSUE TITLE
REFPROP DLL Expired

### ISSUE THREAD

**Issue by grgrynlds** [usnistgov/REFPROP-issues#665]
I'm getting Error 777: 
The REFPROP DLL you are using has expired (Version 10.0.0.98a... ). Please return to the Refprop website and download the latest installer. 

I'm seeing others having this error, and the solution seems to be a personal email for a link to the current DLL.  

Thank you,
Greg

**Comment by ianhbell** [comment]
Correct: ian.bell@nist.gov

**Comment by grgrynlds** [comment]
Hi Ian, I also sent directly to your nist email... Not sure which is
preferred or if it makes a difference.

I don't understand why the DLL expired. My license is valid. Could this
happen again? Usually I'm working from my office, but sometimes I'm in the
field (like next week) when it would be a bit inconvenient. I'd have to
read P-H charts! Oh my.

Greg


Greg Reynolds, PhD, PE              903-424-5293         ***@***.***
Integrated Engineering & Testing Services
￼

**Comment by ianhbell** [comment]
Please send me a direct email to the address above. The expiry only applies to development versions, the v10.0 DLL never expire.

**Comment by grgrynlds** [comment]
OK, sent that direct email to your NIST address last night.
Thanks,
Greg

**Comment by ianhbell** [comment]
Got it, was in spam

**Comment by grgrynlds** [comment]
Hi Ian, I still have the same DLL Expired issue with the updated Beta DLLs at the link that you sent. 

I see that the REFPRP64.DLL at the link you sent is the same size (3,261 KB) as one I found online (at https://trc.nist.gov/refprop/10-BETA/REFPROP.HTM) that said, "Last updated: February 17, 2022". 

Can I just go back to the most recent non-beta?

Thanks,
Greg

**Comment by ianhbell** [comment]
Then you have multiple copies of REFPROP installed on your machine. Search your machine for ALL copies of REFPROP.DLL on your machine and delete them. Then, and only then, replace with the beta installed from the link. If you have 10.0.0.78, that is a clear indication you have another REFPROP.dll living somewhere

**Comment by grgrynlds** [comment]
OK, that worked.  I had various copies in Downloads and some documentation folders... and in \MIXTURES for some reason.  

Thanks much, I'm up and running.
Greg

**Comment by Rishu2425** [comment]
I am getting the same error. 
I am trying to install RefProp in Python, but  I am getting the following error:

"The REFPROP DLL you are using has expired. Please return to the Refprop website and download the latest installer."

We have a licensed version of RefProp, but I don't know why I am getting this error. Kindly, help me with this

**Comment by ianhbell** [comment]
@Rishu2425 what precise version of REFPROP do you use? It sounds like an old beta release if it is expired. The current beta should expire in two weeks

**Comment by Rishu2425** [comment]
I use a licensed version of RefProp 10.0.0.0.
