### ISSUE TITLE
 Inconsistent results if the order of the components is different

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#667]
### Description

The thermodynamic properties are inconsistent if the order of the components is different. The example case is having a mixture of hydrogen/o-hydrogen/p-hydrogen.

### Steps to Reproduce

1. Add components hydrogen/o-hydrogen/p-hydrogen and specify Mole Fraction 0.0/0.5/0.5. Calculate density at bubble point.
2. Define a new mixture and add components o-hydrogen/p-hydrogen/hydrogen and specify Mole Fraction 0.5/0.5/0.0. Calculate density at bubble point.
3. Observe these two use cases are producing different values of thermodynamic properties.

**Expected behavior:** Regardless of order of the components, results should be same.

**Actual behavior:** Results are different if component order is changed.

### Versions

**REFPROP Version:** REFPROP 10.0
**Operating System and Version:** Windows 10 Enterprise
**Access Method:** REFPROP software 

### Additional Information

A screenshot is attached.
![download](https://github.com/usnistgov/REFPROP-issues/assets/174985347/44354947-0aaf-4ba9-bb71-2b9d52c74136)

**Comment by ianhbell** [comment]
Yes this is a known issue (please search the issues). Please email me (ian.bell@nist.gov) for a beta that fixes this problem.

**Comment by ghost** [comment]
The beta build is requested via email. Thanks.
