### ISSUE TITLE
Viscosity and thermal conductivity is not calculated for ortho hydrogen, while it gets calculated for para hydrogen

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#668]
### Description

Viscosity and thermal conductivity calculations are missing in ORTHOHYD.FLD; however, these calculations are available in PARAHYD.FLD.  I am curious to know why ortho hydrogen is missing these properties. What would be the possible solution for this issue.

### Steps to Reproduce

1. Add components o-hydrogen and observe viscosity and thermal conductivity are calculated
2. Add components p-hydrogen and observe viscosity and thermal conductivity are not calculated

**Expected behavior:** Viscosity and thermal conductivity should be calculated for o-hydrogen.

**Actual behavior:** Viscosity and thermal conductivity are not calculated for o-hydrogen.

### Versions

**REFPROP Version:** REFPROP 10.0
**Operating System and Version:** Windows 10 Enterprise
**Access Method:** REFPROP software

### Additional Information

Screenshot is attached.
![thumbnail_image004](https://github.com/usnistgov/REFPROP-issues/assets/174985347/f5534d22-3afd-425e-8ebb-a05f4faa5741)

**Comment by ianhbell** [comment]
At the time we took a conservative approach given the data availability for otho hydrogen and didn't include any model. Are you aware of experimental data for pure orthohydrogen? (As an aside, this is quite unlikely due to the ortho/para conversion issue; you essentially never have pure orthohydrogen)

**Comment by nist-aharvey** [comment]
As @ianhbell mentions, pure ortho-hydrogen doesn't really exist.  If you need it to make up a specific ortho-para mixture, it would be reasonable for most engineering purposes to use the correlation for normal hydrogen to describe ortho-H2. [I don't know the details of REFPROP well enough to know whether that would be easy or hard to do in the FLD file.] That could maybe get you into trouble if you were near the critical point (especially for thermal conductivity), but at other conditions I think it should be a pretty good approximation.
[You can get some idea of how big the differences are likely to be by comparing the transport properties for normal H2 to those for para-H2.]

**Comment by ghost** [comment]
If these properties are not calculated for non-existing ortho hydrogen, there is no problem. The problem arises when these properties are not calculated even for mixture of ortho and para hydrogen (which exists in nature). 

![transportproprefprop](https://github.com/user-attachments/assets/83b9db88-87eb-43f8-bb1c-10ea2238ba94)

Hence, if the transport properties calculation is missing for either of the fluid in a mixture, the property for the mixture is not calculated. This is a concern.

**Comment by nist-aharvey** [comment]
In addition to my suggestion above, I would note that any physically occurring composition of ortho/para hydrogen could be constructed by combining "normal" hydrogen (which is 75% ortho) and para-hydrogen.  You'd have to do a bit of arithmetic behind the scenes to figure out the appropriate mixture of those 2 compositions, but that would provide a way to calculate the mixture transport properties.
In the example you pasted in, the distribution of spin states is exactly that of normal hydrogen, so no need to model it as a mixture at all.
