### ISSUE TITLE
methanol/water mixture

### ISSUE THREAD

**Issue by DarshVader23** [usnistgov/REFPROP-issues#669]
[Description of the issue]

Not sure if i have done something wrong but i wanted to determine the denisty of methanol/water mixtute which is 40% w/w methanol at 20°C .  THe mixture density is different to other literature that says it should be  934 kg/m3 instead i get 926 kg/m3

### Steps to Reproduce

Go to subtance and select "define new mixture"
Select methanol and water
select mass fraction and set methanol at 0.4 and water at 0.6
go to calcaute and select "specified sate points"
Enter 20°C and 0 barg.

**Expected behavior:** [What you expect to happen]
I expect to see the density to be 934 kg/m3 which is the expermental data as shown in coulson and richardson vol6 p315, 4th edition.

**Actual behavior:** [What actually happens]
The result show the density is 926 kg/m3

### Versions

**REFPROP Version:** version 10, reference database 23
**Operating System and Version:** Windows 10
**Access Method:** through NIST software

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![MetWat](https://github.com/usnistgov/REFPROP-issues/assets/127499255/39dffcf2-6d96-4e4a-98ec-32780606f7fa)

**Comment by ianhbell** [comment]
What mixture model is being used for methanol/water? I don't know if it is reference-quality, so some deviations are to be expected. Also, one should not accept experimental data uncritically without comparison with other newer more accurate measurements (where possible)
