### ISSUE TITLE
Water properties calculation issue with PH as input parameters in subcooled region

### ISSUE THREAD

**Issue by ishceyhan** [usnistgov/REFPROP-issues#67]
I am using REFPROP 10 with Excel.  I am having a problem with PH convergence in the subcooled region.    Please see the attached Excel file for an illustration.

The specific problem is calculating properties at the following point:
P=6.103 MPa
T=313.15K=40°C
rho=994.83 kg/m3
h=172.93 kJ/kg
s=0.5700 kJ/kg/K
At this temperature, Psat=0.0074 MPa, so the state is subcooled liquid.

If I specify T and P as inputs (case A in attached file), I get the correct results.
If I specify P and H as inputs (case B), the T calculation doesn't converge, and the rho and s values that are returned seem to be incorrect.
If I specify T and rho (case C), I get the correct results.
If I specify h and s (case D), I get the correct results.

I would appreciate i you could look into this.  

Thank you!

[Refprop_10_Issue.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2559864/Refprop_10_Issue.xlsx)

**Comment by EricLemmon** [comment]
We have a new beta version of the DLL that most likely has fixed this, please contact us directory to obtain it (eric.lemmon@nist.gov)

**Comment by ishceyhan** [comment]
The 10.0.0.2 version of the DLL solved the problem.  Thank you.

**Comment by EricLemmon** [comment]
If this issue has been resolved, could you close this issue?
