### ISSUE TITLE
Ammonia Mixtures

### ISSUE THREAD

**Issue by eric-hintz** [usnistgov/REFPROP-issues#671]
### Description

I am using an HMX.bnc file provided to me by the Refprop team instead of the standard release version in order to model mixtures containing ammonia. If the Refprop team allows it/requests it, I can provide that file here, but since it is not the standard release version, I won't share it without the team's explicit permission.

Using this file for ammonia mixtures, I have noticed some odd behavior. To illustrate the issue, I have included some figures I made as a (very basic) investigation into what’s going on. To create the figures, I made an initial Ammonia, Nitrogen, and Hydrogen mixture of 0.3 mol Hydrogen, 0.1 mol Nitrogen, and 0.02 mol Ammonia. I then calculated the enthalpy of the mixture while varying the mole amounts stoichiometrically with the Ammonia synthesis reaction (N2 + 3H2 -> 2NH3), essentially varying the concentrations of the components. I then did the same for all three binary pairs in the mixture using the same molar flows from calculating the total mixture. All of this was done at a constant temperature and pressure of 750 K and 20 MPa (normal inlet conditions for a Haber-Bosch reactor).

![N,H,NH3 Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/be5055d8-78e8-4f25-8408-834bd43f74a3)
![N,NH3 Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/1b915a2c-e5c7-4106-b42d-23c4986428e8)
![H,NH3 Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/d02452bc-4697-49d1-8722-8075af129d52)
![N,H Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/0465123b-9674-42d7-b2a3-f1b080c5b515)

As the figures show, in certain concentration bands, the enthalpy drops to -9999990.0, which is of course the error value. This occurs in any of the ammonia containing mixtures, and not the nitrogen and hydrogen mixture. Obviously, this is not a complete thorough analysis of all the problems that could occur. For example, I believe similar problems happen when varying temperatures at a constant concentration and pressure. I also assume this to be an issue with other ammonia containing mixtures, but again, I'm not sure.
 
Another oddity I have noticed, though not documented, is that it sometimes occurs that I can calculate the enthalpy of an ammonia mixture at a given temperature, and then, if I use that enthalpy to calculate the temperature at the same pressure, I get a different temperature than I started with. Then, I get a different enthalpy than I calculated the first time using this temperature. However, the cycle stops here, and the calculation is perfectly reversible at this new temperature/enthalpy. If I instead calculate the enthalpy from the REFPROP GUI and use the DLL to calculate the temperature, the same issue occurs. 
 
What is especially odd about this issue is that if I repeat the step where I input the correct enthalpy and get the wrong temperature many times, it does sometimes output the correct temperature. In fact, if I, for example, calculate the temperature 10 times and print out an array of the results, one of those will usually be correct. If I repeat running the code, the correct answer will remain in the same exact position in the array. However, if I copy and paste that code to a different location in the file or another file and run it again, the position of the correct answer will change. I have replicated this behavior on three computers now, so I don’t believe it to be an odd hardware issue or something along those lines. If needed, I can document this problem more thoroughly, so please let me know.

### Versions

**REFPROP Version:** 10.0 
**Operating System and Version:** Windows 10 and Windows 11 
**Access Method:** Python wrapper

### Additional Information

Code used for figure generation:
```python
# -*- coding: utf-8 -*-
"""
Created on Tues July 2 5:35:00 2024

@author: erich
"""

from Stream_Object import *
import numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
import os
import matplotlib.pyplot as plt

os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
unit = RP.GETENUMdll(0, 'MOLAR SI')[0]
fluids = ['NITROGEN','HYDROGEN','AMMONIA']

m_n = 0.1 #mol/s
m_h = 0.3 #mol/s
m_a = 0.02 #mol/s

f = 100
n_rng = np.arange(0,0.1,.1/f)
h_rng = np.arange(0,0.3,.3/f)
a_rng = np.arange(0,0.2,.2/f)

n = -n_rng + m_n
h = -h_rng + m_h
a = a_rng + m_a

fluidid = ';'.join(fluids)

H = [RP.REFPROPdll(hFld=fluidid,hIn='TP',hOut='H',iUnits=unit,iMass=0,iFlag=1,a=750,b=20,z=np.array([mn,mh,ma])/np.sum(np.array([mn,mh,ma]))).Output[0] for mn,mh,ma in zip(n,h,a)]
x = np.linspace(0,100,100)
fig, ax = plt.subplots()
ax.plot(x,H)
ax.set_title('Nitrogen, Hydrogen, and Ammonia Mixture Enthalpy vs Nitrogen Conversion in Ammonia Synthesis Reaction')
ax.set_ylabel('Fluid Mixture Enthalpy (J/mol)')
ax.set_xlabel('Nitrogen Conversion (% on mole basis)')
plt.show()

H = [RP.REFPROPdll(hFld=fluidid,hIn='TP',hOut='H',iUnits=unit,iMass=0,iFlag=1,a=750,b=20,z=np.array([mn,mh])/np.sum(np.array([mn,mh]))).Output[0] for mn,mh in zip(n,h)]
x = np.linspace(0,100,100)
fig, ax = plt.subplots()
ax.plot(x,H)
ax.set_title('Nitrogen and Hydrogen Mixture Enthalpy vs Nitrogen Conversion in Ammonia Synthesis Reaction')
ax.set_ylabel('Fluid Mixture Enthalpy (J/mol)')
ax.set_xlabel('Nitrogen Conversion (% on mole basis)')
plt.show()

H = [RP.REFPROPdll(hFld=fluidid,hIn='TP',hOut='H',iUnits=unit,iMass=0,iFlag=1,a=750,b=20,z=np.array([mn,ma])/np.sum(np.array([mn,ma]))).Output[0] for mn,ma in zip(n,a)]
x = np.linspace(0,100,100)
fig, ax = plt.subplots()
ax.plot(x,H)
ax.set_title('Nitrogen and Ammonia Mixture Enthalpy vs Nitrogen Conversion in Ammonia Synthesis Reaction')
ax.set_ylabel('Fluid Mixture Enthalpy (J/mol)')
ax.set_xlabel('Nitrogen Conversion (% on mole basis)')
plt.show()

H = [RP.REFPROPdll(hFld=fluidid,hIn='TP',hOut='H',iUnits=unit,iMass=0,iFlag=1,a=750,b=20,z=np.array([mh,ma])/np.sum(np.array([mh,ma]))).Output[0] for mh,ma in zip(n,a)]
x = np.linspace(0,100,100)
fig, ax = plt.subplots()
ax.plot(x,H)
ax.set_title('Hydrogen and Ammonia Mixture Enthalpy vs Nitrogen Conversion in Ammonia Synthesis Reaction')
ax.set_ylabel('Fluid Mixture Enthalpy (J/mol)')
ax.set_xlabel('Nitrogen Conversion (% on mole basis)')
plt.show()
```

**Comment by ianhbell** [comment]
a) What error do you get where you get errors?
b) Regarding the non-repeatability, I'd like you to try with the beta, we have fixed some uninitialized memory issues which might be what you are seeing here. Please email me (ian.bell@nist.gov) for a copy of the beta.

@nist-aharvey This general approach should be fine, right? There is nothing physically amiss that you can see aside from likely failures in iterative routines?

**Comment by nist-aharvey** [comment]
I agree that this seems like convergence issues, at least mostly.  One should be able to calculate H(T,P) and then get back to the original T with T(P,H).  If this puts you in the 2-phase region I expect convergence might be more difficult.
The issue mentioned in the last paragraph, where repeat calculations give inconsistent results, sounds like it could be a different bug.
It should also be noted that mixing GUI and DLL calculations for mixtures is dangerous, because the default reference state for enthalpy is different between the two.

**Comment by eric-hintz** [comment]
Thanks for the responses!

> a) What error do you get where you get errors?

No error is actually thrown, I just get a result of -9999990.0 for whatever property I am trying to calculate.


> Please email me ([ian.bell@nist.gov](mailto:ian.bell@nist.gov)) for a copy of the beta.

Will do, thank you!


> If this puts you in the 2-phase region I expect convergence might be more difficult.

Certainly not saying that your assessment otherwise is wrong, but just for diagnostics sake, the fluid would have to be many hundreds Kelvin cooler for any one of the components in the mixture to begin condensing. From what I understand and my experiences trying to get some implementations of cubic EOSs to function properly, however, convergence for this mixture is indeed a common problem.


> It should also be noted that mixing GUI and DLL calculations for mixtures is dangerous, because the default reference state for enthalpy is different between the two.

Good to know, thanks for the info. Typically my workflow hasn't involved any mixing of GUI and DLL use except for checking things like this, so I'll continue to keep away from it and take any comparisons with a grain of salt at least.


It is also worth noting that the only possible workaround I've found for this right now is implementing my own mixing parameters in CoolProp with the parameters being implemented here in REFPROP. However, I've found that CoolProp will only accept T, P, and Q inputs for the mixture, so I still need to write a small root-finding function to allow me to "directly" vary enthalpy in order to integrate it into my model. That being said, if I can find some time later today, I will try and repeat the process I used for the figures above using the CoolProp implementation and see what I find.

**Comment by eric-hintz** [comment]
Great news, I tried the beta @ianhbell sent me, and it seems to have worked! Here's the new figures generated in the same procedure as what I did in the original post:

![N,H,NH Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/4f53da7f-d327-4361-a4ed-6c30f244643f)

![N,H Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/af28675a-a081-49ae-acff-46216aa783cc)

![N,NH Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/3bf55c09-2b42-4c80-a5a2-83f2674e0a1f)

![H,NH Enthalpy vs Nitrogen Conversion](https://github.com/user-attachments/assets/3499af6d-3ba1-4e63-a844-dbf2956ae57f)

I will update again if I encounter any more issues (such as the non-repeatability), but otherwise, it seems to be working well.

**Comment by ianhbell** [comment]
Ok good, I guess we can close for now.
