### ISSUE TITLE
Inquiry on REFPROP coding in Excel to GERG-8

### ISSUE THREAD

**Issue by REFPROPBeginner** [usnistgov/REFPROP-issues#673]
Good day! I'm currently trying to link REFPROP to the Excel sheet. I was able to do it manually by incorporating the formula below:

![image](https://github.com/user-attachments/assets/47bccea4-35a8-429b-b55f-05c6a90172c1)

=REFPROP("D",FluidString10($C$3:$C$24,$E$3:$E$24),"TP","SI WITH C",$M$4,$M$5)

This is for the density only, but when I ran it in the software, I realized that Excel is calculating it using AGA-8. I wanted to use only GERG-8 to calculate the values, but I got confused with the instructions in the coding section in REFPROP10Code. It says here to use the formula below in the code, but I’m unsure where to type it out.

![image](https://github.com/user-attachments/assets/eb4c5a84-4a65-4eac-97d6-1885ea059e45)

Hoping for your assistance on this matter. Thank you and have a great day ahead!

**Comment by ianhbell** [comment]
By default REFPROP uses more accurate EOS than are in GERG-2008. If you want to use the GERG-2008 model, uncomment (remove the ' at the beginning of the line) in the VBA code you show

**Comment by REFPROPBeginner** [comment]
Thank you so much, Ian! It's working now, but may I ask if there's a possibility of the code reverting to another EoS suddenly if ever? I don't know if it's just my system, but there twice the instance where the values reverted to AGA-8 values? Thanks again!

**Comment by ianhbell** [comment]
AGA8 is never on by default, you need to explictly request it by a call to ``FLAGSdll`` or ``SETAGAdll``
