### ISSUE TITLE
.FLD files locked by Windows Defender

### ISSUE THREAD

**Issue by ericlamnguyen** [usnistgov/REFPROP-issues#675]
I have a program that makes several calls to SETUPdll during execution, occasionally, the SETUPdll call will returns error code 101 which was caused by the .FLD files being locked by Windows Defender which prevents REFPROP from reading the .FLD files.

We are thinking of white-listing REFPROP folder from Windows Defender to prevent it from locking up the FLD files, but I'd like to get your input into this issue and if there is a better solution available.

Thanks and regards,
Eric Nguyen

**Comment by ianhbell** [comment]
Sounds like you need to white-list as you propose

**Comment by ericlamnguyen** [comment]
Thanks for the feedback Ian!
