### ISSUE TITLE
P-h plots not plotting decimal values of Entropy

### ISSUE THREAD

**Issue by Daddownunder** [usnistgov/REFPROP-issues#676]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

P-h plots not plotting decimal values of Entropy

[Description of the issue]

### Steps to Reproduce

1. Open new P-h plot
2.set up parameters Entropy step 0.1
3. [and so on...]

**Expected behavior:** Expect a plot with Entropy plotted every 0.1 kJ/kg/K

**Actual behavior:** Plots every 1 kJ/kg/K

### Versions

**REFPROP 10.0 recently downloaded
**Operating System and Version:** Windows 11
**Access Method:** PC app

### Additional Information
Uninstalled REFPROP and reinstalled no effect

![image](https://github.com/user-attachments/assets/b140839e-0c4f-45b3-9cd8-fda275c37486)

![image](https://github.com/user-attachments/assets/3326a993-4c01-4532-971c-99179a586b26)

**Comment by ianhbell** [comment]
Did you also try 0.1 as the step?

**Comment by nist-aharvey** [comment]
This must have been fixed at some point; it works correctly with the December 4 2021 beta and DLL Version 10.0.0.98b, using exactly the same specs as in the example:

![image](https://github.com/user-attachments/assets/c05e8e78-d498-4cfe-9462-1bbaf1f9dedd)

Strangely, I cannot reproduce the bug in mini-REFPROP, which I would have expected to match REFPROP 10.0.
And I note that the plot and the Setup window in the report don't match each other (for example, the axis limits), which makes me wonder if there might have been a user error.

**Comment by Daddownunder** [comment]
This was not a problem until I changed over to Windows 11 and reinstalled REFPROP after having a problem with excel looking up properties

Dave Bond
+66 62 242 3837

**Comment by Daddownunder** [comment]
I have always used 0.1 as the step, this is when the issue appeared. It only appeared after I uninstalled REFPROP and reinstalled it because I was having an issue with getting properties in excel. The reinstallation fixed the excel issue but then the 1 step turned up even when I was using 0.1

Dave Bond
+66 62 242 3837

**Comment by ianhbell** [comment]
Sounds like a localization issue perhaps. Can you try 0,1 as your step?

**Comment by Daddownunder** [comment]
That solved it. The panel shows 0.1 but works with 0,1. What do I need to change in windows to prevent this issue?

**Comment by ianhbell** [comment]
Not sure; you'll have to do some googling. You are looking for something about decimal delimiter.

**Comment by nist-aharvey** [comment]
There is also a setting in REFPROP under Options, Preferences, for "Flip usage of commas and periods in numbers". You might see how that is set and try the other setting to see what happens.
Looking closely at the Setup window you pasted in, it looks like REFPROP is using commas for the decimal marker (for example, see the y-axis range that has a 0,5), so either that Preferences setting has gotten set or else your Windows thinks you are in continental Europe or some other place that uses the comma as the decimal marker. [You might try going into Excel and computing 1/2 to see how it writes the result.]

Edited to Add: In Windows 11, it appears that you get to the relevant settings via Settings ... Time & Language ... Language & Region.

**Comment by Daddownunder** [comment]
Firstly, I found out how to change the comma setting to a period in windows:
How to Change the Windows 11 List Separator: A Step-by-Step Guide - Support Your Tech<https://www.supportyourtech.com/tech/how-to-change-the-windows-11-list-separator-a-step-by-step-guide/>

Having done that tried to plot a p-h plot of CO2 using default settings:
***@***.***
Note all setting now with periods not commas in Entropy.
Get this plot with no Entropy plotting
***@***.***
Add decimal numbers in  Step in entropy
***@***.***
This gives this plot:
***@***.***
There is either something else affecting the plot in Windows 11 or a bug.

Thanks for the help at least I can get back to plotting p-h plots



Dave Bond
+66 62 242 3837

**Comment by ianhbell** [comment]
You'll need to use the web interface to attach the images

**Comment by Daddownunder** [comment]
Firstly, I found out how to change the comma setting to a period in windows:
[How to Change the Windows 11 List Separator: A Step-by-Step Guide - Support Your Tech](https://www.supportyourtech.com/tech/how-to-change-the-windows-11-list-separator-a-step-by-step-guide/)

Having done that tried to plot a p-h plot of CO2 using default settings:
 
![image](https://github.com/user-attachments/assets/7148d21c-f873-493d-bd4a-9e3383cfa1e5)

Note all setting now with periods not commas in Entropy. 
Get this plot with no Entropy plotting
 
![image](https://github.com/user-attachments/assets/198450ca-80e4-48f6-a1df-d8c12720dfb2)

Add decimal numbers in  Step in entropy
 
![image](https://github.com/user-attachments/assets/716261e2-80cf-4ce3-8570-84f6185cc9e4)

This gives this plot:
 
![image](https://github.com/user-attachments/assets/f2e88902-1961-47b4-b3eb-2203cfad236d)

There is either something else affecting the plot in Windows 11 or a bug.

Thanks for the help at least I can get back to plotting p-h plots
