### ISSUE TITLE
Unsupported fluids question

### ISSUE THREAD

**Issue by wandadars** [usnistgov/REFPROP-issues#679]
What is the approach that should be taken when trying to use data that isn't in the REFPROP fluid library? For example, I'm looking for fluid viscosity data in the species NO2,  which doesn't seem to be in the database. Is there a way to create a new fluid file and provide REFPROP with say, experimental values such that it can construct a model from those of the viscosity? Is this impossible? Is there a best-practice for such a situation?

Thank you,
-Chris

**Comment by nist-aharvey** [comment]
Others will have to address the other parts of your question (I think there is no simple way to do that in REFPROP), but I happened to search for NO2/N2O4 viscosity data a couple of years ago (a colleague wanted to develop a viscosity correlation, but I don't think he ever did), so I might as well share the references, which cover both the liquid and vapor. Excluding a couple of things that are over 100 years old, the sources are:
1) C.C. Addison and B.C. Smith, J. Chem. Soc. (London), 1783-1788 (1960).
2) O.V. Belyaeva et al., Dissotsiiruyushie Gazy Teplonoisiteli Rab. Tela Energ. Ustanovok, Pt. 1, 12-19 (1973).
3) I. Petker and D.M. Mason, J. Chem. Eng. Data 9, 280-281 (1964).
4) G.N. Richter et al., Ind. Eng. Chem. 45, 2117-2119 (1953).
5) D.L. Timrot et al., Teplofiz. Vys. Temp. 7, 885-892 (1969).

P.S. If you have NIST's ThermoDataEngine product:
https://trc.nist.gov/tde.html
it does have the ability to generate simple viscosity correlations based on input experimental data; I see that it has done so (based on the sources above, I think) for both vapor and liquid NO2. But TDE is more expensive than REFPROP ...

**Comment by ianhbell** [comment]
For NO2, you can either:
1) Use extended corresponding states, in predictive mode (grab a block from another fluid file using ECS)
2) Use the RES model in predictive mode: https://link.springer.com/article/10.1007/s10765-022-03096-9 (not yet implemented in REFPROP, but the code is in the SI of that paper)

**Comment by ianhbell** [comment]
I had in mind N2O which is in REFPROP already, rather than NO2, which is a reactive system (e.g., https://www.sciencedirect.com/science/article/pii/S2590174524000515). Sorry, they are easily confused.
