### ISSUE TITLE
Propane convergence close to critical point

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#684]
![image](https://github.com/user-attachments/assets/401b89df-abd0-4405-a340-3e16e2964fe1)

For pure fluid propane, I think I see convergence issues close to the critical point. In the GUI, select propane, then enter 

1. first row "crt"
2. second row density 219V or density 219 and quality 1
3. third row density 221L or density 221 and quality 0

Third row will give an error, but different one for the ways of specifying the same.

DLL version 10.0, even though I think I had a newer one in between.

**Comment by ianhbell** [comment]
Yeah, that's always tricky to do those calculations because the slope of the function to be solved goes infinite. The only super robust solution is to use the superancillary equations: https://pubs.aip.org/aip/jpr/article/53/1/013102/3270194
