### ISSUE TITLE
Issue with the correct value of Q using REFPROP function in Excel

### ISSUE THREAD

**Issue by NickPooleRSL** [usnistgov/REFPROP-issues#686]
### Description

Seems to be an error in using Q in the REFPROP function within Excel.

### Steps to Reproduce

Attached is an example Excel spreadsheet illustrating the issue.
Looking at the Calc tab.

Lines 31 and 32 show the mass fractions of a blend (specified in M3 and I27) at 35oC and with a quality of 0.5 and 0.46166 as generated by Refprop 10. Refprop was set to use SI with C as the units and Q, in the results, is in kg/kg. This data was generated from within the Refprop program using the Calculate -> Specified State Points option using a temperate of 35oC and a quality of 0.5 as the arguments to generate the data.

Cell K43 of the attached Excel spreadsheet shows a call to the REFPROP function to calculate the mass fraction of the 1st component in the blend (R32) at 35oC and with a quality of 0.5.

The function call in excel is specifying the arguments as 'TQ' i.e. has not specified if Q is measured by mass or by moles. However the function call can be adjusted to 'TQMASS', 'TQMOLE' and we get the same results.

**Expected behavior:** [What you expect to happen]

Expected the excel generated mass fraction of R32 (cell K43) to match that of the data generated directly from Refprop (cell R32).

**Actual behavior:** [What actually happens]

The values do not match. Slightly more strangly the value generated by the REFPROP function from within Excel using a Q of 0.5 matches that of the mass fraction generated directly within Refprop using a quality of 0.46166.

### Versions

**REFPROP Version:** [REFPROP version you are using] 
Refprop 10.0.0.98b
**Operating System and Version:** [OS you are running REFPROP on]  
Windows 11
**Access Method:** [How you are accessing RE
Excel Add-In
[2024_09_23 REFPROP quality anomaly.xlsx](https://github.com/user-attachments/files/17129603/2024_09_23.REFPROP.quality.anomaly.xlsx)

**Comment by ianhbell** [comment]
Strongly recommend to use mole fractions. While in general either should be possible, there are some bugs that only appear with the use of mass fractions. Can you do that and try again?

**Comment by NickPooleRSL** [comment]
Using mole fractions works!

**Comment by ianhbell** [comment]
Sigh; yes I need to add another test here it seems like.
