### ISSUE TITLE
PHFLSH error 248 - Oxygen & Helium

### ISSUE THREAD

**Issue by IdahoEngr** [usnistgov/REFPROP-issues#690]
### Description

I’m trying to simulate a cryogenic spacecraft propellant tank pressurization and propellant expulsion and getting an error that I can’t seem to get around.  I have an insulated tank with a volume of liquid oxygen and a volume of vapor containing oxygen and helium.

I’m calling REFPROP.dll function PHFLSH for a mixture of oxygen and helium and getting the following

[PHFLSH error 248] Single-phase iteration did not converge for P = 6.20527 MPa and H = 5935.08 J/mol.

The mixture is Oxygen:4.67%, Helium:95.33%
The call was made with P = 900.00[psi], & H = 480.5772[BTU/lbm]

When I tried to calculate the same in the user interface, I got the same result, but with a ‘do you wish to continue calculations?’ question.  However, saying yes didn’t help.
[PHFLSH error 248] Single-phase iteration did not converge for P = 6.20528 MPa and H = 5931.70 J/mol.                                                                                                                                                         

![image](https://github.com/user-attachments/assets/5b63c641-9852-42f7-9c1f-b0554293aa6c)

### Steps to Reproduce

1. open REFPROP GUI
2. Select Oxygen & Helium, then specify 4.67% & 95.33% mole fractions, respectively.
3. Calculate a state point with pressure = 900 psi and enthalpy = 480.5772 BTU/lbm

**Expected behavior:**

Should return state

**Actual behavior:**

PFLSH error 248

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 11 Pro, 23H2, 22631.4169
**Access Method:** C++ call to RefProp.dll and REFPROP GUI

**Comment by ianhbell** [comment]
For mixture flash calculations, about all that we can suggest is to make sure that saturation splines are enabled in the preferences. Doing iterative calculations for mixtures is very difficult to achieve in a close to 100% reliable fashion.

Unlikely this is the problem, but it is slightly more reliable to work in SI units with REFPROP because it avoids a layer of unit conversion code.

**Comment by nist-aharvey** [comment]
A crude workaround in your case could be to do some iteration on your side, performing P-T flashes with REFPROP and varying the temperature until you meet the enthalpy criterion.  P-T flashes typically converge more easily than P-H flashes.
But in general mixture flash calculations are hard to converge when the components differ greatly in volatility, especially if you are in or near the 2-phase region.

**Comment by IdahoEngr** [comment]
Is there a way to enable the saturation splines for the DLL, or is that just in the GUI?

**Comment by ianhbell** [comment]
Indeed. You want to use the SATSPLNdll function, or look at the iFlag in the REFPROPdll high-level interface. Docs here: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SATSPLNdll and https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

**Comment by IdahoEngr** [comment]
Thanks ianhbell, I will try that.

What are the 'basic' properties that REFPROP uses when calculating the properties?  If both enthalpy and temperature require a search, then what properties are used to find them?  I guess I could figure that out in the FORTRAN code, but I haven't used FORTRAN much in 40 years.

Also, since both fluids are at a supercritical pressure @ 900 psi, how does having the saturation curves help the search?

**Comment by ianhbell** [comment]
The EOS is explicit in temperature and density so the iteration is for temperature and density.

The solver doesn't have any idea where the phase envelope is until it figures it out, and that knowledge is useful for the iterative routines. Maybe not a panacea, but often (but not always) helps.

**Comment by IdahoEngr** [comment]
Thanks again, ianhbell.
