### ISSUE TITLE
use refprop by matlab calculate Q with negative valve

### ISSUE THREAD

**Issue by yplakaka** [usnistgov/REFPROP-issues#693]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[Hello , I am using refprop by matlab to calculate some valves, I met some problems when I was trying  to calculate mixed refrigerants vapor fraction ,It showed a negative valve. and I also tried use refprop via python, the same negative valve showed]

### Steps to Reproduce

1. [T_1=373.15;%K]
2. [P_1=19936;%kPa]
3. [Q_1=refpropm('Q','T',378.15,'P',P_1,'R134a','R245FA',[0.38376, 0.61624]);]

**Expected behavior:** [It should be 0.424]

**Actual behavior:** [the result calculate was -998]

### Versions

**REFPROP Version:** [REFPROP 10.0]  
**Operating System and Version:** [windows 10]  
**Access Method:** [matlab]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
If I remember correctly ``refpropm`` uses mass fractions? I recommend to only use molar fractions although mass fractions are technically supported, there are a few bugs that are related to the use of mass fractions.

**Comment by yplakaka** [comment]
<img width="441" alt="image" src="https://github.com/user-attachments/assets/2e3ce57d-1950-4b7f-b861-1d02e26ad2d3">
I checked the refprop DLL documentation. The reason of negative valve is that refprop thinks it is a Subcooled liquid, but quality not defined (usually P > Pc)
https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html

**Comment by ianhbell** [comment]
Can you please confirm whether your compositions are mass or molar? Have you enabled the saturation splines? You should; it helps sometimes, but not always.
