### ISSUE TITLE
Reproduce REFPROP UI values when calculating the 2-phase state properties of mixtures

### ISSUE THREAD

**Issue by renjie-github** [usnistgov/REFPROP-issues#694]
### Description
I'm trying to calculate the properties of mixtures that in 2-phase region (temperature glide region) and I want to reproduce those properties in Python to get the same values as what shown in the REFPROP UI.
Take density for example. In the REFPROP UI, there should have 3 columns which correspond to the bulk (overall) density, vapor phase density and liquid phase density. But with Coolprop or REFPROP, I can only get the bulk value. How to also get the vapor phase and liquid phase density?

### Steps to Reproduce
```Python
import os
os.environ['RPPREFIX'] = "fill in here"
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
RP.GERG08dll(len(COMPONENTS_NAMES), 1)

MASS_BASE_SI = RP.GETENUMdll(0, "MASS BASE SI").iEnum

components = 'NITROGEN;METHANE;ETHANE;PROPANE;BUTANE;PENTANE;HEXANE'
mole_fractions = [0.005, 0.855, 0.088, 0.03, 0.0125, 0.0095, 0]
mixture_temperature_K = 133.15
mixture_pressure_Pa = 170000

print(dict(zip(components.split(";"), mole_fractions)))

print('Mixture temperature (K): ', mixture_temperature_K)
print('Mixture pressure (Pa): ', mixture_pressure_Pa)

# Critical properties
crit_temp_K = RP.REFPROPdll(components, 'ESPLINE', 'TC', MASS_BASE_SI, 0, 0, 0, 0, mole_fractions).Output[0]
print('Critical temperature (K): ', crit_temp_K)

crit_pres_Pa = RP.REFPROPdll(components, 'ESPLINE', 'PC', MASS_BASE_SI, 0, 0, 0, 0, mole_fractions).Output[0]
print('Critical pressure (Pa): ', crit_pres_Pa)

print('mixture_temperature_K > crit_temp_K ? ', mixture_temperature_K > crit_temp_K)
print('mixture_pressure_Pa > crit_pres_Pa ? ', mixture_pressure_Pa > crit_pres_Pa)

# Determine phase without forcing
phase = RP.REFPROPdll(components, 'TP;ESPLINE', 'PHASE', MASS_BASE_SI, 0, 0, mixture_temperature_K, mixture_pressure_Pa, mole_fractions).hUnits
print(f"Phase under temperature(K) {mixture_temperature_K} and pressure(Pa) {mixture_pressure_Pa} is: {phase}")

# Density calculation (no phase forced) with splines
density_bulk = RP.REFPROPdll(components, 'TP;ESPLINE', 'D', MASS_BASE_SI, 0, 0, mixture_temperature_K, mixture_pressure_Pa, mole_fractions).Output[0]
print(f"Density(bulk) under temperature(K) {mixture_temperature_K} and pressure(Pa) {mixture_pressure_Pa} is: {density_bulk}")

# FIXME: How to separately get the vapor phase and liquid phase density in this 2-phase region
density_vapor = RP.REFPROPdll(components, 'TPV;ESPLINE', 'D', MASS_BASE_SI, 0, 0, mixture_temperature_K, mixture_pressure_Pa, mole_fractions).Output[0]
print(f"Density(vapor) under temperature(K) {mixture_temperature_K} and pressure(Pa) {mixture_pressure_Pa} is: {density_vapor}")

density_liquid = RP.REFPROPdll(components, 'TPL;ESPLINE', 'D', MASS_BASE_SI, 0, 0, mixture_temperature_K, mixture_pressure_Pa, mole_fractions).Output[0]
print(f"Density(liquid) under temperature(K) {mixture_temperature_K} and pressure(Pa) {mixture_pressure_Pa} is: {density_liquid}")
```

**Expected behavior:**
```bash
NITROGEN;METHANE;ETHANE;PROPANE;BUTANE;PENTANE;HEXANE [0.005, 0.855, 0.088, 0.03, 0.0125, 0.0095, 0]
Mixture temperature (K):  133.15
Mixture pressure (Pa):  170000
Critical temperature (K):  223.24449849185814
Critical pressure (Pa):  6307516.084394081
mixture_temperature_K > crit_temp_K ?  False
mixture_pressure_Pa > crit_pres_Pa ?  False
Phase under temperature(K) 133.15 and pressure(Pa) 170000 is: Two-phase
Density(bulk) under temperature(K) 133.15 and pressure(Pa) 170000 is: 3.771820261577121
Density(vapor) under temperature(K) 133.15 and pressure(Pa) 170000 is: 2.5798
Density(liquid) under temperature(K) 133.15 and pressure(Pa) 170000 is: 609.95
```

**Actual behavior:**
```bash
NITROGEN;METHANE;ETHANE;PROPANE;BUTANE;PENTANE;HEXANE [0.005, 0.855, 0.088, 0.03, 0.0125, 0.0095, 0]
Mixture temperature (K):  133.15
Mixture pressure (Pa):  170000
Critical temperature (K):  223.24449849185814
Critical pressure (Pa):  6307516.084394081
mixture_temperature_K > crit_temp_K ?  False
mixture_pressure_Pa > crit_pres_Pa ?  False
Phase under temperature(K) 133.15 and pressure(Pa) 170000 is: Two-phase
Density(bulk) under temperature(K) 133.15 and pressure(Pa) 170000 is: 3.771820261577121
Density(vapor) under temperature(K) 133.15 and pressure(Pa) 170000 is: 3.124381587520966
Density(liquid) under temperature(K) 133.15 and pressure(Pa) 170000 is: 447.7989453767245
```
### Versions
**REFPROP Version:** Version 10.0
**Operating System and Version:** Windows 10
**Actual behavior:**
Python wrapper:
- ctREFPROP
- CoolProp==6.6.0 (prefer)

### Additional Information

If possible, I prefer to use CoolProp but I can't figure out a way to calculate that properties also.
In CoolProp, I calculate properties with:
```Python
import CoolProp.CoolProp as CP
root_path = "fill your installation path of REFPROP here"  # Window format path
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, str(root_path))
CP.set_config_string(CP.ALTERNATIVE_REFPROP_LIBRARY_PATH, str(self.root_path / 'REFPRP64.DLL'))
CP.set_config_string(CP.ALTERNATIVE_REFPROP_HMX_BNC_PATH, str(self.root_path / 'FLUIDS' / 'HMX.BNC'))
CP.set_config_bool(CP.REFPROP_USE_GERG, True)

temperature = 
pressure = 
components_str_CP = ['NITROGEN', 'METHANE', 'ETHANE', 'PROPANE', 'BUTANE', 'PENTANE', 'HEXANE']
mole_fractions = [0.005, 0.855, 0.088, 0.03, 0.0125, 0.0095, 0.0]
# How I calculate the bulk properties
density_bulk = CP.PropsSI('D', 'T', temperature, 'P', pressure, components_str_CP) # can only get the bulk value
# But how to calculate the vapor and liquid phase properties separately?
```
Software results:
![ff2a38aef4b40e7292991c20755b546](https://github.com/user-attachments/assets/3e5aa005-82ba-409b-9be4-169c34da56b7)

**Comment by ianhbell** [comment]
Please read the docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll . You want the LIQ and VAP suffixes on D output variable.

In CoolProp, you want the ``saturated_liquid_keyed_output`` method on the AbstractState: http://coolprop.org/apidoc/CoolProp.AbstractState.html#CoolProp.AbstractState.saturated_liquid_keyed_output

**Comment by renjie-github** [comment]
Thanks a lot! It's very useful.

**Comment by renjie-github** [comment]
Hi @ianhbell,

I've successfully used `saturated_liquid_keyed_output` to calculate vapor and liquid density. However, I also need to calculate properties like **viscosity**, **thermal conductivity**, and **specific heat capacity (CpMass)** separately.

I've reviewed the reference API but couldn't find clear guidance on which functions to use or how to pass the required arguments for these properties. Could you suggest the appropriate methods or provide some pointers?

Thank you, and apologies for the multiple questions!

**Comment by ianhbell** [comment]
For the REFPROP backend in CoolProp you are a bit stuck because only the saturated densities are available for architectural reasons. To get other properties you would need to do another calculation with each of the densities, probably with the phase specified to avoid the flash calculation. Or you could add the functionality with a pull request to CoolProp.

**Comment by renjie-github** [comment]
Thanks for conforming that information!
Actually I tried to calculate those properties in 2-phase region with some legacy API functions of REFPROP. In most occasions they work pretty good and I can get the exact same results as the REFPROP software. One issue I found there is in 2-phase region, when the temperature close to the dew point temperature, thoes properties' values are totally wrong with error indicates not converged.
PS. the CoolProp function `saturated_liquid_keyed_output` can get the correct vapor and liquid density even when temperature close to the dew point temperature.
E.g
```Python
# the following mixtures corresponds to a dew point temperature: -44.9564 celsius
components = ["NITROGEN", "METHANE", "ETHANE", "PROPANE", "BUTANE", "PENTANE", "HEXANE"]
mole_fractions = [0.005, 0.855, 0.088, 0.03, 0.0125, 0.0095, 0.0]
pressure = 170  # kPa

temperature = -46.95+273.15 # Kelvin, temperature in 2-phase region and close to the dew point temperature
# How I calculate those properties with legacy API
density_overall = self.RP.TPFL2dll(temperature, pressure/1000, mole_fractions)
liquid_density, vapor_density = density_overall.Dl, density_overall.Dv # density of liquid and vapor

liquid_vis_cond = self.RP.TRNPRPdll(temperature, liquid_density, density_overall.x)
liquid_vis_pa_s = liquid_vis_cond.eta * 1e-6
liquid_cond_w_m = liquid_vis_cond.tcx

liquid_Cp = self.RP.CVCPdll(temperature, liquid_density, density_overall.x).Cp
vapor_Cp = self.RP.CVCPdll(temperature, vapor_density, density_overall.y).Cp
```
Take Cpmass for example, the Cpmass (vapor) value calculated with the above method is: 8.314472 while the software gives value: 1.9406. The values not close to the dew point temperature are all exactly matched.

Also tried to use High level API but can't find where to specify 2-phase:
`RP.REFPROPdll(components_str, 'TP>', 'DVAP', RP.MASS_BASE_SI, 1, 1, temperature, pressure, mole_fractions).Output[0] # for density`

**Comment by ianhbell** [comment]
I think this is related: https://github.com/usnistgov/REFPROP-issues/issues/573

**Comment by ianhbell** [comment]
A note about ``saturated_liquid_keyed_output``: it is the liquid density, not the two-phase one

**Comment by renjie-github** [comment]
@ianhbell Thanks for confirming that. And I found the values close to bubble point have the same issue.

**Comment by ianhbell** [comment]
I'm going to close this issue as the linked issue is the placeholder for this bug.
