### ISSUE TITLE
Saturation state with predefined mixture R-431A

### ISSUE THREAD

**Issue by MicheleZehnder** [usnistgov/REFPROP-issues#696]
### Description

Saturation state of predefined mixture 1: Propane, 2: R-152a and mix. 3: R-431A (R-290/R-152a [71/29])
@Temperature 20°C

Saturation Pressure of the 3 fluids     1: 8.36bar, 2: 5.13bar, 3: 9.36bar

Question: Is this physically correct? I attend the mixture be situated in between of the pure fluid values.
                Do you have an explanation of this?

### Steps to Reproduce

1. Choose fluid 1, 2, 3
2. Calculate Saturation Table at 20°C
3. look at the values e.g. the Pressure levels.

** Pressure of mixture in between the 2 pure fluid's value ?

### Versions

**REFPROP Version: 10.0  
**Operating System and Version: Windows 10
**Access Method:** Refprop Program

**Comment by ianhbell** [comment]
The presence of positive-pressure (or negative-pressure) azeotropes can certainly result in a pressure outside the saturation pressure of the pures at the given temperature. There are many references one could point to on that theme, but mine I have easily at hand and it is open-access: https://doi.org/10.1021/acs.jced.1c00192.

**Comment by MicheleZehnder** [comment]
Thanks for the very interesting link. As I understand there are quite a few experimental Datapoints for this mixture. (Figure 3 of your survey).

**Comment by ianhbell** [comment]
Yes, that is right.
