### ISSUE TITLE
Refprop on MacOS and MATLAB: error "REFPRP64_thunk_pcwin64.dylib' (no such file)"

### ISSUE THREAD

**Issue by raffcil** [usnistgov/REFPROP-issues#697]
### Description

Hi, I'm on Mac Os 14.6.1 and I successfully cloned and installed the refprop repository as discussed in https://github.com/usnistgov/REFPROP-cmake. I'm now trying to link it to matlab through refpropm.m, rp_proto and rp_proto64. However, this error appears "REFPRP64_thunk_pcwin64.dylib' (no such file)". Can someone help me solve this? 

### Steps to Reproduce

1. Install Refprop library (librefprop.dylib)
2. point refpropm.m to the correct file
3. refpropm('P','T',25,'Q',0,'CO2') 

**Expected behavior:** pressure of CO2 

**Actual behavior:** REFPRP64_thunk_pcwin64.dylib' (no such file)

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Mac Os Sonoma 14.6.1

**Comment by ianhbell** [comment]
refpropm is no longer supported. Please migrate to the Python interface to MATLAB.

**Comment by raffcil** [comment]
is it retrocompatible with my old windows matlab scripts using refpropm?

**Comment by ianhbell** [comment]
No. refpropm had limited functionality and the new interface is much richer. There is a wrapper function developed by my colleagues at NIST: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab

**Comment by raffcil** [comment]
Ok i'll try to install the wrapper. Thanks
