### ISSUE TITLE
Latest R1234YF.FLD and R1336MZZE.FLD not loading.

### ISSUE THREAD

**Issue by kenjTT** [usnistgov/REFPROP-issues#700]
### Description

I downloaded the latest FLDs and HMX.BNC from https://pages.nist.gov/REFPROP-docs/#new-refrigerant-models-2023.  The REFPROP GUI appears to read the new R152A.FLD correctly, listing EoS = FEQ in place of the previous MBWR, ...
![image](https://github.com/user-attachments/assets/a8f15389-8a44-4a55-a963-0c734d9dc863)
However, the new R1234YF.FLD and R1336MZZE.FLD are not being read correctly; all values show as zeros and EoS is blank...
![image](https://github.com/user-attachments/assets/54d7ff21-9ffd-460b-a203-b3c701fdd25e)
![image](https://github.com/user-attachments/assets/18d00540-2204-4623-96e3-c4da86fb7c70)
I then replaced R1234YF.FLD with the file included in the supplementary materials to the 2022 Lemmon & Akasaka paper (NEWR1234YF.FLD); this file appears to read in correctly...
![image](https://github.com/user-attachments/assets/643643a7-f7ee-400e-8100-7b5a89abdb41)
I notice that there are some (very subtle, I'd guess) differences between NEWR1234YF.FLD and the latest R1234YF.FLD.

### Versions

**REFPROP Version:**   version 10.0, beta version (Sept. 21, 2020)
![image](https://github.com/user-attachments/assets/e68018ac-0b32-458a-860a-8f317952d389)

**Operating System and Version:**  Windows 10 Enterprise (1/2/2024)

**Access Method:** Running REFPROP via user interface.

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
What are the differences between the files you identify? I would like to fix that ASAP

**Comment by ianhbell** [comment]
It's weird, because the R1234YF.FLD I put in the zip to be copied over should be exactly what was in the paper.

**Comment by ianhbell** [comment]
Can you try with version 10.0.0?

**Comment by ianhbell** [comment]
Hmm. I just pulled the FLD from https://link.springer.com/article/10.1007/s10765-022-03015-y#Sec23 and that is identical to what I have in the zip.

**Comment by kenjTT** [comment]
NEWR1234YF.FLD is from 2022 publication supplemental materials.  Or maybe from the supplemental materials attached to your new mixture models paper.

R1234YF.FLD is from https://pages.nist.gov/REFPROP-docs/#new-refrigerant-models-2023 zipped archive ...
[A screenshot of a computer  Description automatically generated]


Ken
_________________________________
Ken Schultz
Thermal System/Project Engineer
Trane Technologies
***@***.***
***@***.******@***.***>
(608) 769-6326 (personal cell)

**Comment by ianhbell** [comment]
Sorry I deleted your response, please add your comment in the github web interface

**Comment by ianhbell** [comment]
You can also email me at ian.bell@nist.gov as I only have access to what appears to be an invalid email address for you.
