### ISSUE TITLE
Exergy values provided by NIST

### ISSUE THREAD

**Issue by tsionbehar** [usnistgov/REFPROP-issues#705]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

Please provide explanation on how exergy is being calculated by NIST and whether it can be used for exergy analysis of a refrigeration cycle.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [N/A]

**Actual behavior:** [N/A]

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by tsionbehar** [comment]
In the meantime, I have found the answer:
For a closed system:
x = (u - u0) +P0(v - v0) -T0(s - s0) + V^2/2 + gz
For a flow exergy:
x = (h - h0) - T0(s - s0) + V^2/2 + gz
The calculation of the values in NIST ignores kinetic and gravitational factors since it deals with theoretical process conditions.
Flow exergy is to be used when analyzing efficiencies of compressors, turbines, heat exchangers and JT valves. NIST can provide x in and x out but x destroyed needs to be calculated, then:
x in - x out - x destroyed = delta x system

**Comment by ianhbell** [comment]
Good - I would recommend to calculate it yourself to force you to think explicitly about the reference state for exergy (which is not necessarily the reference state for enthalpy or entropy)
