### ISSUE TITLE
GUI: F1 does not bring up Help

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#71]
If I start up REFPROP and bring up a window of any sort (for example, Units), pushing F1 does not bring up the Help as expected.  The cursor briefly turns into a swirling circle like it is trying to do something, but nothing happens.
If I open the Help from the Menu bar and then close it, after that F1 correctly opens a Help topic on any window for the remainder of that REFPROP session (but then the bug happens again if I close REFPROP and restart it).
So there must be something not getting initialized right that prevents F1 from opening the Help, that then gets properly initialized if you open the Help from the Menu bar.
If it matters, this is on a Windows 7 system.
If it matters, the same behavior happened in REFPROP 9.

**Comment by nist-aharvey** [comment]
Same bug occurs on my new Windows 10 system, so it was not specific to Windows 7.

**Comment by ianhbell** [comment]
@nist-aharvey where did you install REFPROP?  Default location?  I found for me that it doesn't open either, and I have mine installed in ``d:/Program Files (x86)/REFPROP`` instead of the default.

**Comment by nist-aharvey** [comment]
I don’t think it matters where it is installed for this bug.
It behaved that way when I had it in the default install location, but it also happens now after I reinstalled it under users/aharvey.

**Comment by EricLemmon** [comment]
This is an issue for which we do not know how to correct.  Perhaps some of our Refprop users who are reading these emails will be able to help.

**Comment by EricLemmon** [comment]
With some help from colleagues, we've figured out how to do this.  I've built a new refprop.exe file that is available if you would like it.
