### ISSUE TITLE
The unit systems used in Refprop

### ISSUE THREAD

**Issue by umitgunes** [usnistgov/REFPROP-issues#75]
```
import os;
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
r = RP.REFPROPdll("Water","TQ","H",101,0,0,375.15,1,[1.0])
print(r.hUnits
```

### Description

I got "P" as a pressure unit instead of Pa because 101 is for MASS BASE SI unit.

### Steps to Reproduce

**Expected behavior:** [Pa]

**Actual behavior:** [P]

### Versions

**REFPROP Version:** [DDL version is 10.0.0.54]  
**Operating System and Version:** [Windows 10, 1809]  
**Access Method:** [ Python]

**Comment by ianhbell** [comment]
Thanks for the report!

**Comment by EricLemmon** [comment]
It appears that we left two typos in the explanation of the units numbering.  The correct lines are shown below:
```
                         MOLAR       MASS
                         BASE SI     BASE SI     ENGLISH       MOLAR ENGLISH
        iUnits --->      20          21          5             6
```
This is a good example of why using the hard-coded enumerated values is not recommended, rather call subroutine GETENUM with iFlag set to 1 and hEnum set to 'Mass Base SI'.

**Comment by umitgunes** [comment]
Hi Eric,
Thank you very much.
Could you also update RefProp document to avoid confusing please:
https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

**Comment by EricLemmon** [comment]
We can definitely do that.  I'm currently working on a number of issues posted on github, and once those are all finished I'll ask Ian to rerun the scripts that made that document.

**Comment by umitgunes** [comment]
Hi Eric,
Could you also update the information on https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll
Thank you

**Comment by EricLemmon** [comment]
We will definitely do that once I finish fixing all other bugs that have been posted on github, which I'm working on right now.

**Comment by umitgunes** [comment]
Hi Eric,

I just checked the units and I found some bugs:

```
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
r = RP.REFPROPdll("Water","TQ","H",3,0,0,375.15,1,[1.0])
print(r.hUnits)
```

It turns as H not J/g

Also, the same problem occurs for iUnits as 3.

By the way, it is better to be updated iUnits 101 as 20 ans 102 as 21 in https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

Thank you

**Comment by EricLemmon** [comment]
The reason this happened is because the value of T that you sent is greater than the critical temperature.  Unit system 3 assumes that temperatures are in C, not K as you appear to be using.  The call to the Refprop routine returned an error number, and thus all outputs coming from the routine have no meaning.  The error number should always be checked.  If this is not done, the answers you get back will be completely wrong when an error occurs.
