### ISSUE TITLE
Problem with Entropy calculation for Ammonia in saturation state 

### ISSUE THREAD

**Issue by TomEck89** [usnistgov/REFPROP-issues#77]
Hi here is Thomas,

I work in the field of chiller applications with natural refrigerants. For this application I calculate different entropy points at saturation state of ammonia. 

There is a mismatch of 7 % between Refprop and literature tables and log p-h diagrams. 
Problem: Gas-phase Entropy-Calculation of pure ammonia: 
Input: Temperature=255 K, Quality = 1  (saturation state) 

Expected Output: appr. 5.87 kj/kg K (source: http://www.peacesoftware.de/einigewerte/calc_nh3.php7) and attachted PDF) 

Actual behavior: 6.3 kj/kg K (Refprop)

Versions

REFPROP Version: 9.1 and 10.0  
Operating System and Version: Windows 10
Access Method: Directly on REFPROP   

Additional Information
[ammonia_log-p-h.pdf](https://github.com/usnistgov/REFPROP-issues/files/2624552/ammonia_log-p-h.pdf)

**Comment by ianhbell** [comment]
One issue, the most frequently asked question about REFPROP, is that enthalpy and entropy are RELATIVE properties.  Please see: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences .  Does your reference use the same reference state as REFPROP?

But also, we have improved the EOS for ammonia, so some of the difference could be attributable to that.
