### ISSUE TITLE
VLE diagram

### ISSUE THREAD

**Issue by savinashg** [usnistgov/REFPROP-issues#79]
### Description

Mixture VLE : I just wanted to know , for a predefined mixture e.g. R450A is it possible to generate a VLE (Vapour Liquid Equilibrium) diagram/plot which can specifically show the vapour mole fraction in equilibrium with the liquid mole faction ( of course the lower boiling point component). What this means I should be able to read out (or generate a Table) the 'y' value ( i.e. vapour) at a given Temperature for an input 'x' value ( i.e. liquid mole fraction).

**Comment by ianhbell** [comment]
Do you want to do this from the REFPROP GUI? If so, you have several options for this in the "Calculate" menu in the GUI.

If from Excel (or Python, or ...) then please let us know.

**Comment by savinashg** [comment]
Thanks for your inputs. Yes I would like to do it from RefProp GUI. Please let me know steps to generate VLE ( similar to Figure shown below) from 'Calculate' menu.

![image](https://user-images.githubusercontent.com/45715818/49698754-18b36b80-fbee-11e8-94b9-80ef723dec30.png)

**Comment by ianhbell** [comment]
Which options in the Calculate menu have you tried so far?

**Comment by savinashg** [comment]
Hello Ian,
Well, I am just planning to purchase Refprop for my research work. I do have Mini Refprop but as you know it has very limited fluids ( no mixtures I think).
So all I wanted to know/confirm that with Version 10, I will be able to generate VLE data as I had posted on GitHub.
Let me know.
Thanks & regards
Avinash Shaligram

    On Sunday, 9 December, 2018, 11:25:25 PM IST, Ian Bell <notifications@github.com> wrote:  
 
 Which options in the Calculate menu have you tried so far?

**Comment by ianhbell** [comment]
Yes, that is certainly doable with REFPROP 10!  In fact we have new plotting routines to generate P-X diagrams that I wrote 😊

**Comment by EricLemmon** [comment]
Could you please close this if all your answers have been addressed?

**Comment by savinashg** [comment]
Hi!

I need to know steps/commands to generate the vapour mole fraction for a binary mixture which is at the same saturation temperature as liquid. This means I want "y" value for a given "x" value ( of the more volatile component) at a given temperature. I am not able to understand how to to do this in Version 10. I am now a user of Version 10. Maybe you can illustrate this with an example of R450A which is a mixture of R134a and R1234ze(E).
Thanks.

**Comment by EricLemmon** [comment]
To calculate equilibrium compositions, first go to Options/Properties and click on the Mixtures tab.  Then select composition as one of the outputs.  Then go to Calculate/Saturation Tables, choose "Liquid at bubble point with coexisting vapor", and press OK.  On the next menu, enter your starting and ending  temperatures and press OK again.  You will then get a table as shown below that has the y values for composition.

![image](https://user-images.githubusercontent.com/42392984/50376303-85544000-05c8-11e9-99c6-d5871d758e8a.png)

To make a plot as you showed above, go back to Calculate/Saturation Properties, click the top left option and then the "Composition at fixed P" option.  A sample output is shown below:

![image](https://user-images.githubusercontent.com/42392984/50376515-c2b9cd00-05ca-11e9-93e8-75aee1b98af4.png)

Note carefully:  **There are two state points listed on each line!  These are not equilibrium points, but a saturated liquid state and a saturated vapor state.  Use this table with caution.**

To plot the data, choose Plot/New Plot, then choose "Mass Fraction (L)" for the x axis and "Temperature (L)" for the y axis.  Once the plot is finished, go to Plot/Overlay Plot and then select "Mass Fraction (V)" for the x axis and "Temperature (V)" for the y axis.  This will give you a plot similar to the one you posted earlier.

![image](https://user-images.githubusercontent.com/42392984/50376484-6e165200-05ca-11e9-84ac-d48c5293b7ca.png)
