### ISSUE TITLE
Refreshing REFPROP BIPs in Excel add-in/vba mode 

### ISSUE THREAD

**Issue by UWAXiongXiao** [usnistgov/REFPROP-issues#80]
Dear REFPROP develop team:
  I am a PhD student from the University of Western Australia. We would like to tune some of the binary mixtures by modifying BIPs in REFPROP. The way of doing it is to modify the BIPs in HMX.BNC file by VBA and run it in the EXCEL file by EXCEL add-in.
  Now I have successfully set up the VBA code to modify the BIP in HMX.BNC file, however, every time I have to close the EXCEL file and re-open it to let the new BIPs take effective. Do you know how to reset the REFPROP initial state without closing the EXCEL file?
  You can view my VBA code as attached. It is reading the BIPs in HMX.BNC file, give one of the BIPs a value and tests the new BIP calculation results for thermodynamic properties. I have not set up the iterations yet.  
Many thanks
Xiong

Sub write_R1234yf_R1234zeE()
Dim myfile As String, text As String, textline As String, mixture As Long, model As Long
Dim BetaV As Long, GammaV As Long, Fij As Long
Dim TextFile As Integer, FileContent As String
Dim i As Double, a As Double, b As Double
Dim strFile As String
strFile = "C:\Xiong Xiao\ARRC\mitsubishi\modelling\text reading.xlsm"
myfile = "C:\Program Files (x86)\REFPROP\FLUIDS\HMX.BNC"
Open myfile For Input As #1

Do Until EOF(1)
  Line Input #1, textline
  text = text & textline
Loop
Close #1
'40377b40/9905ef70 refers to R1234yf/R1234ze(E)
mixture = InStr(text, "R1234yf/R1234ze(E)")
model = InStr(text, "40377b40/9905ef70")
Range("D3").Value = Mid(text, mixture, 18)
Range("D4").Value = Mid(text, model + 21, 3) 'model
Range("E4").Value = Mid(text, model + 30, 13) 'BetaT
Range("F4").Value = Mid(text, model + 45, 13) 'GammaT
Range("G4").Value = Mid(text, model + 60, 13) 'BetaV
Range("H4").Value = Mid(text, model + 75, 13) 'GammaV
TextFile = FreeFile
Open myfile For Input As TextFile
FileContent = Input(LOF(TextFile), TextFile) 'LOF function knows the length of a file that is not open
Close TextFile

'a = Range("J14").Value
i = 0.969
Range("J15").Value = i
FileContent = Replace(FileContent, Mid(text, model + 30, 13), Format(Range("J15").Value, "#,###########0.00000000000"), Count:=1) 'BetaT

Open myfile For Output As TextFile
Print #TextFile, FileContent
Close TextFile
'Range("J18").Value = REFPROP("d", "Nitrogen", "TP", "SI", "300", "0.1")
'ActiveWorkbook.Close SaveChanges:=True
'Workbooks.Open Filename:=strFile
End Sub

**Comment by ianhbell** [comment]
I don’t know about the internals of Excel, but you could also do the same thing with the SETKTV and GETKTV functions directly, which would take effect immediately.  More generally, I would use a tool that has a straightforward execution path, like C++, Python, or MATLAB.  What you are trying to do is a two-liner in Python: https://github.com/ianhbell/binfit/blob/master/binary_fitter.py#L151-L155 .  See also my paper: https://pubs.acs.org/doi/abs/10.1021/acs.jced.6b00257

**Comment by UWAXiongXiao** [comment]
Thanks Ian.
I am thinking of calling the DLL files to do the calculations. From your VBA code for REFPROP 10 (Refprop10Code), it requires 23 inputs for "Call REFPROPdll". I did find the manual you put online (https://www.nist.gov/sites/default/files/documents/2018/05/23/refprop10a.pdf). But it is not easy of me to understand the meaning for some of the inputs (like "Output", "x3") without an example.
  Do you have some of the available examples for subroutine REFPROPdll(I guess that is the same one as Call REFPROPdll in vba?)? Output (200) [double,out] :: Array of properties specified by the hOut string, what does this input "Output(200)" mean? How do I specify it? And for x(20), y(20), x3(20) these seem to be the calculated results? How can I have values as inputs in the beginning? How to specify "q" "ierr" and "herr"? 
  I might misunderstand something. Some of the inputs seem like outputs.
  Hope answering my question will not add too much trouble to you.
Thanks
Xiong

**Comment by UWAXiongXiao** [comment]
> I don’t know about the internals of Excel, but you could also do the same thing with the SETKTV and GETKTV functions directly, which would take effect immediately. More generally, I would use a tool that has a straightforward execution path, like C++, Python, or MATLAB. What you are trying to do is a two-liner in Python: https://github.com/ianhbell/binfit/blob/master/binary_fitter.py#L151-L155 . See also my paper: https://pubs.acs.org/doi/abs/10.1021/acs.jced.6b00257

Thanks Ian.
I am thinking of calling the DLL files to do the calculations. From your VBA code for REFPROP 10 (Refprop10Code), it requires 23 inputs for "Call REFPROPdll". I did find the manual you put online (https://www.nist.gov/sites/default/files/documents/2018/05/23/refprop10a.pdf). But it is not easy of me to understand the meaning for some of the inputs (like "Output", "x3") without an example.
Do you have some of the available examples for subroutine REFPROPdll(I guess that is the same one as Call REFPROPdll in vba?)? Output (200) [double,out] :: Array of properties specified by the hOut string, what does this input "Output(200)" mean? How do I specify it? And for x(20), y(20), x3(20) these seem to be the calculated results? How can I have values as inputs in the beginning? How to specify "q" "ierr" and "herr"?
I might misunderstand something. Some of the inputs seem like outputs.
Hope answering my question will not add too much trouble to you.
Thanks
Xiong

**Comment by ianhbell** [comment]
Did you look at the XLA file?  It calls REFPROPdll internally and you can just copy-paste that code into your VBA.  But really, you should consider a more fully-fledged environment for doing analysis.

Also, do you know about https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html ?

**Comment by UWAXiongXiao** [comment]
> There is a flag called "Reset HMX" in subroutine FLAGS that you can call to do this. The documentation from the REFPROP.FOR file is shown below:
> 
> ```
> Reset the caching flag so that the HMX.BNC file is read again on the next call to SETUP.  
> This option is only useful during fitting mixture models or modifying the HMX.BNC file to 
> add new interaction parameters, otherwise this flag will only slow down the program by 
> forcing a reread of the mixture file.  The output variable kFlag will be 0 or 1 to indicate 
> whether or not the HMX.BNC will be read on the next call to SETUP.                               
> ```
> In VBA, you can use this to call the FLAGS routine and reset the cached variables:
> 
> ```
>         hIn = "Flags"
>         hFld = ""
>         hOut = "Reset HMX"
>         Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 1&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
> ```
> You should look at the rest of the VBA code in the REFPROP.XLA file to setup the variables correctly.
> 
> Please let us know if any information required to do this is missing here.

Thanks. Now I believe the issue has been solved.

**Comment by EricLemmon** [comment]
See #21

**Comment by EricLemmon** [comment]
Ooops, please ignore that link to 21 above, I meant to add the link to 31
