### ISSUE TITLE
R514A

### ISSUE THREAD

**Issue by savinashg** [usnistgov/REFPROP-issues#86]
Why does Refprop 10 not include a mixture file for R514A?

**Comment by EricLemmon** [comment]
R514A is composed of 2 component fluids - R1336mzz(Z) and R1130(E). It is considered as a drop-in replacement for R123.  Version 10 has a fluid file and equation of state for R1336mzz(Z), but not R1130(E).  Hopefully that will change soon once measurements become available, but I do not know when.  Making an equation for R1130(E) (or any other fluid) is hundreds of hours of work, including both measurements and fitting - we cannot easily include any new fluid in the program.

P.S.  I changed your text to include the question on why Refprop does not include this mixture.
