### ISSUE TITLE
REFPROP 10.0.0.2 DLL File

### ISSUE THREAD

**Issue by ishceyhan** [usnistgov/REFPROP-issues#87]
I need to obtain the REFPROP 10.0.0.2 DLL file.  Unfortunately, the website where this resides is down due to the US government shutdown.  Is there an alternative location?  I need to reinstall the file on a new computer.  Thank you in advance for any help.

**Comment by Shahrooz87** [comment]
Hi, I am not sure these are the files you are looking for. I got these library files from NIST website before.


[Refprop library files for Matlab.zip](https://github.com/usnistgov/REFPROP-issues/files/2774307/Refprop.library.files.for.Matlab.zip)

**Comment by ishceyhan** [comment]
Unfortunately, this is still v10.0 DLL, so it is not the file I am looking for.  Thank you anyway!

**Comment by ianhbell** [comment]
@Shahrooz87  - I deleted your message because it contained information that is meant to only be available to users that have a valid license

**Comment by ianhbell** [comment]
P.S. NIST reopens tomorrow

**Comment by MorterzaAbbaszadeh** [comment]
I am sorry if I violated any copyright issues. These 2 files were on the website free to access when I downloaded them (REFPRP64.DLL and REFPRP64_thunk_pcwin64.dll). I thought they are only unavailable due to government shut down. Otherwise, I wouldn't share them.

**Comment by mina-shahrooz** [comment]
I am sorry if I violated any copyright issues. These 2 files were on the website free to access when I downloaded them (REFPRP64.DLL and REFPRP64_thunk_pcwin64.dll). I thought they are only unavailable due to government shut down. Otherwise, I wouldn't share them.

**Comment by quiro87** [comment]
Is there a possibility to download demo version of REFPROP.
Found a miniREFPROP 9.1 software online but it seems to be outdated.
Since it has been developed by NIST i am curious whether you can provide can newest versions or licences?
I am currently working with supercritical fluids and want to use REFPROP for creating p-T plots of CO2 with Joule coefficients. Thanks in advanced

**Comment by ianhbell** [comment]
I'm afraid we don't offer any trial version of REFPROP.  You can also email me at ian.bell@nist.gov and I can fill you in on some other options.

**Comment by ishceyhan** [comment]
I was able to obtain the DLL files now that NIST websites are back up and running.  Thank you!
