### ISSUE TITLE
The issue of first few rows always blank regardless of T, P conditions.

### ISSUE THREAD

**Issue by msuresh20** [usnistgov/REFPROP-issues#90]
### Description
The issue of first few rows always blank regardless of T, P conditions.

[Description of the issue]
The first 10 rows of the test case appear blank, regardless of Temperature and Pressure conditions. 
We tried a set of 3 Temperature-Pressure ranges on the same set of components for same test case:

Range 1: 
200K – 470K 
200kPa – 470kPa

Range 2:
300K – 570K
300kPa – 570kPa

Range 3:
400K – 600K
400kPa – 600kPa

### Steps to Reproduce

1. [First Step]
Define a new mixture with these Components: Diethanolamine, Monoethanolamine   with molar composition (0.5/0.5)
2. [Second Step]

Try to calculate various thermodynamic properties Enthalpy, Entropy, Density, Internal Energy] in the range specified below
Temperature: 200K – 470K 
Pressure:    200kPa – 470kPa

**Expected behavior:** [What you expect to happen]
Blank spaces should not be generated. Able to display all calculated results.
**Actual behavior:** [What actually happens]
The first 10 rows of the test case appear blank, regardless of Temperature and Pressure conditions. 

### Versions

**REFPROP Version:** [10.0.0.02]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Direct, Standalone NIST application]  

### Additional Information

Additional Information
Please refer to the attached zip file 
[3_Initial_rows_blank.zip](https://github.com/usnistgov/REFPROP-issues/files/2781951/3_Initial_rows_blank.zip)
 where in attached the REFPROP input, output result files.

**Comment by EricLemmon** [comment]
The points at low temperature are all below the lower temperature limit for the mixture and thus nothing is calculated.  When I enter values at these points, a message appears to this effect.  Did you get a message about T<T_low?

**Comment by msuresh20** [comment]
No, I do not get the message. To be precise, I am getting the message only a few times. The issue seems to be with consistency in RefProp as I am not observing consistency in reproducing this issue.

**Comment by msuresh20** [comment]
However, when the issue occurs its as can be seen in the document attached with this reply. 
[First rows blank.docx](https://github.com/usnistgov/REFPROP-issues/files/2858853/First.rows.blank.docx)

**Comment by EricLemmon** [comment]
How are you entering the data in that table?  Are you right clicking on the headers on the top that say "Temperature" and "Pressure" and telling it to fill the columns with values from 200 to 470 in steps of 10?  I tried that and got the error message shown below, along with the output shown in the second picture.  The blank lines are states outside the range of validity set by the program, as described in the first picture.

![image](https://user-images.githubusercontent.com/42392984/52794663-7a001c80-302d-11e9-9653-f9cd6356ac58.png)
![image](https://user-images.githubusercontent.com/42392984/52794794-c0ee1200-302d-11e9-88b9-2f69f2634c85.png)

**Comment by EricLemmon** [comment]
Can this issue be closed now?
