### ISSUE TITLE
How to optimise VLE calculations using the Refprop dll-interface and python in matlab?

### ISSUE THREAD

**Issue by Lupetta253** [usnistgov/REFPROP-issues#93]
### Description

We are currently working on a matlab code to calculate the evaporation rates of different droplets. Since the evaporation process occurs at high pressure conditions, we need to include solubility effects of the inert gas into the liquid droplet.

The matlab code uses the phython interface to access the refprop.dll function. From the dll-interface we would like to obtain the equilibrium vapour mass fraction y_eq of fuel, which differs from one due to the above mentioned solubility effects. Our input variables are:

T_d  =  droplet temperature
p_am = total ambient pressure

Sought variables are: y_eq or alternatively the saturation pressure of the binary mixture, being p_sat,binary = y_eq * p_sat, pure fuel

In order to perform these calculations, we thought to employ the subroutine  “XMASSVAP” and change iteratively the composition until the condition Q=1  is met. The questions I have are the following:

1) Are we using Refprop efficiently? My impression is that when I use the GUI interface, such calculations are much faster.

2) Could you please suggested an alternative way to perform these VLE calculations in a more efficient manner?

Thanks a lot in advance for the help

### Versions

**REFPROP Version:** [10.0]  
**Operating System and Version:** [Windows]  
**Access Method:** [Python and Matlab]

**Comment by Lupetta253** [comment]
The VLE calculation is performed by calling a function  from the main program at each time step.

Within the function, there are two different calls to Refprop. At the beginning, outside the 
iteration loop,  we write:

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\\REFPRP64.DLL');

Within the iteration loop for Q=> 1 (or Q =>0 depending on the case), we iteratively have this call
r = RP.REFPROPdll(str_c1,'PT','M',int8(0),int8(0),int8(0),pamb*1e-3,Td,{1.0});

I hope it is clear. Otherwise I'll send the code excerpt.

**Comment by ianhbell** [comment]
Hmm, that seems correct.  You might also want to check out my paper on humid air, which requires the same approach for finding the phase composition: https://www.sciencedirect.com/science/article/pii/S014070071730381X 

But in your case, the best approach is probably to call a lower-level function like PQFLSHdll and iterate on the composition until your temperature is the specified one.  Or alternatively, the same approach with TQFLSHdll.

**Comment by Lupetta253** [comment]
Ok, I'll try that right away and let you know whether the code speeds up.

**Comment by Lupetta253** [comment]
The problem is solved now. We were doing something stupid. Given p_am and T_drop as input, we were iterating on the composition trying to approximate exactly the condition Q=1 (or Q=0). This took very long and was never exact. In reality, this not necessary. We just need to be within the two-phase dome and then simply ask Refprop for the variable XMOLVAP and XMOLLIQ (or any other variable along the binodal). For this we need max a couple of iteration. Thanks a lot.

**Comment by ianhbell** [comment]
Ok, good to hear!  Can you please close the issue then?
