### ISSUE TITLE
specify fluid composition mini REFPROP

### ISSUE THREAD

**Issue by quiro87** [usnistgov/REFPROP-issues#94]
Is it possible to specify CO2-MeOH as a fluid composition within mini REFPROP?

**Comment by ianhbell** [comment]
Nope, mini REFPROP is intentionally not fully featured, intended only for teaching purposes.  I should caution you that the model in the full REFPROP is also problematic for CO2+MeOH.  Mixtures of CO2 + alcohols are tricky to model.

**Comment by quiro87** [comment]
thanks, ian!

**Comment by quiro87** [comment]
By the way  I was able to download miniREFPROP yesterday. I guess because govermental shutdown ended and the servers are up again since then.
