### ISSUE TITLE
V.10 improvements: mixture properties of HFA/ethanol,  Co2/ethanol and supercritical properties 

### ISSUE THREAD

**Issue by BarzinG** [usnistgov/REFPROP-issues#97]
### Description

1.  Previously in V.9.1  HFA (134a, 227ea, 152a) /ethanol mixture properties were not available   since measured data were not available. Is there any progress made in V.10?
2.  As far as I remember, there was a minimum and maximum limit to the temperature (min lim =216K). For my application I would require to evaluated properties at lower temperature especially for the substances  that their sublimation point is below their triple point (such as Co2). Is this limit now extended to capture phase properties below triple point (vapour-solid state) when link REFPROP with Matlab?
3.  Are mixture properties of Co2 and ethanol is available ?
4.  Are supercritical Co2 properties available?

### Versions

**REFPROP Version:** [V.9.1]  
**Operating System and Version:** [Windows]  
**Access Method:** [Matlab)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
What does HFA stand for?

1. Yes, I fit parameters in my paper: https://pubs.acs.org/doi/abs/10.1021/acs.jced.6b00257 , but I wouldn't trust these models.  Alcohol + refrigerants have complicated phase behavior.
2. You can ignore the warnings coming back from REFPROP.  Are you talking pure fluids or mixtures?  Mixtures are a harder case to ignore warnings.
3. There is a model in 10, it isn't perfect.
4. For sure, and have been for a long time.

**Comment by BarzinG** [comment]
Great thanks for the prompt reply. Please would you kindly clarify the followings:

re item 1. when you are suggesting you fit the parameters in your paper, are this available also in refprop matlab files ? can I use material properties of refrigerant + ethanol mixtures over a wide range of temperature and ethanol fraction in Matlab?

re item 2: I meant pure fluids but I actually meant using this in Matlab environment. In Matlab when the error occurs, the code terminates. 

re item 3. Is this model implementable in Matlab via *m file ?

re item 4. same as 3.

I appreciate your input and many thanks for your help with this.

Best wishes

**Comment by ianhbell** [comment]
1. Yes, the parameters are implemented in REFPROP 10, you can use these models through REFPROP, but you should be suspicious about the numbers that you get.
2. Use the Python interface in MATLAB, that let's you decide what to do about the errors
3. Yes, call REFPROP with the Python interface
4. Yes, call REFPROP with the Python interface

**Comment by BarzinG** [comment]
Thank you ever so much :)

**Comment by BarzinG** [comment]
> What does HFA stand for?
> 
> 1. Yes, I fit parameters in my paper: https://pubs.acs.org/doi/abs/10.1021/acs.jced.6b00257 , but I wouldn't trust these models.  Alcohol + refrigerants have complicated phase behavior.
> 2. You can ignore the warnings coming back from REFPROP.  Are you talking pure fluids or mixtures?  Mixtures are a harder case to ignore warnings.
> 3. There is a model in 10, it isn't perfect.
> 4. For sure, and have been for a long time.

Sorry, Just seen the question on the top. It stands for hydrofluoroalkane

**Comment by ianhbell** [comment]
Ah, usually we refer to them as HFC (hydrofluorocarbons), but HFA also works, and is a bit more specific

**Comment by EricLemmon** [comment]
Can this issue be closed now?
